RECIPES_KR = {
    "korean/rice": [
        {
            "id": "kimchi-fried-rice",
            "name": {"ko": "김치볶음밥", "en": "Kimchi Fried Rice", "ja": "キムチチャーハン", "zh": "泡菜炒饭"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "남은 밥과 김치로 15분 안에 뚝딱", "en": "Quick one-pan meal with leftover rice and kimchi", "ja": "残りご飯とキムチで15分で完成", "zh": "剩饭和泡菜15分钟搞定"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "묵은 김치", "amount": "100g"},
                {"name": "계란", "amount": "1개"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "김치는 적당히 잘라 준비해요.", "en": "Chop the kimchi into bite-sized pieces.", "ja": "キムチを適当な大きさに切って準備します。", "zh": "将泡菜切成适口大小备用。"},
                {"ko": "팬에 기름을 두르고 중불로 달군 뒤 김치를 볶아요. 김치 국물도 조금 넣으면 더 맛있어요.", "en": "Heat oil over medium heat and stir-fry the kimchi. Add a splash of kimchi juice for more flavor.", "ja": "フライパンに油をひき中火で熱したらキムチを炒めます。キムチの汁も少し入れると美味しさアップ。", "zh": "锅中倒油，中火加热后翻炒泡菜。加少量泡菜汁味道更佳。"},
                {"ko": "밥을 넣고 주걱으로 잘 풀어가며 볶아요.", "en": "Add rice and break it up with a spatula while stir-frying.", "ja": "ご飯を加えてしゃもじでほぐしながら炒めます。", "zh": "加入米饭，用锅铲边拨散边翻炒。"},
                {"ko": "간장을 넣고 30초 더 볶다가 불을 끄고 참기름을 뿌려요.", "en": "Add soy sauce, stir-fry 30 more seconds, then turn off heat and drizzle sesame oil.", "ja": "醤油を加えてさらに30秒炒め、火を止めてごま油を回しかけます。", "zh": "加入酱油再炒30秒，关火后淋上香油。"},
                {"ko": "별도 팬에 계란 프라이를 해서 밥 위에 올려요.", "en": "Fry an egg in a separate pan and place on top of the rice.", "ja": "別のフライパンで目玉焼きを作り、ご飯の上にのせます。", "zh": "另起锅煎荷包蛋，放在米饭上即完成。"},
            ],
        },
        {
            "id": "bibimbap",
            "name": {"ko": "비빔밥", "en": "Bibimbap", "ja": "ビビンバ", "zh": "拌饭"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "각종 나물과 고추장으로 비벼 먹는 한식의 대표", "en": "Classic Korean mixed rice bowl with vegetables and gochujang", "ja": "ナムルとコチュジャンを混ぜる韓国の定番ご飯", "zh": "各种凉拌菜和辣椒酱拌在一起的韩国代表性料理"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "시금치", "amount": "한 줌"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "계란", "amount": "1개"},
                {"name": "고추장", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "시금치는 끓는 물에 30초 데쳐 물기를 짜고, 소금·참기름으로 무쳐요.", "en": "Blanch spinach 30 seconds, squeeze out water, season with salt and sesame oil.", "ja": "ほうれん草を沸騰したお湯で30秒茹で、水気を絞り塩とごま油で和えます。", "zh": "菠菜在沸水中焯30秒，挤干水分，用盐和香油拌匀。"},
                {"ko": "당근은 채 썰어 팬에 기름 없이 살짝 볶아요.", "en": "Julienne carrots and sauté briefly in a dry pan.", "ja": "にんじんを千切りにして油なしのフライパンで軽く炒めます。", "zh": "胡萝卜切丝，在干锅中稍微翻炒一下。"},
                {"ko": "달걀을 프라이하거나 반숙으로 삶아요.", "en": "Fry or soft-boil the egg.", "ja": "卵を目玉焼きか半熟に茹でます。", "zh": "将鸡蛋煎成荷包蛋或煮成溏心蛋。"},
                {"ko": "그릇에 밥을 담고 나물과 계란을 예쁘게 올려요.", "en": "Place rice in a bowl and arrange vegetables and egg on top.", "ja": "器にご飯を盛りナムルと卵をきれいに並べます。", "zh": "碗里盛上米饭，将凉拌菜和鸡蛋摆放整齐。"},
                {"ko": "고추장과 참기름을 올리고 취향껏 비벼서 드세요.", "en": "Add gochujang and sesame oil, then mix everything together.", "ja": "コチュジャンとごま油をのせ、お好みで混ぜていただきます。", "zh": "放上辣椒酱和香油，按喜好拌匀食用。"},
            ],
        },
        {
            "id": "chicken-porridge",
            "name": {"ko": "닭죽", "en": "Chicken Porridge", "ja": "鶏のお粥", "zh": "鸡肉粥"},
            "time": 45, "difficulty": 1,
            "desc": {"ko": "속이 편한 든든한 한 그릇, 몸이 안 좋을 때 최고", "en": "Comforting rice porridge great for sick days", "ja": "体に優しい一杯、体調が悪い時に最適", "zh": "温暖肠胃的一碗，身体不适时的最佳选择"},
            "ingredients": [
                {"name": "쌀", "amount": "1/2컵"},
                {"name": "닭가슴살", "amount": "100g"},
                {"name": "물 또는 닭육수", "amount": "4컵"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "쌀은 30분 이상 불려요.", "en": "Soak rice for at least 30 minutes.", "ja": "お米を30分以上水に浸します。", "zh": "大米浸泡30分钟以上。"},
                {"ko": "닭가슴살은 물에 삶아 결대로 찢어요.", "en": "Boil chicken breast, then shred along the grain.", "ja": "鶏むね肉を水で茹でて繊維に沿って裂きます。", "zh": "鸡胸肉用水煮熟，顺着纹路撕开。"},
                {"ko": "냄비에 참기름을 두르고 불린 쌀을 2분 볶아요.", "en": "Heat sesame oil in a pot and stir-fry soaked rice for 2 minutes.", "ja": "鍋にごま油をひき浸したお米を2分炒めます。", "zh": "锅中倒入香油，将浸好的米炒2分钟。"},
                {"ko": "육수를 붓고 약불에서 20-25분 저어가며 끓여요.", "en": "Add broth and cook over low heat for 20-25 minutes, stirring occasionally.", "ja": "スープを注ぎ弱火で20〜25分かき混ぜながら煮ます。", "zh": "倒入高汤，小火边搅拌边煮20-25分钟。"},
                {"ko": "닭을 넣고 소금으로 간 맞춘 뒤 쪽파를 올려요.", "en": "Add chicken, season with salt, and garnish with green onions.", "ja": "鶏肉を加えて塩で味を整え小ねぎを散らします。", "zh": "加入鸡肉，用盐调味，撒上葱花即可。"},
            ],
        },
    ],
    "korean/soup": [
        {
            "id": "doenjang-jjigae",
            "name": {"ko": "된장찌개", "en": "Doenjang Jjigae", "ja": "テンジャンチゲ", "zh": "大酱汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "한국인의 소울푸드, 집된장이 없어도 시판 된장으로 OK", "en": "Korea's soul food stew — easy with store-bought doenjang", "ja": "韓国人のソウルフード、市販の味噌でも美味しく作れる", "zh": "韩国人的灵魂食物，用市售大酱也能轻松完成"},
            "ingredients": [
                {"name": "된장", "amount": "2큰술"},
                {"name": "두부", "amount": "1/2모"},
                {"name": "애호박", "amount": "1/4개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "멸치다시마육수", "amount": "2컵"},
                {"name": "고추", "amount": "1개 (선택)"},
            ],
            "steps": [
                {"ko": "두부는 2cm 큐브로, 호박·양파는 한 입 크기로 썰어요.", "en": "Cut tofu into 2cm cubes; dice zucchini and onion into bite-sized pieces.", "ja": "豆腐を2cmのキューブに、かぼちゃと玉ねぎは一口大に切ります。", "zh": "豆腐切成2cm小块，西葫芦和洋葱切成一口大小。"},
                {"ko": "냄비에 육수를 붓고 된장을 풀어 끓여요.", "en": "Pour broth into pot, dissolve doenjang, and bring to a boil.", "ja": "鍋にだし汁を注ぎ味噌を溶かして煮立てます。", "zh": "锅中倒入高汤，将大酱化开后煮沸。"},
                {"ko": "호박·양파·고추를 넣고 5분 끓여요.", "en": "Add zucchini, onion, and chili pepper; boil 5 minutes.", "ja": "かぼちゃ、玉ねぎ、唐辛子を入れて5分煮ます。", "zh": "加入西葫芦、洋葱和辣椒，煮5分钟。"},
                {"ko": "두부를 넣고 3분 더 끓여요.", "en": "Add tofu and boil 3 more minutes.", "ja": "豆腐を加えてさらに3分煮ます。", "zh": "加入豆腐再煮3分钟。"},
                {"ko": "대파를 넣고 불을 꺼요.", "en": "Add green onion and turn off the heat.", "ja": "長ねぎを入れて火を止めます。", "zh": "加入大葱后关火。"},
            ],
        },
        {
            "id": "kimchi-jjigae",
            "name": {"ko": "김치찌개", "en": "Kimchi Jjigae", "ja": "キムチチゲ", "zh": "泡菜汤"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "익은 김치일수록 맛있는 국민 찌개", "en": "The more fermented the kimchi, the better this stew gets", "ja": "キムチが熟すほど美味しくなる国民的チゲ", "zh": "泡菜越熟越好吃的国民汤锅"},
            "ingredients": [
                {"name": "묵은 김치", "amount": "150g"},
                {"name": "돼지고기 (목살 or 삼겹살)", "amount": "100g"},
                {"name": "두부", "amount": "1/2모"},
                {"name": "물", "amount": "1.5컵"},
                {"name": "고추장", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "설탕", "amount": "1/2작은술"},
            ],
            "steps": [
                {"ko": "돼지고기는 한 입 크기로, 두부는 2cm 두께로 썰어요.", "en": "Cut pork into bite-sized pieces and tofu into 2cm slices.", "ja": "豚肉は一口大に、豆腐は2cmの厚さに切ります。", "zh": "猪肉切成一口大小，豆腐切成2cm厚。"},
                {"ko": "냄비에 참기름을 두르고 돼지고기를 볶아요.", "en": "Heat sesame oil in a pot and stir-fry the pork.", "ja": "鍋にごま油をひき豚肉を炒めます。", "zh": "锅中倒入香油，翻炒猪肉。"},
                {"ko": "김치와 고추장을 넣고 2분 더 볶아요.", "en": "Add kimchi and gochujang; stir-fry 2 more minutes.", "ja": "キムチとコチュジャンを加えてさらに2分炒めます。", "zh": "加入泡菜和辣椒酱，再炒2分钟。"},
                {"ko": "물을 붓고 중불에서 10분 끓여요.", "en": "Pour in water and boil over medium heat for 10 minutes.", "ja": "水を注いで中火で10分煮ます。", "zh": "倒入水，中火煮10分钟。"},
                {"ko": "두부를 넣고 5분 더 끓이면 완성이에요.", "en": "Add tofu and boil 5 more minutes. Done!", "ja": "豆腐を加えてさらに5分煮れば完成です。", "zh": "加入豆腐再煮5分钟即可。"},
            ],
        },
        {
            "id": "egg-soup",
            "name": {"ko": "계란국", "en": "Korean Egg Soup", "ja": "卵のスープ", "zh": "鸡蛋汤"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "10분이면 완성, 초보자도 절대 실패 없는 국", "en": "10-minute soup that's impossible to mess up", "ja": "10分で完成、初心者でも失敗なしのスープ", "zh": "10分钟完成，初学者也不会失败的汤"},
            "ingredients": [
                {"name": "계란", "amount": "2개"},
                {"name": "멸치다시마육수", "amount": "2컵"},
                {"name": "국간장", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "참기름", "amount": "1/2작은술"},
            ],
            "steps": [
                {"ko": "계란을 그릇에 풀어 놓아요.", "en": "Beat eggs in a bowl.", "ja": "卵を器で溶きほぐします。", "zh": "将鸡蛋在碗中打散。"},
                {"ko": "냄비에 육수를 붓고 팔팔 끓여요.", "en": "Bring broth to a full boil in a pot.", "ja": "鍋にだし汁を注いで沸騰させます。", "zh": "锅中倒入高汤煮沸。"},
                {"ko": "국간장으로 간을 맞춰요.", "en": "Season with soup soy sauce.", "ja": "だし醤油で味を整えます。", "zh": "用汤用酱油调味。"},
                {"ko": "풀어 놓은 계란을 가느다란 줄기로 천천히 부어가며 저어요.", "en": "Slowly pour beaten eggs into boiling broth in a thin stream while stirring.", "ja": "溶いた卵を細い線状にかき混ぜながらゆっくり注ぎます。", "zh": "将打散的鸡蛋边搅拌边缓缓倒入沸汤中。"},
                {"ko": "쪽파와 참기름을 넣고 불을 꺼요.", "en": "Add green onions and sesame oil, then turn off heat.", "ja": "小ねぎとごま油を入れて火を止めます。", "zh": "加入葱花和香油后关火。"},
            ],
        },
    ],
    "korean/grill": [
        {
            "id": "jeyuk-bokkeum",
            "name": {"ko": "제육볶음", "en": "Spicy Stir-fried Pork", "ja": "チェユクポックム", "zh": "辣炒猪肉"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "밥도둑 1위, 고추장 양념 돼지고기 볶음", "en": "Spicy gochujang pork that goes perfectly with rice", "ja": "ご飯泥棒1位、コチュジャン味付け豚肉炒め", "zh": "最配饭的下饭菜冠军，辣椒酱炒猪肉"},
            "ingredients": [
                {"name": "돼지고기 (앞다리살)", "amount": "200g"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "양파", "amount": "1/2개"},
                {"name": "참기름", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "돼지고기는 0.5cm 두께로 썰어요.", "en": "Slice pork to 0.5cm thickness.", "ja": "豚肉を0.5cmの厚さに切ります。", "zh": "猪肉切成0.5cm厚。"},
                {"ko": "볼에 고추장·고춧가루·간장·설탕·마늘을 섞어 양념을 만들어요.", "en": "Mix gochujang, chili flakes, soy sauce, sugar, and garlic to make the sauce.", "ja": "ボウルにコチュジャン・唐辛子粉・醤油・砂糖・にんにくを混ぜてたれを作ります。", "zh": "将辣椒酱、辣椒粉、酱油、糖、蒜末混合制成腌料。"},
                {"ko": "고기를 양념에 20분 이상 재워요.", "en": "Marinate pork in the sauce for at least 20 minutes.", "ja": "肉をたれに20分以上漬け込みます。", "zh": "将猪肉在腌料中腌制20分钟以上。"},
                {"ko": "달군 팬에 양파를 먼저 볶다가 고기를 넣고 센불에서 볶아요.", "en": "Stir-fry onion first in a hot pan, then add pork and cook over high heat.", "ja": "熱したフライパンで玉ねぎを先に炒め肉を加えて強火で炒めます。", "zh": "在热锅中先翻炒洋葱，再加入肉用大火翻炒。"},
                {"ko": "고기가 익으면 참기름을 뿌려 마무리해요.", "en": "When pork is cooked through, drizzle with sesame oil to finish.", "ja": "肉に火が通ったらごま油を回しかけて仕上げます。", "zh": "猪肉熟透后淋上香油完成。"},
            ],
        },
        {
            "id": "bulgogi",
            "name": {"ko": "소불고기", "en": "Beef Bulgogi", "ja": "プルコギ", "zh": "韩式烤牛肉"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "달콤한 간장 양념 소고기, 외국인도 반하는 맛", "en": "Sweet soy-marinated beef loved by everyone", "ja": "甘い醤油タレの牛肉、外国人もとりこになる味", "zh": "甜甜酱油腌制的牛肉，连外国人都为之着迷"},
            "ingredients": [
                {"name": "소고기 (불고기용)", "amount": "200g"},
                {"name": "배 또는 사과", "amount": "1/4개 (갈아서)"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "참기름", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "양파", "amount": "1/2개"},
            ],
            "steps": [
                {"ko": "배나 사과를 갈아서 즙을 냅니다. 고기를 연하게 하는 역할이에요.", "en": "Grate pear or apple for the juice — it tenderizes the meat.", "ja": "梨またはりんごをすりおろして果汁を取ります。肉を柔らかくする役割です。", "zh": "将梨或苹果磨成泥取汁，起到软化肉质的作用。"},
                {"ko": "간장·설탕·참기름·마늘·과일즙을 섞어 양념장을 만들어요.", "en": "Mix soy sauce, sugar, sesame oil, garlic, and fruit juice to make the marinade.", "ja": "醤油・砂糖・ごま油・にんにく・果汁を混ぜてたれを作ります。", "zh": "将酱油、糖、香油、蒜末、果汁混合制成腌料。"},
                {"ko": "고기에 양념장을 넣고 양파와 함께 버무려 30분 이상 재워요.", "en": "Mix beef with marinade and sliced onion; marinate at least 30 minutes.", "ja": "肉にたれと玉ねぎを加えてよく混ぜ30分以上漬け込みます。", "zh": "将牛肉与腌料和洋葱拌匀，腌制30分钟以上。"},
                {"ko": "달군 팬에 센불로 고기를 볶아요. 국물이 생기면 졸여 주세요.", "en": "Stir-fry over high heat. If liquid forms, reduce it down.", "ja": "熱したフライパンで強火で肉を炒めます。汁が出たら煮詰めてください。", "zh": "在热锅中用大火翻炒牛肉，如有汤汁则收干。"},
                {"ko": "참기름을 살짝 더 뿌려 마무리해요.", "en": "Finish with a touch more sesame oil.", "ja": "ごま油を少しだけ加えて仕上げます。", "zh": "再淋上少许香油完成。"},
            ],
        },
        {
            "id": "dak-galbi",
            "name": {"ko": "닭갈비", "en": "Spicy Stir-fried Chicken", "ja": "タッカルビ", "zh": "辣炒鸡肋"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "춘천 명물, 고추장 양념 닭볶음", "en": "Spicy gochujang chicken stir-fry from Chuncheon", "ja": "春川名物、コチュジャン味付け鶏肉炒め", "zh": "春川名产，辣椒酱味炒鸡"},
            "ingredients": [
                {"name": "닭다리살 또는 닭가슴살", "amount": "250g"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "고구마 또는 감자", "amount": "1/2개"},
                {"name": "양배추", "amount": "2장"},
            ],
            "steps": [
                {"ko": "닭은 한 입 크기로, 고구마·양배추도 비슷하게 썰어요.", "en": "Cut chicken, sweet potato, and cabbage into similar bite-sized pieces.", "ja": "鶏肉は一口大に、さつまいもとキャベツも同じくらいの大きさに切ります。", "zh": "鸡肉切成一口大小，红薯和卷心菜也切成类似大小。"},
                {"ko": "고추장·고춧가루·간장·설탕·마늘로 양념을 만들어요.", "en": "Combine gochujang, chili flakes, soy sauce, sugar, and garlic.", "ja": "コチュジャン・唐辛子粉・醤油・砂糖・にんにくでたれを作ります。", "zh": "用辣椒酱、辣椒粉、酱油、糖、蒜末制作腌料。"},
                {"ko": "닭에 양념을 버무려 20분 재워요.", "en": "Coat chicken in sauce and marinate 20 minutes.", "ja": "鶏肉にたれを絡めて20分漬け込みます。", "zh": "将腌料与鸡肉拌匀，腌制20分钟。"},
                {"ko": "팬에 기름 두르고 닭을 먼저 익혀요.", "en": "Heat oil in a pan and cook the chicken first.", "ja": "フライパンに油をひき鶏肉を先に焼きます。", "zh": "锅中倒油，先将鸡肉煎熟。"},
                {"ko": "고구마·양배추를 넣고 뚜껑 덮어 5분 익힌 뒤 잘 섞어요.", "en": "Add sweet potato and cabbage, cover and cook 5 minutes, then toss together.", "ja": "さつまいもとキャベツを加え蓋をして5分加熱したらよく混ぜます。", "zh": "加入红薯和卷心菜，盖锅盖焖5分钟后翻拌均匀。"},
            ],
        },
    ],
    "korean/kimchi": [
        {
            "id": "gyeran-mari",
            "name": {"ko": "계란말이", "en": "Korean Rolled Omelette", "ja": "卵焼き（韓国風）", "zh": "韩式鸡蛋卷"},
            "time": 15, "difficulty": 2,
            "desc": {"ko": "도시락 단골 반찬, 예쁘게 마는 게 포인트", "en": "Classic lunchbox side — the roll is the challenge", "ja": "お弁当の定番おかず、きれいに巻くのがポイント", "zh": "便当常客，漂亮地卷起来才是关键"},
            "ingredients": [
                {"name": "계란", "amount": "3개"},
                {"name": "당근", "amount": "1/8개"},
                {"name": "쪽파", "amount": "2줄기"},
                {"name": "소금", "amount": "1/4작은술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "당근과 쪽파를 잘게 다져요.", "en": "Finely dice carrot and green onion.", "ja": "にんじんと小ねぎを細かく刻みます。", "zh": "将胡萝卜和葱花切碎。"},
                {"ko": "계란을 풀고 당근·쪽파·소금을 넣어 잘 섞어요.", "en": "Beat eggs and mix in carrot, green onion, and salt.", "ja": "卵を溶きほぐしにんじん・小ねぎ・塩を加えてよく混ぜます。", "zh": "打散鸡蛋，加入胡萝卜、葱花和盐拌匀。"},
                {"ko": "팬에 기름을 얇게 두르고 약불로 달군 뒤 계란물 1/3을 부어요.", "en": "Lightly oil a pan over low heat and pour in 1/3 of the egg mixture.", "ja": "フライパンに薄く油をひき弱火で熱し卵液の1/3を流し入れます。", "zh": "平底锅薄薄涂一层油，小火加热后倒入1/3蛋液。"},
                {"ko": "반 익으면 한쪽부터 돌돌 말아요.", "en": "When half-set, roll it up from one side.", "ja": "半熟になったら端からくるくると巻きます。", "zh": "半熟后从一边开始卷起。"},
                {"ko": "남은 계란물을 2번에 나눠 같은 방식으로 말아 두툼하게 만들어요.", "en": "Pour the rest in two batches, rolling each time to build thickness.", "ja": "残りの卵液を2回に分けて同じように巻いて厚みを出します。", "zh": "将剩余蛋液分两次倒入，同样方式卷起使其变厚。"},
                {"ko": "식힌 뒤 썰면 단면이 예쁘게 나와요.", "en": "Let cool before slicing to reveal a clean cross-section.", "ja": "冷ましてから切ると断面がきれいに仕上がります。", "zh": "冷却后切开，截面会非常漂亮。"},
            ],
        },
        {
            "id": "spinach-namul",
            "name": {"ko": "시금치나물", "en": "Spinach Namul", "ja": "ほうれん草のナムル", "zh": "菠菜凉拌"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "데쳐서 무치면 끝, 가장 쉬운 나물 반찬", "en": "Blanch and toss — the easiest Korean side dish", "ja": "茹でて和えるだけ、最も簡単なナムル料理", "zh": "焯熟拌一拌就完成，最简单的小菜"},
            "ingredients": [
                {"name": "시금치", "amount": "200g"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "소금", "amount": "1/2작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "통깨", "amount": "약간"},
            ],
            "steps": [
                {"ko": "끓는 물에 소금 약간 넣고 시금치를 30초만 데쳐요.", "en": "Blanch spinach in salted boiling water for just 30 seconds.", "ja": "沸騰した湯に塩を少し入れほうれん草を30秒だけ茹でます。", "zh": "沸水中加少许盐，将菠菜焯烫30秒。"},
                {"ko": "찬물에 헹궈 물기를 꼭 짜요.", "en": "Rinse in cold water and squeeze out all moisture.", "ja": "冷水でさらし水気をしっかり絞ります。", "zh": "冷水冲洗后，用力挤干水分。"},
                {"ko": "마늘·소금·참기름을 넣고 손으로 조물조물 무쳐요.", "en": "Add garlic, salt, and sesame oil; mix well by hand.", "ja": "にんにく・塩・ごま油を加え手でよく和えます。", "zh": "加入蒜末、盐和香油，用手充分拌匀。"},
                {"ko": "통깨를 뿌려 완성이에요.", "en": "Sprinkle sesame seeds and serve.", "ja": "白ごまをふって完成です。", "zh": "撒上芝麻即可完成。"},
            ],
        },
        {
            "id": "cucumber-salad",
            "name": {"ko": "오이무침", "en": "Spicy Cucumber Salad", "ja": "きゅうりのピリ辛和え", "zh": "拌黄瓜"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "아삭하고 매콤한 여름 반찬의 대명사", "en": "Crisp, spicy cucumber — perfect summer side dish", "ja": "シャキシャキ辛い夏の副菜の代名詞", "zh": "爽脆微辣，夏日小菜的代名词"},
            "ingredients": [
                {"name": "오이", "amount": "1개"},
                {"name": "소금", "amount": "1작은술 (절임용)"},
                {"name": "고춧가루", "amount": "1작은술"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "식초", "amount": "1작은술"},
                {"name": "설탕", "amount": "1/2작은술"},
                {"name": "참기름·통깨", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "오이를 반달 모양으로 0.5cm 두께로 썰어요.", "en": "Slice cucumber into 0.5cm half-moons.", "ja": "きゅうりを半月形に0.5cmの厚さに切ります。", "zh": "黄瓜切成0.5cm厚的半月形。"},
                {"ko": "소금을 뿌려 10분 절인 뒤 물기를 꼭 짜요.", "en": "Sprinkle salt and let sit 10 minutes, then squeeze out liquid.", "ja": "塩をふって10分置いてから水気をしっかり絞ります。", "zh": "撒上盐腌10分钟后，挤干水分。"},
                {"ko": "고춧가루·마늘·식초·설탕을 섞어 양념을 만들어요.", "en": "Mix chili flakes, garlic, vinegar, and sugar for the dressing.", "ja": "唐辛子粉・にんにく・酢・砂糖を混ぜてたれを作ります。", "zh": "将辣椒粉、蒜末、醋、糖混合制成调味料。"},
                {"ko": "오이에 양념을 넣고 조물조물 무쳐요.", "en": "Toss cucumber with the dressing.", "ja": "きゅうりにたれを加えて手でよく和えます。", "zh": "将调味料加入黄瓜中，用手拌匀。"},
                {"ko": "참기름과 통깨를 뿌려 마무리해요.", "en": "Finish with sesame oil and sesame seeds.", "ja": "ごま油と白ごまをふって仕上げます。", "zh": "撒上香油和芝麻完成。"},
            ],
        },
    ],
    "korean/noodle": [
        {
            "id": "japchae",
            "name": {"ko": "잡채", "en": "Japchae", "ja": "チャプチェ", "zh": "杂菜"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "명절 단골 메뉴, 색색의 채소와 당면의 조화", "en": "Festive glass noodles with colorful vegetables", "ja": "お祭りの定番メニュー、色鮮やかな野菜と春雨の調和", "zh": "节日必备，色彩丰富的蔬菜与粉丝的完美搭配"},
            "ingredients": [
                {"name": "당면", "amount": "100g"},
                {"name": "소고기 (채 썰기)", "amount": "80g"},
                {"name": "시금치", "amount": "한 줌"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "설탕", "amount": "1.5큰술"},
                {"name": "참기름", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "당면을 30분 불려요.", "en": "Soak glass noodles for 30 minutes.", "ja": "春雨を30分水に浸します。", "zh": "粉丝泡水30分钟。"},
                {"ko": "소고기는 간장 1큰술·설탕·참기름으로 미리 양념해요.", "en": "Marinate beef with 1 tbsp soy sauce, sugar, and sesame oil.", "ja": "牛肉は醤油大さじ1・砂糖・ごま油で下味をつけます。", "zh": "牛肉提前用1大勺酱油、糖、香油腌制。"},
                {"ko": "채소를 각각 볶아 놓아요 (당근·양파·시금치 순서로).", "en": "Stir-fry each vegetable separately (carrot, onion, spinach).", "ja": "野菜をそれぞれ炒めます（にんじん・玉ねぎ・ほうれん草の順で）。", "zh": "蔬菜分别翻炒（依次是胡萝卜、洋葱、菠菜）。"},
                {"ko": "불린 당면을 끓는 물에 8분 삶아 건져요.", "en": "Boil soaked noodles 8 minutes, then drain.", "ja": "浸した春雨を沸騰した湯で8分茹でてすくい上げます。", "zh": "将泡好的粉丝在沸水中煮8分钟，捞出备用。"},
                {"ko": "모든 재료를 큰 볼에 담고 남은 간장·설탕·참기름으로 버무려요.", "en": "Combine everything in a large bowl and toss with remaining soy sauce, sugar, and sesame oil.", "ja": "全材料を大きなボウルに入れ残りの醤油・砂糖・ごま油で和えます。", "zh": "将所有食材放入大碗，用剩余的酱油、糖、香油拌匀。"},
            ],
        },
        {
            "id": "instant-ramen",
            "name": {"ko": "라면", "en": "Korean Instant Ramen", "ja": "ラーメン", "zh": "方便面"},
            "time": 5, "difficulty": 1,
            "desc": {"ko": "실패 없는 국민 야식, 물 양이 핵심", "en": "Korea's favorite late-night snack — water ratio is everything", "ja": "失敗なしの国民的夜食、水の量が命", "zh": "不会失败的国民宵夜，水的用量是关键"},
            "ingredients": [
                {"name": "라면", "amount": "1개"},
                {"name": "물", "amount": "550ml"},
                {"name": "계란", "amount": "1개 (선택)"},
                {"name": "대파", "amount": "약간 (선택)"},
            ],
            "steps": [
                {"ko": "물 550ml를 냄비에 붓고 끓여요.", "en": "Bring 550ml of water to a boil.", "ja": "鍋に水550mlを注いで沸かします。", "zh": "锅中倒入550ml水煮沸。"},
                {"ko": "물이 끓으면 면과 스프를 넣어요.", "en": "Once boiling, add noodles and soup powder.", "ja": "沸騰したら麺とスープの素を入れます。", "zh": "水沸后放入面条和调料包。"},
                {"ko": "4분 30초 동안 원하는 식감으로 끓여요.", "en": "Cook for about 4 minutes 30 seconds to your preferred texture.", "ja": "約4分30秒、好みの食感になるまで煮ます。", "zh": "煮约4分30秒，达到喜欢的口感。"},
                {"ko": "계란을 넣으면 1분 전에, 대파는 마지막에 넣어요.", "en": "Add egg 1 minute before done; add green onion at the very end.", "ja": "卵は終了1分前に、長ねぎは最後に入れます。", "zh": "鸡蛋提前1分钟放入，大葱最后放入。"},
            ],
        },
        {
            "id": "kalguksu",
            "name": {"ko": "칼국수", "en": "Knife-cut Noodle Soup", "ja": "カルグクス", "zh": "刀切面"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "쫄깃한 면과 진한 국물, 손칼국수의 정석", "en": "Chewy hand-cut noodles in a deep savory broth", "ja": "もちもちの麺と濃いスープ、手打ち麺の王道", "zh": "劲道面条配浓郁汤底，手切面的正统做法"},
            "ingredients": [
                {"name": "칼국수 면 (시판)", "amount": "2인분"},
                {"name": "멸치다시마육수", "amount": "4컵"},
                {"name": "애호박", "amount": "1/3개"},
                {"name": "감자", "amount": "1개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "국간장", "amount": "1큰술"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "감자·호박·양파를 채 썰거나 반달로 썰어요.", "en": "Julienne or slice potato, zucchini, and onion.", "ja": "じゃがいも・かぼちゃ・玉ねぎを千切りか半月切りにします。", "zh": "将土豆、西葫芦、洋葱切丝或切成半月形。"},
                {"ko": "냄비에 육수를 붓고 끓이다가 감자를 먼저 넣어요.", "en": "Bring broth to a boil and add potato first.", "ja": "鍋にだし汁を注いで沸かしじゃがいもを先に入れます。", "zh": "锅中倒入高汤煮沸，先放入土豆。"},
                {"ko": "감자가 반쯤 익으면 호박·양파를 넣어요.", "en": "When potato is half-cooked, add zucchini and onion.", "ja": "じゃがいもが半分火が通ったらかぼちゃと玉ねぎを加えます。", "zh": "土豆半熟后加入西葫芦和洋葱。"},
                {"ko": "칼국수 면을 넣고 면이 익을 때까지 8-10분 끓여요.", "en": "Add noodles and boil 8-10 minutes until cooked through.", "ja": "カルグクスの麺を入れて火が通るまで8〜10分煮ます。", "zh": "加入刀切面，煮8-10分钟至熟透。"},
                {"ko": "국간장·소금으로 간을 맞춰 마무리해요.", "en": "Season with soup soy sauce and salt to taste.", "ja": "だし醤油と塩で味を整えて完成です。", "zh": "用汤用酱油和盐调味完成。"},
            ],
        },
    ],
}
