RECIPES_CN = {
    "chinese/noodle": [
        {
            "id": "jjajangmyeon",
            "name": {"ko": "짜장면", "en": "Jjajangmyeon", "ja": "チャジャンミョン", "zh": "炸酱面"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "춘장으로 만드는 한국식 짜장면", "en": "Korean-style black bean paste noodles"},
            "ingredients": [
                {"name": "생면 또는 건면", "amount": "2인분"},
                {"name": "춘장", "amount": "3큰술"},
                {"name": "돼지고기 (다진 것)", "amount": "150g"},
                {"name": "양파", "amount": "1개"},
                {"name": "감자", "amount": "1개"},
                {"name": "식용유", "amount": "3큰술"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "설탕", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "돼지고기·감자·양파를 1cm 주사위 모양으로 썰어요.", "en": "Dice pork, potato, and onion into 1cm cubes."},
                {"ko": "팬에 기름 넉넉히 두르고 춘장을 약불에서 1-2분 볶아요. 쓴맛이 빠져요.", "en": "Heat plenty of oil and stir-fry chunjang over low heat 1-2 minutes to remove bitterness."},
                {"ko": "볶은 춘장은 덜어두고, 같은 팬에 돼지고기를 볶아요.", "en": "Set aside fried chunjang. In same pan, stir-fry pork."},
                {"ko": "감자·양파를 넣고 2분 볶은 뒤 춘장을 다시 넣고 물 1.5컵을 부어 졸여요.", "en": "Add potato and onion, stir-fry 2 min, return chunjang, add 1.5 cups water and simmer."},
                {"ko": "전분물(전분+물 1:2)을 넣어 걸쭉하게 만들고, 삶은 면에 얹어요.", "en": "Thicken with starch slurry (1:2 ratio) and pour over boiled noodles."},
            ],
        },
        {
            "id": "jjamppong",
            "name": {"ko": "짬뽕", "en": "Jjamppong", "ja": "チャンポン", "zh": "炒码面"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "불향 가득한 매콤한 해물 면", "en": "Spicy seafood noodle soup with wok char"},
            "ingredients": [
                {"name": "생면", "amount": "2인분"},
                {"name": "오징어", "amount": "1/2마리"},
                {"name": "새우", "amount": "6마리"},
                {"name": "고춧가루", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "양배추", "amount": "2장"},
                {"name": "대파", "amount": "1/2대"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "물 또는 육수", "amount": "3컵"},
            ],
            "steps": [
                {"ko": "오징어는 링으로, 새우는 내장 제거, 채소는 큼직하게 썰어요.", "en": "Slice squid into rings, devein shrimp, chop vegetables roughly."},
                {"ko": "팬에 기름 많이 두르고 센불에서 고춧가루·마늘을 10초 볶아요.", "en": "Heat plenty of oil over high heat; stir-fry chili flakes and garlic for 10 seconds."},
                {"ko": "해물을 넣고 센불에서 빠르게 볶아요. 불향이 핵심이에요.", "en": "Add seafood and stir-fry fast over high heat. The wok char is key."},
                {"ko": "채소·굴소스·물을 넣고 5분 끓여요.", "en": "Add vegetables, oyster sauce, and water; boil 5 minutes."},
                {"ko": "삶은 면을 국물에 넣고 2분 더 끓여요.", "en": "Add cooked noodles and boil 2 more minutes."},
            ],
        },
        {
            "id": "mul-mandu",
            "name": {"ko": "물만두", "en": "Boiled Dumplings", "ja": "水餃子", "zh": "水饺"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "직접 빚으면 더 맛있는 집만두", "en": "Homemade dumplings — so much better than frozen"},
            "ingredients": [
                {"name": "만두피 (시판)", "amount": "20장"},
                {"name": "돼지고기 (다진 것)", "amount": "150g"},
                {"name": "두부", "amount": "1/4모"},
                {"name": "김치 (다진 것)", "amount": "50g"},
                {"name": "대파 (다진 것)", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "참기름·소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "두부는 물기를 꼭 짜고, 김치도 물기를 빼요.", "en": "Squeeze moisture from tofu and kimchi thoroughly."},
                {"ko": "돼지고기·두부·김치·대파·마늘·양념을 잘 섞어 소를 만들어요.", "en": "Mix pork, tofu, kimchi, green onion, garlic, and seasonings into the filling."},
                {"ko": "만두피 가장자리에 물을 바르고 소를 올려 꼭꼭 눌러 붙여요.", "en": "Wet the edges of the wrapper, add filling, and seal tightly."},
                {"ko": "끓는 물에 만두를 넣고 떠오르면 2분 더 삶아요.", "en": "Drop dumplings into boiling water; cook 2 more minutes after they float."},
                {"ko": "간장·식초·고춧가루 소스에 찍어 드세요.", "en": "Serve with soy-vinegar dipping sauce."},
            ],
        },
    ],
    "chinese/rice": [
        {
            "id": "egg-fried-rice",
            "name": {"ko": "계란볶음밥", "en": "Egg Fried Rice", "ja": "卵チャーハン", "zh": "蛋炒饭"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "중식의 기본 중의 기본, 센 불이 핵심", "en": "The foundation of Chinese cooking — high heat is everything"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "계란", "amount": "2개"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "계란은 미리 풀어 놓아요.", "en": "Beat eggs in advance."},
                {"ko": "팬을 최대한 강불로 달궈요. 연기가 살짝 날 정도로요.", "en": "Heat pan to maximum — you want it nearly smoking."},
                {"ko": "기름을 두르고 계란을 먼저 스크램블해요. 완전히 익히지 말고 반숙 상태에서 꺼내요.", "en": "Add oil and scramble eggs. Remove while still slightly soft."},
                {"ko": "대파를 볶다가 밥을 넣고 주걱으로 세게 눌러가며 볶아요.", "en": "Stir-fry green onion, add rice and press hard with spatula while tossing."},
                {"ko": "계란을 다시 넣고 간장·소금으로 간을 맞춰 30초 더 볶아요.", "en": "Return eggs, season with soy sauce and salt, stir-fry 30 more seconds."},
            ],
        },
        {
            "id": "shrimp-fried-rice",
            "name": {"ko": "새우볶음밥", "en": "Shrimp Fried Rice", "ja": "エビチャーハン", "zh": "虾仁炒饭"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "새우의 감칠맛이 더해진 고급스러운 볶음밥", "en": "Elevated fried rice with the rich flavor of shrimp"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "새우 (냉동 가능)", "amount": "8마리"},
                {"name": "계란", "amount": "1개"},
                {"name": "냉동 완두콩", "amount": "2큰술"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "새우는 해동 후 키친타월로 물기를 닦고 소금·후추로 밑간해요.", "en": "Thaw shrimp, pat dry, and season lightly with salt and pepper."},
                {"ko": "센불 팬에 기름 두르고 새우를 1분 볶아 꺼내요.", "en": "Stir-fry shrimp in a very hot oiled pan for 1 minute, then set aside."},
                {"ko": "계란을 스크램블한 뒤, 대파·밥을 넣고 센불에서 볶아요.", "en": "Scramble eggs, then add green onion and rice; stir-fry over high heat."},
                {"ko": "굴소스·간장을 넣어 볶고, 새우·완두콩을 넣어 30초 더 볶아요.", "en": "Add oyster sauce and soy sauce, return shrimp and peas, stir-fry 30 seconds."},
            ],
        },
        {
            "id": "three-delights-rice",
            "name": {"ko": "삼선볶음밥", "en": "Three Delights Fried Rice", "ja": "三鮮チャーハン", "zh": "三鲜炒饭"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "새우·오징어·채소의 삼박자가 맞는 고급 볶음밥", "en": "Premium fried rice with shrimp, squid, and vegetables"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "새우", "amount": "5마리"},
                {"name": "오징어", "amount": "1/4마리"},
                {"name": "당근", "amount": "1/8개"},
                {"name": "계란", "amount": "1개"},
                {"name": "굴소스", "amount": "1.5큰술"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "새우·오징어를 한 입 크기로, 당근은 작게 깍둑썰어요.", "en": "Cut shrimp and squid bite-sized; dice carrot small."},
                {"ko": "센불 팬에 기름 두르고 해물을 빠르게 볶아 꺼내요.", "en": "Stir-fry seafood quickly in a very hot pan; set aside."},
                {"ko": "당근을 볶다가 계란을 넣어 스크램블해요.", "en": "Stir-fry carrot, then add egg and scramble."},
                {"ko": "밥을 넣고 센불에서 주걱으로 누르며 볶아요.", "en": "Add rice and stir-fry over high heat, pressing with spatula."},
                {"ko": "해물을 다시 넣고 굴소스로 간해 30초 볶아요.", "en": "Return seafood, add oyster sauce, and stir-fry 30 seconds."},
            ],
        },
    ],
    "chinese/stirfry": [
        {
            "id": "mapo-tofu",
            "name": {"ko": "마파두부", "en": "Mapo Tofu", "ja": "麻婆豆腐", "zh": "麻婆豆腐"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "얼얼하고 칼칼한 사천식 두부 요리", "en": "Numbingly spicy Sichuan tofu dish"},
            "ingredients": [
                {"name": "두부 (연두부)", "amount": "1모"},
                {"name": "돼지고기 (다진 것)", "amount": "80g"},
                {"name": "두반장", "amount": "1.5큰술"},
                {"name": "다진 마늘·생강", "amount": "각 1작은술"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "참기름·고춧가루", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "두부는 2cm 큐브로 썰어 끓는 물에 1분 데쳐요. 모양이 잘 유지돼요.", "en": "Cut tofu into 2cm cubes and blanch in boiling water for 1 minute to hold shape."},
                {"ko": "팬에 기름 두르고 두반장·마늘·생강을 볶아 기름에 붉은색이 돌게 해요.", "en": "Stir-fry doubanjiang, garlic, and ginger until oil turns red."},
                {"ko": "다진 돼지고기를 넣고 볶아요.", "en": "Add ground pork and stir-fry."},
                {"ko": "물 1컵을 붓고 두부를 넣어 3분 끓여요.", "en": "Add 1 cup water, add tofu, and simmer 3 minutes."},
                {"ko": "전분물로 걸쭉하게 만들고 대파·참기름으로 마무리해요.", "en": "Thicken with starch slurry; finish with green onion and sesame oil."},
            ],
        },
        {
            "id": "tangsuyuk",
            "name": {"ko": "탕수육", "en": "Sweet & Sour Pork", "ja": "酢豚", "zh": "糖醋肉"},
            "time": 45, "difficulty": 3,
            "desc": {"ko": "바삭한 튀김에 새콤달콤 소스, 부먹 vs 찍먹 논쟁의 주인공", "en": "Crispy fried pork with tangy sweet sauce — pour or dip?"},
            "ingredients": [
                {"name": "돼지고기 (안심)", "amount": "200g"},
                {"name": "전분", "amount": "4큰술"},
                {"name": "계란", "amount": "1개"},
                {"name": "식초", "amount": "3큰술"},
                {"name": "설탕", "amount": "3큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "파인애플·당근·양파", "amount": "조금씩"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
            ],
            "steps": [
                {"ko": "돼지고기를 한 입 크기로 썰어 소금·후추로 밑간해요.", "en": "Cut pork into bite-sized pieces and season with salt and pepper."},
                {"ko": "계란·전분을 섞어 반죽을 만들고 고기에 입혀요.", "en": "Mix egg and starch into batter and coat pork."},
                {"ko": "170°C 기름에 5분 튀겨 꺼내고, 180°C에서 2분 더 튀겨 바삭하게 해요.", "en": "Deep-fry at 170°C for 5 minutes, remove, then fry again at 180°C for 2 minutes."},
                {"ko": "식초·설탕·간장·물(각 3큰술)을 끓이고 채소를 넣어 소스를 만들어요.", "en": "Boil vinegar, sugar, soy sauce, and water (3 tbsp each) with vegetables for the sauce."},
                {"ko": "전분물로 소스를 걸쭉하게 만든 뒤 고기에 붓거나 곁들여요.", "en": "Thicken sauce with starch slurry; pour over pork or serve on the side."},
            ],
        },
        {
            "id": "gganpunggi",
            "name": {"ko": "깐풍기", "en": "Dry Braised Spicy Chicken", "ja": "乾焼チキン", "zh": "干烹鸡"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "매콤달콤 소스가 닭에 쫙 배인 인기 중식 메뉴", "en": "Spicy-sweet sauce clings to every piece of chicken"},
            "ingredients": [
                {"name": "닭다리살", "amount": "250g"},
                {"name": "전분", "amount": "3큰술"},
                {"name": "건고추", "amount": "3개"},
                {"name": "다진 마늘·생강", "amount": "각 1작은술"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "고추기름", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "닭다리살을 한 입 크기로 썰어 소금·후추·전분을 묻혀요.", "en": "Cut chicken into pieces; coat with salt, pepper, and starch."},
                {"ko": "170°C 기름에 5분 튀겨요.", "en": "Deep-fry at 170°C for 5 minutes."},
                {"ko": "팬에 고추기름·건고추·마늘·생강을 볶아 향을 내요.", "en": "Stir-fry chili oil, dried chilies, garlic, and ginger until fragrant."},
                {"ko": "간장·설탕·식초를 넣고 소스를 만들어요.", "en": "Add soy sauce, sugar, and vinegar to make the sauce."},
                {"ko": "튀긴 닭을 넣고 소스가 배도록 센불에서 빠르게 볶아요.", "en": "Add fried chicken and toss over high heat until sauce is absorbed."},
            ],
        },
    ],
    "chinese/soup": [
        {
            "id": "egg-drop-soup",
            "name": {"ko": "계란탕", "en": "Egg Drop Soup", "ja": "玉子スープ", "zh": "蛋花汤"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "중식당 단골 수프, 집에서 5분이면 완성", "en": "Chinese restaurant staple ready in 5 minutes at home"},
            "ingredients": [
                {"name": "계란", "amount": "2개"},
                {"name": "닭육수 또는 물", "amount": "2컵"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "소금", "amount": "1/2작은술"},
                {"name": "참기름", "amount": "1/2작은술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "육수를 끓이고 소금으로 간해요.", "en": "Bring broth to a boil and season with salt."},
                {"ko": "전분을 물 2큰술에 풀어 넣고 살살 저어 걸쭉하게 만들어요.", "en": "Stir in starch dissolved in 2 tbsp water to thicken."},
                {"ko": "계란을 잘 풀어 가느다란 줄기로 천천히 부어요.", "en": "Beat eggs well and pour in a thin stream, stirring gently."},
                {"ko": "참기름을 뿌리고 쪽파로 마무리해요.", "en": "Drizzle sesame oil and garnish with green onion."},
            ],
        },
        {
            "id": "corn-soup",
            "name": {"ko": "옥수수 크림수프", "en": "Cream of Corn Soup", "ja": "コーンスープ", "zh": "奶油玉米汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "달콤하고 부드러운 크림옥수수수프", "en": "Sweet, creamy corn soup that's impossibly easy"},
            "ingredients": [
                {"name": "옥수수 크림 캔", "amount": "1캔(425g)"},
                {"name": "닭육수 또는 물", "amount": "1.5컵"},
                {"name": "계란", "amount": "1개"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "소금·설탕", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "냄비에 육수와 옥수수 크림을 넣고 끓여요.", "en": "Combine broth and canned corn cream in a pot; bring to a boil."},
                {"ko": "소금과 설탕으로 간을 맞춰요.", "en": "Season with salt and a pinch of sugar."},
                {"ko": "전분물을 넣어 살짝 걸쭉하게 만들어요.", "en": "Add starch slurry to thicken slightly."},
                {"ko": "풀어 놓은 계란을 가느다랗게 부어 실타래처럼 만들어요.", "en": "Drizzle beaten egg in a thin stream to create silky threads."},
            ],
        },
        {
            "id": "seafood-hotpot",
            "name": {"ko": "해물탕", "en": "Spicy Seafood Hotpot", "ja": "海鮮チゲ", "zh": "海鲜火锅"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "신선한 해물이 가득, 시원하고 매운 탕", "en": "Packed with fresh seafood — spicy and deeply savory"},
            "ingredients": [
                {"name": "새우·오징어·홍합", "amount": "각 적당량"},
                {"name": "고추장", "amount": "1큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "무", "amount": "1/4개"},
                {"name": "대파", "amount": "1/2대"},
                {"name": "물 또는 멸치육수", "amount": "3컵"},
            ],
            "steps": [
                {"ko": "무를 나박썰기하고 해물은 깨끗이 손질해요.", "en": "Slice radish thinly; clean and prep all seafood."},
                {"ko": "냄비에 물·무를 넣고 끓여 육수를 내요.", "en": "Boil water with radish to make a base stock."},
                {"ko": "고추장·고춧가루·마늘을 넣어 칼칼한 국물을 만들어요.", "en": "Add gochujang, chili flakes, and garlic for a spicy broth."},
                {"ko": "해물을 넣고 5-7분 끓여요. 홍합이 입을 벌리면 익은 거예요.", "en": "Add seafood and boil 5-7 minutes. Mussels are done when they open."},
                {"ko": "대파를 넣고 마무리해요.", "en": "Finish with green onion and serve."},
            ],
        },
    ],
    "chinese/dim": [
        {
            "id": "steamed-dumplings",
            "name": {"ko": "찐만두", "en": "Steamed Dumplings", "ja": "蒸し餃子", "zh": "蒸饺"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "쫄깃한 피와 육즙이 가득한 찐만두", "en": "Juicy dumplings with chewy steamed wrappers"},
            "ingredients": [
                {"name": "만두피 (두꺼운 것)", "amount": "20장"},
                {"name": "돼지고기 (다진 것)", "amount": "150g"},
                {"name": "배추 (절여서)", "amount": "100g"},
                {"name": "부추 또는 쪽파", "amount": "30g"},
                {"name": "다진 생강", "amount": "1작은술"},
                {"name": "간장·참기름·소금", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "배추는 소금에 절여 물기를 꼭 짜요.", "en": "Salt cabbage, let sit, then squeeze out all moisture."},
                {"ko": "돼지고기·배추·부추·생강·양념을 잘 섞어 소를 만들어요.", "en": "Mix pork, cabbage, chives, ginger, and seasonings for the filling."},
                {"ko": "만두피에 소를 올리고 주름을 잡아 예쁘게 빚어요.", "en": "Fill wrappers and pleat to seal."},
                {"ko": "찜기 바닥에 면포를 깔고 만두를 올려요.", "en": "Line steamer with cloth and arrange dumplings."},
                {"ko": "센불로 물을 끓인 뒤 중불에서 12-15분 쪄요.", "en": "Bring water to a boil, then steam over medium heat 12-15 minutes."},
            ],
        },
        {
            "id": "spring-rolls",
            "name": {"ko": "춘권", "en": "Spring Rolls", "ja": "春巻き", "zh": "春卷"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "바삭한 튀김옷 속에 각종 채소가 가득", "en": "Crispy shells packed with colorful vegetables"},
            "ingredients": [
                {"name": "춘권피", "amount": "10장"},
                {"name": "돼지고기 (채썰기)", "amount": "80g"},
                {"name": "당근·양배추·당면", "amount": "각 50g"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간"},
                {"name": "밀가루 풀 (밀가루+물)", "amount": "2큰술씩"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
            ],
            "steps": [
                {"ko": "당면을 불리고, 채소와 고기를 채 썰어요.", "en": "Soak glass noodles; julienne vegetables and pork."},
                {"ko": "팬에 고기 볶고, 채소·당면·굴소스를 넣고 볶아 소를 만들어요.", "en": "Stir-fry pork, then add vegetables, noodles, and oyster sauce for filling."},
                {"ko": "소를 한 김 식힌 뒤 춘권피에 올리고 돌돌 말아요.", "en": "Cool filling slightly, place on wrapper and roll tightly."},
                {"ko": "끝부분을 밀가루 풀로 붙여요.", "en": "Seal the end with flour paste."},
                {"ko": "170°C 기름에 황금색이 될 때까지 3-4분 튀겨요.", "en": "Deep-fry at 170°C until golden, about 3-4 minutes."},
            ],
        },
    ],
}
