RECIPES_EXTRA2 = {
    # ── 한식 추가 ────────────────────────────────────────────────
    "korean/rice": [
        {
            "id": "tuna-mayo-rice",
            "name": {"ko": "참치마요덮밥", "en": "Tuna Mayo Rice Bowl", "ja": "ツナマヨ丼", "zh": "金枪鱼蛋黄酱饭"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "캔참치 하나로 뚝딱, 가장 쉬운 덮밥", "en": "Easiest rice bowl with canned tuna and mayo", "ja": "缶詰めツナで作る一番簡単な丼", "zh": "用罐头金枪鱼做的最简单盖饭"},
            "ingredients": [
                {"name": "따뜻한 밥", "amount": "1공기"},
                {"name": "참치캔", "amount": "1개 (150g)"},
                {"name": "마요네즈", "amount": "2큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "김 가루", "amount": "약간"},
            ],
            "steps": [
                {"ko": "참치캔의 기름을 최대한 빼요.", "en": "Drain the tuna can as much as possible.", "ja": "ツナ缶の油をできるだけ切ります。", "zh": "尽量将金枪鱼罐头中的油沥干。"},
                {"ko": "참치에 마요네즈·간장을 넣고 잘 섞어요.", "en": "Mix tuna with mayo and soy sauce.", "ja": "ツナにマヨネーズと醤油を入れてよく混ぜます。", "zh": "将金枪鱼与蛋黄酱和酱油混合均匀。"},
                {"ko": "따뜻한 밥 위에 참치마요를 올려요.", "en": "Spoon tuna mayo over hot rice.", "ja": "温かいご飯の上にツナマヨを乗せます。", "zh": "将金枪鱼蛋黄酱盖在热饭上。"},
                {"ko": "쪽파와 김 가루를 뿌려 완성이에요.", "en": "Top with green onions and nori flakes.", "ja": "ネギと青海苔をかけて完成です。", "zh": "撒上小葱和海苔碎即完成。"},
            ],
        },
        {
            "id": "curry-rice",
            "name": {"ko": "카레라이스", "en": "Japanese-style Curry Rice", "ja": "カレーライス", "zh": "咖喱饭"},
            "time": 35, "difficulty": 1,
            "desc": {"ko": "시판 카레 루로 누구나 성공하는 부드러운 카레", "en": "Foolproof curry with store-bought roux", "ja": "市販のルーで誰でも成功するカレー", "zh": "用市售咖喱块轻松制作的香浓咖喱"},
            "ingredients": [
                {"name": "카레 루 (시판)", "amount": "3조각"},
                {"name": "감자", "amount": "1개"},
                {"name": "당근", "amount": "1/2개"},
                {"name": "양파", "amount": "1개"},
                {"name": "돼지고기 또는 닭고기", "amount": "150g"},
                {"name": "물", "amount": "500ml"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "감자·당근·양파를 한 입 크기로 썰고 고기도 썰어요.", "en": "Cut potato, carrot, onion, and meat into bite-sized pieces.", "ja": "じゃがいも・にんじん・玉ねぎを一口大に切り、肉も切ります。", "zh": "将土豆、胡萝卜、洋葱和肉切成适口大小。"},
                {"ko": "냄비에 기름 두르고 양파를 투명해질 때까지 볶아요.", "en": "Sauté onion in oil until translucent.", "ja": "鍋に油を引き、玉ねぎが透明になるまで炒めます。", "zh": "锅中倒油，翻炒洋葱至透明。"},
                {"ko": "고기를 넣고 겉이 익을 때까지 볶아요.", "en": "Add meat and cook until the outside is done.", "ja": "肉を加えて表面が焼けるまで炒めます。", "zh": "加入肉，翻炒至表面变色。"},
                {"ko": "감자·당근·물을 넣고 재료가 부드러워질 때까지 20분 끓여요.", "en": "Add potato, carrot, and water; boil 20 minutes until tender.", "ja": "じゃがいも・にんじん・水を入れて20分煮ます。", "zh": "加入土豆、胡萝卜和水，煮20分钟至软烂。"},
                {"ko": "불을 끄고 카레 루를 녹여 잘 섞은 뒤 5분 더 끓여요.", "en": "Turn off heat, dissolve roux, stir well, then simmer 5 more minutes.", "ja": "火を止めてルーを溶かしてよく混ぜ、さらに5分煮ます。", "zh": "关火后溶入咖喱块搅拌均匀，再煮5分钟。"},
            ],
        },
        {
            "id": "egg-bowl",
            "name": {"ko": "계란덮밥", "en": "Egg Rice Bowl", "ja": "卵丼", "zh": "鸡蛋盖饭"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "달걀과 간장만으로 만드는 초간단 덮밥", "en": "Super simple egg bowl with just eggs and soy sauce", "ja": "卵と醤油だけで作る超簡単丼", "zh": "只需鸡蛋和酱油的超简单盖饭"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "계란", "amount": "2개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "간장", "amount": "1.5큰술"},
                {"name": "미림 또는 설탕", "amount": "1큰술"},
                {"name": "물", "amount": "4큰술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "양파를 얇게 썰어요.", "en": "Thinly slice the onion.", "ja": "玉ねぎを薄く切ります。", "zh": "将洋葱切薄片。"},
                {"ko": "작은 냄비에 간장·미림·물을 넣고 끓이다가 양파를 넣어 2분 익혀요.", "en": "Combine soy sauce, mirin, and water in a small pot; boil then add onion and cook 2 minutes.", "ja": "小鍋に醤油・みりん・水を入れて煮立て、玉ねぎを加えて2分煮ます。", "zh": "小锅中加入酱油、味醂和水煮沸，加入洋葱煮2分钟。"},
                {"ko": "계란을 풀어 양파 위에 원을 그리며 부어요.", "en": "Beat eggs and pour in a circular motion over the onion.", "ja": "卵を溶いて玉ねぎの上に円を描くように流し入れます。", "zh": "将鸡蛋打散，以画圆的方式淋在洋葱上。"},
                {"ko": "뚜껑 덮고 반숙이 될 때까지 30초만 익혀요.", "en": "Cover and cook just 30 seconds until soft-set.", "ja": "蓋をして30秒だけ加熱して半熟にします。", "zh": "盖上锅盖仅加热30秒至半熟。"},
                {"ko": "밥 위에 올리고 쪽파를 뿌려요.", "en": "Slide over rice and top with green onions.", "ja": "ご飯の上に乗せてネギをかけます。", "zh": "盖在米饭上，撒上小葱。"},
            ],
        },
        {
            "id": "kongnamul-bap",
            "name": {"ko": "콩나물밥", "en": "Bean Sprout Rice", "ja": "もやしご飯", "zh": "豆芽饭"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "솥에 한 번에 짓는 콩나물밥, 양념장이 핵심", "en": "One-pot rice with bean sprouts; the dipping sauce is key", "ja": "一鍋で炊くもやしご飯、タレが決め手", "zh": "一锅煮的豆芽饭，蘸汁是关键"},
            "ingredients": [
                {"name": "쌀", "amount": "1컵"},
                {"name": "콩나물", "amount": "150g"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "쌀을 씻어 물에 30분 불려요.", "en": "Rinse rice and soak in water 30 minutes.", "ja": "米を洗って30分浸水させます。", "zh": "将米洗净，在水中浸泡30分钟。"},
                {"ko": "냄비에 불린 쌀과 동량의 물을 넣고 콩나물을 위에 올려요.", "en": "Put soaked rice and equal amount water in pot; pile bean sprouts on top.", "ja": "鍋に浸水させた米と同量の水を入れ、もやしを上に乗せます。", "zh": "锅中放入泡好的米和等量的水，将豆芽堆在上面。"},
                {"ko": "강불로 끓이다가 끓으면 약불로 줄여 15분 뜸 들여요. 절대 뚜껑 열지 마세요.", "en": "Bring to boil over high heat, reduce to low and steam 15 minutes without opening the lid.", "ja": "強火で煮立て、沸騰したら弱火にして15分蒸らします。絶対蓋を開けないでください。", "zh": "大火煮沸后转小火焖15分钟，绝对不要开盖。"},
                {"ko": "그동안 간장·고춧가루·마늘·참기름·쪽파로 양념장을 만들어요.", "en": "Meanwhile, mix soy sauce, chili flakes, garlic, sesame oil, and green onion for the sauce.", "ja": "その間に醤油・唐辛子粉・にんにく・ごま油・ネギでタレを作ります。", "zh": "同时用酱油、辣椒粉、蒜末、芝麻油和小葱制作蘸汁。"},
                {"ko": "밥과 콩나물을 섞고 양념장을 곁들여 드세요.", "en": "Mix rice and bean sprouts together and serve with the sauce.", "ja": "ご飯ともやしを混ぜてタレを添えてお召し上がりください。", "zh": "将米饭和豆芽搅拌均匀，配上蘸汁食用。"},
            ],
        },
    ],
    "korean/soup": [
        {
            "id": "miyeok-guk",
            "name": {"ko": "미역국", "en": "Seaweed Soup", "ja": "ワカメスープ", "zh": "海带汤"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "생일에 꼭 먹는 그 국, 소고기 미역국", "en": "Birthday staple — seaweed soup with beef", "ja": "誕生日に欠かせないわかめスープ", "zh": "生日必喝的海带汤"},
            "ingredients": [
                {"name": "건미역", "amount": "15g"},
                {"name": "소고기 (양지 or 국거리)", "amount": "80g"},
                {"name": "국간장", "amount": "1.5큰술"},
                {"name": "참기름", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "물", "amount": "4컵"},
            ],
            "steps": [
                {"ko": "미역은 찬물에 10분 불린 뒤 먹기 좋게 잘라요.", "en": "Soak dried seaweed in cold water 10 minutes, then cut into pieces.", "ja": "乾燥わかめを冷水に10分浸けてから食べやすい大きさに切ります。", "zh": "将干海带在冷水中浸泡10分钟，然后切成适口大小。"},
                {"ko": "냄비에 참기름을 두르고 소고기를 볶아요.", "en": "Stir-fry beef in sesame oil.", "ja": "鍋にごま油を引いて牛肉を炒めます。", "zh": "锅中倒入芝麻油，翻炒牛肉。"},
                {"ko": "미역과 마늘을 넣고 2분 더 볶아요.", "en": "Add seaweed and garlic; stir-fry 2 more minutes.", "ja": "わかめとにんにくを加えてさらに2分炒めます。", "zh": "加入海带和大蒜，再翻炒2分钟。"},
                {"ko": "물을 붓고 15분 끓여요.", "en": "Pour in water and boil 15 minutes.", "ja": "水を注いで15分煮ます。", "zh": "倒入水，煮15分钟。"},
                {"ko": "국간장으로 간을 맞춰요.", "en": "Season with soup soy sauce.", "ja": "薄口醤油で味を整えます。", "zh": "用汤用酱油调味。"},
            ],
        },
        {
            "id": "kongnamul-guk",
            "name": {"ko": "콩나물국", "en": "Bean Sprout Soup", "ja": "もやしスープ", "zh": "豆芽汤"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "숙취 해소에 최고, 시원하고 깔끔한 국", "en": "Best hangover cure — clean and refreshing broth", "ja": "二日酔いに最高のさっぱりスープ", "zh": "解酒最佳选择，清爽鲜美的汤"},
            "ingredients": [
                {"name": "콩나물", "amount": "200g"},
                {"name": "물", "amount": "3컵"},
                {"name": "국간장", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "쪽파·고춧가루", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "콩나물을 씻어요.", "en": "Rinse bean sprouts.", "ja": "もやしを洗います。", "zh": "洗净豆芽。"},
                {"ko": "냄비에 물과 콩나물을 넣고 뚜껑 덮어 강불로 끓여요. 끓기 전엔 뚜껑 열지 마세요 (비린내 방지).", "en": "Add water and bean sprouts, cover and boil on high. Don't lift the lid before boiling (prevents fishy smell).", "ja": "鍋に水ともやしを入れて蓋をして強火で煮ます。沸騰前は蓋を開けないでください（生臭さ防止）。", "zh": "锅中加入水和豆芽，盖上锅盖大火煮沸。沸腾前不要开盖（防止腥味）。"},
                {"ko": "끓으면 마늘을 넣고 5분 더 끓여요.", "en": "Once boiling, add garlic and boil 5 more minutes.", "ja": "沸騰したらにんにくを加えてさらに5分煮ます。", "zh": "沸腾后加入大蒜，再煮5分钟。"},
                {"ko": "국간장·소금으로 간하고 쪽파·고춧가루를 올려요.", "en": "Season with soy sauce and salt; garnish with green onion and chili flakes.", "ja": "醤油と塩で味を整え、ネギと唐辛子粉をかけます。", "zh": "用酱油和盐调味，撒上小葱和辣椒粉。"},
            ],
        },
        {
            "id": "budae-jjigae",
            "name": {"ko": "부대찌개", "en": "Army Base Stew", "ja": "部隊チゲ", "zh": "部队锅"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "햄·소시지·라면 다 넣는 푸짐한 찌개", "en": "Hearty stew loaded with ham, sausage, and ramen", "ja": "ハム・ソーセージ・ラーメン入りのボリューム満点チゲ", "zh": "加入火腿、香肠和拉面的丰盛火锅"},
            "ingredients": [
                {"name": "스팸 또는 햄", "amount": "100g"},
                {"name": "소시지", "amount": "2개"},
                {"name": "김치", "amount": "100g"},
                {"name": "두부", "amount": "1/4모"},
                {"name": "라면 사리", "amount": "1개"},
                {"name": "고추장", "amount": "1큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "물", "amount": "2컵"},
            ],
            "steps": [
                {"ko": "햄·소시지·두부·김치를 먹기 좋게 썰어요.", "en": "Slice ham, sausage, tofu, and kimchi.", "ja": "ハム・ソーセージ・豆腐・キムチを食べやすい大きさに切ります。", "zh": "将火腿、香肠、豆腐和泡菜切成适口大小。"},
                {"ko": "냄비에 재료를 보기 좋게 담고 고추장·고춧가루·마늘을 올려요.", "en": "Arrange all ingredients in the pot and top with gochujang, chili flakes, and garlic.", "ja": "鍋に材料を見栄えよく並べ、コチュジャン・唐辛子粉・にんにくをのせます。", "zh": "将食材整齐摆入锅中，顶部放上辣椒酱、辣椒粉和大蒜。"},
                {"ko": "물을 붓고 중강불에서 끓여요.", "en": "Add water and bring to a boil over medium-high heat.", "ja": "水を注いで中強火で煮ます。", "zh": "倒入水，用中大火煮沸。"},
                {"ko": "끓으면 라면 사리를 넣고 면이 익을 때까지 3분 더 끓여요.", "en": "Add ramen noodles and cook 3 more minutes until done.", "ja": "沸騰したらラーメンを加えて麺が煮えるまでさらに3分煮ます。", "zh": "沸腾后加入拉面，再煮3分钟至面条熟透。"},
            ],
        },
        {
            "id": "tteok-guk",
            "name": {"ko": "떡국", "en": "Rice Cake Soup", "ja": "トックク", "zh": "年糕汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "설날의 맛, 쫄깃한 떡국", "en": "Lunar New Year classic with chewy rice cake slices", "ja": "お正月の味、もちもちトック", "zh": "农历新年传统美食，软糯年糕汤"},
            "ingredients": [
                {"name": "흰 떡 (얇게 썬 것)", "amount": "200g"},
                {"name": "사골육수 또는 멸치육수", "amount": "4컵"},
                {"name": "계란", "amount": "1개"},
                {"name": "국간장", "amount": "1큰술"},
                {"name": "소금", "amount": "약간"},
                {"name": "김 가루·쪽파", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "떡을 찬물에 10분 담가 불려요.", "en": "Soak rice cake slices in cold water for 10 minutes.", "ja": "餅を冷水に10分浸けてふやかします。", "zh": "将年糕片在冷水中浸泡10分钟。"},
                {"ko": "육수를 끓이고 국간장으로 간해요.", "en": "Bring broth to a boil and season with soup soy sauce.", "ja": "出汁を煮立て、薄口醤油で味を整えます。", "zh": "将高汤煮沸，用汤用酱油调味。"},
                {"ko": "떡을 넣고 떠오를 때까지 5분 끓여요.", "en": "Add rice cakes and boil 5 minutes until they float.", "ja": "餅を加えて浮き上がるまで5分煮ます。", "zh": "加入年糕，煮5分钟直到浮起。"},
                {"ko": "계란을 풀어 가늘게 부어가며 저어요.", "en": "Beat egg and pour in a thin stream while stirring.", "ja": "卵を溶いて細く流しながらかき混ぜます。", "zh": "将鸡蛋打散，细细倒入并搅拌。"},
                {"ko": "그릇에 담고 김 가루·쪽파를 올려요.", "en": "Serve topped with nori flakes and green onions.", "ja": "器に盛り、青海苔とネギをかけます。", "zh": "盛入碗中，撒上海苔碎和小葱。"},
            ],
        },
    ],
    "korean/grill": [
        {
            "id": "samgyeopsal",
            "name": {"ko": "삼겹살 구이", "en": "Grilled Pork Belly", "ja": "サムギョプサル", "zh": "五花肉烤肉"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "집에서도 즐기는 삼겹살, 쌈 채소와 함께", "en": "Home-grilled pork belly served with wrapping vegetables", "ja": "家でも楽しめるサムギョプサル、野菜巻き", "zh": "在家享受的五花肉烤肉，配蔬菜包着吃"},
            "ingredients": [
                {"name": "삼겹살", "amount": "200g"},
                {"name": "상추·깻잎", "amount": "한 줌씩"},
                {"name": "쌈장", "amount": "2큰술"},
                {"name": "마늘", "amount": "4쪽"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "삼겹살을 0.5cm 두께로 썰어요.", "en": "Slice pork belly to about 0.5cm thickness.", "ja": "豚バラ肉を約0.5cmの厚さに切ります。", "zh": "将五花肉切成约0.5cm厚的片。"},
                {"ko": "팬이나 그릴 팬을 강불로 달궈요.", "en": "Heat a pan or grill pan over high heat.", "ja": "フライパンまたはグリルパンを強火で熱します。", "zh": "将平底锅或烤盘用大火加热。"},
                {"ko": "삼겹살을 올리고 소금·후추를 뿌려 양면을 노릇하게 구워요.", "en": "Add pork belly, season with salt and pepper, and grill until golden on both sides.", "ja": "豚バラ肉を乗せて塩こしょうを振り、両面こんがり焼きます。", "zh": "放入五花肉，撒上盐和胡椒，煎至两面金黄。"},
                {"ko": "마늘도 함께 구워요.", "en": "Grill garlic cloves alongside.", "ja": "にんにくも一緒に焼きます。", "zh": "同时烤大蒜。"},
                {"ko": "상추나 깻잎에 밥·고기·마늘·쌈장을 올려 싸서 드세요.", "en": "Wrap rice, meat, garlic, and ssamjang in lettuce or perilla leaves.", "ja": "サンチュや大葉にご飯・肉・にんにく・サムジャンを乗せて包んで食べます。", "zh": "用生菜或紫苏叶包裹米饭、肉、大蒜和包饭酱食用。"},
            ],
        },
        {
            "id": "ojingeo-bokkeum",
            "name": {"ko": "오징어볶음", "en": "Spicy Stir-fried Squid", "ja": "イカの辛炒め", "zh": "辣炒鱿鱼"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "칼칼하고 쫄깃한 오징어볶음, 밥 두 그릇 각오", "en": "Chewy, fiery squid stir-fry — you'll want extra rice", "ja": "コリコリ辛いイカ炒め、ご飯が進む", "zh": "鲜嫩辣爽的炒鱿鱼，让人多吃两碗饭"},
            "ingredients": [
                {"name": "오징어", "amount": "1마리"},
                {"name": "양파", "amount": "1/2개"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "참기름·쪽파", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "오징어는 내장을 제거하고 몸통은 링 모양, 다리는 먹기 좋게 잘라요.", "en": "Remove innards from squid; slice body into rings and cut legs into pieces.", "ja": "イカの内臓を取り除き、胴体はリング状に、足は食べやすい大きさに切ります。", "zh": "去除鱿鱼内脏，身体切成圆圈状，腿切成适口大小。"},
                {"ko": "고추장·고춧가루·간장·설탕·마늘을 섞어 양념을 만들어요.", "en": "Mix gochujang, chili flakes, soy sauce, sugar, and garlic for the sauce.", "ja": "コチュジャン・唐辛子粉・醤油・砂糖・にんにくを混ぜてタレを作ります。", "zh": "将辣椒酱、辣椒粉、酱油、砂糖和大蒜混合制作酱料。"},
                {"ko": "팬을 강불로 달구고 양파를 먼저 볶아요.", "en": "Heat pan on high and stir-fry onion first.", "ja": "フライパンを強火で熱し、まず玉ねぎを炒めます。", "zh": "大火加热锅，先翻炒洋葱。"},
                {"ko": "오징어를 넣고 양념을 붓고 센불에서 빠르게 2~3분 볶아요.", "en": "Add squid and sauce; stir-fry quickly on high heat for 2-3 minutes.", "ja": "イカを加えてタレを注ぎ、強火で素早く2〜3分炒めます。", "zh": "加入鱿鱼和酱料，大火快速翻炒2-3分钟。"},
                {"ko": "참기름을 뿌리고 쪽파를 올려요.", "en": "Drizzle sesame oil and top with green onions.", "ja": "ごま油を回しかけてネギを乗せます。", "zh": "淋上芝麻油，撒上小葱。"},
            ],
        },
        {
            "id": "gyeranmari",
            "name": {"ko": "계란말이", "en": "Korean Rolled Omelette", "ja": "卵焼き", "zh": "韩式蛋卷"},
            "time": 10, "difficulty": 2,
            "desc": {"ko": "김밥 속 단골 메뉴, 폭신하고 달큰한 계란말이", "en": "Fluffy sweet rolled egg, a classic in Korean lunchboxes", "ja": "ふわふわ甘い卵焼き、お弁当の定番", "zh": "松软香甜的蛋卷，便当的经典配菜"},
            "ingredients": [
                {"name": "계란", "amount": "3개"},
                {"name": "당근", "amount": "약간 (다진 것)"},
                {"name": "쪽파", "amount": "약간 (다진 것)"},
                {"name": "소금", "amount": "한 꼬집"},
                {"name": "설탕", "amount": "1/2작은술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "계란에 다진 당근·쪽파·소금·설탕을 넣고 잘 풀어요.", "en": "Beat eggs with minced carrot, green onion, salt, and sugar.", "ja": "卵にみじん切りのにんじん・ネギ・塩・砂糖を入れてよく溶きます。", "zh": "鸡蛋中加入切碎的胡萝卜、小葱、盐和砂糖，充分打散。"},
                {"ko": "팬에 기름을 얇게 두르고 약불로 달궈요.", "en": "Lightly oil a pan and heat over low heat.", "ja": "フライパンに薄く油を引いて弱火で熱します。", "zh": "平底锅薄薄涂一层油，用小火加热。"},
                {"ko": "계란물의 1/3을 붓고 반숙 상태에서 한쪽으로 말아요.", "en": "Pour in 1/3 of egg mixture; while still soft, roll toward one side.", "ja": "卵液の1/3を流し入れ、半熟の状態で片側に巻きます。", "zh": "倒入1/3的蛋液，在半熟状态下向一侧卷起。"},
                {"ko": "말아 놓은 계란을 팬 한쪽으로 밀고 남은 계란물을 부어 다시 말아요.", "en": "Push the roll to one side, pour more egg, and roll again onto the previous roll.", "ja": "巻いた卵を端に寄せ、残りの卵液を注いでまた巻きます。", "zh": "将卷好的蛋推到一侧，倒入剩余蛋液再次卷起。"},
                {"ko": "남은 계란물도 같은 방법으로 말아요. 식히면 더 모양이 잘 잡혀요.", "en": "Repeat with remaining egg. Let cool for better shape.", "ja": "残りの卵液も同じ方法で巻きます。冷ますと形がきれいに整います。", "zh": "用同样方法处理剩余蛋液。冷却后形状更好。"},
            ],
        },
        {
            "id": "dakbokkeum-tang",
            "name": {"ko": "닭볶음탕", "en": "Spicy Braised Chicken", "ja": "タッポックムタン", "zh": "辣焖鸡"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "칼칼하게 조린 닭고기, 감자와 당근이 포인트", "en": "Fiery braised chicken with potato and carrot", "ja": "カリカリ辛煮込みチキン、じゃがいもにんじん入り", "zh": "辣味红烧鸡，配土豆和胡萝卜"},
            "ingredients": [
                {"name": "닭 (토막 낸 것)", "amount": "500g"},
                {"name": "감자", "amount": "1개"},
                {"name": "당근", "amount": "1/2개"},
                {"name": "양파", "amount": "1/2개"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "물", "amount": "1컵"},
            ],
            "steps": [
                {"ko": "닭을 끓는 물에 2분 데쳐 핏물을 빼요.", "en": "Blanch chicken in boiling water for 2 minutes to remove blood.", "ja": "鶏肉を沸騰したお湯で2分茹でて血抜きをします。", "zh": "将鸡肉在沸水中焯2分钟去血水。"},
                {"ko": "감자·당근·양파를 큼직하게 썰어요.", "en": "Cut potato, carrot, and onion into large chunks.", "ja": "じゃがいも・にんじん・玉ねぎを大きめに切ります。", "zh": "将土豆、胡萝卜和洋葱切成大块。"},
                {"ko": "볼에 고추장·고춧가루·간장·마늘·설탕을 섞어 양념을 만들어요.", "en": "Mix gochujang, chili flakes, soy sauce, garlic, and sugar for the sauce.", "ja": "ボウルにコチュジャン・唐辛子粉・醤油・にんにく・砂糖を混ぜてタレを作ります。", "zh": "在碗中混合辣椒酱、辣椒粉、酱油、大蒜和砂糖制作酱料。"},
                {"ko": "냄비에 닭·채소·양념·물을 넣고 강불로 끓여요.", "en": "Combine chicken, vegetables, sauce, and water in a pot; bring to boil on high.", "ja": "鍋に鶏肉・野菜・タレ・水を入れて強火で煮ます。", "zh": "将鸡肉、蔬菜、酱料和水放入锅中，大火煮沸。"},
                {"ko": "끓으면 중불로 줄여 뚜껑 덮고 25분 익혀요.", "en": "Reduce to medium, cover, and cook 25 minutes.", "ja": "沸騰したら中火に下げて蓋をして25分煮ます。", "zh": "沸腾后转中火，盖上锅盖煮25分钟。"},
            ],
        },
    ],
    "korean/kimchi": [
        {
            "id": "kkakdugi",
            "name": {"ko": "깍두기", "en": "Cubed Radish Kimchi", "ja": "カクテキ", "zh": "萝卜泡菜"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "아삭하게 깍둑 썬 무 김치, 설렁탕·삼계탕의 단짝", "en": "Crunchy cubed radish kimchi — perfect with broth soups", "ja": "サクサクの大根キムチ、クッパの名コンビ", "zh": "爽脆的萝卜泡菜，是各种汤品的最佳搭配"},
            "ingredients": [
                {"name": "무", "amount": "500g"},
                {"name": "고춧가루", "amount": "3큰술"},
                {"name": "새우젓", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "다진 생강", "amount": "1/2작은술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "쪽파", "amount": "2대"},
                {"name": "소금", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "무를 2cm 크기로 깍둑 썰고 소금에 20분 절여요.", "en": "Cube radish into 2cm pieces and salt for 20 minutes.", "ja": "大根を2cm角に切り、塩で20分漬けます。", "zh": "将萝卜切成2cm的小块，用盐腌制20分钟。"},
                {"ko": "절인 무의 물을 꽉 짜요.", "en": "Squeeze out excess water from salted radish.", "ja": "塩漬け大根の水分をしっかり絞ります。", "zh": "将腌好的萝卜中的水分挤干。"},
                {"ko": "고춧가루를 먼저 무에 버무려 빨갛게 물을 들여요.", "en": "Toss radish with chili flakes first until evenly red.", "ja": "まず唐辛子粉を大根に和えて赤く色をつけます。", "zh": "先将辣椒粉与萝卜拌匀，染成红色。"},
                {"ko": "새우젓·마늘·생강·설탕·쪽파를 넣고 잘 버무려요.", "en": "Add salted shrimp, garlic, ginger, sugar, and green onion; mix well.", "ja": "塩エビ・にんにく・しょうが・砂糖・ネギを加えてよく和えます。", "zh": "加入虾酱、大蒜、姜、砂糖和小葱，充分拌匀。"},
                {"ko": "통에 담아 실온 하루 발효 후 냉장 보관해요.", "en": "Pack into a container, ferment at room temperature 1 day, then refrigerate.", "ja": "容器に入れ、室温で1日発酵させてから冷蔵保存します。", "zh": "装入容器，在室温下发酵1天后冷藏保存。"},
            ],
        },
        {
            "id": "oi-muchim",
            "name": {"ko": "오이무침", "en": "Spicy Cucumber Salad", "ja": "きゅうりの辛和え", "zh": "拌黄瓜"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "5분 만에 완성하는 아삭아삭 오이 반찬", "en": "Crunchy Korean cucumber salad done in 5 minutes", "ja": "5分でできるサクサクきゅうりのおかず", "zh": "5分钟搞定的爽脆黄瓜小菜"},
            "ingredients": [
                {"name": "오이", "amount": "1개"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "식초", "amount": "1작은술"},
                {"name": "설탕", "amount": "1/2작은술"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "참기름·깨", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "오이를 0.5cm 두께로 어슷 썰어요.", "en": "Cut cucumber diagonally into 0.5cm slices.", "ja": "きゅうりを0.5cm厚さの斜め切りにします。", "zh": "将黄瓜斜切成0.5cm厚的片。"},
                {"ko": "소금 1/2작은술로 5분 절였다가 물기를 꽉 짜요.", "en": "Salt lightly and leave 5 minutes, then squeeze out water.", "ja": "小さじ1/2の塩で5分漬けてから水分をしっかり絞ります。", "zh": "用1/2小勺盐腌制5分钟，然后挤干水分。"},
                {"ko": "고춧가루·간장·식초·설탕·마늘을 넣고 버무려요.", "en": "Toss with chili flakes, soy sauce, vinegar, sugar, and garlic.", "ja": "唐辛子粉・醤油・酢・砂糖・にんにくを加えて和えます。", "zh": "加入辣椒粉、酱油、醋、砂糖和大蒜拌匀。"},
                {"ko": "참기름과 깨를 뿌려 완성이에요.", "en": "Finish with sesame oil and sesame seeds.", "ja": "ごま油とごまを振って完成です。", "zh": "撒上芝麻油和芝麻即完成。"},
            ],
        },
        {
            "id": "gamja-jorim",
            "name": {"ko": "감자조림", "en": "Braised Sweet Soy Potatoes", "ja": "じゃがいもの甘辛煮", "zh": "酱焖土豆"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "달콤 짭짤하게 조린 감자, 도시락 단골 반찬", "en": "Sweet and salty braised potatoes — a lunchbox staple", "ja": "甘じょっぱい煮じゃがいも、お弁当の定番おかず", "zh": "甜咸入味的焖土豆，便当常见小菜"},
            "ingredients": [
                {"name": "감자", "amount": "2개"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "물엿 또는 올리고당", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "물", "amount": "4큰술"},
                {"name": "참기름·깨", "amount": "약간씩"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "감자를 2cm 크기로 깍둑 썰어 찬물에 10분 담가 전분을 빼요.", "en": "Cube potato into 2cm pieces and soak in cold water 10 minutes to remove starch.", "ja": "じゃがいもを2cm角に切り、冷水に10分浸けてデンプンを抜きます。", "zh": "将土豆切成2cm小块，在冷水中浸泡10分钟去除淀粉。"},
                {"ko": "물기를 닦고 팬에 기름 두르고 감자를 중불로 살짝 볶아요.", "en": "Pat dry and stir-fry potato in oil over medium heat briefly.", "ja": "水気を拭いてフライパンに油を引き、じゃがいもを中火で軽く炒めます。", "zh": "擦干水分，锅中倒油，用中火轻炒土豆。"},
                {"ko": "간장·설탕·물엿·마늘·물을 넣고 약불에서 뚜껑 덮어 10분 조려요.", "en": "Add soy sauce, sugar, syrup, garlic, and water; cover and simmer on low 10 minutes.", "ja": "醤油・砂糖・水飴・にんにく・水を加えて弱火で蓋をして10分煮詰めます。", "zh": "加入酱油、砂糖、糖浆、大蒜和水，盖上锅盖用小火焖10分钟。"},
                {"ko": "뚜껑 열고 강불로 윤기 나게 조려요.", "en": "Uncover and cook on high to glaze.", "ja": "蓋を取って強火でつやが出るまで煮詰めます。", "zh": "开盖用大火收汁至光亮。"},
                {"ko": "참기름과 깨를 뿌려요.", "en": "Finish with sesame oil and seeds.", "ja": "ごま油とごまを振ります。", "zh": "撒上芝麻油和芝麻。"},
            ],
        },
        {
            "id": "kongnamul-muchim",
            "name": {"ko": "콩나물무침", "en": "Seasoned Bean Sprouts", "ja": "もやしナムル", "zh": "凉拌豆芽"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "비빔밥 속 필수 나물, 고소하고 아삭한 콩나물무침", "en": "Bibimbap essential — nutty and crisp seasoned bean sprouts", "ja": "ビビンバに欠かせない、香ばしくシャキシャキのもやしナムル", "zh": "拌饭必备，香脆可口的凉拌豆芽"},
            "ingredients": [
                {"name": "콩나물", "amount": "200g"},
                {"name": "소금", "amount": "1/2작은술"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "깨", "amount": "약간"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "끓는 물에 소금 한 꼬집을 넣고 콩나물을 3분 데쳐요.", "en": "Blanch bean sprouts in salted boiling water for 3 minutes.", "ja": "ひとつまみの塩を入れた沸騰したお湯でもやしを3分茹でます。", "zh": "在加了一撮盐的沸水中将豆芽焯3分钟。"},
                {"ko": "찬물에 헹궈 물기를 꽉 짜요.", "en": "Rinse in cold water and squeeze out moisture.", "ja": "冷水で洗って水分をしっかり絞ります。", "zh": "用冷水冲洗，挤干水分。"},
                {"ko": "소금·마늘·참기름을 넣고 조물조물 무쳐요.", "en": "Season with salt, garlic, and sesame oil; mix gently.", "ja": "塩・にんにく・ごま油を加えてやさしく和えます。", "zh": "加入盐、大蒜和芝麻油，轻轻拌匀。"},
                {"ko": "깨와 쪽파를 뿌려 완성이에요.", "en": "Top with sesame seeds and green onions.", "ja": "ごまとネギをかけて完成です。", "zh": "撒上芝麻和小葱即完成。"},
            ],
        },
    ],
    "korean/noodle": [
        {
            "id": "bibim-guksu",
            "name": {"ko": "비빔국수", "en": "Spicy Cold Noodles", "ja": "ビビム麺", "zh": "拌面"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "여름에 먹는 시원하고 새콤달콤한 비빔국수", "en": "Sweet, spicy, tangy cold noodles perfect for summer", "ja": "夏に食べる甘辛酸っぱい冷やし麺", "zh": "夏日必吃的甜辣酸爽拌面"},
            "ingredients": [
                {"name": "소면", "amount": "1인분 (90g)"},
                {"name": "고추장", "amount": "1.5큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "오이", "amount": "1/4개"},
                {"name": "계란 (삶은 것)", "amount": "1개"},
            ],
            "steps": [
                {"ko": "소면을 끓는 물에 4분 삶아 찬물에 여러 번 헹궈요.", "en": "Boil somen 4 minutes, rinse thoroughly in cold water.", "ja": "素麺を沸騰したお湯で4分茹でて冷水で何度も洗います。", "zh": "将素面在沸水中煮4分钟，用冷水多次冲洗。"},
                {"ko": "고추장·식초·설탕·간장·참기름을 섞어 양념장을 만들어요.", "en": "Mix gochujang, vinegar, sugar, soy sauce, and sesame oil for the sauce.", "ja": "コチュジャン・酢・砂糖・醤油・ごま油を混ぜてタレを作ります。", "zh": "将辣椒酱、醋、砂糖、酱油和芝麻油混合制作酱料。"},
                {"ko": "오이를 채 썰어요.", "en": "Julienne the cucumber.", "ja": "きゅうりを千切りにします。", "zh": "将黄瓜切成细丝。"},
                {"ko": "면의 물기를 빼고 양념장으로 버무려요.", "en": "Drain noodles and toss with sauce.", "ja": "麺の水気を切ってタレで和えます。", "zh": "沥干面条，用酱料拌匀。"},
                {"ko": "그릇에 담고 오이와 반숙 달걀을 올려요.", "en": "Plate and top with cucumber and a soft-boiled egg.", "ja": "器に盛り、きゅうりと半熟卵をのせます。", "zh": "盛盘，顶部放上黄瓜和半熟蛋。"},
            ],
        },
        {
            "id": "janchi-guksu",
            "name": {"ko": "잔치국수", "en": "Banquet Noodle Soup", "ja": "ジャンチグクス", "zh": "宴会面"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "잔치·생일에 먹는 따뜻한 멸치 국물 소면", "en": "Warm somen in anchovy broth served at celebrations", "ja": "お祝いの場で食べる温かいアンチョビ出汁素麺", "zh": "庆典生日必备的温热鳀鱼汤素面"},
            "ingredients": [
                {"name": "소면", "amount": "1인분 (90g)"},
                {"name": "멸치다시마육수", "amount": "2컵"},
                {"name": "애호박", "amount": "1/4개"},
                {"name": "당근", "amount": "약간"},
                {"name": "계란", "amount": "1개"},
                {"name": "국간장·소금", "amount": "약간씩"},
                {"name": "식용유", "amount": "약간"},
            ],
            "steps": [
                {"ko": "호박·당근을 채 썰어요.", "en": "Julienne zucchini and carrot.", "ja": "ズッキーニとにんじんを千切りにします。", "zh": "将西葫芦和胡萝卜切成细丝。"},
                {"ko": "팬에 기름 두르고 각각 살짝 볶고 소금 간해요.", "en": "Sauté each separately with a little oil and salt.", "ja": "フライパンに油を引いてそれぞれ別々に軽く炒め、塩で味付けします。", "zh": "锅中倒油，分别轻炒并用盐调味。"},
                {"ko": "계란은 황백을 분리해 지단을 부쳐 채 썰어요.", "en": "Separate egg yolk and white, make thin omelettes, and cut into strips.", "ja": "卵を黄身と白身に分けて薄焼き卵を作り、細切りにします。", "zh": "将蛋黄和蛋白分开，分别摊成薄蛋皮，切成细条。"},
                {"ko": "소면을 삶아 찬물에 헹군 뒤 그릇에 담아요.", "en": "Boil somen, rinse in cold water, and place in bowl.", "ja": "素麺を茹でて冷水でよく洗い、器に盛ります。", "zh": "将素面煮熟，用冷水冲洗后盛入碗中。"},
                {"ko": "끓인 육수를 국간장으로 간하고 면 위에 부어요. 고명을 올려요.", "en": "Season hot broth with soup soy sauce and pour over noodles. Top with garnishes.", "ja": "煮立てた出汁を薄口醤油で整え、麺の上に注ぎます。具材をのせます。", "zh": "将煮沸的高汤用汤用酱油调味，浇在面上，再放上配料。"},
            ],
        },
        {
            "id": "rabokki",
            "name": {"ko": "라볶이", "en": "Rabokki (Ramen Tteokbokki)", "ja": "ラポッキ", "zh": "拉炒年糕"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "라면+떡볶이의 환상 조합, 편의점 단골 메뉴", "en": "Ramen meets tteokbokki — a beloved convenience-store combo", "ja": "ラーメン＋トッポッキの最強コンビ", "zh": "拉面与炒年糕的完美组合，便利店经典"},
            "ingredients": [
                {"name": "떡볶이 떡", "amount": "150g"},
                {"name": "라면 사리", "amount": "1개"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "물", "amount": "2컵"},
                {"name": "쪽파·깨", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "냄비에 물·고추장·간장·설탕을 넣고 끓여요.", "en": "Boil water with gochujang, soy sauce, and sugar.", "ja": "鍋に水・コチュジャン・醤油・砂糖を入れて煮ます。", "zh": "锅中加入水、辣椒酱、酱油和砂糖煮沸。"},
                {"ko": "떡을 넣고 5분 끓여요.", "en": "Add rice cakes and boil 5 minutes.", "ja": "餅を加えて5分煮ます。", "zh": "加入年糕煮5分钟。"},
                {"ko": "라면 사리를 넣고 2분 더 끓여요.", "en": "Add ramen noodles and cook 2 more minutes.", "ja": "ラーメンを加えてさらに2分煮ます。", "zh": "加入拉面再煮2分钟。"},
                {"ko": "쪽파와 깨를 뿌려요.", "en": "Top with green onion and sesame seeds.", "ja": "ネギとごまをかけます。", "zh": "撒上小葱和芝麻。"},
            ],
        },
        {
            "id": "jjol-myeon",
            "name": {"ko": "쫄면", "en": "Chewy Spicy Cold Noodles", "ja": "チョルミョン", "zh": "韩式劲道凉面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "탱탱 쫄깃한 면발에 새콤달콤 양념, 여름 별미", "en": "Springy noodles in sweet-spicy sauce, a summer treat", "ja": "もちもち麺に甘辛ダレ、夏のご馳走", "zh": "Q弹面条配甜辣酱，夏日美味"},
            "ingredients": [
                {"name": "쫄면 사리", "amount": "1인분"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "콩나물·오이·양배추", "amount": "약간씩"},
                {"name": "삶은 계란", "amount": "1개"},
            ],
            "steps": [
                {"ko": "쫄면을 끓는 물에 4~5분 삶아 찬물에 헹궈요.", "en": "Boil chewy noodles 4-5 minutes; rinse in cold water.", "ja": "太麺を沸騰したお湯で4〜5分茹でて冷水で洗います。", "zh": "将劲道面条在沸水中煮4-5分钟，用冷水冲洗。"},
                {"ko": "콩나물을 데치고 오이·양배추는 채 썰어요.", "en": "Blanch bean sprouts; julienne cucumber and cabbage.", "ja": "もやしを茹でてきゅうり・キャベツを千切りにします。", "zh": "焯烫豆芽；将黄瓜和卷心菜切成细丝。"},
                {"ko": "고추장·식초·설탕·간장·참기름을 섞어 양념을 만들어요.", "en": "Mix gochujang, vinegar, sugar, soy sauce, and sesame oil.", "ja": "コチュジャン・酢・砂糖・醤油・ごま油を混ぜてタレを作ります。", "zh": "将辣椒酱、醋、砂糖、酱油和芝麻油混合制作酱料。"},
                {"ko": "면과 채소를 그릇에 담고 양념을 올려요.", "en": "Arrange noodles and vegetables in a bowl; top with sauce.", "ja": "麺と野菜を器に盛り、タレをのせます。", "zh": "将面条和蔬菜盛入碗中，淋上酱料。"},
                {"ko": "삶은 계란을 반으로 잘라 올리고 잘 비벼 드세요.", "en": "Add halved boiled egg and toss everything together.", "ja": "ゆで卵を半分に切ってのせてよく混ぜて食べます。", "zh": "放上对半切的煮蛋，搅拌均匀后食用。"},
            ],
        },
    ],
    # ── 일식 추가 ────────────────────────────────────────────────
    "japanese/sushi": [
        {
            "id": "inari-sushi",
            "name": {"ko": "유부초밥", "en": "Inari Sushi", "ja": "いなり寿司", "zh": "稻荷寿司"},
            "time": 30, "difficulty": 1,
            "desc": {"ko": "달콤하게 조린 유부 안에 초밥을 채운 소풍 도시락", "en": "Sweet braised tofu pockets stuffed with sushi rice", "ja": "甘く煮た油揚げに酢飯を詰めたピクニック弁当", "zh": "甜味油豆腐皮包裹醋饭，野餐便当首选"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "유부 (사각)", "amount": "6장"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "설탕", "amount": "2큰술"},
                {"name": "미림", "amount": "1큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "소금", "amount": "한 꼬집"},
                {"name": "깨", "amount": "약간"},
            ],
            "steps": [
                {"ko": "유부를 끓는 물에 1분 데쳐 기름기를 뺀 뒤 꽉 짜요.", "en": "Blanch tofu pockets 1 minute to remove oil; squeeze dry.", "ja": "油揚げを沸騰したお湯で1分茹でて油抜きし、しっかり絞ります。", "zh": "将油豆腐皮在沸水中焯1分钟去油，然后挤干。"},
                {"ko": "냄비에 간장·설탕·미림·물 4큰술을 넣고 유부를 15분 조려요.", "en": "Simmer tofu pockets in soy sauce, sugar, mirin, and 4 tbsp water for 15 minutes.", "ja": "鍋に醤油・砂糖・みりん・水大さじ4を入れて油揚げを15分煮ます。", "zh": "锅中加入酱油、砂糖、味醂和4大勺水，将油豆腐皮煮15分钟。"},
                {"ko": "따뜻한 밥에 식초·소금을 넣고 섞어 초밥을 만들어요.", "en": "Mix warm rice with vinegar and salt to make sushi rice.", "ja": "温かいご飯に酢と塩を混ぜて酢飯を作ります。", "zh": "在温热米饭中加入醋和盐，拌匀做成醋饭。"},
                {"ko": "유부를 반으로 갈라 초밥을 채워요.", "en": "Open each tofu pocket and stuff with sushi rice.", "ja": "油揚げを半分に開いて酢飯を詰めます。", "zh": "将油豆腐皮从中间打开，填入醋饭。"},
                {"ko": "깨를 뿌려 완성이에요.", "en": "Sprinkle with sesame seeds.", "ja": "ごまを振って完成です。", "zh": "撒上芝麻即完成。"},
            ],
        },
        {
            "id": "onigiri",
            "name": {"ko": "오니기리", "en": "Onigiri (Rice Ball)", "ja": "おにぎり", "zh": "饭团"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "일본 편의점의 상징, 집에서 만드는 주먹밥", "en": "Japan's iconic convenience-store rice ball made at home", "ja": "コンビニの象徴、家で作るおにぎり", "zh": "日本便利店标志性食品，在家自制饭团"},
            "ingredients": [
                {"name": "따뜻한 밥", "amount": "2공기"},
                {"name": "참치캔 + 마요네즈", "amount": "1캔 + 1큰술"},
                {"name": "소금", "amount": "약간"},
                {"name": "구운 김", "amount": "2장"},
                {"name": "참기름", "amount": "약간 (선택)"},
            ],
            "steps": [
                {"ko": "참치 기름을 빼고 마요네즈와 섞어 속재료를 만들어요.", "en": "Drain tuna and mix with mayo for the filling.", "ja": "ツナの油を切りマヨネーズと混ぜて具を作ります。", "zh": "沥干金枪鱼油，与蛋黄酱混合制作馅料。"},
                {"ko": "손에 물을 묻히고 소금을 살짝 묻혀요.", "en": "Wet hands and coat lightly with salt.", "ja": "手を濡らして塩を軽くつけます。", "zh": "用水沾湿双手，薄薄涂上一层盐。"},
                {"ko": "밥 한 움큼을 평평하게 펴고 속재료를 가운데 올려요.", "en": "Flatten a handful of rice and place filling in the center.", "ja": "一握りのご飯を平らに広げて中央に具を乗せます。", "zh": "将一把米饭摊平，在中间放上馅料。"},
                {"ko": "삼각형이나 원형으로 꽉 쥐어 모양을 만들어요.", "en": "Mold into a triangle or round shape, pressing firmly.", "ja": "三角形または丸型にしっかり握って形を作ります。", "zh": "捏成三角形或圆形，用力压实。"},
                {"ko": "김을 적당히 잘라 겉을 감싸요.", "en": "Wrap with a strip of nori.", "ja": "海苔を適当な大きさに切って外側を巻きます。", "zh": "将海苔剪成适当大小，包裹外侧。"},
            ],
        },
        {
            "id": "temaki",
            "name": {"ko": "테마키", "en": "Temaki Hand Roll", "ja": "手巻き寿司", "zh": "手卷寿司"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "나만의 재료로 마는 원뿔형 수제 초밥", "en": "DIY cone sushi — fill with whatever you like", "ja": "好きな具材を巻くコーン型手巻き寿司", "zh": "自由搭配食材的圆锥形手卷寿司"},
            "ingredients": [
                {"name": "초밥용 밥", "amount": "1공기"},
                {"name": "연어 (회용)", "amount": "80g"},
                {"name": "아보카도", "amount": "1/2개"},
                {"name": "오이", "amount": "1/4개"},
                {"name": "구운 김", "amount": "4장"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕·소금", "amount": "약간씩"},
                {"name": "간장·고추냉이", "amount": "취향껏"},
            ],
            "steps": [
                {"ko": "밥에 식초·설탕·소금을 섞어 초밥 밥을 만들어요.", "en": "Mix rice with vinegar, sugar, and salt for sushi rice.", "ja": "ご飯に酢・砂糖・塩を混ぜて酢飯を作ります。", "zh": "将米饭与醋、砂糖和盐混合制成醋饭。"},
                {"ko": "연어·아보카도·오이를 길쭉하게 썰어요.", "en": "Cut salmon, avocado, and cucumber into long strips.", "ja": "サーモン・アボカド・きゅうりを細長く切ります。", "zh": "将三文鱼、牛油果和黄瓜切成长条。"},
                {"ko": "김 한 장을 손바닥에 올리고 밥을 왼쪽에만 얇게 펴요.", "en": "Place nori in hand; spread rice on the left half only.", "ja": "手の上に海苔を1枚乗せて左半分だけにご飯を薄く広げます。", "zh": "将一张海苔放在手掌上，只在左半部分薄薄铺上米饭。"},
                {"ko": "재료를 대각선으로 올려요.", "en": "Lay fillings diagonally across the rice.", "ja": "具材を斜めに乗せます。", "zh": "将馅料斜放在米饭上。"},
                {"ko": "원뿔 모양으로 말아서 간장과 고추냉이에 찍어 드세요.", "en": "Roll into a cone shape and dip in soy sauce with wasabi.", "ja": "円錐形に巻いて醤油とわさびに付けて食べます。", "zh": "卷成圆锥形，蘸酱油和芥末食用。"},
            ],
        },
        {
            "id": "california-roll",
            "name": {"ko": "캘리포니아롤", "en": "California Roll", "ja": "カリフォルニアロール", "zh": "加州卷"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "게맛살·아보카도·오이의 클래식 역방향 롤", "en": "Classic inside-out roll with crab, avocado, and cucumber", "ja": "カニカマ・アボカド・きゅうりの定番裏巻き", "zh": "蟹肉棒、牛油果和黄瓜的经典反卷"},
            "ingredients": [
                {"name": "초밥용 밥", "amount": "1공기"},
                {"name": "게맛살", "amount": "2줄"},
                {"name": "아보카도", "amount": "1/2개"},
                {"name": "오이", "amount": "1/4개"},
                {"name": "구운 김", "amount": "2장"},
                {"name": "마요네즈", "amount": "1큰술"},
                {"name": "식초·설탕·소금", "amount": "약간씩"},
                {"name": "깨", "amount": "약간"},
            ],
            "steps": [
                {"ko": "밥을 식초·설탕·소금으로 간해요.", "en": "Season rice with vinegar, sugar, and salt.", "ja": "ご飯を酢・砂糖・塩で味付けします。", "zh": "用醋、砂糖和盐给米饭调味。"},
                {"ko": "게맛살·아보카도·오이를 길게 썰어요.", "en": "Cut crab sticks, avocado, and cucumber into long strips.", "ja": "カニカマ・アボカド・きゅうりを長く切ります。", "zh": "将蟹肉棒、牛油果和黄瓜切成长条。"},
                {"ko": "김발 위에 랩을 깔고 밥을 김 위에 얇게 펴요.", "en": "Lay plastic wrap on rolling mat; spread rice on nori.", "ja": "巻き簾の上にラップを敷いて海苔の上にご飯を薄く広げます。", "zh": "在卷帘上铺保鲜膜，将米饭薄薄铺在海苔上。"},
                {"ko": "뒤집어서 재료와 마요네즈를 가운데 올려요.", "en": "Flip over; place fillings and mayo in the center.", "ja": "ひっくり返して具材とマヨネーズを中央に乗せます。", "zh": "翻转过来，将馅料和蛋黄酱放在中间。"},
                {"ko": "꽉 눌러가며 말아 8조각으로 잘라요.", "en": "Roll firmly and cut into 8 pieces.", "ja": "しっかり押しながら巻いて8切れに切ります。", "zh": "用力卷起，切成8块。"},
            ],
        },
    ],
    "japanese/ramen": [
        {
            "id": "miso-ramen",
            "name": {"ko": "미소라멘", "en": "Miso Ramen", "ja": "味噌ラーメン", "zh": "味噌拉面"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "구수한 된장 베이스의 일본 라멘", "en": "Rich miso-based Japanese ramen", "ja": "こくのある味噌ベースの日本ラーメン", "zh": "浓郁味噌底汤日式拉面"},
            "ingredients": [
                {"name": "라멘 면 (생면 또는 건면)", "amount": "1인분"},
                {"name": "된장 (일본 백미소)", "amount": "2큰술"},
                {"name": "닭 육수", "amount": "400ml"},
                {"name": "돼지고기 (슬라이스)", "amount": "60g"},
                {"name": "옥수수 (캔)", "amount": "2큰술"},
                {"name": "버터", "amount": "1작은술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "냄비에 버터를 녹이고 마늘·돼지고기를 볶아요.", "en": "Melt butter and stir-fry garlic and pork.", "ja": "鍋にバターを溶かし、にんにくと豚肉を炒めます。", "zh": "锅中融化黄油，翻炒大蒜和猪肉。"},
                {"ko": "육수를 붓고 끓여요.", "en": "Add broth and bring to a boil.", "ja": "スープを注いで煮ます。", "zh": "倒入高汤，煮沸。"},
                {"ko": "된장을 국자로 풀어가며 넣고 잘 섞어요.", "en": "Dissolve miso into the broth using a ladle.", "ja": "味噌をお玉で溶かしながら加えてよく混ぜます。", "zh": "用勺子将味噌溶入汤中，搅拌均匀。"},
                {"ko": "면을 삶아 그릇에 담고 수프를 부어요.", "en": "Cook noodles and place in bowl; pour soup over.", "ja": "麺を茹でて器に盛り、スープを注ぎます。", "zh": "将面条煮熟盛入碗中，倒入汤料。"},
                {"ko": "옥수수·버터 한 조각·쪽파를 올려요.", "en": "Top with corn, a pat of butter, and green onions.", "ja": "コーン・バター一切れ・ネギをのせます。", "zh": "放上玉米、一块黄油和小葱。"},
            ],
        },
        {
            "id": "yaki-udon",
            "name": {"ko": "야키우동", "en": "Yaki Udon", "ja": "焼きうどん", "zh": "炒乌冬面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "굵은 우동을 간장 소스로 볶은 간단 요리", "en": "Thick udon stir-fried in a savory soy sauce", "ja": "太麺うどんを醤油ソースで炒めた簡単料理", "zh": "粗乌冬面用酱油炒制的简单料理"},
            "ingredients": [
                {"name": "우동 사리", "amount": "1인분"},
                {"name": "돼지고기 (슬라이스)", "amount": "80g"},
                {"name": "양배추", "amount": "2장"},
                {"name": "당근", "amount": "약간"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "참기름·가쓰오부시", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "우동을 끓는 물에 1분 데쳐 풀어요.", "en": "Blanch udon in boiling water for 1 minute to loosen.", "ja": "うどんを沸騰したお湯で1分茹でてほぐします。", "zh": "将乌冬面在沸水中焯1分钟使其松散。"},
                {"ko": "팬에 기름 두르고 돼지고기를 볶다가 채소를 넣어요.", "en": "Stir-fry pork in oil, then add vegetables.", "ja": "フライパンに油を引いて豚肉を炒めてから野菜を加えます。", "zh": "锅中倒油翻炒猪肉，然后加入蔬菜。"},
                {"ko": "우동을 넣고 간장·굴소스로 간해요.", "en": "Add udon and season with soy sauce and oyster sauce.", "ja": "うどんを加えて醤油とオイスターソースで味付けします。", "zh": "加入乌冬面，用酱油和蚝油调味。"},
                {"ko": "센불로 잘 볶아요.", "en": "Stir-fry on high heat.", "ja": "強火でよく炒めます。", "zh": "大火翻炒均匀。"},
                {"ko": "참기름을 뿌리고 가쓰오부시를 올려요.", "en": "Drizzle sesame oil and top with bonito flakes.", "ja": "ごま油を回しかけてかつお節をのせます。", "zh": "淋上芝麻油，撒上木鱼花。"},
            ],
        },
        {
            "id": "cold-soba",
            "name": {"ko": "자루소바", "en": "Cold Zaru Soba", "ja": "ざるそば", "zh": "竹篮荞麦凉面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "여름에 딱인 시원한 소바, 쯔유에 찍어 먹어요", "en": "Chilled buckwheat noodles served with tsuyu dipping sauce", "ja": "夏にぴったりの冷たいそば、つゆで食べる", "zh": "夏日必吃的冰凉荞麦面，配蘸汁享用"},
            "ingredients": [
                {"name": "소바 면", "amount": "1인분"},
                {"name": "쯔유 (시판)", "amount": "3큰술"},
                {"name": "물", "amount": "9큰술"},
                {"name": "와사비", "amount": "약간"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "김 가루", "amount": "약간"},
            ],
            "steps": [
                {"ko": "소바를 끓는 물에 3~4분 삶아요.", "en": "Boil soba noodles 3-4 minutes.", "ja": "そばを沸騰したお湯で3〜4分茹でます。", "zh": "将荞麦面在沸水中煮3-4分钟。"},
                {"ko": "찬물에 여러 번 헹궈 전분을 충분히 빼요.", "en": "Rinse thoroughly in cold water to remove starch.", "ja": "冷水で何度も洗ってデンプンをしっかり抜きます。", "zh": "用冷水多次冲洗，充分去除淀粉。"},
                {"ko": "얼음물에 담가 차갑게 해요.", "en": "Place in ice water to chill.", "ja": "氷水に浸けて冷やします。", "zh": "放入冰水中冷却。"},
                {"ko": "쯔유와 물을 3:9 비율로 섞어 소스를 만들어요.", "en": "Mix tsuyu and water in a 3:9 ratio for the dipping sauce.", "ja": "つゆと水を3:9の割合で混ぜてソースを作ります。", "zh": "将蘸汁与水按3:9的比例混合制作蘸料。"},
                {"ko": "소바를 대나무 채반(또는 그릇)에 담고 김·와사비·쪽파와 함께 즐겨요.", "en": "Serve soba on a bamboo mat or plate with nori, wasabi, and green onion.", "ja": "そばを竹のざる（または器）に盛り、海苔・わさび・ネギと一緒に楽しみます。", "zh": "将荞麦面盛在竹篓（或碗）中，配上海苔、芥末和小葱享用。"},
            ],
        },
        {
            "id": "nabeyaki-udon",
            "name": {"ko": "나베야키우동", "en": "Hot Udon Hot Pot", "ja": "鍋焼きうどん", "zh": "砂锅乌冬面"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "뚝배기에 끓여 먹는 따뜻한 일식 우동", "en": "Warm udon simmered in a clay pot with toppings", "ja": "土鍋で温かく食べる日本のうどん", "zh": "在砂锅中炖煮的温热日式乌冬面"},
            "ingredients": [
                {"name": "우동 사리", "amount": "1인분"},
                {"name": "닭고기 (슬라이스)", "amount": "60g"},
                {"name": "시금치", "amount": "한 줌"},
                {"name": "쯔유 또는 간장", "amount": "3큰술"},
                {"name": "물", "amount": "350ml"},
                {"name": "계란", "amount": "1개"},
                {"name": "어묵", "amount": "1장"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "물에 쯔유를 풀어 국물을 만들어요.", "en": "Dissolve tsuyu in water to make the broth.", "ja": "水にめんつゆを溶かしてスープを作ります。", "zh": "将蘸汁溶入水中制作汤底。"},
                {"ko": "뚝배기에 국물을 끓이다가 닭고기·어묵을 넣어요.", "en": "Bring broth to a boil in a clay pot; add chicken and fish cake.", "ja": "土鍋でスープを煮立て、鶏肉とさつま揚げを加えます。", "zh": "在砂锅中将汤底煮沸，加入鸡肉和鱼饼。"},
                {"ko": "우동 사리를 넣고 3분 끓여요.", "en": "Add udon and cook 3 minutes.", "ja": "うどんを加えて3分煮ます。", "zh": "加入乌冬面煮3分钟。"},
                {"ko": "시금치를 올리고 중앙에 계란을 깨 넣어요.", "en": "Add spinach and crack an egg in the center.", "ja": "ほうれん草をのせて中央に卵を割り入れます。", "zh": "放上菠菜，在中间打入一个鸡蛋。"},
                {"ko": "계란이 원하는 익힘으로 됐을 때 쪽파 뿌려 바로 드세요.", "en": "When egg is cooked to your liking, top with green onions and serve immediately.", "ja": "卵がお好みの固さになったらネギをかけてすぐに食べます。", "zh": "当鸡蛋煮至喜欢的程度时，撒上小葱立即享用。"},
            ],
        },
    ],
    "japanese/donburi": [
        {
            "id": "shogayaki-don",
            "name": {"ko": "쇼가야키동", "en": "Ginger Pork Rice Bowl", "ja": "生姜焼き丼", "zh": "姜汁猪肉盖饭"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "생강향 나는 돼지고기 덮밥, 일식의 정석", "en": "Classic Japanese ginger-marinated pork over rice", "ja": "生姜の香りが食欲をそそる豚丼", "zh": "姜香浓郁的日式猪肉盖饭"},
            "ingredients": [
                {"name": "돼지고기 (슬라이스)", "amount": "150g"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "미림", "amount": "2큰술"},
                {"name": "생강즙", "amount": "1큰술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "양파", "amount": "1/2개"},
                {"name": "밥", "amount": "1공기"},
            ],
            "steps": [
                {"ko": "간장·미림·생강즙·설탕을 섞어 양념을 만들어요.", "en": "Mix soy sauce, mirin, ginger juice, and sugar for the marinade.", "ja": "醤油・みりん・生姜汁・砂糖を混ぜてタレを作ります。", "zh": "将酱油、味醂、姜汁和砂糖混合制作腌料。"},
                {"ko": "돼지고기를 양념에 10분 재워요.", "en": "Marinate pork for 10 minutes.", "ja": "豚肉をタレに10分漬けます。", "zh": "将猪肉在腌料中腌制10分钟。"},
                {"ko": "팬에 기름 두르고 양파를 볶아요.", "en": "Stir-fry onion in oil.", "ja": "フライパンに油を引いて玉ねぎを炒めます。", "zh": "锅中倒油，翻炒洋葱。"},
                {"ko": "돼지고기를 양념째 넣고 센불에서 볶아요.", "en": "Add pork with marinade and stir-fry on high heat.", "ja": "豚肉をタレごと加えて強火で炒めます。", "zh": "将猪肉连同腌料一起加入，大火翻炒。"},
                {"ko": "밥 위에 올려 완성이에요.", "en": "Serve over rice.", "ja": "ご飯の上に乗せて完成です。", "zh": "盖在米饭上即完成。"},
            ],
        },
        {
            "id": "salmon-don",
            "name": {"ko": "연어덮밥", "en": "Salmon Don", "ja": "サーモン丼", "zh": "三文鱼盖饭"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "신선한 연어를 얹은 간단하고 고급스러운 덮밥", "en": "Fresh salmon over sushi rice — simple and elegant", "ja": "新鮮なサーモンを乗せたシンプルで上品な丼", "zh": "新鲜三文鱼配醋饭，简单优雅"},
            "ingredients": [
                {"name": "연어 (회용 또는 스시용)", "amount": "120g"},
                {"name": "밥", "amount": "1공기"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1/2작은술"},
                {"name": "소금", "amount": "한 꼬집"},
                {"name": "간장·와사비", "amount": "취향껏"},
                {"name": "쪽파·깨", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "밥에 식초·설탕·소금을 섞어 초밥 밥을 만들어요.", "en": "Mix rice with vinegar, sugar, and salt to make sushi rice.", "ja": "ご飯に酢・砂糖・塩を混ぜて酢飯を作ります。", "zh": "将米饭与醋、砂糖和盐混合制成醋饭。"},
                {"ko": "연어를 먹기 좋게 슬라이스해요.", "en": "Slice salmon into serving pieces.", "ja": "サーモンを食べやすい大きさにスライスします。", "zh": "将三文鱼切成适口大小的薄片。"},
                {"ko": "그릇에 밥을 담고 연어를 예쁘게 올려요.", "en": "Place rice in bowl and arrange salmon on top.", "ja": "器にご飯を盛り、サーモンをきれいに乗せます。", "zh": "将米饭盛入碗中，将三文鱼漂亮地摆在上面。"},
                {"ko": "쪽파와 깨를 뿌리고 간장·와사비를 곁들여요.", "en": "Top with green onion and sesame seeds; serve with soy sauce and wasabi.", "ja": "ネギとごまをかけて醤油とわさびを添えます。", "zh": "撒上小葱和芝麻，配上酱油和芥末。"},
            ],
        },
        {
            "id": "natto-don",
            "name": {"ko": "낫토덮밥", "en": "Natto Rice Bowl", "ja": "納豆丼", "zh": "纳豆盖饭"},
            "time": 5, "difficulty": 1,
            "desc": {"ko": "5분 완성, 낫토 특유의 향이 매력적인 건강 덮밥", "en": "5-minute healthy bowl — natto's distinctive flavor grows on you", "ja": "5分完成、納豆の独特な香りが魅力の健康丼", "zh": "5分钟完成，纳豆独特风味的健康盖饭"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "낫토", "amount": "1팩"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "겨자 (낫토 포함)", "amount": "약간"},
                {"name": "계란 노른자", "amount": "1개"},
                {"name": "쪽파·김 가루", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "낫토에 포함된 간장·겨자를 넣고 끈기가 생길 때까지 잘 저어요.", "en": "Add the included soy sauce and mustard to natto; stir vigorously until sticky.", "ja": "付属の醤油とからしを納豆に加え、粘りが出るまでよく混ぜます。", "zh": "将附赠的酱油和芥末加入纳豆，搅拌至产生黏性。"},
                {"ko": "따뜻한 밥 위에 낫토를 올려요.", "en": "Spoon natto over warm rice.", "ja": "温かいご飯の上に納豆を乗せます。", "zh": "将纳豆盖在温热米饭上。"},
                {"ko": "계란 노른자를 가운데 올려요.", "en": "Place egg yolk in the center.", "ja": "卵黄を中央に乗せます。", "zh": "将蛋黄放在中间。"},
                {"ko": "쪽파와 김 가루를 뿌리고 잘 비벼 드세요.", "en": "Top with green onion and nori flakes; mix well before eating.", "ja": "ネギと青海苔をかけてよく混ぜて食べます。", "zh": "撒上小葱和海苔碎，搅拌均匀后食用。"},
            ],
        },
        {
            "id": "karaage-don",
            "name": {"ko": "가라아게동", "en": "Karaage Chicken Rice Bowl", "ja": "唐揚げ丼", "zh": "炸鸡盖饭"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "바삭한 일본식 닭튀김을 올린 든든한 덮밥", "en": "Hearty bowl topped with crispy Japanese fried chicken", "ja": "カリカリ唐揚げをのせたボリューム満点丼", "zh": "搭配酥脆日式炸鸡的丰盛盖饭"},
            "ingredients": [
                {"name": "닭 허벅지살", "amount": "200g"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "미림", "amount": "1큰술"},
                {"name": "다진 마늘·생강", "amount": "각 1작은술"},
                {"name": "전분", "amount": "4큰술"},
                {"name": "튀김용 식용유", "amount": "충분히"},
                {"name": "밥", "amount": "1공기"},
                {"name": "레몬·마요네즈", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "닭고기를 한 입 크기로 잘라 간장·미림·마늘·생강에 15분 재워요.", "en": "Cut chicken into pieces and marinate in soy sauce, mirin, garlic, and ginger for 15 minutes.", "ja": "鶏肉を一口大に切り、醤油・みりん・にんにく・生姜に15分漬けます。", "zh": "将鸡肉切成适口大小，在酱油、味醂、大蒜和姜中腌制15分钟。"},
                {"ko": "전분을 골고루 묻혀요.", "en": "Coat evenly with potato starch.", "ja": "片栗粉を全体にまぶします。", "zh": "均匀裹上淀粉。"},
                {"ko": "170°C 기름에서 5분 튀겨요. 꺼내서 2분 후 다시 넣어 1분 더 튀겨요.", "en": "Fry at 170°C for 5 minutes. Remove, rest 2 minutes, then fry 1 more minute.", "ja": "170°Cの油で5分揚げます。取り出して2分休ませてからもう1分揚げます。", "zh": "在170°C的油中炸5分钟，取出休息2分钟后再炸1分钟。"},
                {"ko": "밥 위에 올리고 레몬즙을 뿌려요.", "en": "Serve over rice with a squeeze of lemon.", "ja": "ご飯の上に乗せてレモン汁をかけます。", "zh": "盖在米饭上，挤上柠檬汁。"},
                {"ko": "마요네즈를 곁들여 드세요.", "en": "Serve with mayonnaise on the side.", "ja": "マヨネーズを添えて食べます。", "zh": "配上蛋黄酱食用。"},
            ],
        },
    ],
    "japanese/tempura": [
        {
            "id": "vegetable-tempura",
            "name": {"ko": "야채튀김", "en": "Vegetable Tempura", "ja": "野菜の天ぷら", "zh": "蔬菜天妇罗"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "바삭한 튀김옷을 입은 계절 채소 모둠 튀김", "en": "Seasonal vegetables in light crispy tempura batter", "ja": "サクサクの衣をまとった季節野菜の盛り合わせ天ぷら", "zh": "裹着酥脆面衣的时令蔬菜天妇罗"},
            "ingredients": [
                {"name": "고구마·가지·브로콜리·피망", "amount": "각 50g"},
                {"name": "박력분", "amount": "100g"},
                {"name": "계란", "amount": "1개"},
                {"name": "얼음물", "amount": "150ml"},
                {"name": "튀김용 식용유", "amount": "충분히"},
                {"name": "쯔유", "amount": "취향껏"},
            ],
            "steps": [
                {"ko": "채소를 먹기 좋게 썰어 물기를 닦아요.", "en": "Cut vegetables into serving pieces and pat dry.", "ja": "野菜を食べやすい大きさに切り、水気を拭きます。", "zh": "将蔬菜切成适口大小，擦干水分。"},
                {"ko": "계란과 얼음물을 먼저 섞고 박력분을 넣어 날가루가 안 보일 정도만 가볍게 섞어요 (덜 섞어야 바삭해요).", "en": "Whisk egg and ice water first, add flour and mix lightly until just combined — don't overmix.", "ja": "卵と氷水を先に混ぜ、薄力粉を加えて粉が見えなくなる程度に軽く混ぜます（混ぜすぎるとサクサクになりません）。", "zh": "先将鸡蛋和冰水混合，加入低筋面粉轻轻搅拌至看不到干粉即可（过度搅拌会影响酥脆度）。"},
                {"ko": "채소에 튀김옷을 얇게 입혀요.", "en": "Coat vegetables lightly with batter.", "ja": "野菜に衣を薄くつけます。", "zh": "将蔬菜薄薄裹上面衣。"},
                {"ko": "180°C 기름에서 2~3분 튀겨 노릇해지면 꺼내요.", "en": "Fry at 180°C for 2-3 minutes until golden.", "ja": "180°Cの油で2〜3分揚げて黄金色になったら取り出します。", "zh": "在180°C的油中炸2-3分钟至金黄色。"},
                {"ko": "쯔유에 무 간 것을 넣어 찍어 드세요.", "en": "Serve with tsuyu dipping sauce and grated daikon.", "ja": "つゆに大根おろしを入れて付けて食べます。", "zh": "配上加了萝卜泥的蘸汁食用。"},
            ],
        },
        {
            "id": "saba-shioyaki",
            "name": {"ko": "고등어 소금구이", "en": "Salt-grilled Mackerel", "ja": "さばの塩焼き", "zh": "盐烤鲭鱼"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "소금만 뿌려도 맛있는 고등어 구이, 일본 정식의 기본", "en": "Simple salt-seasoned grilled mackerel — a Japanese set meal staple", "ja": "塩だけで美味しい焼き魚、和食定食の基本", "zh": "只需盐就美味的烤鲭鱼，日式定食基本款"},
            "ingredients": [
                {"name": "고등어 (반 마리)", "amount": "1토막"},
                {"name": "소금", "amount": "1작은술"},
                {"name": "레몬 또는 유자", "amount": "1/4개"},
                {"name": "무 (강판에 간 것)", "amount": "2큰술"},
                {"name": "간장", "amount": "약간"},
            ],
            "steps": [
                {"ko": "고등어 양면에 소금을 뿌리고 15분 둬요.", "en": "Salt both sides of mackerel and rest for 15 minutes.", "ja": "さばの両面に塩を振って15分置きます。", "zh": "在鲭鱼两面撒盐，静置15分钟。"},
                {"ko": "키친타월로 물기를 닦아요.", "en": "Pat dry with paper towels.", "ja": "キッチンペーパーで水気を拭きます。", "zh": "用厨房纸巾擦干水分。"},
                {"ko": "그릴 팬이나 오븐에서 껍질 쪽을 아래로 먼저 5분 구워요.", "en": "Grill skin-side down for 5 minutes on a grill pan or in oven.", "ja": "グリルパンまたはオーブンで皮を下にして5分焼きます。", "zh": "在烤盘或烤箱中皮朝下烤5分钟。"},
                {"ko": "뒤집어 3분 더 구워요.", "en": "Flip and grill 3 more minutes.", "ja": "ひっくり返してさらに3分焼きます。", "zh": "翻面再烤3分钟。"},
                {"ko": "무 간 것과 레몬을 곁들여 드세요.", "en": "Serve with grated daikon and lemon.", "ja": "大根おろしとレモンを添えて食べます。", "zh": "配上萝卜泥和柠檬食用。"},
            ],
        },
        {
            "id": "yakitori",
            "name": {"ko": "야키토리", "en": "Yakitori Chicken Skewers", "ja": "焼き鳥", "zh": "烤鸡串"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "달콤 짭조름 타레 소스를 바른 일본식 닭꼬치", "en": "Japanese chicken skewers glazed with sweet-savory tare sauce", "ja": "甘辛いタレを塗った日本の焼き鳥", "zh": "涂抹甜咸烤汁的日式烤鸡串"},
            "ingredients": [
                {"name": "닭 허벅지살", "amount": "200g"},
                {"name": "대파 (흰 부분)", "amount": "1대"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "미림", "amount": "3큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "산초 또는 후추", "amount": "약간"},
            ],
            "steps": [
                {"ko": "닭과 대파를 3cm 크기로 잘라 번갈아 꼬치에 꿰어요.", "en": "Cut chicken and white part of green onion into 3cm pieces; skewer alternately.", "ja": "鶏肉と白ネギを3cmに切り、交互に串に刺します。", "zh": "将鸡肉和大葱白色部分切成3cm，交替穿在串上。"},
                {"ko": "간장·미림·설탕을 냄비에 넣고 약불로 1/3 되게 졸여 타레를 만들어요.", "en": "Combine soy sauce, mirin, and sugar in a saucepan; simmer over low heat until reduced by 1/3 to make tare.", "ja": "醤油・みりん・砂糖を鍋に入れて弱火で1/3になるまで煮詰めてタレを作ります。", "zh": "将酱油、味醂和砂糖放入锅中，小火熬至减少1/3制作烤汁。"},
                {"ko": "그릴 팬을 달구고 꼬치를 소금만 뿌려 중불로 구워요.", "en": "Heat grill pan; grill skewers with just salt over medium heat.", "ja": "グリルパンを熱して串に塩だけ振って中火で焼きます。", "zh": "加热烤盘，串上只撒盐，用中火烤制。"},
                {"ko": "어느 정도 익으면 타레를 바르고 다시 구워요.", "en": "When mostly cooked, brush with tare and grill again.", "ja": "ある程度焼けたらタレを塗ってまた焼きます。", "zh": "烤至差不多熟时，刷上烤汁再继续烤。"},
                {"ko": "타레를 한 번 더 발라 마무리해요.", "en": "Brush with another layer of tare to finish.", "ja": "タレをもう一度塗って仕上げます。", "zh": "再刷一次烤汁作为收尾。"},
            ],
        },
        {
            "id": "korokke",
            "name": {"ko": "고로케", "en": "Korokke (Japanese Croquette)", "ja": "コロッケ", "zh": "日式可乐饼"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "으깬 감자에 고기를 넣어 튀긴 일본식 고로케", "en": "Crispy Japanese potato croquette stuffed with meat", "ja": "マッシュポテトに肉を詰めて揚げたコロッケ", "zh": "土豆泥包裹肉馅的酥炸日式可乐饼"},
            "ingredients": [
                {"name": "감자", "amount": "2개"},
                {"name": "다진 돼지고기", "amount": "80g"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "밀가루·계란·빵가루", "amount": "적당량씩"},
                {"name": "튀김용 식용유", "amount": "충분히"},
                {"name": "우스터 소스 또는 돈카츠 소스", "amount": "취향껏"},
            ],
            "steps": [
                {"ko": "감자를 삶아 뜨거울 때 으깨요.", "en": "Boil potatoes and mash while hot.", "ja": "じゃがいもを茹でて熱いうちに潰します。", "zh": "将土豆煮熟，趁热捣成泥。"},
                {"ko": "팬에 기름 두르고 양파·다진 돼지고기를 볶아 소금·후추로 간해요.", "en": "Stir-fry onion and ground pork; season with salt and pepper.", "ja": "フライパンに油を引いて玉ねぎと豚ひき肉を炒め、塩こしょうで味付けします。", "zh": "锅中倒油，翻炒洋葱和猪肉末，用盐和胡椒调味。"},
                {"ko": "으깬 감자에 볶은 고기를 섞어요.", "en": "Mix the fried meat into the mashed potato.", "ja": "マッシュポテトに炒めた肉を混ぜます。", "zh": "将炒好的肉末混入土豆泥中。"},
                {"ko": "타원형으로 모양 잡아 밀가루→계란물→빵가루 순으로 입혀요.", "en": "Shape into ovals; coat in flour, then beaten egg, then breadcrumbs.", "ja": "楕円形に形を整えて小麦粉→溶き卵→パン粉の順に衣をつけます。", "zh": "整形成椭圆形，依次裹上面粉、蛋液和面包糠。"},
                {"ko": "175°C 기름에서 3~4분 황금빛으로 튀겨요.", "en": "Fry at 175°C for 3-4 minutes until golden.", "ja": "175°Cの油で3〜4分黄金色に揚げます。", "zh": "在175°C的油中炸3-4分钟至金黄色。"},
            ],
        },
    ],
    "japanese/miso": [
        {
            "id": "asari-misoshiru",
            "name": {"ko": "바지락 미소시루", "en": "Clam Miso Soup", "ja": "あさりのみそ汁", "zh": "蛤蜊味噌汤"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "바지락 국물의 시원한 맛이 일품인 미소시루", "en": "Refreshing miso soup with the deep umami of clams", "ja": "あさりの旨みが抜群のみそ汁", "zh": "蛤蜊鲜味十足的清爽味噌汤"},
            "ingredients": [
                {"name": "바지락", "amount": "200g"},
                {"name": "된장 (일본 미소)", "amount": "1.5큰술"},
                {"name": "물", "amount": "400ml"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "소금", "amount": "약간 (해감용)"},
            ],
            "steps": [
                {"ko": "바지락을 소금물에 1시간 해감해요.", "en": "Soak clams in salted water for 1 hour to purge sand.", "ja": "あさりを塩水に1時間浸けて砂抜きします。", "zh": "将蛤蜊在盐水中浸泡1小时吐沙。"},
                {"ko": "냄비에 물과 바지락을 넣고 가열해요.", "en": "Put water and clams in a pot and heat.", "ja": "鍋に水とあさりを入れて加熱します。", "zh": "锅中加入水和蛤蜊，加热。"},
                {"ko": "조개 껍데기가 열리면 거품을 걷어요.", "en": "When shells open, skim off any foam.", "ja": "貝殻が開いたらアクを取ります。", "zh": "贝壳打开后，撇去浮沫。"},
                {"ko": "불을 약하게 줄이고 된장을 국자로 풀어요.", "en": "Reduce heat and dissolve miso through a ladle.", "ja": "火を弱めて味噌をお玉で溶かします。", "zh": "转小火，用勺子将味噌溶入汤中。"},
                {"ko": "끓이지 말고 쪽파를 올려 바로 서빙해요.", "en": "Don't boil after adding miso; top with green onions and serve immediately.", "ja": "味噌を入れたら沸騰させずにネギをのせてすぐ出します。", "zh": "加入味噌后不要再煮沸，撒上小葱立即上桌。"},
            ],
        },
        {
            "id": "chawanmushi",
            "name": {"ko": "차완무시", "en": "Chawanmushi (Steamed Egg Custard)", "ja": "茶碗蒸し", "zh": "茶碗蒸"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "부드럽고 고급스러운 일본식 계란찜", "en": "Silky smooth Japanese steamed egg custard", "ja": "なめらかでリッチな日本の茶碗蒸し", "zh": "嫩滑高档的日式蒸蛋"},
            "ingredients": [
                {"name": "계란", "amount": "2개"},
                {"name": "다시 국물 (멸치 or 다시마)", "amount": "300ml"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "미림", "amount": "1작은술"},
                {"name": "소금", "amount": "한 꼬집"},
                {"name": "새우·표고버섯·은행", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "계란을 잘 풀고 다시 국물·간장·미림·소금을 넣어 섞어요.", "en": "Beat eggs and mix with dashi, soy sauce, mirin, and salt.", "ja": "卵をよく溶いてだし・醤油・みりん・塩を加えて混ぜます。", "zh": "将鸡蛋充分打散，加入高汤、酱油、味醂和盐混合。"},
                {"ko": "계란물을 체에 걸러 기포를 없애요.", "en": "Strain the egg mixture through a sieve to remove bubbles.", "ja": "卵液を漉して気泡を取り除きます。", "zh": "将蛋液过筛去除气泡。"},
                {"ko": "그릇에 새우·버섯·은행을 넣고 계란물을 부어요.", "en": "Place shrimp, mushroom, and ginkgo in cups; pour egg mixture over.", "ja": "器にエビ・椎茸・銀杏を入れて卵液を注ぎます。", "zh": "在碗中放入虾、香菇和银杏，倒入蛋液。"},
                {"ko": "찜통에 물을 끓여 거품 올라오면 약불로 낮추고 15분 쪄요.", "en": "Steam over boiling water; when steam rises reduce to low heat and steam 15 minutes.", "ja": "蒸し器に水を沸かして蒸気が出たら弱火にして15分蒸します。", "zh": "蒸锅中将水烧开，冒蒸汽后转小火蒸15分钟。"},
                {"ko": "이쑤시개로 찔러 맑은 물이 나오면 완성이에요.", "en": "It's done when a skewer comes out clear.", "ja": "竹串を刺して透明な液が出たら完成です。", "zh": "用牙签插入，流出清澈液体即完成。"},
            ],
        },
        {
            "id": "oden",
            "name": {"ko": "오뎅탕", "en": "Oden", "ja": "おでん", "zh": "关东煮"},
            "time": 45, "difficulty": 2,
            "desc": {"ko": "겨울에 먹는 따뜻한 일본식 어묵탕", "en": "Warm Japanese fishcake stew, a winter classic", "ja": "冬に食べる温かいおでん", "zh": "冬日暖心的日式关东煮"},
            "ingredients": [
                {"name": "어묵 모둠", "amount": "200g"},
                {"name": "무", "amount": "200g"},
                {"name": "계란 (삶은 것)", "amount": "2개"},
                {"name": "곤약", "amount": "100g"},
                {"name": "쯔유", "amount": "4큰술"},
                {"name": "물", "amount": "700ml"},
                {"name": "다시마", "amount": "1장"},
            ],
            "steps": [
                {"ko": "무를 2cm 두께로 썰고 곤약을 칼집 내어 준비해요.", "en": "Cut daikon into 2cm rounds and score the konjac.", "ja": "大根を2cm厚さに切り、こんにゃくに切り込みを入れて準備します。", "zh": "将萝卜切成2cm厚的圆片，在魔芋上划刀备用。"},
                {"ko": "무를 쌀뜨물에 10분 삶아 잡내를 없애요.", "en": "Parboil daikon in rice washing water for 10 minutes.", "ja": "大根を米のとぎ汁で10分下茹でして臭みを取ります。", "zh": "将萝卜在淘米水中焯10分钟去除异味。"},
                {"ko": "냄비에 물·쯔유·다시마를 넣고 국물을 만들어요.", "en": "Combine water, tsuyu, and kelp to make the broth.", "ja": "鍋に水・めんつゆ・昆布を入れてスープを作ります。", "zh": "锅中加入水、蘸汁和昆布制作汤底。"},
                {"ko": "모든 재료를 넣고 20~30분 약불로 끓여요.", "en": "Add all ingredients and simmer on low for 20-30 minutes.", "ja": "全ての材料を入れて弱火で20〜30分煮ます。", "zh": "放入所有食材，用小火煮20-30分钟。"},
                {"ko": "겨자나 된장을 찍어 드세요.", "en": "Serve with mustard or miso for dipping.", "ja": "からしや味噌を付けて食べます。", "zh": "蘸芥末或味噌食用。"},
            ],
        },
        {
            "id": "hiyayakko",
            "name": {"ko": "히야야코", "en": "Hiyayakko (Cold Tofu)", "ja": "冷奴", "zh": "冷豆腐"},
            "time": 5, "difficulty": 1,
            "desc": {"ko": "5분 완성, 여름에 딱인 일본식 냉 두부", "en": "5-minute summer classic — cold silken tofu with toppings", "ja": "5分完成、夏にぴったりの冷奴", "zh": "5分钟完成，夏日必吃的冷豆腐"},
            "ingredients": [
                {"name": "연두부", "amount": "1/2모"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "생강 (간 것)", "amount": "약간"},
                {"name": "가쓰오부시", "amount": "약간"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "참기름", "amount": "약간 (선택)"},
            ],
            "steps": [
                {"ko": "연두부를 찬물에 씻고 적당히 잘라요.", "en": "Rinse silken tofu in cold water and cut into portions.", "ja": "絹豆腐を冷水で洗って適当な大きさに切ります。", "zh": "将嫩豆腐用冷水冲洗，切成适当大小。"},
                {"ko": "접시에 담고 쪽파·생강·가쓰오부시를 올려요.", "en": "Place on a plate and top with green onion, ginger, and bonito flakes.", "ja": "皿に盛り、ネギ・生姜・かつお節をのせます。", "zh": "盛盘，放上小葱、姜末和木鱼花。"},
                {"ko": "간장을 뿌려 바로 드세요.", "en": "Drizzle with soy sauce and serve immediately.", "ja": "醤油を回しかけてすぐに食べます。", "zh": "淋上酱油，立即享用。"},
            ],
        },
    ],
}
