RECIPES_KR = {
    "korean/rice": [
        {
            "id": "kimchi-fried-rice",
            "name": {"ko": "김치볶음밥", "en": "Kimchi Fried Rice", "ja": "キムチチャーハン", "zh": "泡菜炒饭"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "남은 밥과 김치로 15분 안에 뚝딱", "en": "Quick one-pan meal with leftover rice and kimchi", "ja": "残りご飯とキムチで15分で完成", "zh": "剩饭和泡菜15分钟搞定"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "묵은 김치", "amount": "100g"},
                {"name": "계란", "amount": "1개"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "김치는 적당히 잘라 준비해요.", "en": "Chop the kimchi into bite-sized pieces."},
                {"ko": "팬에 기름을 두르고 중불로 달군 뒤 김치를 볶아요. 김치 국물도 조금 넣으면 더 맛있어요.", "en": "Heat oil over medium heat and stir-fry the kimchi. Add a splash of kimchi juice for more flavor."},
                {"ko": "밥을 넣고 주걱으로 잘 풀어가며 볶아요.", "en": "Add rice and break it up with a spatula while stir-frying."},
                {"ko": "간장을 넣고 30초 더 볶다가 불을 끄고 참기름을 뿌려요.", "en": "Add soy sauce, stir-fry 30 more seconds, then turn off heat and drizzle sesame oil."},
                {"ko": "별도 팬에 계란 프라이를 해서 밥 위에 올려요.", "en": "Fry an egg in a separate pan and place on top of the rice."},
            ],
        },
        {
            "id": "bibimbap",
            "name": {"ko": "비빔밥", "en": "Bibimbap", "ja": "ビビンバ", "zh": "拌饭"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "각종 나물과 고추장으로 비벼 먹는 한식의 대표", "en": "Classic Korean mixed rice bowl with vegetables and gochujang", "ja": "ナムルとコチュジャンを混ぜる韓国の定番ご飯", "zh": "各种凉拌菜和辣椒酱拌在一起的韩国代表性料理"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "시금치", "amount": "한 줌"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "계란", "amount": "1개"},
                {"name": "고추장", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "시금치는 끓는 물에 30초 데쳐 물기를 짜고, 소금·참기름으로 무쳐요.", "en": "Blanch spinach 30 seconds, squeeze out water, season with salt and sesame oil."},
                {"ko": "당근은 채 썰어 팬에 기름 없이 살짝 볶아요.", "en": "Julienne carrots and sauté briefly in a dry pan."},
                {"ko": "달걀을 프라이하거나 반숙으로 삶아요.", "en": "Fry or soft-boil the egg."},
                {"ko": "그릇에 밥을 담고 나물과 계란을 예쁘게 올려요.", "en": "Place rice in a bowl and arrange vegetables and egg on top."},
                {"ko": "고추장과 참기름을 올리고 취향껏 비벼서 드세요.", "en": "Add gochujang and sesame oil, then mix everything together."},
            ],
        },
        {
            "id": "chicken-porridge",
            "name": {"ko": "닭죽", "en": "Chicken Porridge", "ja": "鶏のお粥", "zh": "鸡肉粥"},
            "time": 45, "difficulty": 1,
            "desc": {"ko": "속이 편한 든든한 한 그릇, 몸이 안 좋을 때 최고", "en": "Comforting rice porridge great for sick days", "ja": "体に優しい一杯、体調が悪い時に最適", "zh": "温暖肠胃的一碗，身体不适时的最佳选择"},
            "ingredients": [
                {"name": "쌀", "amount": "1/2컵"},
                {"name": "닭가슴살", "amount": "100g"},
                {"name": "물 또는 닭육수", "amount": "4컵"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "쌀은 30분 이상 불려요.", "en": "Soak rice for at least 30 minutes."},
                {"ko": "닭가슴살은 물에 삶아 결대로 찢어요.", "en": "Boil chicken breast, then shred along the grain."},
                {"ko": "냄비에 참기름을 두르고 불린 쌀을 2분 볶아요.", "en": "Heat sesame oil in a pot and stir-fry soaked rice for 2 minutes."},
                {"ko": "육수를 붓고 약불에서 20-25분 저어가며 끓여요.", "en": "Add broth and cook over low heat for 20-25 minutes, stirring occasionally."},
                {"ko": "닭을 넣고 소금으로 간 맞춘 뒤 쪽파를 올려요.", "en": "Add chicken, season with salt, and garnish with green onions."},
            ],
        },
    ],
    "korean/soup": [
        {
            "id": "doenjang-jjigae",
            "name": {"ko": "된장찌개", "en": "Doenjang Jjigae", "ja": "テンジャンチゲ", "zh": "大酱汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "한국인의 소울푸드, 집된장이 없어도 시판 된장으로 OK", "en": "Korea's soul food stew — easy with store-bought doenjang", "ja": "韓国人のソウルフード、市販の味噌でも美味しく作れる", "zh": "韩国人的灵魂食物，用市售大酱也能轻松完成"},
            "ingredients": [
                {"name": "된장", "amount": "2큰술"},
                {"name": "두부", "amount": "1/2모"},
                {"name": "애호박", "amount": "1/4개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "멸치다시마육수", "amount": "2컵"},
                {"name": "고추", "amount": "1개 (선택)"},
            ],
            "steps": [
                {"ko": "두부는 2cm 큐브로, 호박·양파는 한 입 크기로 썰어요.", "en": "Cut tofu into 2cm cubes; dice zucchini and onion into bite-sized pieces."},
                {"ko": "냄비에 육수를 붓고 된장을 풀어 끓여요.", "en": "Pour broth into pot, dissolve doenjang, and bring to a boil."},
                {"ko": "호박·양파·고추를 넣고 5분 끓여요.", "en": "Add zucchini, onion, and chili pepper; boil 5 minutes."},
                {"ko": "두부를 넣고 3분 더 끓여요.", "en": "Add tofu and boil 3 more minutes."},
                {"ko": "대파를 넣고 불을 꺼요.", "en": "Add green onion and turn off the heat."},
            ],
        },
        {
            "id": "kimchi-jjigae",
            "name": {"ko": "김치찌개", "en": "Kimchi Jjigae", "ja": "キムチチゲ", "zh": "泡菜汤"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "익은 김치일수록 맛있는 국민 찌개", "en": "The more fermented the kimchi, the better this stew gets", "ja": "キムチが熟すほど美味しくなる国民的チゲ", "zh": "泡菜越熟越好吃的国民汤锅"},
            "ingredients": [
                {"name": "묵은 김치", "amount": "150g"},
                {"name": "돼지고기 (목살 or 삼겹살)", "amount": "100g"},
                {"name": "두부", "amount": "1/2모"},
                {"name": "물", "amount": "1.5컵"},
                {"name": "고추장", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "설탕", "amount": "1/2작은술"},
            ],
            "steps": [
                {"ko": "돼지고기는 한 입 크기로, 두부는 2cm 두께로 썰어요.", "en": "Cut pork into bite-sized pieces and tofu into 2cm slices."},
                {"ko": "냄비에 참기름을 두르고 돼지고기를 볶아요.", "en": "Heat sesame oil in a pot and stir-fry the pork."},
                {"ko": "김치와 고추장을 넣고 2분 더 볶아요.", "en": "Add kimchi and gochujang; stir-fry 2 more minutes."},
                {"ko": "물을 붓고 중불에서 10분 끓여요.", "en": "Pour in water and boil over medium heat for 10 minutes."},
                {"ko": "두부를 넣고 5분 더 끓이면 완성이에요.", "en": "Add tofu and boil 5 more minutes. Done!"},
            ],
        },
        {
            "id": "egg-soup",
            "name": {"ko": "계란국", "en": "Korean Egg Soup", "ja": "卵のスープ", "zh": "鸡蛋汤"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "10분이면 완성, 초보자도 절대 실패 없는 국", "en": "10-minute soup that's impossible to mess up", "ja": "10分で完成、初心者でも失敗なしのスープ", "zh": "10分钟完成，初学者也不会失败的汤"},
            "ingredients": [
                {"name": "계란", "amount": "2개"},
                {"name": "멸치다시마육수", "amount": "2컵"},
                {"name": "국간장", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "참기름", "amount": "1/2작은술"},
            ],
            "steps": [
                {"ko": "계란을 그릇에 풀어 놓아요.", "en": "Beat eggs in a bowl."},
                {"ko": "냄비에 육수를 붓고 팔팔 끓여요.", "en": "Bring broth to a full boil in a pot."},
                {"ko": "국간장으로 간을 맞춰요.", "en": "Season with soup soy sauce."},
                {"ko": "풀어 놓은 계란을 가느다란 줄기로 천천히 부어가며 저어요.", "en": "Slowly pour beaten eggs into boiling broth in a thin stream while stirring."},
                {"ko": "쪽파와 참기름을 넣고 불을 꺼요.", "en": "Add green onions and sesame oil, then turn off heat."},
            ],
        },
    ],
    "korean/grill": [
        {
            "id": "jeyuk-bokkeum",
            "name": {"ko": "제육볶음", "en": "Spicy Stir-fried Pork", "ja": "チェユクポックム", "zh": "辣炒猪肉"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "밥도둑 1위, 고추장 양념 돼지고기 볶음", "en": "Spicy gochujang pork that goes perfectly with rice", "ja": "ご飯泥棒1位、コチュジャン味付け豚肉炒め", "zh": "最配饭的下饭菜冠军，辣椒酱炒猪肉"},
            "ingredients": [
                {"name": "돼지고기 (앞다리살)", "amount": "200g"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "양파", "amount": "1/2개"},
                {"name": "참기름", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "돼지고기는 0.5cm 두께로 썰어요.", "en": "Slice pork to 0.5cm thickness."},
                {"ko": "볼에 고추장·고춧가루·간장·설탕·마늘을 섞어 양념을 만들어요.", "en": "Mix gochujang, chili flakes, soy sauce, sugar, and garlic to make the sauce."},
                {"ko": "고기를 양념에 20분 이상 재워요.", "en": "Marinate pork in the sauce for at least 20 minutes."},
                {"ko": "달군 팬에 양파를 먼저 볶다가 고기를 넣고 센불에서 볶아요.", "en": "Stir-fry onion first in a hot pan, then add pork and cook over high heat."},
                {"ko": "고기가 익으면 참기름을 뿌려 마무리해요.", "en": "When pork is cooked through, drizzle with sesame oil to finish."},
            ],
        },
        {
            "id": "bulgogi",
            "name": {"ko": "소불고기", "en": "Beef Bulgogi", "ja": "プルコギ", "zh": "韩式烤牛肉"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "달콤한 간장 양념 소고기, 외국인도 반하는 맛", "en": "Sweet soy-marinated beef loved by everyone", "ja": "甘い醤油タレの牛肉、外国人もとりこになる味", "zh": "甜甜酱油腌制的牛肉，连外国人都为之着迷"},
            "ingredients": [
                {"name": "소고기 (불고기용)", "amount": "200g"},
                {"name": "배 또는 사과", "amount": "1/4개 (갈아서)"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "참기름", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "양파", "amount": "1/2개"},
            ],
            "steps": [
                {"ko": "배나 사과를 갈아서 즙을 냅니다. 고기를 연하게 하는 역할이에요.", "en": "Grate pear or apple for the juice — it tenderizes the meat."},
                {"ko": "간장·설탕·참기름·마늘·과일즙을 섞어 양념장을 만들어요.", "en": "Mix soy sauce, sugar, sesame oil, garlic, and fruit juice to make the marinade."},
                {"ko": "고기에 양념장을 넣고 양파와 함께 버무려 30분 이상 재워요.", "en": "Mix beef with marinade and sliced onion; marinate at least 30 minutes."},
                {"ko": "달군 팬에 센불로 고기를 볶아요. 국물이 생기면 졸여 주세요.", "en": "Stir-fry over high heat. If liquid forms, reduce it down."},
                {"ko": "참기름을 살짝 더 뿌려 마무리해요.", "en": "Finish with a touch more sesame oil."},
            ],
        },
        {
            "id": "dak-galbi",
            "name": {"ko": "닭갈비", "en": "Spicy Stir-fried Chicken", "ja": "タッカルビ", "zh": "辣炒鸡肋"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "춘천 명물, 고추장 양념 닭볶음", "en": "Spicy gochujang chicken stir-fry from Chuncheon", "ja": "春川名物、コチュジャン味付け鶏肉炒め", "zh": "春川名产，辣椒酱味炒鸡"},
            "ingredients": [
                {"name": "닭다리살 또는 닭가슴살", "amount": "250g"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "고구마 또는 감자", "amount": "1/2개"},
                {"name": "양배추", "amount": "2장"},
            ],
            "steps": [
                {"ko": "닭은 한 입 크기로, 고구마·양배추도 비슷하게 썰어요.", "en": "Cut chicken, sweet potato, and cabbage into similar bite-sized pieces."},
                {"ko": "고추장·고춧가루·간장·설탕·마늘로 양념을 만들어요.", "en": "Combine gochujang, chili flakes, soy sauce, sugar, and garlic."},
                {"ko": "닭에 양념을 버무려 20분 재워요.", "en": "Coat chicken in sauce and marinate 20 minutes."},
                {"ko": "팬에 기름 두르고 닭을 먼저 익혀요.", "en": "Heat oil in a pan and cook the chicken first."},
                {"ko": "고구마·양배추를 넣고 뚜껑 덮어 5분 익힌 뒤 잘 섞어요.", "en": "Add sweet potato and cabbage, cover and cook 5 minutes, then toss together."},
            ],
        },
    ],
    "korean/kimchi": [
        {
            "id": "gyeran-mari",
            "name": {"ko": "계란말이", "en": "Korean Rolled Omelette", "ja": "卵焼き（韓国風）", "zh": "韩式鸡蛋卷"},
            "time": 15, "difficulty": 2,
            "desc": {"ko": "도시락 단골 반찬, 예쁘게 마는 게 포인트", "en": "Classic lunchbox side — the roll is the challenge", "ja": "お弁当の定番おかず、きれいに巻くのがポイント", "zh": "便当常客，漂亮地卷起来才是关键"},
            "ingredients": [
                {"name": "계란", "amount": "3개"},
                {"name": "당근", "amount": "1/8개"},
                {"name": "쪽파", "amount": "2줄기"},
                {"name": "소금", "amount": "1/4작은술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "당근과 쪽파를 잘게 다져요.", "en": "Finely dice carrot and green onion."},
                {"ko": "계란을 풀고 당근·쪽파·소금을 넣어 잘 섞어요.", "en": "Beat eggs and mix in carrot, green onion, and salt."},
                {"ko": "팬에 기름을 얇게 두르고 약불로 달군 뒤 계란물 1/3을 부어요.", "en": "Lightly oil a pan over low heat and pour in 1/3 of the egg mixture."},
                {"ko": "반 익으면 한쪽부터 돌돌 말아요.", "en": "When half-set, roll it up from one side."},
                {"ko": "남은 계란물을 2번에 나눠 같은 방식으로 말아 두툼하게 만들어요.", "en": "Pour the rest in two batches, rolling each time to build thickness."},
                {"ko": "식힌 뒤 썰면 단면이 예쁘게 나와요.", "en": "Let cool before slicing to reveal a clean cross-section."},
            ],
        },
        {
            "id": "spinach-namul",
            "name": {"ko": "시금치나물", "en": "Spinach Namul", "ja": "ほうれん草のナムル", "zh": "菠菜凉拌"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "데쳐서 무치면 끝, 가장 쉬운 나물 반찬", "en": "Blanch and toss — the easiest Korean side dish", "ja": "茹でて和えるだけ、最も簡単なナムル料理", "zh": "焯熟拌一拌就完成，最简单的小菜"},
            "ingredients": [
                {"name": "시금치", "amount": "200g"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "소금", "amount": "1/2작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "통깨", "amount": "약간"},
            ],
            "steps": [
                {"ko": "끓는 물에 소금 약간 넣고 시금치를 30초만 데쳐요.", "en": "Blanch spinach in salted boiling water for just 30 seconds."},
                {"ko": "찬물에 헹궈 물기를 꼭 짜요.", "en": "Rinse in cold water and squeeze out all moisture."},
                {"ko": "마늘·소금·참기름을 넣고 손으로 조물조물 무쳐요.", "en": "Add garlic, salt, and sesame oil; mix well by hand."},
                {"ko": "통깨를 뿌려 완성이에요.", "en": "Sprinkle sesame seeds and serve."},
            ],
        },
        {
            "id": "cucumber-salad",
            "name": {"ko": "오이무침", "en": "Spicy Cucumber Salad", "ja": "きゅうりのピリ辛和え", "zh": "拌黄瓜"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "아삭하고 매콤한 여름 반찬의 대명사", "en": "Crisp, spicy cucumber — perfect summer side dish", "ja": "シャキシャキ辛い夏の副菜の代名詞", "zh": "爽脆微辣，夏日小菜的代名词"},
            "ingredients": [
                {"name": "오이", "amount": "1개"},
                {"name": "소금", "amount": "1작은술 (절임용)"},
                {"name": "고춧가루", "amount": "1작은술"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "식초", "amount": "1작은술"},
                {"name": "설탕", "amount": "1/2작은술"},
                {"name": "참기름·통깨", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "오이를 반달 모양으로 0.5cm 두께로 썰어요.", "en": "Slice cucumber into 0.5cm half-moons."},
                {"ko": "소금을 뿌려 10분 절인 뒤 물기를 꼭 짜요.", "en": "Sprinkle salt and let sit 10 minutes, then squeeze out liquid."},
                {"ko": "고춧가루·마늘·식초·설탕을 섞어 양념을 만들어요.", "en": "Mix chili flakes, garlic, vinegar, and sugar for the dressing."},
                {"ko": "오이에 양념을 넣고 조물조물 무쳐요.", "en": "Toss cucumber with the dressing."},
                {"ko": "참기름과 통깨를 뿌려 마무리해요.", "en": "Finish with sesame oil and sesame seeds."},
            ],
        },
    ],
    "korean/noodle": [
        {
            "id": "japchae",
            "name": {"ko": "잡채", "en": "Japchae", "ja": "チャプチェ", "zh": "杂菜"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "명절 단골 메뉴, 색색의 채소와 당면의 조화", "en": "Festive glass noodles with colorful vegetables", "ja": "お祭りの定番メニュー、色鮮やかな野菜と春雨の調和", "zh": "节日必备，色彩丰富的蔬菜与粉丝的完美搭配"},
            "ingredients": [
                {"name": "당면", "amount": "100g"},
                {"name": "소고기 (채 썰기)", "amount": "80g"},
                {"name": "시금치", "amount": "한 줌"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "설탕", "amount": "1.5큰술"},
                {"name": "참기름", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "당면을 30분 불려요.", "en": "Soak glass noodles for 30 minutes."},
                {"ko": "소고기는 간장 1큰술·설탕·참기름으로 미리 양념해요.", "en": "Marinate beef with 1 tbsp soy sauce, sugar, and sesame oil."},
                {"ko": "채소를 각각 볶아 놓아요 (당근·양파·시금치 순서로).", "en": "Stir-fry each vegetable separately (carrot, onion, spinach)."},
                {"ko": "불린 당면을 끓는 물에 8분 삶아 건져요.", "en": "Boil soaked noodles 8 minutes, then drain."},
                {"ko": "모든 재료를 큰 볼에 담고 남은 간장·설탕·참기름으로 버무려요.", "en": "Combine everything in a large bowl and toss with remaining soy sauce, sugar, and sesame oil."},
            ],
        },
        {
            "id": "instant-ramen",
            "name": {"ko": "라면", "en": "Korean Instant Ramen", "ja": "ラーメン", "zh": "方便面"},
            "time": 5, "difficulty": 1,
            "desc": {"ko": "실패 없는 국민 야식, 물 양이 핵심", "en": "Korea's favorite late-night snack — water ratio is everything", "ja": "失敗なしの国民的夜食、水の量が命", "zh": "不会失败的国民宵夜，水的用量是关键"},
            "ingredients": [
                {"name": "라면", "amount": "1개"},
                {"name": "물", "amount": "550ml"},
                {"name": "계란", "amount": "1개 (선택)"},
                {"name": "대파", "amount": "약간 (선택)"},
            ],
            "steps": [
                {"ko": "물 550ml를 냄비에 붓고 끓여요.", "en": "Bring 550ml of water to a boil."},
                {"ko": "물이 끓으면 면과 스프를 넣어요.", "en": "Once boiling, add noodles and soup powder."},
                {"ko": "4분 30초 동안 원하는 식감으로 끓여요.", "en": "Cook for about 4 minutes 30 seconds to your preferred texture."},
                {"ko": "계란을 넣으면 1분 전에, 대파는 마지막에 넣어요.", "en": "Add egg 1 minute before done; add green onion at the very end."},
            ],
        },
        {
            "id": "kalguksu",
            "name": {"ko": "칼국수", "en": "Knife-cut Noodle Soup", "ja": "カルグクス", "zh": "刀切面"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "쫄깃한 면과 진한 국물, 손칼국수의 정석", "en": "Chewy hand-cut noodles in a deep savory broth", "ja": "もちもちの麺と濃いスープ、手打ち麺の王道", "zh": "劲道面条配浓郁汤底，手切面的正统做法"},
            "ingredients": [
                {"name": "칼국수 면 (시판)", "amount": "2인분"},
                {"name": "멸치다시마육수", "amount": "4컵"},
                {"name": "애호박", "amount": "1/3개"},
                {"name": "감자", "amount": "1개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "국간장", "amount": "1큰술"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "감자·호박·양파를 채 썰거나 반달로 썰어요.", "en": "Julienne or slice potato, zucchini, and onion."},
                {"ko": "냄비에 육수를 붓고 끓이다가 감자를 먼저 넣어요.", "en": "Bring broth to a boil and add potato first."},
                {"ko": "감자가 반쯤 익으면 호박·양파를 넣어요.", "en": "When potato is half-cooked, add zucchini and onion."},
                {"ko": "칼국수 면을 넣고 면이 익을 때까지 8-10분 끓여요.", "en": "Add noodles and boil 8-10 minutes until cooked through."},
                {"ko": "국간장·소금으로 간을 맞춰 마무리해요.", "en": "Season with soup soy sauce and salt to taste."},
            ],
        },
    ],
}
