RECIPES_CN = {
    "chinese/noodle": [
        {
            "id": "jjajangmyeon",
            "name": {"ko": "짜장면", "en": "Jjajangmyeon", "ja": "チャジャンミョン", "zh": "炸酱面"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "춘장으로 만드는 한국식 짜장면", "en": "Korean-style black bean paste noodles", "ja": "チュンジャンで作る韓国式炸醤麺", "zh": "用韩式春酱制作的韩式炸酱面"},
            "ingredients": [
                {"name": "생면 또는 건면", "amount": "2인분"},
                {"name": "춘장", "amount": "3큰술"},
                {"name": "돼지고기 (다진 것)", "amount": "150g"},
                {"name": "양파", "amount": "1개"},
                {"name": "감자", "amount": "1개"},
                {"name": "식용유", "amount": "3큰술"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "설탕", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "돼지고기·감자·양파를 1cm 주사위 모양으로 썰어요.", "en": "Dice pork, potato, and onion into 1cm cubes.", "ja": "豚肉・じゃがいも・玉ねぎを1cmの角切りにします。", "zh": "猪肉、土豆、洋葱切成1cm方块。"},
                {"ko": "팬에 기름 넉넉히 두르고 춘장을 약불에서 1-2분 볶아요. 쓴맛이 빠져요.", "en": "Heat plenty of oil and stir-fry chunjang over low heat 1-2 minutes to remove bitterness.", "ja": "フライパンに油を多めにひき春醤を弱火で1〜2分炒めます。苦味が抜けます。", "zh": "锅中多放油，小火将春酱炒1-2分钟去除苦味。"},
                {"ko": "볶은 춘장은 덜어두고, 같은 팬에 돼지고기를 볶아요.", "en": "Set aside fried chunjang. In same pan, stir-fry pork.", "ja": "炒めた春醤を取り出し同じフライパンで豚肉を炒めます。", "zh": "将炒好的春酱取出，同锅翻炒猪肉。"},
                {"ko": "감자·양파를 넣고 2분 볶은 뒤 춘장을 다시 넣고 물 1.5컵을 부어 졸여요.", "en": "Add potato and onion, stir-fry 2 min, return chunjang, add 1.5 cups water and simmer.", "ja": "じゃがいもと玉ねぎを加えて2分炒め春醤を戻して水1.5カップを加えて煮詰めます。", "zh": "加入土豆和洋葱翻炒2分钟，放回春酱，加入1.5杯水收汁。"},
                {"ko": "전분물(전분+물 1:2)을 넣어 걸쭉하게 만들고, 삶은 면에 얹어요.", "en": "Thicken with starch slurry (1:2 ratio) and pour over boiled noodles.", "ja": "水溶き片栗粉（1:2）でとろみをつけ茹でた麺にかけます。", "zh": "用淀粉水（1:2）勾芡，浇在煮好的面条上。"},
            ],
        },
        {
            "id": "jjamppong",
            "name": {"ko": "짬뽕", "en": "Jjamppong", "ja": "チャンポン", "zh": "炒码面"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "불향 가득한 매콤한 해물 면", "en": "Spicy seafood noodle soup with wok char", "ja": "炎の香りいっぱいの辛い海鮮麺", "zh": "充满锅气的香辣海鲜面"},
            "ingredients": [
                {"name": "생면", "amount": "2인분"},
                {"name": "오징어", "amount": "1/2마리"},
                {"name": "새우", "amount": "6마리"},
                {"name": "고춧가루", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "양배추", "amount": "2장"},
                {"name": "대파", "amount": "1/2대"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "물 또는 육수", "amount": "3컵"},
            ],
            "steps": [
                {"ko": "오징어는 링으로, 새우는 내장 제거, 채소는 큼직하게 썰어요.", "en": "Slice squid into rings, devein shrimp, chop vegetables roughly.", "ja": "イカはリング状に、エビは背わたを取り、野菜は大きめに切ります。", "zh": "鱿鱼切成圈，虾去背肠，蔬菜切大块。"},
                {"ko": "팬에 기름 많이 두르고 센불에서 고춧가루·마늘을 10초 볶아요.", "en": "Heat plenty of oil over high heat; stir-fry chili flakes and garlic for 10 seconds.", "ja": "フライパンに油を多めにひき強火で唐辛子粉とにんにくを10秒炒めます。", "zh": "锅中多放油，大火将辣椒粉和蒜末炒10秒。"},
                {"ko": "해물을 넣고 센불에서 빠르게 볶아요. 불향이 핵심이에요.", "en": "Add seafood and stir-fry fast over high heat. The wok char is key.", "ja": "海鮮を加えて強火で素早く炒めます。焼き目の香りが命です。", "zh": "加入海鲜，大火快速翻炒。锅气是关键。"},
                {"ko": "채소·굴소스·물을 넣고 5분 끓여요.", "en": "Add vegetables, oyster sauce, and water; boil 5 minutes.", "ja": "野菜・オイスターソース・水を加えて5分煮ます。", "zh": "加入蔬菜、蚝油、水煮5分钟。"},
                {"ko": "삶은 면을 국물에 넣고 2분 더 끓여요.", "en": "Add cooked noodles and boil 2 more minutes.", "ja": "茹でた麺をスープに入れてさらに2分煮ます。", "zh": "将煮好的面条放入汤中再煮2分钟。"},
            ],
        },
        {
            "id": "mul-mandu",
            "name": {"ko": "물만두", "en": "Boiled Dumplings", "ja": "水餃子", "zh": "水饺"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "직접 빚으면 더 맛있는 집만두", "en": "Homemade dumplings — so much better than frozen", "ja": "手作りすればもっと美味しい家庭の餃子", "zh": "自己包的饺子更好吃，远胜冷冻水饺"},
            "ingredients": [
                {"name": "만두피 (시판)", "amount": "20장"},
                {"name": "돼지고기 (다진 것)", "amount": "150g"},
                {"name": "두부", "amount": "1/4모"},
                {"name": "김치 (다진 것)", "amount": "50g"},
                {"name": "대파 (다진 것)", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "참기름·소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "두부는 물기를 꼭 짜고, 김치도 물기를 빼요.", "en": "Squeeze moisture from tofu and kimchi thoroughly.", "ja": "豆腐はしっかり水気を絞りキムチも水気を切ります。", "zh": "豆腐用力挤干水分，泡菜也要沥干。"},
                {"ko": "돼지고기·두부·김치·대파·마늘·양념을 잘 섞어 소를 만들어요.", "en": "Mix pork, tofu, kimchi, green onion, garlic, and seasonings into the filling.", "ja": "豚肉・豆腐・キムチ・長ねぎ・にんにく・調味料をよく混ぜて具を作ります。", "zh": "将猪肉、豆腐、泡菜、大葱、蒜末、调料充分混合制成馅料。"},
                {"ko": "만두피 가장자리에 물을 바르고 소를 올려 꼭꼭 눌러 붙여요.", "en": "Wet the edges of the wrapper, add filling, and seal tightly.", "ja": "餃子の皮の端に水を塗り具をのせてしっかり閉じます。", "zh": "在饺子皮边缘涂水，放上馅料用力捏紧密封。"},
                {"ko": "끓는 물에 만두를 넣고 떠오르면 2분 더 삶아요.", "en": "Drop dumplings into boiling water; cook 2 more minutes after they float.", "ja": "沸騰したお湯に餃子を入れ浮き上がったらさらに2分茹でます。", "zh": "将饺子放入沸水中，浮起后再煮2分钟。"},
                {"ko": "간장·식초·고춧가루 소스에 찍어 드세요.", "en": "Serve with soy-vinegar dipping sauce.", "ja": "醤油・酢・唐辛子粉のタレにつけてお召し上がりください。", "zh": "蘸酱油、醋、辣椒粉调成的蘸汁食用。"},
            ],
        },
    ],
    "chinese/rice": [
        {
            "id": "egg-fried-rice",
            "name": {"ko": "계란볶음밥", "en": "Egg Fried Rice", "ja": "卵チャーハン", "zh": "蛋炒饭"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "중식의 기본 중의 기본, 센 불이 핵심", "en": "The foundation of Chinese cooking — high heat is everything", "ja": "中華料理の基本中の基本、強火が命", "zh": "中式料理的基础，大火是关键"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "계란", "amount": "2개"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "계란은 미리 풀어 놓아요.", "en": "Beat eggs in advance.", "ja": "卵を事前に溶きほぐしておきます。", "zh": "提前打散鸡蛋备用。"},
                {"ko": "팬을 최대한 강불로 달궈요. 연기가 살짝 날 정도로요.", "en": "Heat pan to maximum — you want it nearly smoking.", "ja": "フライパンを最大限強火で熱します。少し煙が出るくらいまで。", "zh": "将锅用最大火加热，加热至微微冒烟程度。"},
                {"ko": "기름을 두르고 계란을 먼저 스크램블해요. 완전히 익히지 말고 반숙 상태에서 꺼내요.", "en": "Add oil and scramble eggs. Remove while still slightly soft.", "ja": "油をひいて先に卵をスクランブルします。完全に火を通さず半熟の状態で取り出します。", "zh": "倒油后先将鸡蛋炒散，不要全熟，在半熟状态取出。"},
                {"ko": "대파를 볶다가 밥을 넣고 주걱으로 세게 눌러가며 볶아요.", "en": "Stir-fry green onion, add rice and press hard with spatula while tossing.", "ja": "長ねぎを炒めてご飯を加えしゃもじで強く押しながら炒めます。", "zh": "翻炒大葱后加入米饭，用锅铲用力按压翻炒。"},
                {"ko": "계란을 다시 넣고 간장·소금으로 간을 맞춰 30초 더 볶아요.", "en": "Return eggs, season with soy sauce and salt, stir-fry 30 more seconds.", "ja": "卵を戻し入れ醤油・塩で味を整えてさらに30秒炒めます。", "zh": "将鸡蛋放回锅中，用酱油、盐调味再炒30秒。"},
            ],
        },
        {
            "id": "shrimp-fried-rice",
            "name": {"ko": "새우볶음밥", "en": "Shrimp Fried Rice", "ja": "エビチャーハン", "zh": "虾仁炒饭"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "새우의 감칠맛이 더해진 고급스러운 볶음밥", "en": "Elevated fried rice with the rich flavor of shrimp", "ja": "エビの旨味が加わった上品な炒飯", "zh": "加入虾仁鲜味的高档炒饭"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "새우 (냉동 가능)", "amount": "8마리"},
                {"name": "계란", "amount": "1개"},
                {"name": "냉동 완두콩", "amount": "2큰술"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "새우는 해동 후 키친타월로 물기를 닦고 소금·후추로 밑간해요.", "en": "Thaw shrimp, pat dry, and season lightly with salt and pepper.", "ja": "エビを解凍してキッチンペーパーで水気を拭き塩・コショウで下味をつけます。", "zh": "虾解冻后用厨房纸擦干，用盐和胡椒粉腌制。"},
                {"ko": "센불 팬에 기름 두르고 새우를 1분 볶아 꺼내요.", "en": "Stir-fry shrimp in a very hot oiled pan for 1 minute, then set aside.", "ja": "強火の鍋に油をひきエビを1分炒めて取り出します。", "zh": "大火热锅倒油，将虾翻炒1分钟后取出。"},
                {"ko": "계란을 스크램블한 뒤, 대파·밥을 넣고 센불에서 볶아요.", "en": "Scramble eggs, then add green onion and rice; stir-fry over high heat.", "ja": "卵をスクランブルしてから長ねぎとご飯を加えて強火で炒めます。", "zh": "将鸡蛋炒散后加入大葱和米饭，大火翻炒。"},
                {"ko": "굴소스·간장을 넣어 볶고, 새우·완두콩을 넣어 30초 더 볶아요.", "en": "Add oyster sauce and soy sauce, return shrimp and peas, stir-fry 30 seconds.", "ja": "オイスターソース・醤油を加えて炒めエビとグリーンピースを入れてさらに30秒炒めます。", "zh": "加入蚝油、酱油翻炒，再放入虾和豌豆炒30秒。"},
            ],
        },
        {
            "id": "three-delights-rice",
            "name": {"ko": "삼선볶음밥", "en": "Three Delights Fried Rice", "ja": "三鮮チャーハン", "zh": "三鲜炒饭"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "새우·오징어·채소의 삼박자가 맞는 고급 볶음밥", "en": "Premium fried rice with shrimp, squid, and vegetables", "ja": "エビ・イカ・野菜の三拍子が揃った高級炒飯", "zh": "虾仁、鱿鱼、蔬菜三鲜齐备的高档炒饭"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "새우", "amount": "5마리"},
                {"name": "오징어", "amount": "1/4마리"},
                {"name": "당근", "amount": "1/8개"},
                {"name": "계란", "amount": "1개"},
                {"name": "굴소스", "amount": "1.5큰술"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "새우·오징어를 한 입 크기로, 당근은 작게 깍둑썰어요.", "en": "Cut shrimp and squid bite-sized; dice carrot small.", "ja": "エビとイカを一口大に、にんじんは小さめの角切りにします。", "zh": "虾和鱿鱼切成一口大小，胡萝卜切成小丁。"},
                {"ko": "센불 팬에 기름 두르고 해물을 빠르게 볶아 꺼내요.", "en": "Stir-fry seafood quickly in a very hot pan; set aside.", "ja": "強火の鍋に油をひき海鮮を素早く炒めて取り出します。", "zh": "大火热锅倒油，将海鲜快速翻炒后取出。"},
                {"ko": "당근을 볶다가 계란을 넣어 스크램블해요.", "en": "Stir-fry carrot, then add egg and scramble.", "ja": "にんじんを炒めてから卵を加えてスクランブルします。", "zh": "翻炒胡萝卜后加入鸡蛋炒散。"},
                {"ko": "밥을 넣고 센불에서 주걱으로 누르며 볶아요.", "en": "Add rice and stir-fry over high heat, pressing with spatula.", "ja": "ご飯を加えて強火でしゃもじで押しながら炒めます。", "zh": "加入米饭，大火用锅铲按压翻炒。"},
                {"ko": "해물을 다시 넣고 굴소스로 간해 30초 볶아요.", "en": "Return seafood, add oyster sauce, and stir-fry 30 seconds.", "ja": "海鮮を戻し入れオイスターソースで味付けして30秒炒めます。", "zh": "放回海鲜，用蚝油调味再炒30秒。"},
            ],
        },
    ],
    "chinese/stirfry": [
        {
            "id": "mapo-tofu",
            "name": {"ko": "마파두부", "en": "Mapo Tofu", "ja": "麻婆豆腐", "zh": "麻婆豆腐"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "얼얼하고 칼칼한 사천식 두부 요리", "en": "Numbingly spicy Sichuan tofu dish", "ja": "しびれるほど辛い四川式豆腐料理", "zh": "麻辣刺激的四川风味豆腐料理"},
            "ingredients": [
                {"name": "두부 (연두부)", "amount": "1모"},
                {"name": "돼지고기 (다진 것)", "amount": "80g"},
                {"name": "두반장", "amount": "1.5큰술"},
                {"name": "다진 마늘·생강", "amount": "각 1작은술"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "참기름·고춧가루", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "두부는 2cm 큐브로 썰어 끓는 물에 1분 데쳐요. 모양이 잘 유지돼요.", "en": "Cut tofu into 2cm cubes and blanch in boiling water for 1 minute to hold shape.", "ja": "豆腐を2cmのキューブに切り沸騰したお湯で1分下茹でします。形が崩れにくくなります。", "zh": "豆腐切成2cm小块，在沸水中焯1分钟，这样不易碎。"},
                {"ko": "팬에 기름 두르고 두반장·마늘·생강을 볶아 기름에 붉은색이 돌게 해요.", "en": "Stir-fry doubanjiang, garlic, and ginger until oil turns red.", "ja": "フライパンに油をひき豆板醤・にんにく・生姜を炒めて油が赤く色づくまで炒めます。", "zh": "锅中倒油，翻炒豆瓣酱、蒜末、姜末至油变红。"},
                {"ko": "다진 돼지고기를 넣고 볶아요.", "en": "Add ground pork and stir-fry.", "ja": "ひき肉を加えて炒めます。", "zh": "加入猪肉末翻炒。"},
                {"ko": "물 1컵을 붓고 두부를 넣어 3분 끓여요.", "en": "Add 1 cup water, add tofu, and simmer 3 minutes.", "ja": "水1カップを注いで豆腐を加えて3分煮ます。", "zh": "倒入1杯水，加入豆腐煮3分钟。"},
                {"ko": "전분물로 걸쭉하게 만들고 대파·참기름으로 마무리해요.", "en": "Thicken with starch slurry; finish with green onion and sesame oil.", "ja": "水溶き片栗粉でとろみをつけ長ねぎとごま油で仕上げます。", "zh": "用淀粉水勾芡，加入大葱和香油完成。"},
            ],
        },
        {
            "id": "tangsuyuk",
            "name": {"ko": "탕수육", "en": "Sweet & Sour Pork", "ja": "酢豚", "zh": "糖醋肉"},
            "time": 45, "difficulty": 3,
            "desc": {"ko": "바삭한 튀김에 새콤달콤 소스, 부먹 vs 찍먹 논쟁의 주인공", "en": "Crispy fried pork with tangy sweet sauce — pour or dip?", "ja": "カリカリ揚げに甘酸っぱいソース、ソースかけ vs つけ派論争の主役", "zh": "酥脆炸肉配酸甜酱汁，浇汁派vs蘸汁派论战的主角"},
            "ingredients": [
                {"name": "돼지고기 (안심)", "amount": "200g"},
                {"name": "전분", "amount": "4큰술"},
                {"name": "계란", "amount": "1개"},
                {"name": "식초", "amount": "3큰술"},
                {"name": "설탕", "amount": "3큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "파인애플·당근·양파", "amount": "조금씩"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
            ],
            "steps": [
                {"ko": "돼지고기를 한 입 크기로 썰어 소금·후추로 밑간해요.", "en": "Cut pork into bite-sized pieces and season with salt and pepper.", "ja": "豚肉を一口大に切り塩・コショウで下味をつけます。", "zh": "猪肉切成一口大小，用盐和胡椒粉腌制。"},
                {"ko": "계란·전분을 섞어 반죽을 만들고 고기에 입혀요.", "en": "Mix egg and starch into batter and coat pork.", "ja": "卵と片栗粉を混ぜて衣を作り肉にまぶします。", "zh": "将鸡蛋和淀粉混合制成面糊，裹在猪肉上。"},
                {"ko": "170°C 기름에 5분 튀겨 꺼내고, 180°C에서 2분 더 튀겨 바삭하게 해요.", "en": "Deep-fry at 170°C for 5 minutes, remove, then fry again at 180°C for 2 minutes.", "ja": "170°Cの油で5分揚げて取り出し180°Cでさらに2分揚げてカリッとさせます。", "zh": "170°C油炸5分钟取出，再用180°C炸2分钟使其更酥脆。"},
                {"ko": "식초·설탕·간장·물(각 3큰술)을 끓이고 채소를 넣어 소스를 만들어요.", "en": "Boil vinegar, sugar, soy sauce, and water (3 tbsp each) with vegetables for the sauce.", "ja": "酢・砂糖・醤油・水（各大さじ3）を煮立て野菜を加えてソースを作ります。", "zh": "将醋、糖、酱油、水（各3大勺）煮沸，加入蔬菜制成酱汁。"},
                {"ko": "전분물로 소스를 걸쭉하게 만든 뒤 고기에 붓거나 곁들여요.", "en": "Thicken sauce with starch slurry; pour over pork or serve on the side.", "ja": "水溶き片栗粉でソースにとろみをつけてから肉にかけるか添えます。", "zh": "用淀粉水将酱汁勾芡，浇在猪肉上或作为蘸汁。"},
            ],
        },
        {
            "id": "gganpunggi",
            "name": {"ko": "깐풍기", "en": "Dry Braised Spicy Chicken", "ja": "乾焼チキン", "zh": "干烹鸡"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "매콤달콤 소스가 닭에 쫙 배인 인기 중식 메뉴", "en": "Spicy-sweet sauce clings to every piece of chicken", "ja": "甘辛ソースが鶏肉にしっかり染み込んだ人気中華メニュー", "zh": "甜辣酱汁浸透每一块鸡肉的人气中式菜肴"},
            "ingredients": [
                {"name": "닭다리살", "amount": "250g"},
                {"name": "전분", "amount": "3큰술"},
                {"name": "건고추", "amount": "3개"},
                {"name": "다진 마늘·생강", "amount": "각 1작은술"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "고추기름", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "닭다리살을 한 입 크기로 썰어 소금·후추·전분을 묻혀요.", "en": "Cut chicken into pieces; coat with salt, pepper, and starch.", "ja": "鶏もも肉を一口大に切り塩・コショウ・片栗粉をまぶします。", "zh": "鸡腿肉切成一口大小，裹上盐、胡椒粉和淀粉。"},
                {"ko": "170°C 기름에 5분 튀겨요.", "en": "Deep-fry at 170°C for 5 minutes.", "ja": "170°Cの油で5分揚げます。", "zh": "170°C油炸5分钟。"},
                {"ko": "팬에 고추기름·건고추·마늘·생강을 볶아 향을 내요.", "en": "Stir-fry chili oil, dried chilies, garlic, and ginger until fragrant.", "ja": "フライパンに唐辛子油・乾燥唐辛子・にんにく・生姜を炒めて香りを出します。", "zh": "锅中翻炒辣椒油、干辣椒、蒜末、姜末炒出香气。"},
                {"ko": "간장·설탕·식초를 넣고 소스를 만들어요.", "en": "Add soy sauce, sugar, and vinegar to make the sauce.", "ja": "醤油・砂糖・酢を加えてソースを作ります。", "zh": "加入酱油、糖、醋制成酱汁。"},
                {"ko": "튀긴 닭을 넣고 소스가 배도록 센불에서 빠르게 볶아요.", "en": "Add fried chicken and toss over high heat until sauce is absorbed.", "ja": "揚げた鶏を加えてソースが染み込むよう強火で素早く炒めます。", "zh": "加入炸好的鸡肉，大火快速翻炒至酱汁充分吸收。"},
            ],
        },
    ],
    "chinese/soup": [
        {
            "id": "egg-drop-soup",
            "name": {"ko": "계란탕", "en": "Egg Drop Soup", "ja": "玉子スープ", "zh": "蛋花汤"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "중식당 단골 수프, 집에서 5분이면 완성", "en": "Chinese restaurant staple ready in 5 minutes at home", "ja": "中華レストランの定番スープ、家で5分で完成", "zh": "中餐馆常备汤品，在家5分钟完成"},
            "ingredients": [
                {"name": "계란", "amount": "2개"},
                {"name": "닭육수 또는 물", "amount": "2컵"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "소금", "amount": "1/2작은술"},
                {"name": "참기름", "amount": "1/2작은술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "육수를 끓이고 소금으로 간해요.", "en": "Bring broth to a boil and season with salt.", "ja": "スープを煮立て塩で味を整えます。", "zh": "将高汤煮沸，用盐调味。"},
                {"ko": "전분을 물 2큰술에 풀어 넣고 살살 저어 걸쭉하게 만들어요.", "en": "Stir in starch dissolved in 2 tbsp water to thicken.", "ja": "片栗粉を水大さじ2で溶いて加えやさしくかき混ぜてとろみをつけます。", "zh": "将淀粉用2大勺水化开倒入，轻轻搅拌使其变稠。"},
                {"ko": "계란을 잘 풀어 가느다란 줄기로 천천히 부어요.", "en": "Beat eggs well and pour in a thin stream, stirring gently.", "ja": "卵をよく溶いて細い線状にゆっくり注ぎます。", "zh": "将鸡蛋充分打散，缓缓倒入成细丝状。"},
                {"ko": "참기름을 뿌리고 쪽파로 마무리해요.", "en": "Drizzle sesame oil and garnish with green onion.", "ja": "ごま油をかけて小ねぎで仕上げます。", "zh": "淋上香油，用葱花点缀完成。"},
            ],
        },
        {
            "id": "corn-soup",
            "name": {"ko": "옥수수 크림수프", "en": "Cream of Corn Soup", "ja": "コーンスープ", "zh": "奶油玉米汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "달콤하고 부드러운 크림옥수수수프", "en": "Sweet, creamy corn soup that's impossibly easy", "ja": "甘くてなめらかなクリームコーンスープ", "zh": "甜美顺滑的奶油玉米汤"},
            "ingredients": [
                {"name": "옥수수 크림 캔", "amount": "1캔(425g)"},
                {"name": "닭육수 또는 물", "amount": "1.5컵"},
                {"name": "계란", "amount": "1개"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "소금·설탕", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "냄비에 육수와 옥수수 크림을 넣고 끓여요.", "en": "Combine broth and canned corn cream in a pot; bring to a boil.", "ja": "鍋にスープとコーンクリームを入れて煮立てます。", "zh": "锅中加入高汤和奶油玉米罐头煮沸。"},
                {"ko": "소금과 설탕으로 간을 맞춰요.", "en": "Season with salt and a pinch of sugar.", "ja": "塩と砂糖で味を整えます。", "zh": "用盐和少许糖调味。"},
                {"ko": "전분물을 넣어 살짝 걸쭉하게 만들어요.", "en": "Add starch slurry to thicken slightly.", "ja": "水溶き片栗粉を加えて少しとろみをつけます。", "zh": "加入淀粉水轻微勾芡。"},
                {"ko": "풀어 놓은 계란을 가느다랗게 부어 실타래처럼 만들어요.", "en": "Drizzle beaten egg in a thin stream to create silky threads.", "ja": "溶いた卵を細く注いで糸状に仕上げます。", "zh": "将打散的鸡蛋细细倒入形成丝状。"},
            ],
        },
        {
            "id": "seafood-hotpot",
            "name": {"ko": "해물탕", "en": "Spicy Seafood Hotpot", "ja": "海鮮チゲ", "zh": "海鲜火锅"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "신선한 해물이 가득, 시원하고 매운 탕", "en": "Packed with fresh seafood — spicy and deeply savory", "ja": "新鮮な海鮮たっぷり、さっぱり辛い鍋", "zh": "新鲜海鲜满满，清爽又辛辣的火锅"},
            "ingredients": [
                {"name": "새우·오징어·홍합", "amount": "각 적당량"},
                {"name": "고추장", "amount": "1큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "무", "amount": "1/4개"},
                {"name": "대파", "amount": "1/2대"},
                {"name": "물 또는 멸치육수", "amount": "3컵"},
            ],
            "steps": [
                {"ko": "무를 나박썰기하고 해물은 깨끗이 손질해요.", "en": "Slice radish thinly; clean and prep all seafood.", "ja": "大根を薄くスライスし海鮮は綺麗に下処理します。", "zh": "萝卜切薄片，海鲜清洗处理干净。"},
                {"ko": "냄비에 물·무를 넣고 끓여 육수를 내요.", "en": "Boil water with radish to make a base stock.", "ja": "鍋に水と大根を入れて煮立ててスープをとります。", "zh": "锅中加入水和萝卜煮沸熬制汤底。"},
                {"ko": "고추장·고춧가루·마늘을 넣어 칼칼한 국물을 만들어요.", "en": "Add gochujang, chili flakes, and garlic for a spicy broth.", "ja": "コチュジャン・唐辛子粉・にんにくを加えてピリ辛スープにします。", "zh": "加入辣椒酱、辣椒粉、蒜末制作辛辣汤底。"},
                {"ko": "해물을 넣고 5-7분 끓여요. 홍합이 입을 벌리면 익은 거예요.", "en": "Add seafood and boil 5-7 minutes. Mussels are done when they open.", "ja": "海鮮を加えて5〜7分煮ます。ムール貝が口を開けたら火が通った証拠です。", "zh": "加入海鲜煮5-7分钟。贻贝开口即表示熟了。"},
                {"ko": "대파를 넣고 마무리해요.", "en": "Finish with green onion and serve.", "ja": "長ねぎを加えて完成です。", "zh": "加入大葱完成。"},
            ],
        },
    ],
    "chinese/dim": [
        {
            "id": "steamed-dumplings",
            "name": {"ko": "찐만두", "en": "Steamed Dumplings", "ja": "蒸し餃子", "zh": "蒸饺"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "쫄깃한 피와 육즙이 가득한 찐만두", "en": "Juicy dumplings with chewy steamed wrappers", "ja": "もちもちの皮と肉汁たっぷりの蒸し餃子", "zh": "劲道外皮包裹满满肉汁的蒸饺"},
            "ingredients": [
                {"name": "만두피 (두꺼운 것)", "amount": "20장"},
                {"name": "돼지고기 (다진 것)", "amount": "150g"},
                {"name": "배추 (절여서)", "amount": "100g"},
                {"name": "부추 또는 쪽파", "amount": "30g"},
                {"name": "다진 생강", "amount": "1작은술"},
                {"name": "간장·참기름·소금", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "배추는 소금에 절여 물기를 꼭 짜요.", "en": "Salt cabbage, let sit, then squeeze out all moisture.", "ja": "白菜を塩漬けにして水気をしっかり絞ります。", "zh": "白菜用盐腌制后用力挤干水分。"},
                {"ko": "돼지고기·배추·부추·생강·양념을 잘 섞어 소를 만들어요.", "en": "Mix pork, cabbage, chives, ginger, and seasonings for the filling.", "ja": "豚肉・白菜・ニラ・生姜・調味料をよく混ぜて具を作ります。", "zh": "将猪肉、白菜、韭菜、姜末、调料充分混合制成馅料。"},
                {"ko": "만두피에 소를 올리고 주름을 잡아 예쁘게 빚어요.", "en": "Fill wrappers and pleat to seal.", "ja": "餃子の皮に具をのせてひだを作りきれいに包みます。", "zh": "将馅料放在饺子皮上，捏出褶皱整形。"},
                {"ko": "찜기 바닥에 면포를 깔고 만두를 올려요.", "en": "Line steamer with cloth and arrange dumplings.", "ja": "蒸し器の底に布を敷いて餃子を並べます。", "zh": "在蒸锅底部铺上纱布，将饺子摆上。"},
                {"ko": "센불로 물을 끓인 뒤 중불에서 12-15분 쪄요.", "en": "Bring water to a boil, then steam over medium heat 12-15 minutes.", "ja": "強火で水を沸かしてから中火で12〜15分蒸します。", "zh": "大火将水烧沸后转中火蒸12-15分钟。"},
            ],
        },
        {
            "id": "spring-rolls",
            "name": {"ko": "춘권", "en": "Spring Rolls", "ja": "春巻き", "zh": "春卷"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "바삭한 튀김옷 속에 각종 채소가 가득", "en": "Crispy shells packed with colorful vegetables", "ja": "サクサクの揚げ衣の中に様々な野菜が入った春巻き", "zh": "酥脆外皮内包满各种蔬菜的春卷"},
            "ingredients": [
                {"name": "춘권피", "amount": "10장"},
                {"name": "돼지고기 (채썰기)", "amount": "80g"},
                {"name": "당근·양배추·당면", "amount": "각 50g"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간"},
                {"name": "밀가루 풀 (밀가루+물)", "amount": "2큰술씩"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
            ],
            "steps": [
                {"ko": "당면을 불리고, 채소와 고기를 채 썰어요.", "en": "Soak glass noodles; julienne vegetables and pork.", "ja": "春雨を水に浸し野菜と肉を千切りにします。", "zh": "粉丝泡发，蔬菜和肉切成丝。"},
                {"ko": "팬에 고기 볶고, 채소·당면·굴소스를 넣고 볶아 소를 만들어요.", "en": "Stir-fry pork, then add vegetables, noodles, and oyster sauce for filling.", "ja": "フライパンで肉を炒め野菜・春雨・オイスターソースを加えて炒めて具を作ります。", "zh": "锅中翻炒猪肉，加入蔬菜、粉丝、蚝油炒好制成馅料。"},
                {"ko": "소를 한 김 식힌 뒤 춘권피에 올리고 돌돌 말아요.", "en": "Cool filling slightly, place on wrapper and roll tightly.", "ja": "具を少し冷ましてから春巻きの皮にのせてしっかり巻きます。", "zh": "馅料稍微冷却后放在春卷皮上，紧紧卷起。"},
                {"ko": "끝부분을 밀가루 풀로 붙여요.", "en": "Seal the end with flour paste.", "ja": "端を小麦粉のりで貼り付けます。", "zh": "用面粉糊将末端封口。"},
                {"ko": "170°C 기름에 황금색이 될 때까지 3-4분 튀겨요.", "en": "Deep-fry at 170°C until golden, about 3-4 minutes.", "ja": "170°Cの油でキツネ色になるまで3〜4分揚げます。", "zh": "170°C油炸3-4分钟至金黄色。"},
            ],
        },
    ],
}
