RECIPES_EXTRA = {
    # ── 한식 추가 ────────────────────────────────────────────────
    "korean/rice": [
        {
            "id": "omurice",
            "name": {"ko": "오므라이스", "en": "Omurice", "ja": "オムライス", "zh": "蛋包饭"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "케첩볶음밥을 얇은 계란으로 감싼 인기 메뉴", "en": "Ketchup fried rice wrapped in a thin egg omelette"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "계란", "amount": "3개"},
                {"name": "닭가슴살 또는 햄", "amount": "60g"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "케첩", "amount": "3큰술"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "닭가슴살과 양파를 잘게 다져요.", "en": "Finely dice chicken and onion."},
                {"ko": "버터에 양파·닭을 볶다가 밥과 케첩을 넣고 볶아요. 소금·후추로 간해요.", "en": "Sauté onion and chicken in butter, add rice and ketchup, season with salt and pepper."},
                {"ko": "볶음밥을 타원형으로 그릇에 모양 잡아 놓아요.", "en": "Shape the fried rice into an oval on the plate."},
                {"ko": "계란 2개를 잘 풀어 약불 팬에 얇게 펼쳐요. 반숙 상태에서 밥 위에 덮어요.", "en": "Beat 2 eggs and spread thin over low heat. Drape over rice while still soft."},
                {"ko": "케첩을 줄무늬로 뿌려 마무리해요.", "en": "Drizzle ketchup on top and serve."},
            ],
        },
        {
            "id": "butter-rice",
            "name": {"ko": "버터 간장밥", "en": "Butter Soy Rice", "ja": "バター醤油ご飯", "zh": "黄油酱油饭"},
            "time": 5, "difficulty": 1,
            "desc": {"ko": "3분이면 완성, 밥도둑 중의 밥도둑", "en": "Three-ingredient rice bowl ready in 3 minutes"},
            "ingredients": [
                {"name": "따뜻한 밥", "amount": "1공기"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "계란 노른자 (선택)", "amount": "1개"},
                {"name": "김 가루", "amount": "약간"},
            ],
            "steps": [
                {"ko": "뜨거운 밥 위에 버터를 올려요.", "en": "Place butter on hot rice."},
                {"ko": "간장을 뿌리고 버터가 녹을 때까지 기다렸다 섞어요.", "en": "Add soy sauce and let butter melt before stirring."},
                {"ko": "계란 노른자를 올리고 김 가루를 뿌려요.", "en": "Top with egg yolk and sprinkle nori flakes."},
                {"ko": "잘 비벼서 드세요.", "en": "Mix everything together and enjoy."},
            ],
        },
    ],
    "korean/soup": [
        {
            "id": "sundubu-jjigae",
            "name": {"ko": "순두부찌개", "en": "Sundubu Jjigae", "ja": "スンドゥブチゲ", "zh": "嫩豆腐汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "부드러운 순두부와 칼칼한 국물의 조화", "en": "Silky tofu in a fiery, comforting broth"},
            "ingredients": [
                {"name": "순두부", "amount": "1팩"},
                {"name": "바지락 또는 새우", "amount": "80g"},
                {"name": "고춧가루", "amount": "1.5큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "계란", "amount": "1개"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "국간장·소금", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "냄비에 참기름 두르고 고춧가루·마늘을 30초 볶아요.", "en": "Stir-fry chili flakes and garlic in sesame oil for 30 seconds."},
                {"ko": "양파와 해물을 넣고 볶아요.", "en": "Add onion and seafood; stir-fry."},
                {"ko": "물 1.5컵을 붓고 끓여요.", "en": "Add 1.5 cups water and bring to a boil."},
                {"ko": "순두부를 숟가락으로 퍼 넣고 3분 끓여요.", "en": "Spoon in soft tofu and simmer 3 minutes."},
                {"ko": "계란을 깨 넣고 국간장·소금으로 간해요.", "en": "Crack in egg and season with soy sauce and salt."},
            ],
        },
        {
            "id": "yukgaejang",
            "name": {"ko": "육개장", "en": "Yukgaejang", "ja": "ユッケジャン", "zh": "辣牛肉汤"},
            "time": 50, "difficulty": 2,
            "desc": {"ko": "소고기와 고사리가 어우러진 칼칼한 탕", "en": "Spicy shredded beef soup with fernbrake and vegetables"},
            "ingredients": [
                {"name": "소고기 (양지 또는 사태)", "amount": "200g"},
                {"name": "고사리 (삶은 것)", "amount": "80g"},
                {"name": "대파", "amount": "1대"},
                {"name": "고춧가루", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "국간장", "amount": "1큰술"},
                {"name": "참기름", "amount": "1큰술"},
                {"name": "물", "amount": "4컵"},
            ],
            "steps": [
                {"ko": "소고기를 물에 삶아 건져 결대로 찢어요. 육수는 버리지 마세요.", "en": "Boil beef, remove and shred along the grain. Keep the broth."},
                {"ko": "찢은 소고기·고사리·대파를 고춧가루·마늘·참기름으로 양념해 볶아요.", "en": "Season shredded beef, fernbrake, and green onion with chili flakes, garlic, and sesame oil; stir-fry."},
                {"ko": "육수를 붓고 20분 끓여요.", "en": "Add the reserved beef broth and boil 20 minutes."},
                {"ko": "국간장으로 간을 맞춰요.", "en": "Season with soup soy sauce to taste."},
            ],
        },
    ],
    "korean/grill": [
        {
            "id": "gyeran-jjim",
            "name": {"ko": "계란찜", "en": "Korean Steamed Egg", "ja": "韓国風茶碗蒸し", "zh": "韩式蒸蛋"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "뚝배기에서 부풀어 오르는 폭신한 계란찜", "en": "Puffed, souffle-like steamed egg in a clay pot"},
            "ingredients": [
                {"name": "계란", "amount": "3개"},
                {"name": "멸치육수 또는 물", "amount": "180ml"},
                {"name": "국간장", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "쪽파·참기름", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "계란에 육수·국간장·소금을 넣고 잘 풀어요.", "en": "Beat eggs with broth, soup soy sauce, and salt."},
                {"ko": "뚝배기에 계란물을 부어요.", "en": "Pour into a clay pot or small pot."},
                {"ko": "약불에서 뚜껑 덮고 10분 익혀요.", "en": "Cover and cook over low heat for 10 minutes."},
                {"ko": "뚜껑을 열고 쪽파·참기름을 뿌려요. 살짝 부풀면 완성이에요.", "en": "Remove lid, add green onion and sesame oil. It should be puffed up."},
            ],
        },
        {
            "id": "dubu-jorim",
            "name": {"ko": "두부조림", "en": "Braised Spicy Tofu", "ja": "豆腐の煮付け", "zh": "辣炖豆腐"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "양념이 배어 쫄깃해진 두부, 밥 한 공기 순삭", "en": "Tofu soaked in spicy-sweet sauce — a rice stealer"},
            "ingredients": [
                {"name": "두부 (부침용)", "amount": "1모"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "참기름·쪽파", "amount": "약간씩"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "두부를 1.5cm 두께로 썰어 키친타월로 물기를 닦아요.", "en": "Slice tofu 1.5cm thick and pat dry with paper towels."},
                {"ko": "팬에 기름 두르고 두부를 중불에서 양면 노릇하게 구워요.", "en": "Fry tofu in oil over medium heat until golden on both sides."},
                {"ko": "고춧가루·간장·마늘·설탕·물 3큰술을 섞어 소스를 만들어요.", "en": "Mix chili flakes, soy sauce, garlic, sugar, and 3 tbsp water for sauce."},
                {"ko": "소스를 두부 위에 붓고 약불에서 2분 졸여요.", "en": "Pour sauce over tofu and simmer on low 2 minutes."},
                {"ko": "참기름과 쪽파로 마무리해요.", "en": "Finish with sesame oil and green onion."},
            ],
        },
    ],
    "korean/kimchi": [
        {
            "id": "japchae-egg",
            "name": {"ko": "미역줄기볶음", "en": "Stir-fried Wakame Stem", "ja": "わかめの茎の炒め物", "zh": "炒裙带菜茎"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "바다향 가득한 저칼로리 밑반찬", "en": "Low-calorie sea vegetable side with ocean flavor"},
            "ingredients": [
                {"name": "미역줄기 (염장 or 시판)", "amount": "150g"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "통깨", "amount": "약간"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "염장 미역줄기는 물에 30분 담가 짠맛을 빼고, 한 입 크기로 잘라요.", "en": "Soak salted wakame stem 30 minutes to remove salt; cut into pieces."},
                {"ko": "끓는 물에 1분 데쳐 찬물에 헹궈요.", "en": "Blanch 1 minute; rinse in cold water."},
                {"ko": "팬에 기름 두르고 마늘을 볶다가 미역줄기를 넣어요.", "en": "Stir-fry garlic in oil, then add wakame stem."},
                {"ko": "간장으로 간하고 참기름·통깨를 뿌려요.", "en": "Season with soy sauce, then finish with sesame oil and sesame seeds."},
            ],
        },
        {
            "id": "kongnamul",
            "name": {"ko": "콩나물무침", "en": "Bean Sprout Namul", "ja": "豆もやしのナムル", "zh": "豆芽凉拌"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "아삭아삭 해장에도 좋은 국민 반찬", "en": "Crunchy, refreshing — great after a long night too"},
            "ingredients": [
                {"name": "콩나물", "amount": "200g"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "소금", "amount": "1/2작은술"},
                {"name": "고춧가루", "amount": "1/2작은술 (선택)"},
                {"name": "통깨", "amount": "약간"},
            ],
            "steps": [
                {"ko": "냄비에 물을 붓고 소금 약간 넣어 끓여요.", "en": "Bring salted water to a boil."},
                {"ko": "콩나물을 넣고 뚜껑 덮어 4분 삶아요. 뚜껑을 열면 비린내가 나요.", "en": "Add bean sprouts, cover, and boil 4 minutes. Don't lift the lid or they'll smell fishy."},
                {"ko": "찬물에 헹궈 물기를 빼요.", "en": "Rinse in cold water and drain."},
                {"ko": "마늘·참기름·소금·고춧가루를 넣고 조물조물 무쳐 통깨를 뿌려요.", "en": "Toss with garlic, sesame oil, salt, and chili flakes; sprinkle sesame seeds."},
            ],
        },
    ],
    "korean/noodle": [
        {
            "id": "bibim-noodles",
            "name": {"ko": "비빔국수", "en": "Spicy Mixed Noodles", "ja": "ビビム麺", "zh": "拌面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "새콤달콤 매콤한 여름 국수, 10분이면 완성", "en": "Tangy, spicy, sweet — summer in a bowl"},
            "ingredients": [
                {"name": "소면 또는 중면", "amount": "1인분"},
                {"name": "고추장", "amount": "1.5큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "오이·당근·계란", "amount": "토핑용"},
            ],
            "steps": [
                {"ko": "고추장·식초·설탕·간장·참기름을 섞어 소스를 만들어요.", "en": "Mix gochujang, vinegar, sugar, soy sauce, and sesame oil for the sauce."},
                {"ko": "면을 삶아 찬물에 헹궈 쫄깃하게 만들어요.", "en": "Cook noodles and rinse in cold water until chewy."},
                {"ko": "오이와 당근을 채 썰어요.", "en": "Julienne cucumber and carrot."},
                {"ko": "면에 소스를 넣고 골고루 버무려요.", "en": "Toss noodles with sauce until evenly coated."},
                {"ko": "채소와 반숙 계란을 올려 마무리해요.", "en": "Top with vegetables and a soft-boiled egg."},
            ],
        },
        {
            "id": "tteokbokki",
            "name": {"ko": "떡볶이", "en": "Tteokbokki", "ja": "トッポキ", "zh": "炒年糕"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "국민 분식의 대명사, 쫄깃한 떡과 달콤 매콤한 소스", "en": "Korea's most beloved street food — chewy rice cakes in spicy sauce"},
            "ingredients": [
                {"name": "떡볶이 떡", "amount": "200g"},
                {"name": "어묵", "amount": "1장"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "멸치육수 또는 물", "amount": "1.5컵"},
                {"name": "대파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "떡은 찬물에 10분 담가 불려요.", "en": "Soak rice cakes in cold water for 10 minutes."},
                {"ko": "냄비에 육수·고추장·고춧가루·설탕·간장을 넣고 끓여요.", "en": "Combine broth, gochujang, chili flakes, sugar, and soy sauce; bring to a boil."},
                {"ko": "어묵을 먹기 좋게 잘라 넣어요.", "en": "Cut fish cake into pieces and add."},
                {"ko": "떡을 넣고 중불에서 소스가 졸아들 때까지 10분 저어가며 끓여요.", "en": "Add rice cakes and stir over medium heat for 10 minutes until sauce thickens."},
                {"ko": "대파를 올려 마무리해요.", "en": "Garnish with green onion and serve."},
            ],
        },
    ],

    # ── 중식 추가 ────────────────────────────────────────────────
    "chinese/noodle": [
        {
            "id": "chow-mein",
            "name": {"ko": "볶음면 (차오미엔)", "en": "Chow Mein", "ja": "チャーメン", "zh": "炒面"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "굵은 면을 채소와 함께 센불에서 볶는 중식 볶음면", "en": "Thick noodles stir-fried with vegetables over high heat"},
            "ingredients": [
                {"name": "중화면 (볶음용)", "amount": "2인분"},
                {"name": "숙주나물", "amount": "한 줌"},
                {"name": "양파·당근", "amount": "각 1/4개"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "면을 삶아 찬물에 헹군 뒤 기름을 살짝 버무려 놓아요.", "en": "Boil noodles, rinse cold, toss with a little oil to prevent sticking."},
                {"ko": "채소를 채 썰어요.", "en": "Julienne all vegetables."},
                {"ko": "센불 팬에 기름 두르고 채소를 빠르게 볶아요.", "en": "Stir-fry vegetables quickly over high heat."},
                {"ko": "면을 넣고 간장·굴소스를 넣어 센불에서 골고루 볶아요.", "en": "Add noodles with soy sauce and oyster sauce; toss over high heat."},
                {"ko": "참기름을 뿌리고 마무리해요.", "en": "Finish with sesame oil."},
            ],
        },
        {
            "id": "wonton-soup",
            "name": {"ko": "완탕면", "en": "Wonton Noodle Soup", "ja": "ワンタン麺", "zh": "云吞面"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "부드러운 완탕과 맑은 국물의 홍콩식 면 요리", "en": "Silky wontons in a clear, delicate Hong Kong-style broth"},
            "ingredients": [
                {"name": "완탕피", "amount": "15장"},
                {"name": "새우+돼지고기 (다진 것)", "amount": "각 50g"},
                {"name": "중화면", "amount": "1인분"},
                {"name": "닭육수", "amount": "3컵"},
                {"name": "간장·참기름·소금", "amount": "약간씩"},
                {"name": "생강 (다진 것)", "amount": "1/2작은술"},
            ],
            "steps": [
                {"ko": "다진 새우·돼지고기·생강·간장·참기름을 섞어 소를 만들어요.", "en": "Mix minced shrimp, pork, ginger, soy sauce, and sesame oil for filling."},
                {"ko": "완탕피에 소를 넣고 삼각형으로 접어 끝을 붙여요.", "en": "Fold wonton wrappers into triangles, sealing the edges tightly."},
                {"ko": "끓는 물에 완탕을 넣어 떠오르면 2분 더 삶아요.", "en": "Boil wontons until they float, then 2 more minutes."},
                {"ko": "닭육수를 끓여 소금·간장으로 간해요.", "en": "Bring chicken broth to a boil and season with salt and soy sauce."},
                {"ko": "그릇에 삶은 면·완탕을 담고 육수를 부어요.", "en": "Place noodles and wontons in bowl; pour broth over."},
            ],
        },
    ],
    "chinese/rice": [
        {
            "id": "yangzhou-rice",
            "name": {"ko": "양저우볶음밥", "en": "Yangzhou Fried Rice", "ja": "揚州チャーハン", "zh": "扬州炒饭"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "새우·햄·완두콩이 어우러진 화려한 중국식 볶음밥", "en": "The classic Chinese fried rice with shrimp, ham, and peas"},
            "ingredients": [
                {"name": "밥 (찬밥)", "amount": "1공기"},
                {"name": "새우", "amount": "5마리"},
                {"name": "햄", "amount": "40g"},
                {"name": "완두콩", "amount": "2큰술"},
                {"name": "계란", "amount": "2개"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "새우·햄을 작게 썰어요.", "en": "Dice shrimp and ham small."},
                {"ko": "센불 팬에 기름 두르고 계란을 스크램블해 꺼내요.", "en": "Scramble eggs in very hot oiled pan; set aside."},
                {"ko": "같은 팬에 새우·햄·완두콩을 볶아요.", "en": "Stir-fry shrimp, ham, and peas in same pan."},
                {"ko": "찬밥을 넣고 센불에서 눌러가며 볶아요. 찬밥이 낱알이 더 잘 살아요.", "en": "Add cold rice and stir-fry over high heat, pressing firmly. Cold rice fries better."},
                {"ko": "계란을 다시 넣고 간장·소금으로 간해요.", "en": "Return eggs and season with soy sauce and salt."},
            ],
        },
        {
            "id": "claypot-rice",
            "name": {"ko": "라프메이판 (소시지 솥밥)", "en": "Lap Mei Fan (Sausage Clay Pot Rice)", "ja": "臘味飯", "zh": "腊味饭"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "중국식 소시지와 함께 솥에서 지은 향기로운 밥", "en": "Aromatic rice cooked with Chinese sausage in a pot"},
            "ingredients": [
                {"name": "쌀", "amount": "1컵"},
                {"name": "중국식 소시지 (라장)", "amount": "2개"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "굴소스", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "쌀을 씻어 30분 불려요.", "en": "Wash rice and soak 30 minutes."},
                {"ko": "두꺼운 냄비에 쌀+물(1:1.2)을 넣고 끓여요.", "en": "Add rice and water (1:1.2 ratio) to a heavy pot; bring to a boil."},
                {"ko": "끓어오르면 약불로 줄이고 뚜껑 덮어 10분 뜸 들여요.", "en": "Reduce to low, cover, and steam 10 minutes."},
                {"ko": "소시지를 얇게 썰어 밥 위에 올리고 5분 더 뜸 들여요.", "en": "Slice sausage and arrange on rice; steam 5 more minutes."},
                {"ko": "간장·굴소스·참기름을 섞어 뿌리고 쪽파를 올려요.", "en": "Mix soy sauce, oyster sauce, and sesame oil; drizzle over and top with green onion."},
            ],
        },
    ],
    "chinese/stirfry": [
        {
            "id": "chive-pork",
            "name": {"ko": "부추잡채", "en": "Pork with Garlic Chives", "ja": "ニラと豚肉の炒め物", "zh": "韭菜炒肉"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "부추 향기와 돼지고기의 조합, 술안주로도 최고", "en": "Fragrant garlic chives with pork — great with rice or beer"},
            "ingredients": [
                {"name": "부추", "amount": "1단"},
                {"name": "돼지고기 (앞다리살)", "amount": "120g"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "돼지고기를 얇게 채 썰어 간장으로 밑간해요.", "en": "Slice pork thin; marinate with soy sauce."},
                {"ko": "부추는 5cm 길이로 잘라요.", "en": "Cut chives into 5cm pieces."},
                {"ko": "센불 팬에 기름 두르고 마늘→돼지고기 순으로 볶아요.", "en": "Stir-fry garlic then pork in a very hot oiled pan."},
                {"ko": "부추를 넣고 굴소스를 더해 1분만 센불에서 빠르게 볶아요. 오래 볶으면 숨이 죽어요.", "en": "Add chives and oyster sauce; stir-fry just 1 minute over high heat. Overcooking wilts them."},
                {"ko": "참기름을 뿌려 마무리해요.", "en": "Drizzle sesame oil and serve."},
            ],
        },
        {
            "id": "kung-pao-chicken",
            "name": {"ko": "궁보기정 (쿵파오 치킨)", "en": "Kung Pao Chicken", "ja": "宮保鶏丁", "zh": "宫保鸡丁"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "얼얼하고 달콤한 사천식 닭고기 볶음", "en": "Sichuan classic — spicy, sweet, and numbing"},
            "ingredients": [
                {"name": "닭가슴살", "amount": "200g"},
                {"name": "땅콩", "amount": "3큰술"},
                {"name": "건고추", "amount": "4개"},
                {"name": "화자오 (산초, 선택)", "amount": "1/2작은술"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "전분", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "닭을 2cm 큐브로 썰어 간장·전분으로 밑간해요.", "en": "Dice chicken into 2cm cubes; marinate with soy sauce and starch."},
                {"ko": "간장·식초·설탕·전분을 섞어 소스를 만들어요.", "en": "Mix soy sauce, vinegar, sugar, and starch for the sauce."},
                {"ko": "팬에 기름 두르고 화자오·건고추를 볶아 향을 내요.", "en": "Stir-fry Sichuan pepper and dried chilies until fragrant."},
                {"ko": "닭을 넣고 익혀요.", "en": "Add chicken and cook through."},
                {"ko": "소스를 넣어 빠르게 볶고 땅콩을 넣어 마무리해요.", "en": "Pour in sauce and toss quickly; add peanuts to finish."},
            ],
        },
    ],
    "chinese/soup": [
        {
            "id": "hot-sour-soup",
            "name": {"ko": "산라탕 (신 매운 수프)", "en": "Hot and Sour Soup", "ja": "酸辣湯", "zh": "酸辣汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "새콤하고 매콤한 중식 대표 수프, 후추가 핵심", "en": "Tangy and spicy — black pepper gives this soup its kick"},
            "ingredients": [
                {"name": "두부", "amount": "1/4모"},
                {"name": "목이버섯 (건조)", "amount": "5g"},
                {"name": "죽순 (시판)", "amount": "50g"},
                {"name": "계란", "amount": "1개"},
                {"name": "닭육수", "amount": "2.5컵"},
                {"name": "식초", "amount": "2큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "전분", "amount": "1.5큰술"},
                {"name": "흑후추", "amount": "넉넉히"},
            ],
            "steps": [
                {"ko": "목이버섯을 물에 불려 얇게 썰고, 두부·죽순도 채 썰어요.", "en": "Soak wood ear mushrooms; julienne mushrooms, tofu, and bamboo shoots."},
                {"ko": "육수를 끓이고 채소를 넣어 2분 익혀요.", "en": "Bring broth to a boil; add vegetables and cook 2 minutes."},
                {"ko": "간장·식초를 넣고 전분물로 걸쭉하게 만들어요.", "en": "Add soy sauce and vinegar; thicken with starch slurry."},
                {"ko": "계란을 풀어 가느다랗게 부어요.", "en": "Drizzle beaten egg in thin streams."},
                {"ko": "흑후추를 넉넉히 갈아 넣어요. 후추가 이 수프의 핵심이에요.", "en": "Grind plenty of black pepper over. Pepper is this soup's soul."},
            ],
        },
        {
            "id": "winter-melon-soup",
            "name": {"ko": "동과탕 (동아 수프)", "en": "Winter Melon Soup", "ja": "冬瓜スープ", "zh": "冬瓜汤"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "부드럽고 담백한 중국 가정식 수프", "en": "Mild, delicate Chinese home-style soup"},
            "ingredients": [
                {"name": "동아 (동과)", "amount": "300g"},
                {"name": "돼지고기 또는 닭고기", "amount": "100g"},
                {"name": "생강", "amount": "2쪽"},
                {"name": "물 또는 육수", "amount": "3컵"},
                {"name": "소금·참기름", "amount": "약간씩"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "동아의 껍질을 벗기고 2cm로 깍둑썰어요.", "en": "Peel winter melon and cut into 2cm cubes."},
                {"ko": "고기를 얇게 썰어요.", "en": "Slice meat thinly."},
                {"ko": "냄비에 물·생강을 넣고 끓이다가 고기를 먼저 익혀요.", "en": "Bring water and ginger to a boil; cook meat first."},
                {"ko": "동아를 넣고 투명해질 때까지 10분 끓여요.", "en": "Add winter melon and simmer 10 minutes until translucent."},
                {"ko": "소금·참기름으로 간하고 쪽파를 올려요.", "en": "Season with salt and sesame oil; garnish with green onion."},
            ],
        },
    ],
    "chinese/dim": [
        {
            "id": "har-gow",
            "name": {"ko": "하가우 (새우만두)", "en": "Har Gow", "ja": "エビ餃子", "zh": "虾饺"},
            "time": 50, "difficulty": 3,
            "desc": {"ko": "반투명한 피가 특징인 홍콩식 딤섬의 꽃", "en": "The crown jewel of Hong Kong dim sum — translucent skin"},
            "ingredients": [
                {"name": "밀전분 (전분+밀가루)", "amount": "80g+20g"},
                {"name": "끓는 물", "amount": "100ml"},
                {"name": "새우", "amount": "150g"},
                {"name": "죽순 (다진 것)", "amount": "30g"},
                {"name": "참기름·소금·설탕", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "밀전분+밀가루에 끓는 물을 부어 반죽해요. 잘 치대야 해요.", "en": "Pour boiling water over starch and flour; knead well."},
                {"ko": "새우는 다져서 죽순·양념과 섞어 소를 만들어요.", "en": "Mince shrimp; mix with bamboo shoots and seasonings."},
                {"ko": "반죽을 얇게 밀어 원형으로 잘라요.", "en": "Roll dough very thin and cut into circles."},
                {"ko": "소를 넣고 주름을 7-9개 잡아 반달 모양으로 빚어요.", "en": "Fill and pleat into crescent shape with 7-9 folds."},
                {"ko": "찜기에 넣고 센불로 7-8분 쪄요.", "en": "Steam over high heat 7-8 minutes."},
            ],
        },
        {
            "id": "egg-tart",
            "name": {"ko": "에그 타르트 (단타)", "en": "Egg Tart", "ja": "エッグタルト", "zh": "蛋挞"},
            "time": 45, "difficulty": 2,
            "desc": {"ko": "바삭한 타르트 껍질과 부드러운 커스터드, 홍콩 길거리 간식", "en": "Flaky pastry with silky egg custard — a Hong Kong classic"},
            "ingredients": [
                {"name": "시판 타르트 반죽 또는 파이지", "amount": "1팩"},
                {"name": "계란", "amount": "2개"},
                {"name": "설탕", "amount": "50g"},
                {"name": "우유", "amount": "150ml"},
                {"name": "바닐라 에센스", "amount": "1/4작은술"},
            ],
            "steps": [
                {"ko": "오븐을 190°C로 예열해요.", "en": "Preheat oven to 190°C."},
                {"ko": "타르트 반죽을 틀에 맞게 잘라 넣고 포크로 찍어요.", "en": "Press pastry into tart molds and prick with a fork."},
                {"ko": "계란·설탕·우유·바닐라를 섞어 체에 걸러 커스터드를 만들어요.", "en": "Mix eggs, sugar, milk, and vanilla; strain for smooth custard."},
                {"ko": "타르트 껍질에 80%만 채워요.", "en": "Fill tart shells only 80% to prevent overflow."},
                {"ko": "190°C에서 20분 구워요. 커스터드가 살짝 흔들리면 OK.", "en": "Bake at 190°C for 20 minutes. Custard should jiggle slightly when done."},
            ],
        },
    ],

    # ── 양식 추가 ────────────────────────────────────────────────
    "western/pasta": [
        {
            "id": "vongole",
            "name": {"ko": "봉골레 파스타", "en": "Spaghetti alle Vongole", "ja": "ボンゴレパスタ", "zh": "蛤蜊意面"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "조개의 바다향이 올리브오일에 녹아드는 이탈리안 클래식", "en": "Clam broth meets olive oil in this Italian seaside classic"},
            "ingredients": [
                {"name": "스파게티 면", "amount": "100g"},
                {"name": "모시조개 또는 바지락", "amount": "200g"},
                {"name": "마늘", "amount": "4쪽"},
                {"name": "올리브오일", "amount": "4큰술"},
                {"name": "화이트와인 (선택)", "amount": "1/4컵"},
                {"name": "건고추", "amount": "1개"},
                {"name": "파슬리", "amount": "약간"},
            ],
            "steps": [
                {"ko": "조개를 소금물에 1시간 해감해요.", "en": "Soak clams in salted water for 1 hour to purge sand."},
                {"ko": "면을 삶아요. 면수는 꼭 보관하세요.", "en": "Cook pasta; reserve pasta water."},
                {"ko": "팬에 올리브오일·마늘·고추를 약불에서 볶아요.", "en": "Warm olive oil, garlic, and chili over low heat."},
                {"ko": "조개와 와인을 넣고 뚜껑 덮어 조개가 입을 벌릴 때까지 쪄요.", "en": "Add clams and wine; cover until clams open."},
                {"ko": "면과 면수 4큰술을 넣고 버무려 파슬리를 뿌려요.", "en": "Add pasta with 4 tbsp pasta water; toss and top with parsley."},
            ],
        },
        {
            "id": "mushroom-cream-pasta",
            "name": {"ko": "버섯 크림파스타", "en": "Mushroom Cream Pasta", "ja": "きのこクリームパスタ", "zh": "奶油蘑菇意面"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "버섯의 깊은 풍미가 살아있는 크리미한 파스타", "en": "Rich cream sauce with deep mushroom flavor"},
            "ingredients": [
                {"name": "펜네 또는 링귀네", "amount": "100g"},
                {"name": "양송이버섯", "amount": "100g"},
                {"name": "생크림", "amount": "150ml"},
                {"name": "마늘", "amount": "2쪽"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "파마산 치즈", "amount": "3큰술"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "버섯은 슬라이스, 양파·마늘은 다져요.", "en": "Slice mushrooms; mince onion and garlic."},
                {"ko": "버터에 양파·마늘을 볶다가 버섯을 넣어 수분이 날아갈 때까지 볶아요.", "en": "Sauté onion and garlic in butter; add mushrooms and cook until dry."},
                {"ko": "생크림을 붓고 2-3분 졸여요.", "en": "Add cream and simmer 2-3 minutes."},
                {"ko": "삶은 면과 면수 2큰술을 넣고 버무려요.", "en": "Add drained pasta and 2 tbsp pasta water; toss."},
                {"ko": "파마산 치즈·소금·후추로 간을 맞춰요.", "en": "Season with parmesan, salt, and pepper."},
            ],
        },
    ],
    "western/meat": [
        {
            "id": "meatballs",
            "name": {"ko": "미트볼 토마토 소스", "en": "Meatballs in Tomato Sauce", "ja": "ミートボールトマトソース", "zh": "番茄肉丸"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "부드럽고 촉촉한 미트볼에 진한 토마토 소스", "en": "Juicy meatballs simmered in rich tomato sauce"},
            "ingredients": [
                {"name": "소·돼지 혼합 다짐육", "amount": "250g"},
                {"name": "빵가루", "amount": "3큰술"},
                {"name": "계란", "amount": "1개"},
                {"name": "파마산 치즈 가루", "amount": "2큰술"},
                {"name": "홀토마토 캔", "amount": "1/2캔"},
                {"name": "마늘", "amount": "2쪽"},
                {"name": "올리브오일", "amount": "2큰술"},
                {"name": "바질·소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "다짐육·빵가루·계란·치즈·소금·후추를 잘 치대어요.", "en": "Mix ground meat, breadcrumbs, egg, cheese, salt, and pepper well."},
                {"ko": "3cm 크기로 동그랗게 빚어요.", "en": "Roll into 3cm balls."},
                {"ko": "팬에 올리브오일 두르고 미트볼 겉면을 굴리며 갈색으로 구워요.", "en": "Sear meatballs in olive oil until browned on all sides."},
                {"ko": "마늘을 볶고 홀토마토를 으깨 넣어 소스를 만들어요.", "en": "Add garlic and crushed tomatoes to make sauce."},
                {"ko": "미트볼을 넣고 15분 약불에서 함께 끓여요.", "en": "Add meatballs and simmer together 15 minutes."},
            ],
        },
        {
            "id": "pork-chop",
            "name": {"ko": "포크찹 (두꺼운 돼지목살 구이)", "en": "Pork Chop", "ja": "ポークチョップ", "zh": "猪排"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "두껍게 썬 돼지목살을 겉은 바삭, 속은 촉촉하게", "en": "Thick pork chop — crispy outside, juicy inside"},
            "ingredients": [
                {"name": "돼지목살 (2cm 두께)", "amount": "1장"},
                {"name": "소금·후추", "amount": "넉넉히"},
                {"name": "마늘 가루", "amount": "1/2작은술"},
                {"name": "로즈마리", "amount": "1줄기"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "고기를 실온에 20분 꺼내 소금·후추·마늘가루를 뿌려요.", "en": "Rest pork at room temperature 20 minutes; season with salt, pepper, and garlic powder."},
                {"ko": "팬을 강불로 달궈 기름을 두르고 고기를 올려요.", "en": "Heat pan with oil over high heat; place pork chop."},
                {"ko": "한 면 3분 씩 구워요. 자꾸 뒤집지 마세요.", "en": "Cook 3 minutes per side. Don't keep flipping."},
                {"ko": "버터와 로즈마리를 넣고 베이스팅하며 1분 더 구워요.", "en": "Add butter and rosemary; baste for 1 more minute."},
                {"ko": "3분 휴지 후 서빙해요.", "en": "Rest 3 minutes before serving."},
            ],
        },
    ],
    "western/salad": [
        {
            "id": "caprese",
            "name": {"ko": "카프레제", "en": "Caprese Salad", "ja": "カプレーゼ", "zh": "卡普里沙拉"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "모짜렐라·토마토·바질의 이탈리아 3색 샐러드", "en": "Italian tricolor of mozzarella, tomato, and basil"},
            "ingredients": [
                {"name": "생모짜렐라 치즈", "amount": "125g"},
                {"name": "토마토", "amount": "1개"},
                {"name": "생바질", "amount": "한 줌"},
                {"name": "엑스트라버진 올리브오일", "amount": "2큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "발사믹 글레이즈 (선택)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "모짜렐라와 토마토를 1cm 두께로 슬라이스해요.", "en": "Slice mozzarella and tomato 1cm thick."},
                {"ko": "접시에 번갈아 가며 예쁘게 올려요.", "en": "Arrange alternately on a plate."},
                {"ko": "바질 잎을 사이사이에 끼워요.", "en": "Tuck basil leaves between the slices."},
                {"ko": "올리브오일을 뿌리고 소금·후추를 갈아요.", "en": "Drizzle olive oil and season with salt and pepper."},
                {"ko": "발사믹 글레이즈를 살짝 뿌리면 더 고급스러워요.", "en": "A drizzle of balsamic glaze makes it extra elegant."},
            ],
        },
        {
            "id": "coleslaw",
            "name": {"ko": "코울슬로", "en": "Coleslaw", "ja": "コールスロー", "zh": "卷心菜沙拉"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "아삭하고 새콤달콤한 양배추 샐러드, 프라이드치킨 단짝", "en": "Crisp, tangy slaw — perfect alongside fried chicken"},
            "ingredients": [
                {"name": "양배추", "amount": "1/4개"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "마요네즈", "amount": "3큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "양배추·당근을 얇게 채 썰어요.", "en": "Shred cabbage and carrot very thin."},
                {"ko": "소금 1작은술을 뿌려 10분 절인 뒤 물기를 꼭 짜요.", "en": "Salt, let sit 10 minutes, then squeeze out moisture."},
                {"ko": "마요네즈·식초·설탕·소금·후추를 섞어 드레싱을 만들어요.", "en": "Mix mayo, vinegar, sugar, salt, and pepper for dressing."},
                {"ko": "채소에 드레싱을 넣고 버무려요.", "en": "Toss vegetables with dressing."},
                {"ko": "냉장고에 30분 두면 맛이 더 좋아요.", "en": "Chill 30 minutes in the fridge for best flavor."},
            ],
        },
    ],
    "western/bread": [
        {
            "id": "croque-monsieur",
            "name": {"ko": "크로크무슈", "en": "Croque Monsieur", "ja": "クロックムッシュ", "zh": "法式火腿芝士三明治"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "구운 햄 치즈 샌드위치의 프랑스 버전, 베샤멜이 핵심", "en": "The French way to do a ham and cheese — béchamel makes it"},
            "ingredients": [
                {"name": "식빵 또는 바게트 슬라이스", "amount": "2장"},
                {"name": "슬라이스 햄", "amount": "2장"},
                {"name": "그뤼에르 또는 모짜렐라 치즈", "amount": "40g"},
                {"name": "버터", "amount": "2큰술"},
                {"name": "밀가루", "amount": "1큰술"},
                {"name": "우유", "amount": "100ml"},
                {"name": "소금·후추·너트맥", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "버터·밀가루를 볶다가 우유를 부어 베샤멜 소스를 만들어요.", "en": "Cook butter and flour, whisk in milk to make béchamel."},
                {"ko": "소금·후추·너트맥으로 간해요.", "en": "Season béchamel with salt, pepper, and nutmeg."},
                {"ko": "빵에 베샤멜·햄·치즈를 올려 샌드위치를 만들어요.", "en": "Spread béchamel on bread, layer ham and cheese, sandwich."},
                {"ko": "위에도 베샤멜을 바르고 치즈를 올려요.", "en": "Spread more béchamel on top and add extra cheese."},
                {"ko": "230°C 오븐에서 치즈가 녹고 황금색이 될 때까지 5-7분 구워요.", "en": "Bake at 230°C 5-7 minutes until cheese is golden and bubbly."},
            ],
        },
        {
            "id": "pancakes",
            "name": {"ko": "아메리칸 팬케이크", "en": "American Pancakes", "ja": "アメリカンパンケーキ", "zh": "美式松饼"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "두툼하고 폭신한 미국식 팬케이크, 주말 아침 최고", "en": "Thick, fluffy pancakes — the ideal weekend breakfast"},
            "ingredients": [
                {"name": "박력분", "amount": "150g"},
                {"name": "설탕", "amount": "2큰술"},
                {"name": "베이킹파우더", "amount": "1.5작은술"},
                {"name": "소금", "amount": "1/4작은술"},
                {"name": "계란", "amount": "1개"},
                {"name": "우유", "amount": "150ml"},
                {"name": "버터 (녹인 것)", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "가루류(밀가루·설탕·베이킹파우더·소금)를 섞어요.", "en": "Whisk together all dry ingredients."},
                {"ko": "계란·우유·녹인 버터를 섞어요.", "en": "Mix together egg, milk, and melted butter."},
                {"ko": "젖은 재료를 가루 재료에 넣고 살살 섞어요. 덩어리가 조금 있어도 OK.", "en": "Pour wet into dry and fold gently. A few lumps are fine."},
                {"ko": "버터 바른 약불 팬에 국자로 떠서 부어요.", "en": "Ladle onto a lightly buttered pan over low-medium heat."},
                {"ko": "표면에 기포가 생기면 뒤집어 1분 더 구워요.", "en": "Flip when bubbles form on the surface; cook 1 more minute."},
            ],
        },
    ],
    "western/baking": [
        {
            "id": "madeleine",
            "name": {"ko": "마들렌", "en": "Madeleine", "ja": "マドレーヌ", "zh": "玛德琳"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "조개 모양 프랑스 구움 과자, 레몬향이 포인트", "en": "French shell-shaped cake with a hint of lemon"},
            "ingredients": [
                {"name": "박력분", "amount": "100g"},
                {"name": "버터 (녹인 것)", "amount": "90g"},
                {"name": "설탕", "amount": "90g"},
                {"name": "계란", "amount": "2개"},
                {"name": "베이킹파우더", "amount": "1/2작은술"},
                {"name": "레몬 제스트", "amount": "1/2개분"},
                {"name": "꿀", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "계란·설탕·꿀을 잘 섞어요.", "en": "Beat eggs, sugar, and honey together well."},
                {"ko": "체 친 밀가루·베이킹파우더를 넣고 섞어요.", "en": "Fold in sifted flour and baking powder."},
                {"ko": "녹인 버터와 레몬 제스트를 넣어요.", "en": "Add melted butter and lemon zest."},
                {"ko": "반죽을 냉장고에 30분 휴지시켜요. 이 단계가 볼록 솟은 배꼽을 만들어요.", "en": "Rest batter in the fridge 30 minutes — this creates the signature hump."},
                {"ko": "버터 바른 틀에 80% 채워 190°C에서 12분 구워요.", "en": "Fill buttered molds 80%; bake at 190°C for 12 minutes."},
            ],
        },
        {
            "id": "cheesecake-nobake",
            "name": {"ko": "노오븐 치즈케이크", "en": "No-Bake Cheesecake", "ja": "ノーベイクチーズケーキ", "zh": "免烤芝士蛋糕"},
            "time": 30, "difficulty": 1,
            "desc": {"ko": "오븐 없이 냉장고에서 굳히는 간단 치즈케이크", "en": "Set in the fridge, not the oven — foolproof cheesecake"},
            "ingredients": [
                {"name": "크림치즈", "amount": "200g"},
                {"name": "생크림", "amount": "150ml"},
                {"name": "설탕", "amount": "50g"},
                {"name": "레몬즙", "amount": "1큰술"},
                {"name": "소화 크래커 (바닥용)", "amount": "100g"},
                {"name": "버터 (녹인 것)", "amount": "50g"},
                {"name": "젤라틴 (판)", "amount": "2장"},
            ],
            "steps": [
                {"ko": "크래커를 잘게 부숴 녹인 버터와 섞어 틀 바닥에 눌러요.", "en": "Crush crackers, mix with melted butter, press into the bottom of a mold."},
                {"ko": "젤라틴을 찬물에 불려요.", "en": "Soak gelatin sheets in cold water."},
                {"ko": "크림치즈·설탕·레몬즙을 부드럽게 섞어요.", "en": "Beat cream cheese with sugar and lemon juice until smooth."},
                {"ko": "생크림을 70%로 휘핑하여 크림치즈에 섞어요.", "en": "Whip cream to 70%; fold into cream cheese mixture."},
                {"ko": "불린 젤라틴을 전자레인지 10초로 녹여 섞고 틀에 부어 4시간 냉장해요.", "en": "Melt gelatin and stir in; pour into mold and refrigerate 4 hours."},
            ],
        },
    ],

    # ── 일식 추가 ────────────────────────────────────────────────
    "japanese/sushi": [
        {
            "id": "maki-sushi",
            "name": {"ko": "마끼 (김초밥)", "en": "Maki Roll", "ja": "巻き寿司", "zh": "卷寿司"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "김에 밥과 재료를 돌돌 만 기본 스시", "en": "The classic nori roll — once you learn it, it's addictive"},
            "ingredients": [
                {"name": "스시 밥", "amount": "1공기"},
                {"name": "김 (초밥용)", "amount": "2장"},
                {"name": "오이", "amount": "1/4개"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "크래미 또는 참치캔", "amount": "50g"},
                {"name": "마요네즈", "amount": "1큰술"},
                {"name": "와사비 (선택)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "오이·당근을 길쭉하게 채 썰어요.", "en": "Cut cucumber and carrot into long thin sticks."},
                {"ko": "참치캔은 기름을 빼고 마요네즈와 섞어요.", "en": "Drain tuna and mix with mayo."},
                {"ko": "대나무 발 위에 김을 올리고 스시 밥을 얇게 펴요. 위쪽 2cm는 남겨요.", "en": "Lay nori on bamboo mat; spread rice thinly, leaving 2cm at the top."},
                {"ko": "가운데에 재료를 올리고 단단히 말아요.", "en": "Place fillings in the center and roll firmly."},
                {"ko": "물에 적신 칼로 먹기 좋게 잘라요.", "en": "Slice with a wet knife."},
            ],
        },
        {
            "id": "inari-sushi",
            "name": {"ko": "이나리즈시 (유부초밥)", "en": "Inari Sushi", "ja": "いなり寿司", "zh": "稻荷寿司"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "달콤한 유부 안에 스시 밥을 채운 간편 초밥", "en": "Sweet tofu pockets filled with seasoned sushi rice"},
            "ingredients": [
                {"name": "스시 밥", "amount": "1공기"},
                {"name": "유부초밥용 유부 (시판)", "amount": "10개"},
                {"name": "통깨", "amount": "약간"},
                {"name": "당근·시금치 등 나물 (선택)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "시판 유부초밥 팩은 유부와 소스가 함께 들어있어요.", "en": "Pre-packaged inari kits include seasoned tofu pockets."},
                {"ko": "스시 밥을 지어 양념을 섞어요.", "en": "Cook and season the sushi rice."},
                {"ko": "밥에 통깨를 넣어 섞어요.", "en": "Mix sesame seeds into the rice."},
                {"ko": "유부를 조심스럽게 열어 밥을 채워요. 너무 꽉 넣지 마세요.", "en": "Gently open each tofu pocket and fill with rice. Don't overstuff."},
                {"ko": "입구를 접어 마무리해요.", "en": "Fold the opening closed."},
            ],
        },
    ],
    "japanese/ramen": [
        {
            "id": "miso-ramen",
            "name": {"ko": "미소 라멘", "en": "Miso Ramen", "ja": "味噌ラーメン", "zh": "味噌拉面"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "된장의 깊은 감칠맛이 살아있는 진한 라멘", "en": "Rich miso broth with deep, savory complexity"},
            "ingredients": [
                {"name": "생라멘 면", "amount": "1인분"},
                {"name": "닭육수", "amount": "2.5컵"},
                {"name": "미소 (된장)", "amount": "2큰술"},
                {"name": "고추장 또는 고추기름", "amount": "1작은술"},
                {"name": "마늘", "amount": "1작은술"},
                {"name": "버터", "amount": "1작은술"},
                {"name": "숙주·옥수수·버터", "amount": "토핑용"},
            ],
            "steps": [
                {"ko": "냄비에 기름 두르고 마늘을 볶아요.", "en": "Stir-fry garlic in a little oil."},
                {"ko": "닭육수를 붓고 끓여요.", "en": "Add chicken broth and bring to a boil."},
                {"ko": "미소를 체에 걸러 풀어요. 끓이지 않아야 풍미가 살아요.", "en": "Dissolve miso through a strainer. Don't boil after adding miso."},
                {"ko": "고추기름을 넣어 매콤하게 해요.", "en": "Add chili oil for heat."},
                {"ko": "삶은 면을 담고 숙주·옥수수·버터를 올려요.", "en": "Add cooked noodles and top with bean sprouts, corn, and butter."},
            ],
        },
        {
            "id": "soba",
            "name": {"ko": "자루소바 (냉소바)", "en": "Zaru Soba", "ja": "ざるそば", "zh": "冷荞麦面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "메밀향이 살아있는 시원한 냉소바", "en": "Chilled buckwheat noodles with fragrant dipping broth"},
            "ingredients": [
                {"name": "소바 면", "amount": "1인분"},
                {"name": "쯔유", "amount": "4큰술"},
                {"name": "물", "amount": "8큰술"},
                {"name": "무즙", "amount": "2큰술"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "와사비", "amount": "약간"},
                {"name": "김 (채 썬 것)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "소바를 끓는 물에 삶아요. 끓어 넘칠 것 같으면 찬물 약간 넣어요.", "en": "Boil soba noodles. If it boils over, add a splash of cold water."},
                {"ko": "찬물에 힘차게 헹궈 전분을 씻어내요.", "en": "Rinse vigorously in cold water to remove starch."},
                {"ko": "쯔유와 물을 섞어 소스를 만들어요.", "en": "Dilute tsuyu with water."},
                {"ko": "소바를 채반에 담고 김을 올려요.", "en": "Arrange soba on a strainer and top with nori."},
                {"ko": "소스에 무즙·쪽파·와사비를 넣어 찍어 드세요.", "en": "Mix grated daikon, green onion, and wasabi into sauce; dip and eat."},
            ],
        },
    ],
    "japanese/donburi": [
        {
            "id": "kaisen-don",
            "name": {"ko": "카이센동 (해산물 덮밥)", "en": "Kaisen Don", "ja": "海鮮丼", "zh": "海鲜盖饭"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "신선한 회를 스시 밥 위에 올리면 끝, 간단 고급 요리", "en": "Fresh sashimi over seasoned rice — effortlessly luxurious"},
            "ingredients": [
                {"name": "스시 밥", "amount": "1공기"},
                {"name": "연어·참치·광어 (회용)", "amount": "각 50g"},
                {"name": "단새우 (선택)", "amount": "3마리"},
                {"name": "와사비", "amount": "약간"},
                {"name": "간장", "amount": "찍어 먹을 것"},
                {"name": "쪽파·초생강", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "스시 밥을 짓고 스시식초를 섞어 식혀요.", "en": "Make sushi rice and let cool."},
                {"ko": "생선을 0.5-1cm 두께로 썰어요.", "en": "Slice fish 0.5-1cm thick."},
                {"ko": "밥을 그릇에 담고 와사비를 올려요.", "en": "Serve rice in a bowl with a touch of wasabi."},
                {"ko": "생선을 예쁘게 펼쳐 올려요.", "en": "Arrange fish slices decoratively over the rice."},
                {"ko": "쪽파·초생강을 올리고 간장을 곁들여요.", "en": "Garnish with green onion and pickled ginger; serve with soy sauce."},
            ],
        },
        {
            "id": "tendon",
            "name": {"ko": "텐동 (튀김 덮밥)", "en": "Tendon", "ja": "天丼", "zh": "天妇罗盖饭"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "바삭한 튀김 위에 달콤한 텐동 소스가 흐르는 덮밥", "en": "Crispy tempura over rice with sweet-savory tendon sauce"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "새우·연근·고구마 등 튀김 재료", "amount": "적당량"},
                {"name": "박력분·계란·얼음물", "amount": "튀김 반죽용"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "미림", "amount": "2큰술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "다시", "amount": "3큰술"},
            ],
            "steps": [
                {"ko": "간장·미림·설탕·다시를 끓여 텐동 소스를 만들어요.", "en": "Simmer soy sauce, mirin, sugar, and dashi to make tendon sauce."},
                {"ko": "튀김 반죽을 만들어요. 얼음물과 밀가루를 섞되 젓가락으로 대충 섞어요.", "en": "Make batter with ice water and flour; mix roughly with chopsticks."},
                {"ko": "재료에 밀가루를 살짝 뿌린 뒤 반죽을 입혀 170°C에서 튀겨요.", "en": "Dust ingredients with flour, dip in batter, and fry at 170°C."},
                {"ko": "밥 위에 튀김을 올려요.", "en": "Place tempura over rice."},
                {"ko": "뜨거운 텐동 소스를 끼얹어요.", "en": "Pour hot tendon sauce over."},
            ],
        },
    ],
    "japanese/tempura": [
        {
            "id": "vegetable-tempura",
            "name": {"ko": "야채튀김", "en": "Vegetable Tempura", "ja": "野菜の天ぷら", "zh": "蔬菜天妇罗"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "제철 채소의 맛을 살린 바삭한 튀김", "en": "Seasonal vegetables in the lightest, crispiest batter"},
            "ingredients": [
                {"name": "단호박·고구마·연근·표고버섯 등", "amount": "각 1/4개 또는 2-3개"},
                {"name": "박력분", "amount": "1컵"},
                {"name": "계란", "amount": "1개"},
                {"name": "얼음물", "amount": "1컵"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
                {"name": "튀김 소금 또는 쯔유", "amount": "찍어 먹을 것"},
            ],
            "steps": [
                {"ko": "채소를 0.5-1cm 두께로 썰어요.", "en": "Slice vegetables 0.5-1cm thick."},
                {"ko": "물기를 완전히 제거해요. 물기가 있으면 튀김이 바삭하지 않아요.", "en": "Pat completely dry — moisture makes tempura soggy."},
                {"ko": "박력분·계란·얼음물을 젓가락으로 10번만 섞어요.", "en": "Mix flour, egg, and ice water with just 10 stirs. Lumps are intentional."},
                {"ko": "채소에 밀가루 살짝 뿌리고 반죽 입혀 170°C에서 2분 튀겨요.", "en": "Dust vegetables with flour, coat in batter, and fry at 170°C for 2 minutes."},
                {"ko": "소금이나 쯔유에 찍어 드세요.", "en": "Serve with tempura salt or tsuyu dipping sauce."},
            ],
        },
        {
            "id": "hire-katsu",
            "name": {"ko": "히레카츠 (안심 돈가스)", "en": "Hire Katsu (Pork Tenderloin Cutlet)", "ja": "ヒレカツ", "zh": "猪里脊排"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "지방이 없는 안심으로 만드는 부드러운 돈가스", "en": "Tender, lean pork cutlet — lighter than regular katsu"},
            "ingredients": [
                {"name": "돼지 안심", "amount": "150g"},
                {"name": "박력분", "amount": "3큰술"},
                {"name": "계란", "amount": "1개"},
                {"name": "빵가루", "amount": "5큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
                {"name": "돈가스 소스·양배추", "amount": "곁들임용"},
            ],
            "steps": [
                {"ko": "안심을 2cm 두께로 잘라 고기망치나 칼등으로 두드려 펴요.", "en": "Cut tenderloin 2cm thick; pound to tenderize."},
                {"ko": "소금·후추로 밑간해요.", "en": "Season with salt and pepper."},
                {"ko": "밀가루→계란→빵가루 순으로 입혀요. 빵가루는 꾹꾹 눌러 붙여요.", "en": "Coat in flour, egg, then breadcrumbs; press crumbs on firmly."},
                {"ko": "170°C 기름에 3분 튀겨요.", "en": "Deep-fry at 170°C for 3 minutes."},
                {"ko": "기름을 빼고 돈가스 소스와 채 썬 양배추와 함께 내요.", "en": "Drain oil and serve with tonkatsu sauce and shredded cabbage."},
            ],
        },
    ],
    "japanese/miso": [
        {
            "id": "miso-glazed-eggplant",
            "name": {"ko": "가지 된장구이 (나스 덴가쿠)", "en": "Miso-Glazed Eggplant", "ja": "なすの田楽", "zh": "味噌烤茄子"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "달콤한 미소 글레이즈가 가지에 배어든 고급 반찬", "en": "Sweet miso glaze soaked into silky eggplant"},
            "ingredients": [
                {"name": "가지", "amount": "2개"},
                {"name": "미소 (된장)", "amount": "2큰술"},
                {"name": "미림", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "청주 또는 물", "amount": "1큰술"},
                {"name": "참기름", "amount": "1큰술"},
                {"name": "통깨", "amount": "약간"},
            ],
            "steps": [
                {"ko": "미소·미림·설탕·청주를 섞어 글레이즈를 만들어요.", "en": "Mix miso, mirin, sugar, and sake for the glaze."},
                {"ko": "가지를 반으로 갈라 칼집을 격자로 넣어요. 잘 익고 양념이 배어요.", "en": "Halve eggplant and score flesh in a crosshatch — helps it cook and absorb flavor."},
                {"ko": "팬에 참기름 두르고 가지를 단면 아래로 놓고 중불에서 4분 구워요.", "en": "Heat sesame oil; place eggplant cut-side down and cook 4 minutes over medium."},
                {"ko": "뒤집어 글레이즈를 단면에 발라요.", "en": "Flip and spread glaze on the cut surface."},
                {"ko": "약불로 줄이고 뚜껑 덮어 3분 더 익혀요. 통깨를 뿌려요.", "en": "Reduce to low, cover, and cook 3 more minutes. Sprinkle sesame seeds."},
            ],
        },
        {
            "id": "sukiyaki",
            "name": {"ko": "스키야키", "en": "Sukiyaki", "ja": "すき焼き", "zh": "寿喜烧"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "달콤한 간장 국물에 소고기와 채소를 끓여 먹는 일본 전골", "en": "Japanese hot pot with beef and vegetables in a sweet soy broth"},
            "ingredients": [
                {"name": "소고기 (얇게 썬 것)", "amount": "200g"},
                {"name": "두부", "amount": "1/2모"},
                {"name": "대파·표고버섯·팽이버섯", "amount": "적당량"},
                {"name": "실곤약", "amount": "1/2팩"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "미림", "amount": "3큰술"},
                {"name": "설탕", "amount": "1.5큰술"},
                {"name": "생계란 (찍어 먹기용)", "amount": "1개"},
            ],
            "steps": [
                {"ko": "간장·미림·설탕을 섞어 와리시타 소스를 만들어요.", "en": "Mix soy sauce, mirin, and sugar to make warishita sauce."},
                {"ko": "전골 냄비에 소기름 또는 식용유를 두르고 소고기를 먼저 구워요.", "en": "Heat beef fat or oil in a pot; sear beef first."},
                {"ko": "와리시타를 붓고 채소·두부·곤약을 넣어요.", "en": "Pour in warishita and add vegetables, tofu, and konnyaku."},
                {"ko": "뚜껑 덮고 5분 끓여요.", "en": "Cover and simmer 5 minutes."},
                {"ko": "생계란을 풀어 재료를 찍어 드세요. 날계란이 싫으면 반숙 계란으로 대체해요.", "en": "Dip ingredients in beaten raw egg. Use soft-boiled if you prefer."},
            ],
        },
    ],
}
