RECIPES_JP = {
    "japanese/sushi": [
        {
            "id": "salmon-sushi",
            "name": {"ko": "연어초밥", "en": "Salmon Sushi", "ja": "サーモン寿司", "zh": "三文鱼寿司"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "집에서 만드는 연어초밥, 밥 온도가 핵심", "en": "Homemade salmon sushi — rice temperature is everything", "ja": "家で作るサーモン寿司、ご飯の温度が命", "zh": "在家制作三文鱼寿司，米饭温度是关键"},
            "ingredients": [
                {"name": "밥 (따뜻한 것)", "amount": "1공기"},
                {"name": "식초", "amount": "2큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "소금", "amount": "1작은술"},
                {"name": "신선한 연어 (회용)", "amount": "100g"},
                {"name": "와사비", "amount": "약간"},
            ],
            "steps": [
                {"ko": "식초·설탕·소금을 섞어 스시식초를 만들어요.", "en": "Mix vinegar, sugar, and salt to make sushi vinegar.", "ja": "酢・砂糖・塩を混ぜてすし酢を作ります。", "zh": "将醋、糖、盐混合制成寿司醋。"},
                {"ko": "따뜻한 밥에 스시식초를 넣고 주걱으로 자르듯 섞어요. 뭉개면 안 돼요.", "en": "Fold sushi vinegar into warm rice with a spatula — don't mash.", "ja": "温かいご飯にすし酢を加えしゃもじで切るように混ぜます。つぶさないように。", "zh": "将寿司醋加入温热米饭中，用饭铲切拌，不要压碎米粒。"},
                {"ko": "부채질하며 한 김 식혀요. 광택이 나야 해요.", "en": "Fan while cooling. The rice should be glossy.", "ja": "うちわで扇ぎながら冷まします。つやが出るはずです。", "zh": "边扇风边冷却，米饭应该有光泽。"},
                {"ko": "밥을 손에 쥐어 타원형으로 만들어요. 손에 물을 묻히면 안 달라붙어요.", "en": "Shape rice into ovals with wet hands to prevent sticking.", "ja": "手に水をつけてご飯を握り楕円形に成形します。水で手を濡らすとくっつきません。", "zh": "手沾水后将米饭握成椭圆形，沾水可防止粘手。"},
                {"ko": "연어를 얇게 썰어 와사비를 살짝 올리고 밥 위에 얹어요.", "en": "Slice salmon, dab a little wasabi, and lay over the rice.", "ja": "サーモンを薄く切りわさびを少しのせてシャリの上に置きます。", "zh": "将三文鱼切薄片，抹少量芥末后放在寿司饭上。"},
            ],
        },
        {
            "id": "tuna-sushi",
            "name": {"ko": "참치초밥", "en": "Tuna Sushi", "ja": "マグロ寿司", "zh": "金枪鱼寿司"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "초밥의 클래식, 참치 아카미로 만드는 정통 초밥", "en": "The classic — authentic nigiri with tuna akami", "ja": "寿司の定番、マグロの赤身で作る本格握り寿司", "zh": "寿司经典之作，用金枪鱼赤身做的正宗握寿司"},
            "ingredients": [
                {"name": "밥 (따뜻한 것)", "amount": "1공기"},
                {"name": "스시식초", "amount": "3큰술"},
                {"name": "신선한 참치 (회용)", "amount": "100g"},
                {"name": "와사비", "amount": "약간"},
                {"name": "간장", "amount": "찍어 먹을 것"},
            ],
            "steps": [
                {"ko": "밥에 스시식초를 섞어 샤리(초밥 밥)를 만들어요.", "en": "Mix vinegar into rice to make shari.", "ja": "ご飯にすし酢を混ぜてシャリを作ります。", "zh": "将寿司醋拌入米饭制成醋饭。"},
                {"ko": "참치를 결 반대로 0.5cm 두께로 썰어요.", "en": "Slice tuna against the grain to 0.5cm thickness.", "ja": "マグロを繊維に逆らって0.5cmの厚さに切ります。", "zh": "金枪鱼逆着纹路切成0.5cm厚。"},
                {"ko": "손바닥에 밥을 올리고 꾹 쥐어 타원형으로 만들어요.", "en": "Place rice on your palm and gently press into an oval.", "ja": "手のひらにご飯をのせてしっかり握り楕円形に成形します。", "zh": "将米饭放在手心用力握成椭圆形。"},
                {"ko": "참치 위에 와사비를 아주 조금 올려요.", "en": "Dab a tiny bit of wasabi on the tuna.", "ja": "マグロの上にわさびをほんの少しのせます。", "zh": "在金枪鱼上放极少量芥末。"},
                {"ko": "밥 위에 참치를 올리고 살짝 눌러 고정해요. 간장에 찍어 드세요.", "en": "Press tuna onto rice and serve with soy sauce for dipping.", "ja": "シャリの上にマグロをのせて軽く押さえ固定します。醤油につけていただきます。", "zh": "将金枪鱼放在醋饭上轻压固定，蘸酱油食用。"},
            ],
        },
        {
            "id": "tamago-sushi",
            "name": {"ko": "계란초밥 (타마고)", "en": "Tamago Sushi", "ja": "玉子寿司", "zh": "厚蛋烧寿司"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "달콤하고 폭신한 두꺼운 달걀말이 초밥", "en": "Sweet and fluffy thick omelette on sushi rice", "ja": "甘くてふんわりした厚焼き玉子の寿司", "zh": "甜软蓬松的厚蛋烧寿司"},
            "ingredients": [
                {"name": "계란", "amount": "3개"},
                {"name": "설탕", "amount": "1.5큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "미림", "amount": "1큰술"},
                {"name": "밥 (스시용)", "amount": "1/2공기"},
                {"name": "김", "amount": "적당히"},
            ],
            "steps": [
                {"ko": "계란·설탕·간장·미림을 잘 섞어요.", "en": "Beat eggs with sugar, soy sauce, and mirin.", "ja": "卵・砂糖・醤油・みりんをよく混ぜます。", "zh": "将鸡蛋、糖、酱油、味醂充分混合。"},
                {"ko": "사각 타마고야키 팬(없으면 일반 팬)에 기름 얇게 두르고 달구어요.", "en": "Lightly oil a rectangular tamagoyaki pan (or regular pan) and heat.", "ja": "玉子焼き専用パン（なければ普通のフライパン）に薄く油をひいて熱します。", "zh": "在玉子烧专用锅（没有的话用普通锅）薄薄涂油后加热。"},
                {"ko": "계란물을 3번에 나눠 부어가며 두툼하게 말아요.", "en": "Pour egg mixture in 3 batches, rolling each time to build layers.", "ja": "卵液を3回に分けて注ぎながら厚みを出して巻きます。", "zh": "将蛋液分3次倒入，每次卷起使其变厚。"},
                {"ko": "식힌 뒤 1cm 두께로 썰어요.", "en": "Cool and slice to 1cm thickness.", "ja": "冷ましてから1cmの厚さに切ります。", "zh": "冷却后切成1cm厚。"},
                {"ko": "스시 밥을 타원으로 만들고 계란을 올려 김으로 고정해요.", "en": "Form rice ovals, top with tamago, and wrap with a strip of nori.", "ja": "寿司飯を楕円形にして玉子をのせ海苔で固定します。", "zh": "将醋饭捏成椭圆形，放上玉子烧，用海苔固定。"},
            ],
        },
    ],
    "japanese/ramen": [
        {
            "id": "shoyu-ramen",
            "name": {"ko": "간장 라멘", "en": "Shoyu Ramen", "ja": "醤油ラーメン", "zh": "酱油拉面"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "깊고 담백한 간장 베이스 라멘, 집에서도 충분히 가능", "en": "Deep, clean soy-based ramen you can make at home", "ja": "深くあっさりした醤油ベースのラーメン、家でも十分作れる", "zh": "深厚清爽的酱油底拉面，在家也能轻松完成"},
            "ingredients": [
                {"name": "생라멘 면 또는 중면", "amount": "1인분"},
                {"name": "닭육수 또는 시판 육수", "amount": "2.5컵"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "미림", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "반숙 계란·차슈·대파", "amount": "토핑용"},
            ],
            "steps": [
                {"ko": "냄비에 육수·간장·미림·마늘을 넣고 끓여요.", "en": "Combine broth, soy sauce, mirin, and garlic; bring to a boil.", "ja": "鍋にスープ・醤油・みりん・にんにくを入れて煮立てます。", "zh": "锅中加入高汤、酱油、味醂、蒜末煮沸。"},
                {"ko": "간을 보고 부족하면 간장·소금으로 조절해요.", "en": "Taste and adjust seasoning with soy sauce or salt.", "ja": "味見して足りなければ醤油や塩で調整します。", "zh": "尝味，不够的话用酱油或盐调整。"},
                {"ko": "면을 별도 냄비에 삶아요.", "en": "Cook noodles in a separate pot.", "ja": "麺を別の鍋で茹でます。", "zh": "另起锅将面条煮熟。"},
                {"ko": "그릇을 뜨겁게 데운 뒤 면을 담아요. 그릇이 차가우면 국물이 식어요.", "en": "Warm the bowl before serving — cold bowls cool the soup fast.", "ja": "器を熱く温めてから麺を入れます。器が冷たいとスープが冷めてしまいます。", "zh": "将碗预热后再放入面条，碗凉会导致汤快速变冷。"},
                {"ko": "국물을 붓고 토핑을 올려요.", "en": "Pour broth over and add toppings.", "ja": "スープを注いでトッピングをのせます。", "zh": "倒入汤底，放上配料。"},
            ],
        },
        {
            "id": "curry-udon",
            "name": {"ko": "카레 우동", "en": "Curry Udon", "ja": "カレーうどん", "zh": "咖喱乌冬面"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "걸쭉한 카레 국물에 쫄깃한 우동면, 간단하고 든든", "en": "Thick curry broth with chewy udon — simple and satisfying", "ja": "とろりカレースープにもちもちうどん麺、簡単でボリューム満点", "zh": "浓稠咖喱汤底配劲道乌冬面，简单又饱腹"},
            "ingredients": [
                {"name": "우동 면 (냉동 가능)", "amount": "1인분"},
                {"name": "시판 카레 루", "amount": "1조각"},
                {"name": "닭육수 또는 물", "amount": "2컵"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "대파", "amount": "약간"},
                {"name": "간장", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "양파를 채 썰어 기름에 볶아요.", "en": "Slice onion and stir-fry in oil.", "ja": "玉ねぎを薄切りにして油で炒めます。", "zh": "洋葱切丝，用油翻炒。"},
                {"ko": "육수를 붓고 끓으면 카레 루를 넣어 녹여요.", "en": "Add broth and dissolve curry roux once boiling.", "ja": "スープを注いで沸騰したらカレールーを入れて溶かします。", "zh": "倒入高汤，沸腾后放入咖喱块融化。"},
                {"ko": "간장으로 간을 맞춰요.", "en": "Season with soy sauce.", "ja": "醤油で味を整えます。", "zh": "用酱油调味。"},
                {"ko": "우동 면을 삶아 그릇에 담아요.", "en": "Cook udon and place in bowl.", "ja": "うどんを茹でて器に盛ります。", "zh": "将乌冬面煮熟后盛入碗中。"},
                {"ko": "카레 국물을 붓고 대파를 올려요.", "en": "Pour curry broth over and top with green onion.", "ja": "カレースープを注いで長ねぎをのせます。", "zh": "倒入咖喱汤，放上大葱。"},
            ],
        },
        {
            "id": "cold-udon",
            "name": {"ko": "냉우동 (자루우동)", "en": "Cold Udon", "ja": "ざるうどん", "zh": "冷乌冬面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "여름에 먹는 시원한 쯔유 우동", "en": "Chilled udon with dipping broth for hot days", "ja": "夏に食べる冷たいつゆうどん", "zh": "夏日必吃的清凉蘸汁乌冬面"},
            "ingredients": [
                {"name": "우동 면", "amount": "1인분"},
                {"name": "쯔유 (시판)", "amount": "3큰술"},
                {"name": "물", "amount": "6큰술 (쯔유 희석용)"},
                {"name": "무즙 (간 무)", "amount": "2큰술"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "김 (채 썬 것)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "우동 면을 삶은 뒤 찬물에 헹궈 쫄깃하게 만들어요.", "en": "Cook udon, then rinse in cold water until firm and chewy.", "ja": "うどんを茹でてから冷水で洗いコシを出します。", "zh": "乌冬面煮熟后用冷水冲洗，使其更加劲道。"},
                {"ko": "쯔유를 물로 희석해 찍어 먹는 소스를 만들어요.", "en": "Dilute tsuyu with water to make the dipping sauce.", "ja": "めんつゆを水で薄めてつけ汁を作ります。", "zh": "将麺露用水稀释制成蘸汁。"},
                {"ko": "면을 채반이나 그릇에 담아요.", "en": "Arrange noodles on a bamboo strainer or plate.", "ja": "麺をざるや器に盛ります。", "zh": "将面条盛入竹笊篱或碗中。"},
                {"ko": "무즙·쪽파·김을 올려요.", "en": "Top with grated daikon, green onion, and nori.", "ja": "大根おろし・小ねぎ・刻み海苔をのせます。", "zh": "放上萝卜泥、葱花和海苔丝。"},
                {"ko": "소스에 찍어 드세요.", "en": "Dip noodles in sauce and enjoy.", "ja": "つゆにつけてお召し上がりください。", "zh": "蘸汁食用。"},
            ],
        },
    ],
    "japanese/donburi": [
        {
            "id": "katsudon",
            "name": {"ko": "가츠동", "en": "Katsudon", "ja": "カツ丼", "zh": "炸猪排饭"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "바삭한 돈가츠를 달걀로 감싸 밥 위에 올린 일본식 덮밥", "en": "Crispy pork cutlet simmered with egg over rice", "ja": "カリカリのトンカツを卵でとじてご飯の上にのせた丼", "zh": "酥脆猪排裹上鸡蛋盖在米饭上的日式盖饭"},
            "ingredients": [
                {"name": "돈가츠 (시판 또는 직접 튀긴 것)", "amount": "1장"},
                {"name": "밥", "amount": "1공기"},
                {"name": "계란", "amount": "2개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "쯔유", "amount": "3큰술"},
                {"name": "물", "amount": "5큰술"},
                {"name": "설탕", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "작은 팬에 쯔유·물·설탕을 넣고 끓여요.", "en": "Simmer tsuyu, water, and sugar in a small pan.", "ja": "小さなフライパンにめんつゆ・水・砂糖を入れて煮立てます。", "zh": "小锅中加入麺露、水、糖煮沸。"},
                {"ko": "양파를 얇게 썰어 넣고 1-2분 익혀요.", "en": "Add sliced onion and cook 1-2 minutes.", "ja": "薄切り玉ねぎを加えて1〜2分炒めます。", "zh": "放入薄切洋葱煮1-2分钟。"},
                {"ko": "돈가츠를 먹기 좋게 썰어 올려요.", "en": "Slice the katsu and lay it in the pan.", "ja": "とんかつを食べやすく切って並べます。", "zh": "将猪排切成合适大小放入锅中。"},
                {"ko": "계란을 풀어 반 정도 익힌 상태로 부어요.", "en": "Beat eggs and pour over, cooking until just half-set.", "ja": "卵を溶いて半熟になるように回しかけます。", "zh": "打散鸡蛋，倒入锅中使其半熟。"},
                {"ko": "뚜껑을 덮고 약불에서 30초, 반숙 상태에서 밥 위에 얹어요.", "en": "Cover and cook on low 30 seconds; slide over rice while still soft.", "ja": "蓋をして弱火で30秒、半熟の状態でご飯の上にのせます。", "zh": "盖锅盖小火焖30秒，在半熟状态下盖在米饭上。"},
            ],
        },
        {
            "id": "oyakodon",
            "name": {"ko": "오야코동", "en": "Oyakodon", "ja": "親子丼", "zh": "亲子丼"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "닭고기와 계란의 조합, 이름이 부모와 자식이라는 뜻", "en": "Chicken and egg together — ooya(parent) + ko(child)", "ja": "鶏肉と卵の組み合わせ、名前は親と子という意味", "zh": "鸡肉与鸡蛋的组合，名字意为亲子"},
            "ingredients": [
                {"name": "닭다리살", "amount": "150g"},
                {"name": "계란", "amount": "2개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "쯔유", "amount": "3큰술"},
                {"name": "물", "amount": "5큰술"},
                {"name": "밥", "amount": "1공기"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "닭다리살을 한 입 크기로 썰어요.", "en": "Cut chicken thigh into bite-sized pieces.", "ja": "鶏もも肉を一口大に切ります。", "zh": "鸡腿肉切成一口大小。"},
                {"ko": "팬에 쯔유·물을 끓이고 양파와 닭을 넣어 익혀요.", "en": "Boil tsuyu and water; add onion and chicken until cooked.", "ja": "フライパンにめんつゆ・水を煮立て玉ねぎと鶏肉を加えて火を通します。", "zh": "锅中将麺露和水煮沸，加入洋葱和鸡肉煮熟。"},
                {"ko": "계란을 풀어 가장자리부터 부어요.", "en": "Beat eggs and pour from the edges inward.", "ja": "卵を溶いて端から回しかけます。", "zh": "打散鸡蛋，从边缘开始倒入。"},
                {"ko": "뚜껑 덮고 30초, 반숙 상태에서 불을 꺼요.", "en": "Cover, 30 seconds, turn off heat while still soft.", "ja": "蓋をして30秒、半熟の状態で火を止めます。", "zh": "盖锅盖30秒，在半熟状态关火。"},
                {"ko": "밥 위에 얹고 쪽파를 올려요.", "en": "Serve over rice and top with green onion.", "ja": "ご飯の上にのせて小ねぎを散らします。", "zh": "盖在米饭上，撒上葱花。"},
            ],
        },
        {
            "id": "gyudon",
            "name": {"ko": "규동", "en": "Gyudon", "ja": "牛丼", "zh": "牛肉盖饭"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "달콤한 간장 소스 소고기덮밥, 요시노야의 그 맛", "en": "Sweet soy beef bowl — the iconic Yoshinoya taste", "ja": "甘い醤油ソースの牛丼、吉野家のあの味", "zh": "甜酱油牛肉盖饭，吉野家的经典味道"},
            "ingredients": [
                {"name": "소고기 (불고기용 또는 얇게 썬 것)", "amount": "150g"},
                {"name": "양파", "amount": "1/2개"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "미림", "amount": "2큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "다시 또는 물", "amount": "1/2컵"},
                {"name": "밥", "amount": "1공기"},
            ],
            "steps": [
                {"ko": "양파를 얇게 슬라이스해요.", "en": "Slice onion thinly.", "ja": "玉ねぎを薄くスライスします。", "zh": "洋葱切成薄片。"},
                {"ko": "냄비에 간장·미림·설탕·다시를 넣고 끓여요.", "en": "Combine soy sauce, mirin, sugar, and dashi; bring to a boil.", "ja": "鍋に醤油・みりん・砂糖・だしを入れて煮立てます。", "zh": "锅中加入酱油、味醂、糖、出汁煮沸。"},
                {"ko": "양파를 넣고 2분 익혀요.", "en": "Add onion and cook 2 minutes.", "ja": "玉ねぎを加えて2分煮ます。", "zh": "加入洋葱煮2分钟。"},
                {"ko": "소고기를 넣어 색이 변할 때까지 익혀요.", "en": "Add beef and cook until no longer pink.", "ja": "牛肉を加えて色が変わるまで火を通します。", "zh": "加入牛肉，煮至变色。"},
                {"ko": "밥 위에 얹어요. 반숙 계란을 올리면 더 맛있어요.", "en": "Serve over rice. A soft-boiled egg on top makes it even better.", "ja": "ご飯の上にのせます。半熟卵をのせるとさらに美味しいです。", "zh": "盖在米饭上。加个溏心蛋会更美味。"},
            ],
        },
    ],
    "japanese/tempura": [
        {
            "id": "shrimp-tempura",
            "name": {"ko": "새우튀김 (에비텐)", "en": "Shrimp Tempura", "ja": "エビ天ぷら", "zh": "虾天妇罗"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "얇고 바삭한 튀김옷이 핵심, 반죽을 과하게 섞지 마세요", "en": "Light, crispy batter is everything — don't overmix", "ja": "薄くサクサクの衣が命、生地を混ぜすぎないで", "zh": "薄而酥脆的面衣是关键，面糊不要过度搅拌"},
            "ingredients": [
                {"name": "큰 새우", "amount": "8마리"},
                {"name": "박력분", "amount": "1컵"},
                {"name": "계란", "amount": "1개"},
                {"name": "얼음물", "amount": "1컵"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "새우는 껍질 벗기고 내장 제거 후, 배 쪽에 2-3군데 칼집을 넣어 펴요.", "en": "Peel and devein shrimp; make 2-3 cuts on the belly side to straighten.", "ja": "エビの殻をむいて背わたを取り除き、お腹側に2〜3ヶ所切れ目を入れて伸ばします。", "zh": "虾去壳去背肠，在腹部划2-3刀使其伸直。"},
                {"ko": "박력분·계란·얼음물을 젓가락으로 대충 섞어요. 덩어리가 있어도 OK.", "en": "Mix flour, egg, and ice water with chopsticks — lumpy is fine.", "ja": "薄力粉・卵・冷水を箸でざっくり混ぜます。ダマがあってもOK。", "zh": "用筷子将低筋面粉、鸡蛋、冰水随意搅拌，有颗粒也没关系。"},
                {"ko": "기름을 170-175°C로 달궈요.", "en": "Heat oil to 170-175°C.", "ja": "油を170〜175°Cに熱します。", "zh": "将油加热至170-175°C。"},
                {"ko": "새우에 밀가루를 살짝 뿌리고 반죽을 입혀요.", "en": "Dust shrimp with flour, then coat in batter.", "ja": "エビに薄く小麦粉をはたき衣をつけます。", "zh": "虾表面薄薄撒上面粉，再裹上面糊。"},
                {"ko": "기름에 넣고 2-3분 바삭하게 튀겨요. 반죽 방울이 고소하게 퍼지면 돼요.", "en": "Fry 2-3 minutes until crispy. Batter droplets in the oil are normal.", "ja": "油に入れて2〜3分カラッと揚げます。衣の油滴が広がればOK。", "zh": "入油炸2-3分钟至酥脆。面糊液滴在油中散开即可。"},
            ],
        },
        {
            "id": "yakitori",
            "name": {"ko": "닭꼬치 (야키토리)", "en": "Yakitori", "ja": "焼き鳥", "zh": "日式烤鸡串"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "달콤 짭짤한 타레 소스를 발라 구운 닭꼬치", "en": "Chicken skewers glazed with sweet-salty tare sauce", "ja": "甘じょっぱいタレを塗って焼いた焼き鳥", "zh": "涂上甜咸照烧酱烤制的日式鸡肉串"},
            "ingredients": [
                {"name": "닭다리살", "amount": "200g"},
                {"name": "대파", "amount": "1/2대"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "미림", "amount": "3큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "꼬치 (나무꼬치는 30분 물에 담가요)", "amount": "8개"},
            ],
            "steps": [
                {"ko": "닭다리살과 대파를 한 입 크기로 썰어요.", "en": "Cut chicken and green onion into bite-sized pieces.", "ja": "鶏もも肉と長ねぎを一口大に切ります。", "zh": "鸡腿肉和大葱切成一口大小。"},
                {"ko": "간장·미림·설탕을 냄비에서 끓여 타레 소스를 만들어요.", "en": "Simmer soy sauce, mirin, and sugar to make tare glaze.", "ja": "醤油・みりん・砂糖を鍋で煮詰めてタレを作ります。", "zh": "将酱油、味醂、糖在锅中煮制制成照烧酱。"},
                {"ko": "닭과 대파를 꼬치에 번갈아 꽂아요.", "en": "Thread chicken and green onion alternately onto skewers.", "ja": "鶏肉と長ねぎを交互に串に刺します。", "zh": "将鸡肉和大葱交替串在竹签上。"},
                {"ko": "그릴 또는 팬에 중불로 구워요.", "en": "Grill over medium heat.", "ja": "グリルまたはフライパンで中火で焼きます。", "zh": "用烤架或平底锅中火烤制。"},
                {"ko": "익으면서 타레 소스를 2-3번 발라가며 구워요.", "en": "Brush with tare 2-3 times during cooking.", "ja": "焼きながらタレを2〜3回塗って仕上げます。", "zh": "烤制过程中刷2-3次照烧酱。"},
            ],
        },
        {
            "id": "grilled-salmon",
            "name": {"ko": "연어 구이 (시오야키)", "en": "Salt-Grilled Salmon", "ja": "鮭の塩焼き", "zh": "盐烤三文鱼"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "소금만 뿌려 구워도 이렇게 맛있는 일본식 생선구이", "en": "Just salt and heat — Japanese simplicity at its best", "ja": "塩を振って焼くだけでこんなに美味しい日本式魚の塩焼き", "zh": "只撒盐烤制却如此美味的日式烤鱼"},
            "ingredients": [
                {"name": "연어 (토막)", "amount": "1토막"},
                {"name": "소금", "amount": "1작은술"},
                {"name": "레몬", "amount": "1/4개"},
                {"name": "식용유", "amount": "약간"},
            ],
            "steps": [
                {"ko": "연어에 소금을 뿌리고 15분 이상 두었다가 키친타월로 닦아요.", "en": "Salt the salmon and let sit 15+ minutes; pat dry with paper towel.", "ja": "サーモンに塩をふり15分以上置いてからキッチンペーパーで水気を拭き取ります。", "zh": "三文鱼撒盐静置15分钟以上，然后用厨房纸擦干。"},
                {"ko": "팬에 기름을 얇게 두르고 중불로 달궈요.", "en": "Lightly oil a pan and heat over medium.", "ja": "フライパンに薄く油をひき中火で熱します。", "zh": "平底锅薄涂一层油，中火加热。"},
                {"ko": "껍질 쪽을 먼저 올려 4분 구워요.", "en": "Start skin-side down and cook 4 minutes.", "ja": "皮を下にして先に4分焼きます。", "zh": "皮面朝下先煎4分钟。"},
                {"ko": "뒤집어 3분 더 구워요.", "en": "Flip and cook 3 more minutes.", "ja": "裏返してさらに3分焼きます。", "zh": "翻面再煎3分钟。"},
                {"ko": "레몬을 짜서 뿌려 드세요.", "en": "Squeeze lemon over and serve.", "ja": "レモンを絞ってかけてお召し上がりください。", "zh": "挤上柠檬汁食用。"},
            ],
        },
    ],
    "japanese/miso": [
        {
            "id": "miso-soup",
            "name": {"ko": "미소시루", "en": "Miso Soup", "ja": "味噌汁", "zh": "味噌汤"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "일본 가정식의 기본 중의 기본, 5분이면 완성", "en": "The cornerstone of Japanese home cooking — done in 5 minutes", "ja": "日本家庭料理の基本中の基本、5分で完成", "zh": "日本家庭料理的基础中的基础，5分钟完成"},
            "ingredients": [
                {"name": "다시마·가쓰오부시 육수 또는 시판 다시", "amount": "2컵"},
                {"name": "된장 (미소)", "amount": "1.5큰술"},
                {"name": "두부 (연두부 또는 부침용)", "amount": "1/4모"},
                {"name": "미역 (건조)", "amount": "1작은술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "건조 미역을 물에 5분 불려요.", "en": "Soak dried wakame in water for 5 minutes.", "ja": "乾燥わかめを水に5分浸して戻します。", "zh": "干裙带菜用水泡发5分钟。"},
                {"ko": "냄비에 육수를 끓여요.", "en": "Bring dashi stock to a boil.", "ja": "鍋でだし汁を沸かします。", "zh": "锅中将出汁煮沸。"},
                {"ko": "두부를 작게 잘라 넣어요.", "en": "Add cubed tofu.", "ja": "豆腐を小さく切って加えます。", "zh": "豆腐切小块加入。"},
                {"ko": "불을 약하게 줄이고 된장을 체에 걸러 풀어요. 끓이지 마세요.", "en": "Reduce heat; dissolve miso through a strainer. Never boil after adding miso.", "ja": "火を弱め味噌をこし器で溶きます。沸騰させないように。", "zh": "将火调小，用滤网将味噌化开。不要煮沸。"},
                {"ko": "미역·쪽파를 넣어 바로 드세요.", "en": "Add wakame and green onion; serve immediately.", "ja": "わかめと小ねぎを加えてすぐにいただきます。", "zh": "加入裙带菜和葱花，立即享用。"},
            ],
        },
        {
            "id": "chawanmushi",
            "name": {"ko": "차완무시", "en": "Chawanmushi", "ja": "茶碗蒸し", "zh": "茶碗蒸"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "달걀을 부드럽게 찐 일본식 계란찜, 다시가 핵심", "en": "Silky steamed egg custard — dashi makes the difference", "ja": "卵を柔らかく蒸した日本式茶碗蒸し、出汁が命", "zh": "柔滑蒸蛋的日式茶碗蒸，出汁是关键"},
            "ingredients": [
                {"name": "계란", "amount": "2개"},
                {"name": "다시 육수", "amount": "300ml"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "미림", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "새우·닭고기·은행 등 속재료", "amount": "취향껏"},
            ],
            "steps": [
                {"ko": "계란을 풀고 다시·간장·미림·소금을 넣어 잘 섞어요.", "en": "Beat eggs with dashi, soy sauce, mirin, and salt.", "ja": "卵を溶きほぐし出汁・醤油・みりん・塩を加えてよく混ぜます。", "zh": "打散鸡蛋，加入出汁、酱油、味醂、盐充分混合。"},
                {"ko": "체에 걸러 기포를 없애요.", "en": "Strain through a sieve to remove bubbles.", "ja": "こし器でこして泡を除きます。", "zh": "用滤网过滤去除气泡。"},
                {"ko": "내열 그릇에 속재료를 넣고 계란물을 부어요.", "en": "Place fillings in heat-safe cups; pour egg mixture over.", "ja": "耐熱容器に具材を入れ卵液を注ぎます。", "zh": "在耐热容器中放入馅料，倒入蛋液。"},
                {"ko": "랩을 느슨하게 덮고 찜기에서 약불로 15분 쪄요. 강불이면 구멍이 생겨요.", "en": "Cover loosely with foil; steam on low for 15 minutes. High heat creates holes.", "ja": "ラップを緩めにかけて蒸し器で弱火15分蒸します。強火だと穴が開きます。", "zh": "松松地盖上保鲜膜，蒸锅小火蒸15分钟。大火会产生气孔。"},
                {"ko": "이쑤시개로 찔러 맑은 액체가 나오면 완성이에요.", "en": "Insert a toothpick — clear liquid means it's done.", "ja": "竹串を刺して澄んだ液体が出れば完成です。", "zh": "用牙签戳入，流出清液即表示完成。"},
            ],
        },
        {
            "id": "tonjiru",
            "name": {"ko": "돼지고기 된장국 (톤지루)", "en": "Tonjiru", "ja": "豚汁", "zh": "猪肉味噌汤"},
            "time": 30, "difficulty": 1,
            "desc": {"ko": "돼지고기와 채소가 가득한 든든한 일본식 된장국", "en": "Hearty miso soup packed with pork and root vegetables", "ja": "豚肉と野菜たっぷりの食べ応えある日本式味噌汁", "zh": "猪肉和蔬菜满满的日式味噌汤"},
            "ingredients": [
                {"name": "돼지고기 (얇게 썬 것)", "amount": "100g"},
                {"name": "무", "amount": "1/6개"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "감자", "amount": "1개"},
                {"name": "된장", "amount": "2.5큰술"},
                {"name": "다시 육수", "amount": "3컵"},
                {"name": "참기름", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "채소를 한 입 크기로 썰어요.", "en": "Chop all vegetables into bite-sized pieces.", "ja": "野菜を一口大に切ります。", "zh": "蔬菜切成一口大小。"},
                {"ko": "냄비에 참기름을 두르고 돼지고기를 볶아요.", "en": "Heat sesame oil in a pot and stir-fry pork.", "ja": "鍋にごま油をひき豚肉を炒めます。", "zh": "锅中倒入香油，翻炒猪肉。"},
                {"ko": "채소를 넣고 2분 볶아요.", "en": "Add vegetables and stir-fry 2 minutes.", "ja": "野菜を加えて2分炒めます。", "zh": "加入蔬菜翻炒2分钟。"},
                {"ko": "다시를 붓고 채소가 익을 때까지 15분 끓여요.", "en": "Pour in dashi and simmer until vegetables are tender, about 15 minutes.", "ja": "だし汁を注いで野菜が柔らかくなるまで15分煮ます。", "zh": "倒入出汁，煮15分钟至蔬菜软烂。"},
                {"ko": "불을 줄이고 된장을 풀어요. 끓이지 않아야 풍미가 살아 있어요.", "en": "Reduce heat and dissolve miso. Don't boil to preserve flavor.", "ja": "火を弱め味噌を溶きます。沸騰させないことで風味が保たれます。", "zh": "将火调小，化开味噌。不煮沸才能保留风味。"},
            ],
        },
    ],
}
