RECIPES_EXTRA3 = {
    # ── 중식 추가 ────────────────────────────────────────────────
    "chinese/noodle": [
        {
            "id": "jjamppong",
            "name": {"ko": "짬뽕", "en": "Jjamppong (Spicy Seafood Noodle)", "ja": "チャンポン", "zh": "炒码面"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "해물과 채소가 가득한 칼칼한 중화 국수", "en": "Fiery Chinese-Korean noodle soup packed with seafood and vegetables", "ja": "海鮮と野菜たっぷりの辛い中華麺", "zh": "满满海鲜蔬菜的辣味中华面"},
            "ingredients": [
                {"name": "중화면 (or 라멘 면)", "amount": "1인분"},
                {"name": "오징어·새우·바지락", "amount": "각 50g"},
                {"name": "양배추·양파·대파", "amount": "각 한 줌"},
                {"name": "고춧가루", "amount": "2큰술"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "물", "amount": "400ml"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "팬에 기름 두르고 마늘·고춧가루를 30초 볶아요.", "en": "Stir-fry garlic and chili flakes in oil for 30 seconds."},
                {"ko": "해물을 넣고 센불에서 볶아요.", "en": "Add seafood and stir-fry over high heat."},
                {"ko": "채소를 넣고 볶다가 물·간장·굴소스를 넣어 끓여요.", "en": "Add vegetables, then pour in water, soy sauce, and oyster sauce; bring to boil."},
                {"ko": "면을 삶아 그릇에 담고 국물을 부어요.", "en": "Cook noodles; place in bowl and pour soup over."},
            ],
        },
        {
            "id": "dan-dan-mian",
            "name": {"ko": "탄탄면", "en": "Dan Dan Noodles", "ja": "担々麺", "zh": "担担面"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "사천 고추기름과 돼지고기 소보로의 마라 국수", "en": "Sichuan noodles with spicy chili oil and pork mince", "ja": "四川の唐辛子油と豚ひき肉のスパイシー麺", "zh": "四川辣椒油和猪肉末的麻辣面"},
            "ingredients": [
                {"name": "중화면", "amount": "1인분"},
                {"name": "다진 돼지고기", "amount": "80g"},
                {"name": "고추기름 (라유)", "amount": "1큰술"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "식초", "amount": "1작은술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "참깨 소스 (tahini 또는 참깨 갈은 것)", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "닭 육수 또는 물", "amount": "200ml"},
            ],
            "steps": [
                {"ko": "팬에 기름 두르고 돼지고기를 볶아 간장 1큰술로 간해요.", "en": "Stir-fry pork in oil and season with 1 tbsp soy sauce."},
                {"ko": "그릇에 고추기름·나머지 간장·식초·설탕·참깨 소스·마늘을 섞어요.", "en": "In the bowl, mix chili oil, remaining soy sauce, vinegar, sugar, sesame sauce, and garlic."},
                {"ko": "뜨거운 육수를 부어 소스를 풀어요.", "en": "Pour hot broth over the sauce to dissolve."},
                {"ko": "삶은 면을 담고 돼지고기 소보로와 쪽파를 올려요.", "en": "Add cooked noodles, top with pork mince and green onions."},
                {"ko": "잘 비벼 드세요.", "en": "Mix well before eating."},
            ],
        },
        {
            "id": "chao-mian",
            "name": {"ko": "볶음면", "en": "Stir-fried Noodles (Chow Mein)", "ja": "チャーメン", "zh": "炒面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "간단 재료로 뚝딱 완성되는 중화 볶음면", "en": "Quick Chinese stir-fried noodles with pantry staples", "ja": "手軽な材料でパパっと作れる中華炒め麺", "zh": "用家常食材轻松制作的中式炒面"},
            "ingredients": [
                {"name": "중화면 (or 우동)", "amount": "1인분"},
                {"name": "양배추·당근·양파", "amount": "각 한 줌"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "식용유", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "면을 끓는 물에 1분만 데쳐 풀어요.", "en": "Blanch noodles in boiling water for 1 minute to loosen."},
                {"ko": "팬을 강불로 달구고 기름과 마늘을 볶아요.", "en": "Heat pan on high; stir-fry garlic in oil."},
                {"ko": "채소를 넣고 센불로 볶아요.", "en": "Add vegetables and stir-fry on high heat."},
                {"ko": "면을 넣고 간장·굴소스를 넣어 빠르게 볶아요.", "en": "Add noodles with soy sauce and oyster sauce; toss quickly."},
                {"ko": "참기름을 뿌려 마무리해요.", "en": "Finish with sesame oil."},
            ],
        },
        {
            "id": "sesame-cold-noodle",
            "name": {"ko": "참깨 비빔면", "en": "Sesame Cold Noodles", "ja": "ごま冷やし中華", "zh": "芝麻凉面"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "고소한 참깨 소스를 비벼 먹는 시원한 냉면", "en": "Cool noodles tossed in a rich sesame sauce", "ja": "濃厚ごまダレを和えた冷たい麺", "zh": "拌入浓郁芝麻酱的冰爽凉面"},
            "ingredients": [
                {"name": "중화면 또는 소면", "amount": "1인분"},
                {"name": "참깨 소스 (tahini)", "amount": "2큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "고추기름 또는 고추장", "amount": "1작은술"},
                {"name": "오이·당근", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "면을 삶아 찬물에 헹궈 차갑게 해요.", "en": "Cook noodles, rinse in cold water to chill."},
                {"ko": "참깨 소스·간장·식초·설탕·고추기름을 잘 섞어요.", "en": "Whisk together sesame sauce, soy sauce, vinegar, sugar, and chili oil."},
                {"ko": "오이와 당근을 채 썰어요.", "en": "Julienne cucumber and carrot."},
                {"ko": "면 위에 채소와 소스를 올려 비벼 드세요.", "en": "Top noodles with vegetables and sauce; mix well."},
            ],
        },
    ],
    "chinese/rice": [
        {
            "id": "yangzhou-fried-rice",
            "name": {"ko": "양주볶음밥", "en": "Yangzhou Fried Rice", "ja": "揚州チャーハン", "zh": "扬州炒饭"},
            "time": 15, "difficulty": 2,
            "desc": {"ko": "새우·계란·햄이 들어간 중식의 정석 볶음밥", "en": "Classic Chinese fried rice with shrimp, egg, and ham", "ja": "エビ・卵・ハム入りの中華チャーハンの定番", "zh": "加入虾仁、鸡蛋和火腿的经典中式炒饭"},
            "ingredients": [
                {"name": "찬밥", "amount": "1공기"},
                {"name": "계란", "amount": "2개"},
                {"name": "새우 (작은 것)", "amount": "60g"},
                {"name": "햄", "amount": "40g"},
                {"name": "쪽파", "amount": "2대"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "계란을 풀어 소금으로 간해요.", "en": "Beat eggs and season with salt."},
                {"ko": "강불로 달군 팬에 기름을 두르고 계란을 스크램블로 익혀 꺼내요.", "en": "Scramble eggs in hot oiled pan; remove."},
                {"ko": "같은 팬에 새우·햄을 볶아요.", "en": "Stir-fry shrimp and ham in the same pan."},
                {"ko": "밥을 넣고 주걱으로 눌러가며 고슬하게 볶아요.", "en": "Add rice and press-stir until separate and slightly crispy."},
                {"ko": "계란을 다시 넣고 간장·쪽파를 넣어 마무리해요.", "en": "Return eggs; add soy sauce and green onions to finish."},
            ],
        },
        {
            "id": "tomato-egg-rice",
            "name": {"ko": "토마토 계란 덮밥", "en": "Tomato and Egg Rice Bowl", "ja": "トマト卵丼", "zh": "番茄炒蛋饭"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "중국 가정식의 국민 요리, 토마토와 계란의 환상 조합", "en": "China's most beloved home dish — tomato and egg harmony", "ja": "中国家庭料理の定番、トマトと卵の最強コンビ", "zh": "中国最受欢迎的家常菜，番茄与鸡蛋的完美搭配"},
            "ingredients": [
                {"name": "토마토", "amount": "2개"},
                {"name": "계란", "amount": "3개"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "식용유", "amount": "2큰술"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "밥", "amount": "1공기"},
            ],
            "steps": [
                {"ko": "토마토를 한 입 크기로 썰고, 계란에 소금을 넣어 풀어요.", "en": "Chop tomatoes; beat eggs with salt."},
                {"ko": "팬에 기름 두르고 계란을 반숙으로 스크램블해 꺼내요.", "en": "Scramble eggs in oiled pan until just set; remove."},
                {"ko": "같은 팬에 기름 조금 더 두르고 토마토를 볶아요.", "en": "Add more oil and stir-fry tomatoes."},
                {"ko": "설탕·소금으로 간하고 계란을 넣어 살짝 섞어요.", "en": "Season with sugar and salt; add eggs and mix gently."},
                {"ko": "밥 위에 올리고 쪽파를 뿌려요.", "en": "Serve over rice with green onions."},
            ],
        },
        {
            "id": "mapo-tofu-rice",
            "name": {"ko": "마파두부 덮밥", "en": "Mapo Tofu Rice Bowl", "ja": "麻婆豆腐丼", "zh": "麻婆豆腐饭"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "얼얼하고 매운 마파두부를 밥 위에 듬뿍", "en": "Numbing-spicy Sichuan mapo tofu poured over rice", "ja": "痺れる辛さの麻婆豆腐をご飯にたっぷりかけて", "zh": "麻辣过瘾的麻婆豆腐浇在米饭上"},
            "ingredients": [
                {"name": "두부 (연두부 or 부침두부)", "amount": "1모"},
                {"name": "다진 돼지고기", "amount": "80g"},
                {"name": "두반장", "amount": "1.5큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "다진 마늘·생강", "amount": "각 1작은술"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "물", "amount": "150ml"},
                {"name": "고추기름·산초가루", "amount": "약간씩"},
                {"name": "밥", "amount": "1공기"},
            ],
            "steps": [
                {"ko": "두부를 2cm 큐브로 썰어요.", "en": "Cut tofu into 2cm cubes."},
                {"ko": "팬에 기름 두르고 마늘·생강·두반장을 30초 볶아요.", "en": "Stir-fry garlic, ginger, and doubanjiang for 30 seconds."},
                {"ko": "돼지고기를 넣고 볶다가 물·간장을 넣어 끓여요.", "en": "Add pork and stir-fry; pour in water and soy sauce; bring to boil."},
                {"ko": "두부를 넣고 2분 끓인 뒤 전분물을 넣어 걸쭉하게 해요.", "en": "Add tofu and boil 2 minutes; stir in cornstarch slurry to thicken."},
                {"ko": "밥 위에 올리고 고추기름·산초가루를 뿌려요.", "en": "Serve over rice; drizzle chili oil and sansho pepper."},
            ],
        },
        {
            "id": "pork-fried-rice",
            "name": {"ko": "돼지고기 볶음밥", "en": "Pork Fried Rice", "ja": "豚チャーハン", "zh": "猪肉炒饭"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "냉장고 파먹기 딱인 돼지고기 볶음밥", "en": "Perfect fridge-cleanout pork fried rice", "ja": "冷蔵庫一掃にぴったりの豚チャーハン", "zh": "清冰箱首选的猪肉炒饭"},
            "ingredients": [
                {"name": "찬밥", "amount": "1공기"},
                {"name": "돼지고기 (다진 것 or 슬라이스)", "amount": "80g"},
                {"name": "계란", "amount": "1개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "간장", "amount": "1.5큰술"},
                {"name": "굴소스", "amount": "1작은술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "팬을 강불로 달구고 돼지고기와 양파를 볶아요.", "en": "Stir-fry pork and onion in a hot pan."},
                {"ko": "밥을 넣고 주걱으로 눌러가며 볶아요.", "en": "Add rice and break up clumps while stir-frying."},
                {"ko": "가운데를 비우고 계란을 넣어 빠르게 스크램블해요.", "en": "Push rice to sides; scramble egg in the center."},
                {"ko": "간장·굴소스·소금·후추로 간하고 전체를 잘 섞어요.", "en": "Season with soy sauce, oyster sauce, salt, and pepper; mix well."},
            ],
        },
    ],
    "chinese/stirfry": [
        {
            "id": "bok-choy-stirfry",
            "name": {"ko": "청경채 볶음", "en": "Stir-fried Bok Choy", "ja": "チンゲン菜の炒め物", "zh": "清炒青菜"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "마늘 향 가득한 초간단 청경채 볶음", "en": "Simple garlic-scented bok choy stir-fry", "ja": "ニンニクの香りたっぷりの簡単チンゲン菜炒め", "zh": "蒜香浓郁的简单清炒青菜"},
            "ingredients": [
                {"name": "청경채", "amount": "200g"},
                {"name": "다진 마늘", "amount": "2쪽"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "청경채를 세로로 반 갈라요.", "en": "Halve bok choy lengthwise."},
                {"ko": "팬을 강불로 달구고 기름에 마늘을 볶아요.", "en": "Heat pan on high; stir-fry garlic in oil."},
                {"ko": "청경채를 넣고 30초 빠르게 볶아요.", "en": "Add bok choy and toss for 30 seconds."},
                {"ko": "굴소스·간장을 넣고 30초 더 볶아요.", "en": "Add oyster sauce and soy sauce; toss 30 more seconds."},
                {"ko": "참기름을 뿌려 마무리해요.", "en": "Finish with sesame oil."},
            ],
        },
        {
            "id": "beef-broccoli",
            "name": {"ko": "소고기 브로콜리 볶음", "en": "Beef and Broccoli", "ja": "牛肉とブロッコリーの炒め", "zh": "西兰花炒牛肉"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "중식 레스토랑의 인기 메뉴를 집에서", "en": "Restaurant-style beef and broccoli at home", "ja": "中華レストランの人気メニューを家で再現", "zh": "在家复刻中餐厅人气菜品"},
            "ingredients": [
                {"name": "소고기 (얇게 썬 것)", "amount": "150g"},
                {"name": "브로콜리", "amount": "1/2개"},
                {"name": "굴소스", "amount": "2큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "전분", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "소고기를 전분·간장 1작은술로 밑간해요.", "en": "Marinate beef with cornstarch and 1 tsp soy sauce."},
                {"ko": "브로콜리를 끓는 물에 1분 데쳐요.", "en": "Blanch broccoli in boiling water for 1 minute."},
                {"ko": "강불 팬에 기름 두르고 소고기를 센불에 볶아요.", "en": "Stir-fry beef in hot oiled pan on high heat."},
                {"ko": "마늘·브로콜리를 넣고 볶아요.", "en": "Add garlic and broccoli; toss."},
                {"ko": "굴소스·나머지 간장·설탕·물 2큰술을 섞어 넣고 볶아요.", "en": "Mix oyster sauce, remaining soy sauce, sugar, and 2 tbsp water; add and toss."},
            ],
        },
        {
            "id": "shrimp-ketchup",
            "name": {"ko": "칠리 새우", "en": "Chili Shrimp", "ja": "エビチリ", "zh": "干烧虾仁"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "새우를 케첩 고추소스로 볶은 중화 요리", "en": "Stir-fried shrimp in sweet-spicy chili tomato sauce", "ja": "エビをケチャップ辛みソースで炒めた中華料理", "zh": "用番茄酱辣椒酱炒制的经典中式虾仁"},
            "ingredients": [
                {"name": "새우 (중간 크기)", "amount": "200g"},
                {"name": "케첩", "amount": "3큰술"},
                {"name": "두반장 또는 고추장", "amount": "1큰술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "다진 마늘·생강", "amount": "각 1작은술"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "새우 등에 칼집 내어 내장을 제거해요.", "en": "Score shrimp backs and remove the vein."},
                {"ko": "팬에 기름 두르고 마늘·생강·두반장을 볶아요.", "en": "Stir-fry garlic, ginger, and doubanjiang in oil."},
                {"ko": "새우를 넣고 빠르게 볶아요.", "en": "Add shrimp and stir-fry quickly."},
                {"ko": "케첩·설탕·물 2큰술을 넣고 새우가 익을 때까지 볶아요.", "en": "Add ketchup, sugar, and 2 tbsp water; toss until shrimp is cooked."},
                {"ko": "쪽파를 뿌려요.", "en": "Top with green onions."},
            ],
        },
        {
            "id": "ganpung-gi",
            "name": {"ko": "깐풍기", "en": "Crispy Sweet-Spicy Chicken", "ja": "カンプンギ", "zh": "干烹鸡"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "바삭하게 튀긴 닭에 새콤달콤 양념을 버무린 중화 치킨", "en": "Crispy fried chicken tossed in tangy-sweet chili sauce", "ja": "カリカリ揚げ鶏に甘辛ダレを絡めた中華チキン", "zh": "酥炸鸡块裹上酸甜辣酱的中式炸鸡"},
            "ingredients": [
                {"name": "닭 가슴살 or 허벅지살", "amount": "200g"},
                {"name": "전분", "amount": "4큰술"},
                {"name": "케첩", "amount": "2큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "고추 (잘게 썬 것)", "amount": "1개"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "튀김용 기름", "amount": "충분히"},
            ],
            "steps": [
                {"ko": "닭을 한 입 크기로 잘라 소금·후추로 간하고 전분을 입혀요.", "en": "Cut chicken into pieces, season with salt and pepper, coat with starch."},
                {"ko": "175°C 기름에 5분 튀겨요.", "en": "Fry at 175°C for 5 minutes."},
                {"ko": "케첩·간장·식초·설탕을 섞어 소스를 만들어요.", "en": "Mix ketchup, soy sauce, vinegar, and sugar for the sauce."},
                {"ko": "팬에 마늘·고추를 볶다가 소스를 넣어 끓여요.", "en": "Stir-fry garlic and chili; add sauce and bring to a boil."},
                {"ko": "튀긴 닭을 소스에 넣고 버무려요.", "en": "Toss fried chicken in the sauce."},
            ],
        },
    ],
    "chinese/soup": [
        {
            "id": "wonton-soup",
            "name": {"ko": "완탕 수프", "en": "Wonton Soup", "ja": "ワンタンスープ", "zh": "馄饨汤"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "쫄깃한 만두피에 새우·돼지고기 소를 넣은 중식 수프", "en": "Delicate dumplings in a clear savory broth", "ja": "もちもちの皮にエビ・豚肉の具を包んだスープ", "zh": "嫩滑馄饨漂浮在清澈鲜美汤汁中"},
            "ingredients": [
                {"name": "완탕피 (시판)", "amount": "20장"},
                {"name": "다진 돼지고기", "amount": "80g"},
                {"name": "새우 (다진 것)", "amount": "60g"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "생강즙", "amount": "1작은술"},
                {"name": "닭 육수", "amount": "600ml"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "돼지고기·새우·간장·참기름·생강즙을 섞어 소를 만들어요.", "en": "Mix pork, shrimp, soy sauce, sesame oil, and ginger for the filling."},
                {"ko": "완탕피에 소를 조금 올리고 삼각형이나 원형으로 접어요.", "en": "Place a little filling on each wrapper and fold into triangles or rounds."},
                {"ko": "끓는 물에 완탕을 5분 삶아요.", "en": "Boil wontons in water for 5 minutes."},
                {"ko": "육수를 별도 냄비에 끓이고 간장으로 간해요.", "en": "Heat broth in a separate pot and season with soy sauce."},
                {"ko": "그릇에 완탕을 담고 육수를 부어 쪽파를 올려요.", "en": "Place wontons in bowls, pour broth over, and top with green onions."},
            ],
        },
        {
            "id": "corn-soup",
            "name": {"ko": "옥수수 수프", "en": "Chinese Corn Soup", "ja": "コーンスープ", "zh": "玉米浓汤"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "달콤하고 부드러운 중식 스타일 옥수수 수프", "en": "Sweet and velvety Chinese-style corn soup", "ja": "甘くてなめらかな中華風コーンスープ", "zh": "甜润丝滑的中式玉米浓汤"},
            "ingredients": [
                {"name": "옥수수 (캔 or 냉동)", "amount": "150g"},
                {"name": "계란", "amount": "1개"},
                {"name": "닭 육수", "amount": "400ml"},
                {"name": "전분", "amount": "2큰술"},
                {"name": "소금", "amount": "약간"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "옥수수를 블렌더로 반 갈아요 (알갱이가 약간 남아도 좋아요).", "en": "Blend corn until roughly smooth — some texture is fine."},
                {"ko": "육수를 끓이고 옥수수를 넣어요.", "en": "Bring broth to a boil and add corn."},
                {"ko": "전분 2큰술을 물 4큰술에 풀어 넣고 걸쭉하게 만들어요.", "en": "Mix cornstarch with 4 tbsp water; stir in to thicken."},
                {"ko": "계란을 풀어 가늘게 부으며 저어요.", "en": "Beat egg and pour in a thin stream while stirring."},
                {"ko": "소금으로 간하고 쪽파를 올려요.", "en": "Season with salt and garnish with green onions."},
            ],
        },
        {
            "id": "hot-sour-soup",
            "name": {"ko": "산라탕", "en": "Hot and Sour Soup", "ja": "酸辣湯", "zh": "酸辣汤"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "새콤하고 매콤한 사천식 수프, 병문안의 단골", "en": "Tangy and spicy Sichuan soup — warming and restorative", "ja": "すっぱくて辛い四川風スープ", "zh": "酸辣开胃的四川风味汤，暖身又滋补"},
            "ingredients": [
                {"name": "두부", "amount": "1/4모"},
                {"name": "표고버섯", "amount": "2개"},
                {"name": "죽순 (캔)", "amount": "50g"},
                {"name": "계란", "amount": "1개"},
                {"name": "닭 육수", "amount": "500ml"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "식초", "amount": "2큰술"},
                {"name": "고추기름 or 고추장", "amount": "1작은술"},
                {"name": "전분", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "두부·버섯·죽순을 얇게 채 썰어요.", "en": "Julienne tofu, mushroom, and bamboo shoot thinly."},
                {"ko": "육수를 끓이고 재료를 넣어 3분 끓여요.", "en": "Bring broth to a boil; add ingredients and cook 3 minutes."},
                {"ko": "간장·식초·고추기름으로 간해요.", "en": "Season with soy sauce, vinegar, and chili oil."},
                {"ko": "전분물을 부어 걸쭉하게 만들어요.", "en": "Stir in starch slurry to thicken."},
                {"ko": "계란을 풀어 천천히 부으며 저어요.", "en": "Slowly drizzle in beaten egg while stirring."},
            ],
        },
        {
            "id": "chicken-congee",
            "name": {"ko": "중식 닭죽 (콘지)", "en": "Chinese Congee (Jook)", "ja": "中華風鶏粥", "zh": "鸡肉粥"},
            "time": 40, "difficulty": 1,
            "desc": {"ko": "부드럽게 퍼진 쌀에 닭 육수를 더한 중식 죽", "en": "Silky Chinese-style rice porridge in rich chicken broth", "ja": "とろとろのお米に鶏スープを合わせた中華粥", "zh": "嫩滑的鸡汤大米粥，滋养温润"},
            "ingredients": [
                {"name": "쌀", "amount": "1/2컵"},
                {"name": "닭 육수", "amount": "5컵"},
                {"name": "닭 가슴살", "amount": "100g"},
                {"name": "생강 (얇게 썬 것)", "amount": "3조각"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "쪽파·고수 (선택)", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "쌀을 씻어 30분 불려요.", "en": "Rinse rice and soak 30 minutes."},
                {"ko": "냄비에 육수·쌀·생강을 넣고 강불로 끓여요.", "en": "Bring broth, rice, and ginger to a boil over high heat."},
                {"ko": "끓으면 약불로 줄여 25분 저어가며 끓여요.", "en": "Reduce to low and simmer 25 minutes, stirring occasionally."},
                {"ko": "닭 가슴살을 얹어 5분 더 익혀 결대로 찢어요.", "en": "Add chicken breast; cook 5 more minutes, then shred."},
                {"ko": "간장·참기름으로 간하고 쪽파·고수를 올려요.", "en": "Season with soy sauce and sesame oil; garnish with green onion and cilantro."},
            ],
        },
    ],
    "chinese/dim": [
        {
            "id": "pan-fried-dumplings",
            "name": {"ko": "군만두", "en": "Pan-fried Dumplings (Potstickers)", "ja": "焼き餃子", "zh": "煎饺"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "바삭한 밑면과 촉촉한 속의 군만두", "en": "Crispy-bottomed juicy potstickers", "ja": "カリカリの底面とジューシーな中身の焼き餃子", "zh": "底部酥脆内馅鲜嫩的煎饺"},
            "ingredients": [
                {"name": "만두피 (시판)", "amount": "20장"},
                {"name": "다진 돼지고기", "amount": "150g"},
                {"name": "배추김치 (다진 것)", "amount": "50g"},
                {"name": "두부 (물기 제거)", "amount": "50g"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "참기름·다진 마늘", "amount": "각 1작은술"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "소 재료를 모두 섞어요.", "en": "Mix all filling ingredients together."},
                {"ko": "만두피에 소를 올리고 반달 모양으로 접어 주름을 잡아요.", "en": "Place filling on wrappers; fold into half-moons and pleat the edges."},
                {"ko": "팬에 기름 두르고 만두를 넣어 중불로 2분 구워요.", "en": "Add oil to pan; cook dumplings over medium heat for 2 minutes."},
                {"ko": "물 50ml를 붓고 뚜껑 덮어 수분이 없어질 때까지 쪄요.", "en": "Add 50ml water, cover, and steam until water evaporates."},
                {"ko": "뚜껑 열고 바닥이 바삭해질 때까지 1~2분 더 구워요.", "en": "Remove lid and fry 1-2 more minutes until bottom is crispy."},
            ],
        },
        {
            "id": "spring-rolls",
            "name": {"ko": "춘권", "en": "Spring Rolls", "ja": "春巻き", "zh": "春卷"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "채소와 돼지고기를 넣어 바삭하게 튀긴 춘권", "en": "Crispy fried rolls stuffed with vegetables and pork", "ja": "野菜と豚肉を入れてカリッと揚げた春巻き", "zh": "蔬菜猪肉馅的酥脆春卷"},
            "ingredients": [
                {"name": "춘권피", "amount": "10장"},
                {"name": "다진 돼지고기", "amount": "100g"},
                {"name": "당면 (불린 것)", "amount": "50g"},
                {"name": "당근·양배추", "amount": "각 한 줌"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "밀가루 풀 (밀가루+물)", "amount": "약간 (봉합용)"},
                {"name": "튀김용 기름", "amount": "충분히"},
            ],
            "steps": [
                {"ko": "채소·고기를 볶아 간장·참기름으로 간하고 식혀요.", "en": "Stir-fry vegetables and pork; season with soy sauce and sesame oil; let cool."},
                {"ko": "당면을 섞어요.", "en": "Mix in soaked glass noodles."},
                {"ko": "춘권피에 소를 올리고 돌돌 말아 밀가루 풀로 봉해요.", "en": "Place filling on wrappers, roll up tightly, and seal edges with flour paste."},
                {"ko": "170°C 기름에서 3분 튀겨요.", "en": "Fry at 170°C for 3 minutes."},
                {"ko": "간장·식초 소스에 찍어 드세요.", "en": "Serve with soy-vinegar dipping sauce."},
            ],
        },
        {
            "id": "steamed-bao",
            "name": {"ko": "찐빵 (바오)", "en": "Steamed Bao Buns", "ja": "蒸しパン（肉まん）", "zh": "蒸包子"},
            "time": 60, "difficulty": 2,
            "desc": {"ko": "폭신한 반죽 안에 달콤 짭짤한 고기 소를 넣은 찐빵", "en": "Fluffy steamed buns with savory-sweet meat filling", "ja": "ふわふわ生地に甘じょっぱい肉あんの蒸しパン", "zh": "松软面皮包裹甜咸猪肉馅的蒸包子"},
            "ingredients": [
                {"name": "박력분", "amount": "200g"},
                {"name": "드라이이스트", "amount": "1작은술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "따뜻한 물", "amount": "110ml"},
                {"name": "다진 돼지고기", "amount": "150g"},
                {"name": "간장", "amount": "1.5큰술"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "참기름·생강", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "따뜻한 물에 이스트·설탕을 넣고 5분 두어 활성화해요.", "en": "Dissolve yeast and sugar in warm water; rest 5 minutes to activate."},
                {"ko": "밀가루에 이스트물을 넣어 반죽하고 따뜻한 곳에서 30분 발효해요.", "en": "Knead flour with yeast water; ferment in a warm spot for 30 minutes."},
                {"ko": "돼지고기에 간장·굴소스·참기름·생강을 넣어 소를 만들어요.", "en": "Mix pork with soy sauce, oyster sauce, sesame oil, and ginger for filling."},
                {"ko": "반죽을 8등분해 얇게 펴고 소를 넣어 주름 잡아 봉해요.", "en": "Divide dough into 8 pieces; flatten each, fill, and pleat to seal."},
                {"ko": "찜통에 물을 끓여 15분 쪄요.", "en": "Steam in a steamer for 15 minutes."},
            ],
        },
        {
            "id": "sesame-balls",
            "name": {"ko": "참깨 공 (전지엔)", "en": "Sesame Balls (Jian Dui)", "ja": "ごま団子", "zh": "煎堆"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "겉은 바삭 깨 코팅, 속은 달콤한 팥소 찹쌀 공", "en": "Crispy sesame-coated glutinous rice balls with sweet filling", "ja": "外はサクサクごまコーティング、中は甘い餡のもち米ボール", "zh": "外酥内软的芝麻糯米球，内馅香甜"},
            "ingredients": [
                {"name": "찹쌀가루", "amount": "150g"},
                {"name": "뜨거운 물", "amount": "80ml"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "팥소 (시판)", "amount": "80g"},
                {"name": "참깨 (흰 것)", "amount": "4큰술"},
                {"name": "튀김용 기름", "amount": "충분히"},
            ],
            "steps": [
                {"ko": "찹쌀가루·설탕·뜨거운 물을 섞어 반죽해요.", "en": "Mix glutinous rice flour, sugar, and hot water into a dough."},
                {"ko": "반죽을 8등분해 납작하게 펴요.", "en": "Divide into 8 pieces and flatten each."},
                {"ko": "팥소를 올리고 꽉 쥐어 동그랗게 봉해요.", "en": "Place red bean paste in center and seal into a ball."},
                {"ko": "물을 살짝 묻혀 참깨를 겉에 꼭꼭 눌러 붙여요.", "en": "Moisten surface slightly and press sesame seeds all over."},
                {"ko": "150°C 기름에서 5분 천천히 튀겨요.", "en": "Fry at 150°C for 5 minutes until golden."},
            ],
        },
    ],
    # ── 양식 추가 ────────────────────────────────────────────────
    "western/pasta": [
        {
            "id": "amatriciana",
            "name": {"ko": "아마트리치아나", "en": "Pasta Amatriciana", "ja": "アマトリチャーナ", "zh": "培根番茄意面"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "베이컨과 토마토소스의 로마식 클래식 파스타", "en": "Roman classic pasta with guanciale and tomato sauce", "ja": "グアンチャーレとトマトのローマ式クラシックパスタ", "zh": "培根与番茄酱汁的罗马经典意面"},
            "ingredients": [
                {"name": "스파게티", "amount": "100g"},
                {"name": "베이컨 또는 판체타", "amount": "80g"},
                {"name": "토마토 캔 (다진 것)", "amount": "200g"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "마늘", "amount": "2쪽"},
                {"name": "올리브유", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "파르메산 치즈", "amount": "약간"},
            ],
            "steps": [
                {"ko": "면을 소금 물에 표기대로 삶아요.", "en": "Boil pasta in salted water according to package directions."},
                {"ko": "팬에 올리브유를 두르고 베이컨을 바삭하게 볶아요.", "en": "Stir-fry bacon in olive oil until crispy."},
                {"ko": "마늘·양파를 넣고 볶아요.", "en": "Add garlic and onion; sauté."},
                {"ko": "토마토 캔을 넣고 10분 졸여요.", "en": "Add canned tomatoes and simmer 10 minutes."},
                {"ko": "면을 건져 소스와 버무리고 치즈·후추를 올려요.", "en": "Drain pasta and toss with sauce; top with cheese and pepper."},
            ],
        },
        {
            "id": "pesto-pasta",
            "name": {"ko": "페스토 파스타", "en": "Pesto Pasta", "ja": "ペストパスタ", "zh": "青酱意面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "바질·마늘·파르메산의 초록 소스 파스타", "en": "Vibrant green pasta with basil, garlic, and parmesan", "ja": "バジル・ニンニク・パルメザンの緑色パスタ", "zh": "罗勒、大蒜和帕玛森奶酪制作的绿色意面"},
            "ingredients": [
                {"name": "링귀네 또는 스파게티", "amount": "100g"},
                {"name": "페스토 소스 (시판)", "amount": "3큰술"},
                {"name": "올리브유", "amount": "1큰술"},
                {"name": "마늘", "amount": "1쪽"},
                {"name": "파르메산 치즈", "amount": "2큰술"},
                {"name": "파스타 삶은 물", "amount": "4큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "면을 소금 넣은 물에 표기대로 삶아요.", "en": "Boil pasta in salted water per package directions."},
                {"ko": "팬에 올리브유와 마늘을 살짝 볶아요.", "en": "Briefly sauté garlic in olive oil."},
                {"ko": "불을 끄고 페스토를 넣어요.", "en": "Turn off heat and add pesto."},
                {"ko": "면과 파스타 물을 조금 넣어 농도를 맞추며 버무려요.", "en": "Add pasta and a splash of pasta water; toss to coat."},
                {"ko": "치즈·후추를 뿌려요.", "en": "Sprinkle with parmesan and pepper."},
            ],
        },
        {
            "id": "vongole-pasta",
            "name": {"ko": "봉골레 파스타", "en": "Spaghetti alle Vongole", "ja": "ボンゴレパスタ", "zh": "白酒蛤蜊意面"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "조개 국물이 베어든 오일 베이스의 클래식 이탈리안 파스타", "en": "Clams and white wine in a light olive oil pasta", "ja": "あさりの旨みが染み込んだオイルベースの定番パスタ", "zh": "蛤蜊鲜味渗透的油基经典意面"},
            "ingredients": [
                {"name": "스파게티", "amount": "100g"},
                {"name": "바지락", "amount": "200g"},
                {"name": "마늘", "amount": "3쪽"},
                {"name": "화이트 와인 또는 청주", "amount": "50ml"},
                {"name": "올리브유", "amount": "3큰술"},
                {"name": "고추 (선택)", "amount": "1개"},
                {"name": "파슬리", "amount": "약간"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "바지락을 소금물에 30분 해감해요.", "en": "Soak clams in salted water 30 minutes to purge sand."},
                {"ko": "면을 삶아요 (1분 일찍 건져 al dente로).", "en": "Boil pasta, drain 1 minute early for al dente."},
                {"ko": "팬에 올리브유·마늘·고추를 볶아요.", "en": "Sauté garlic and chili in olive oil."},
                {"ko": "바지락·와인을 넣고 뚜껑 덮어 조개 입이 열릴 때까지 2분 쪄요.", "en": "Add clams and wine; cover and steam 2 minutes until shells open."},
                {"ko": "면을 넣고 파스타 물을 조금 넣어 볶다가 파슬리를 뿌려요.", "en": "Add pasta, splash of pasta water; toss and top with parsley."},
            ],
        },
        {
            "id": "rose-pasta",
            "name": {"ko": "로제 파스타", "en": "Rosé Pasta", "ja": "ロゼパスタ", "zh": "玫瑰茄汁意面"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "크림+토마토 소스로 만드는 분홍빛 SNS 인기 파스타", "en": "Creamy tomato sauce pasta that's all over social media", "ja": "クリーム+トマトのピンク色SNS人気パスタ", "zh": "奶油加番茄酱制作的粉色网红意面"},
            "ingredients": [
                {"name": "펜네 또는 스파게티", "amount": "100g"},
                {"name": "토마토 소스 (시판)", "amount": "150g"},
                {"name": "생크림", "amount": "100ml"},
                {"name": "마늘", "amount": "2쪽"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "파르메산 치즈·소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "면을 삶아요.", "en": "Cook pasta in salted boiling water."},
                {"ko": "팬에 버터를 녹이고 마늘·양파를 볶아요.", "en": "Melt butter; sauté garlic and onion."},
                {"ko": "토마토 소스를 넣고 3분 졸여요.", "en": "Add tomato sauce and simmer 3 minutes."},
                {"ko": "생크림을 넣고 2분 더 끓여요.", "en": "Add cream and simmer 2 more minutes."},
                {"ko": "면을 넣고 버무려 치즈·후추를 올려요.", "en": "Toss in pasta; finish with cheese and pepper."},
            ],
        },
    ],
    "western/meat": [
        {
            "id": "meatballs",
            "name": {"ko": "미트볼 토마토조림", "en": "Meatballs in Tomato Sauce", "ja": "ミートボールのトマト煮", "zh": "番茄酱汁肉丸"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "파스타나 빵에 곁들여도 완벽한 홈메이드 미트볼", "en": "Homemade meatballs perfect with pasta or bread", "ja": "パスタにもパンにも合うホームメイドミートボール", "zh": "搭配意面或面包都完美的自制肉丸"},
            "ingredients": [
                {"name": "다진 소고기 + 돼지고기", "amount": "250g (반반)"},
                {"name": "빵가루", "amount": "3큰술"},
                {"name": "계란", "amount": "1개"},
                {"name": "파르메산 치즈", "amount": "2큰술"},
                {"name": "토마토 소스 (시판)", "amount": "250g"},
                {"name": "마늘·양파", "amount": "각 약간"},
                {"name": "소금·후추·이탈리안 허브", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "다진 고기·빵가루·계란·치즈·소금·후추·허브를 섞어 반죽해요.", "en": "Combine ground meat, breadcrumbs, egg, cheese, salt, pepper, and herbs."},
                {"ko": "골프공 크기로 빚어요.", "en": "Roll into golf ball-sized balls."},
                {"ko": "팬에 기름 두르고 미트볼을 굴려가며 갈색이 되게 구워요.", "en": "Brown meatballs on all sides in oiled pan."},
                {"ko": "마늘·양파를 볶고 토마토 소스를 넣어요.", "en": "Sauté garlic and onion; add tomato sauce."},
                {"ko": "미트볼을 넣고 15분 약불로 조려요.", "en": "Add meatballs and simmer on low for 15 minutes."},
            ],
        },
        {
            "id": "honey-mustard-chicken",
            "name": {"ko": "허니 머스타드 치킨", "en": "Honey Mustard Chicken", "ja": "ハニーマスタードチキン", "zh": "蜂蜜芥末鸡"},
            "time": 30, "difficulty": 1,
            "desc": {"ko": "달콤한 꿀과 새콤한 머스타드의 환상 조합", "en": "Sweet honey and tangy mustard make a perfect combo", "ja": "甘いはちみつと酸っぱいマスタードの最高コンビ", "zh": "甜蜂蜜与酸芥末的完美搭配"},
            "ingredients": [
                {"name": "닭 허벅지살 or 가슴살", "amount": "200g"},
                {"name": "꿀", "amount": "2큰술"},
                {"name": "디종 머스타드", "amount": "2큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "마늘 가루", "amount": "1/2작은술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "올리브유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "꿀·머스타드·간장·마늘 가루를 섞어 마리네이드를 만들어요.", "en": "Mix honey, mustard, soy sauce, and garlic powder for the marinade."},
                {"ko": "닭에 소금·후추 간하고 마리네이드를 발라 20분 재워요.", "en": "Season chicken with salt and pepper; coat with marinade and rest 20 minutes."},
                {"ko": "팬에 올리브유를 두르고 닭을 중불로 5분 구워요.", "en": "Cook chicken in oiled pan over medium heat for 5 minutes."},
                {"ko": "뒤집어 남은 마리네이드를 붓고 5분 더 구워요.", "en": "Flip, pour remaining marinade over, and cook 5 more minutes."},
                {"ko": "소스가 끈적해질 때까지 약불로 졸여요.", "en": "Reduce heat and glaze until sauce thickens."},
            ],
        },
        {
            "id": "bacon-egg",
            "name": {"ko": "베이컨 에그", "en": "Bacon and Eggs", "ja": "ベーコンエッグ", "zh": "培根鸡蛋"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "영미식 아침 식사의 정수, 10분이면 완성", "en": "The essence of a classic Anglo-American breakfast", "ja": "英米式朝食の定番、10分で完成", "zh": "英美经典早餐精髓，10分钟搞定"},
            "ingredients": [
                {"name": "베이컨", "amount": "3줄"},
                {"name": "계란", "amount": "2개"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "버터 (선택)", "amount": "1작은술"},
                {"name": "식빵 또는 토스트", "amount": "2장"},
            ],
            "steps": [
                {"ko": "팬을 중불로 달궈요.", "en": "Heat pan over medium heat."},
                {"ko": "베이컨을 올리고 양면이 바삭해질 때까지 구워요.", "en": "Cook bacon until crispy on both sides."},
                {"ko": "베이컨을 꺼내고 같은 팬에 계란을 프라이해요.", "en": "Remove bacon; fry eggs in the same pan."},
                {"ko": "소금·후추로 간해요.", "en": "Season with salt and pepper."},
                {"ko": "토스트와 함께 서빙해요.", "en": "Serve alongside toast."},
            ],
        },
        {
            "id": "chicken-masala",
            "name": {"ko": "버터 치킨 커리", "en": "Butter Chicken Curry", "ja": "バターチキンカレー", "zh": "奶油鸡咖喱"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "부드럽고 크리미한 인도식 버터 치킨", "en": "Smooth and creamy Indian butter chicken", "ja": "なめらかでクリーミーなインド風バターチキン", "zh": "浓郁绵滑的印度奶油鸡"},
            "ingredients": [
                {"name": "닭 가슴살 또는 허벅지살", "amount": "250g"},
                {"name": "토마토 캔 (다진 것)", "amount": "200g"},
                {"name": "생크림", "amount": "100ml"},
                {"name": "버터", "amount": "2큰술"},
                {"name": "양파", "amount": "1/2개"},
                {"name": "다진 마늘·생강", "amount": "각 1작은술"},
                {"name": "카레 파우더", "amount": "1.5큰술"},
                {"name": "소금·설탕", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "닭을 한 입 크기로 잘라 소금·카레 파우더 1작은술로 밑간해요.", "en": "Cut chicken into pieces; marinate with salt and 1 tsp curry powder."},
                {"ko": "팬에 버터를 녹이고 닭을 굽다가 꺼내요.", "en": "Brown chicken in melted butter; remove."},
                {"ko": "같은 팬에 양파·마늘·생강을 볶고 카레 파우더를 넣어 30초 볶아요.", "en": "Sauté onion, garlic, and ginger; add curry powder and stir 30 seconds."},
                {"ko": "토마토 캔을 넣고 10분 졸여요.", "en": "Add canned tomatoes and simmer 10 minutes."},
                {"ko": "닭과 생크림을 넣고 10분 더 끓여요.", "en": "Return chicken and add cream; simmer 10 more minutes."},
            ],
        },
    ],
    "western/salad": [
        {
            "id": "coleslaw",
            "name": {"ko": "코울슬로", "en": "Coleslaw", "ja": "コールスロー", "zh": "卷心菜沙拉"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "치킨이나 버거 옆에 빠질 수 없는 크리미 코울슬로", "en": "Creamy coleslaw — essential beside chicken or burgers", "ja": "チキンやバーガーに欠かせないクリーミーなコールスロー", "zh": "搭配炸鸡或汉堡必不可少的奶油卷心菜沙拉"},
            "ingredients": [
                {"name": "양배추", "amount": "1/4개"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "마요네즈", "amount": "3큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "양배추와 당근을 얇게 채 썰어요.", "en": "Finely shred cabbage and carrot."},
                {"ko": "소금을 뿌려 10분 두었다가 물기를 꽉 짜요.", "en": "Salt and rest 10 minutes; squeeze out moisture."},
                {"ko": "마요네즈·식초·설탕·후추를 섞어 드레싱을 만들어요.", "en": "Mix mayo, vinegar, sugar, and pepper for the dressing."},
                {"ko": "채소와 드레싱을 버무려요.", "en": "Toss vegetables with dressing."},
                {"ko": "냉장고에 30분 넣었다 먹으면 더 맛있어요.", "en": "Tastes even better after 30 minutes in the fridge."},
            ],
        },
        {
            "id": "greek-salad",
            "name": {"ko": "그릭 샐러드", "en": "Greek Salad", "ja": "グリークサラダ", "zh": "希腊沙拉"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "토마토·오이·페타 치즈의 지중해 여름 샐러드", "en": "Mediterranean summer salad with tomato, cucumber, and feta", "ja": "トマト・キュウリ・フェタチーズの地中海夏サラダ", "zh": "番茄、黄瓜和菲达奶酪的地中海夏日沙拉"},
            "ingredients": [
                {"name": "토마토", "amount": "2개"},
                {"name": "오이", "amount": "1/2개"},
                {"name": "적양파", "amount": "1/4개"},
                {"name": "올리브 (블랙)", "amount": "한 줌"},
                {"name": "페타 치즈", "amount": "60g"},
                {"name": "올리브유", "amount": "2큰술"},
                {"name": "레몬즙", "amount": "1큰술"},
                {"name": "소금·오레가노", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "토마토와 오이를 먹기 좋게 썰어요.", "en": "Chop tomatoes and cucumber into chunks."},
                {"ko": "적양파를 얇게 슬라이스해요.", "en": "Thinly slice red onion."},
                {"ko": "그릇에 채소와 올리브를 담아요.", "en": "Arrange vegetables and olives in a bowl."},
                {"ko": "올리브유·레몬즙·소금·오레가노를 뿌려요.", "en": "Drizzle with olive oil, lemon juice, salt, and oregano."},
                {"ko": "페타 치즈를 손으로 부숴 올려요.", "en": "Crumble feta cheese on top."},
            ],
        },
        {
            "id": "french-onion-soup",
            "name": {"ko": "프렌치 어니언 수프", "en": "French Onion Soup", "ja": "フレンチオニオンスープ", "zh": "法式洋葱汤"},
            "time": 50, "difficulty": 2,
            "desc": {"ko": "달콤하게 캐러멜라이즈한 양파와 녹인 치즈가 포인트", "en": "Sweet caramelized onions topped with melted cheese crouton", "ja": "甘くキャラメリゼした玉ねぎと溶けたチーズが主役", "zh": "香甜焦糖化洋葱与融化奶酪的法式经典汤品"},
            "ingredients": [
                {"name": "양파", "amount": "3개 (대)"},
                {"name": "버터", "amount": "2큰술"},
                {"name": "쇠고기 육수 또는 콘소메 수프", "amount": "600ml"},
                {"name": "화이트 와인 또는 청주", "amount": "50ml"},
                {"name": "바게트", "amount": "2조각"},
                {"name": "그뤼에르 또는 모짜렐라 치즈", "amount": "40g"},
                {"name": "소금·후추·타임", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "양파를 얇게 슬라이스해요.", "en": "Thinly slice onions."},
                {"ko": "버터를 녹인 냄비에 양파를 넣고 약불로 30분 저어가며 갈색이 될 때까지 캐러멜라이즈해요.", "en": "Caramelize onions in melted butter over low heat for 30 minutes, stirring frequently."},
                {"ko": "와인을 넣고 1분 졸이다가 육수·타임·소금·후추를 넣고 10분 끓여요.", "en": "Add wine and cook 1 minute; add broth, thyme, salt, and pepper; simmer 10 minutes."},
                {"ko": "수프를 내열 그릇에 담고 바게트를 올려요.", "en": "Pour soup into oven-safe bowls; place baguette slice on top."},
                {"ko": "치즈를 올리고 오븐 200°C에서 10분 또는 치즈가 녹을 때까지 구워요.", "en": "Top with cheese; bake at 200°C for 10 minutes or until cheese melts and bubbles."},
            ],
        },
        {
            "id": "minestrone",
            "name": {"ko": "미네스트로네", "en": "Minestrone Soup", "ja": "ミネストローネ", "zh": "意式蔬菜汤"},
            "time": 40, "difficulty": 1,
            "desc": {"ko": "채소가 가득한 이탈리아식 든든한 수프", "en": "Hearty Italian vegetable soup — a full meal in a bowl", "ja": "野菜たっぷりのイタリア風具だくさんスープ", "zh": "满满蔬菜的意大利浓汤，一碗饱足"},
            "ingredients": [
                {"name": "당근·셀러리·양파", "amount": "각 1/2개"},
                {"name": "토마토 캔 (다진 것)", "amount": "200g"},
                {"name": "강낭콩 (캔)", "amount": "100g"},
                {"name": "마카로니 또는 작은 파스타", "amount": "50g"},
                {"name": "닭 or 채소 육수", "amount": "600ml"},
                {"name": "마늘", "amount": "2쪽"},
                {"name": "올리브유", "amount": "1큰술"},
                {"name": "소금·후추·이탈리안 허브", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "당근·셀러리·양파를 작게 깍둑 썰어요.", "en": "Dice carrot, celery, and onion small."},
                {"ko": "냄비에 올리브유를 두르고 마늘·채소를 5분 볶아요.", "en": "Sauté garlic and vegetables in olive oil for 5 minutes."},
                {"ko": "토마토 캔·육수·허브를 넣고 15분 끓여요.", "en": "Add canned tomatoes, broth, and herbs; simmer 15 minutes."},
                {"ko": "파스타와 콩을 넣고 10분 더 끓여요.", "en": "Add pasta and beans; cook 10 more minutes."},
                {"ko": "소금·후추로 간하고 파르메산 치즈를 뿌려요.", "en": "Season with salt and pepper; top with parmesan."},
            ],
        },
    ],
    "western/bread": [
        {
            "id": "avocado-toast",
            "name": {"ko": "아보카도 토스트", "en": "Avocado Toast", "ja": "アボカドトースト", "zh": "牛油果吐司"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "카페 분위기 물씬 나는 건강한 아침 토스트", "en": "Café-style healthy breakfast toast", "ja": "カフェっぽい健康的な朝食トースト", "zh": "充满咖啡厅气息的健康早餐吐司"},
            "ingredients": [
                {"name": "식빵 또는 사워도우", "amount": "2장"},
                {"name": "아보카도", "amount": "1개"},
                {"name": "레몬즙", "amount": "1작은술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "계란 (수란 또는 프라이, 선택)", "amount": "1개"},
                {"name": "칠리 플레이크", "amount": "약간"},
                {"name": "올리브유", "amount": "약간"},
            ],
            "steps": [
                {"ko": "빵을 토스트해요.", "en": "Toast the bread."},
                {"ko": "아보카도를 반 갈라 과육을 포크로 으깨요.", "en": "Halve avocado and mash the flesh with a fork."},
                {"ko": "레몬즙·소금·후추를 넣고 섞어요.", "en": "Mix in lemon juice, salt, and pepper."},
                {"ko": "토스트 위에 아보카도를 올려요.", "en": "Spread avocado on toast."},
                {"ko": "계란 프라이를 올리고 칠리 플레이크·올리브유를 뿌려요.", "en": "Top with a fried egg; drizzle with olive oil and sprinkle chili flakes."},
            ],
        },
        {
            "id": "croque-monsieur",
            "name": {"ko": "크로크무슈", "en": "Croque Monsieur", "ja": "クロックムッシュ", "zh": "火腿奶酪烤三明治"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "프랑스 카페의 클래식 핫 샌드위치", "en": "Classic French hot ham and cheese sandwich", "ja": "フランスカフェの定番ホットサンド", "zh": "法国咖啡馆经典热三明治"},
            "ingredients": [
                {"name": "식빵", "amount": "2장"},
                {"name": "슬라이스 햄", "amount": "2장"},
                {"name": "그뤼에르 또는 모짜렐라 치즈", "amount": "30g"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "디종 머스타드", "amount": "1작은술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "빵 한 면에 머스타드를 발라요.", "en": "Spread mustard on one side of each bread slice."},
                {"ko": "빵→치즈 반→햄→치즈 나머지→빵 순으로 쌓아요.", "en": "Layer: bread, half the cheese, ham, rest of cheese, bread."},
                {"ko": "팬에 버터를 녹이고 샌드위치를 올려 눌러가며 구워요.", "en": "Melt butter in pan; toast sandwich, pressing down."},
                {"ko": "양면이 황금빛이 되고 치즈가 녹을 때까지 구워요.", "en": "Cook until both sides are golden and cheese melts."},
            ],
        },
        {
            "id": "club-sandwich",
            "name": {"ko": "클럽 샌드위치", "en": "Club Sandwich", "ja": "クラブサンドイッチ", "zh": "总汇三明治"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "닭가슴살·베이컨·계란이 층층이 쌓인 풍성한 샌드위치", "en": "Stacked sandwich with chicken, bacon, and egg", "ja": "チキン・ベーコン・卵が重なる豪華サンド", "zh": "鸡肉、培根和鸡蛋层层叠加的丰盛三明治"},
            "ingredients": [
                {"name": "식빵", "amount": "3장"},
                {"name": "닭 가슴살 (삶아 슬라이스)", "amount": "80g"},
                {"name": "베이컨", "amount": "2줄"},
                {"name": "계란 (프라이)", "amount": "1개"},
                {"name": "양상추", "amount": "2장"},
                {"name": "토마토", "amount": "2슬라이스"},
                {"name": "마요네즈", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "빵 3장을 모두 토스트해요.", "en": "Toast all 3 bread slices."},
                {"ko": "베이컨을 바삭하게 구워요.", "en": "Cook bacon until crispy."},
                {"ko": "빵에 마요네즈를 발라요.", "en": "Spread mayo on bread slices."},
                {"ko": "빵→양상추→토마토→닭고기→빵→베이컨→계란→양상추→빵 순으로 쌓아요.", "en": "Stack: bread, lettuce, tomato, chicken, bread, bacon, egg, lettuce, bread."},
                {"ko": "이쑤시개로 고정하고 대각선으로 잘라요.", "en": "Secure with toothpicks and cut diagonally."},
            ],
        },
        {
            "id": "focaccia",
            "name": {"ko": "포카치아", "en": "Focaccia", "ja": "フォカッチャ", "zh": "佛卡夏面包"},
            "time": 70, "difficulty": 2,
            "desc": {"ko": "올리브유 향 가득한 이탈리아 플랫 브레드", "en": "Olive oil-soaked Italian flatbread with dimpled top", "ja": "オリーブオイルたっぷりのイタリアのフラットブレッド", "zh": "充满橄榄油香气的意大利扁面包"},
            "ingredients": [
                {"name": "강력분", "amount": "250g"},
                {"name": "드라이이스트", "amount": "1작은술"},
                {"name": "미지근한 물", "amount": "180ml"},
                {"name": "올리브유", "amount": "3큰술"},
                {"name": "소금", "amount": "1작은술"},
                {"name": "로즈마리·굵은 소금", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "미지근한 물에 이스트를 녹이고 밀가루·소금·올리브유를 넣어 반죽해요.", "en": "Dissolve yeast in warm water; mix in flour, salt, and olive oil into a dough."},
                {"ko": "따뜻한 곳에서 40분 발효해요.", "en": "Ferment in a warm spot for 40 minutes."},
                {"ko": "기름 바른 팬에 반죽을 펴고 손가락으로 구멍을 내요.", "en": "Spread dough in an oiled pan; press dimples with your fingers."},
                {"ko": "올리브유를 넉넉히 뿌리고 로즈마리·굵은 소금을 올려요.", "en": "Drizzle generously with olive oil; top with rosemary and coarse salt."},
                {"ko": "220°C 오븐에서 20분 구워요.", "en": "Bake at 220°C for 20 minutes."},
            ],
        },
    ],
    "western/baking": [
        {
            "id": "brownie",
            "name": {"ko": "브라우니", "en": "Chocolate Brownie", "ja": "ブラウニー", "zh": "布朗尼"},
            "time": 35, "difficulty": 1,
            "desc": {"ko": "겉은 바삭 속은 촉촉한 진한 초콜릿 브라우니", "en": "Crispy-edged, fudgy-centred chocolate brownie", "ja": "外カリ中しっとりの濃厚チョコレートブラウニー", "zh": "外酥内软的浓郁巧克力布朗尼"},
            "ingredients": [
                {"name": "다크 초콜릿 또는 코코아 파우더", "amount": "60g"},
                {"name": "버터", "amount": "80g"},
                {"name": "설탕", "amount": "120g"},
                {"name": "계란", "amount": "2개"},
                {"name": "박력분", "amount": "60g"},
                {"name": "소금", "amount": "한 꼬집"},
                {"name": "바닐라 에센스", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "버터와 초콜릿을 중탕 또는 전자레인지로 녹여요.", "en": "Melt butter and chocolate together using a bain-marie or microwave."},
                {"ko": "설탕·계란·바닐라를 넣고 잘 섞어요.", "en": "Stir in sugar, eggs, and vanilla."},
                {"ko": "박력분·소금을 체 쳐 넣고 날가루가 없어질 만큼만 섞어요.", "en": "Sift in flour and salt; fold just until no flour remains."},
                {"ko": "버터 바른 틀에 붓고 175°C에서 20~25분 구워요.", "en": "Pour into greased pan; bake at 175°C for 20-25 minutes."},
                {"ko": "이쑤시개로 찔러 촉촉하게 묻어나면 완성이에요. 식힌 뒤 잘라요.", "en": "A skewer with a few moist crumbs means done. Cool before slicing."},
            ],
        },
        {
            "id": "no-bake-cheesecake",
            "name": {"ko": "노오븐 치즈케이크", "en": "No-Bake Cheesecake", "ja": "焼かないチーズケーキ", "zh": "免烤芝士蛋糕"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "오븐 없이 만드는 부드러운 크림치즈케이크", "en": "Creamy cheesecake that needs no oven — just a fridge", "ja": "オーブン不要の滑らかなクリームチーズケーキ", "zh": "无需烤箱的绵滑奶油芝士蛋糕，只需冰箱"},
            "ingredients": [
                {"name": "크림치즈", "amount": "200g"},
                {"name": "생크림", "amount": "200ml"},
                {"name": "설탕", "amount": "60g"},
                {"name": "레몬즙", "amount": "1큰술"},
                {"name": "젤라틴 분말", "amount": "5g"},
                {"name": "물 (젤라틴용)", "amount": "2큰술"},
                {"name": "소화 크래커 또는 오레오", "amount": "100g"},
                {"name": "버터 (녹인 것)", "amount": "40g"},
            ],
            "steps": [
                {"ko": "크래커를 잘게 부수고 녹인 버터와 섞어 틀 바닥에 꾹꾹 눌러요.", "en": "Crush crackers, mix with melted butter, and press firmly into the bottom of a mold."},
                {"ko": "젤라틴을 물에 불려 전자레인지로 10초씩 녹여요.", "en": "Bloom gelatin in water; melt in microwave in 10-second bursts."},
                {"ko": "크림치즈·설탕·레몬즙을 부드럽게 풀고 젤라틴을 넣어요.", "en": "Beat cream cheese, sugar, and lemon juice until smooth; add gelatin."},
                {"ko": "생크림을 휘핑해 뿔이 설 때까지 올리고 치즈 반죽에 섞어요.", "en": "Whip cream to stiff peaks; fold into cream cheese mixture."},
                {"ko": "틀에 붓고 냉장고에서 4시간 이상 굳혀요.", "en": "Pour over base; refrigerate at least 4 hours to set."},
            ],
        },
        {
            "id": "oatmeal-cookies",
            "name": {"ko": "오트밀 쿠키", "en": "Oatmeal Cookies", "ja": "オートミールクッキー", "zh": "燕麦曲奇"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "바삭하면서도 고소한 건강한 오트밀 쿠키", "en": "Crispy yet chewy wholesome oatmeal cookies", "ja": "サクサクでもちもちの健康的なオートミールクッキー", "zh": "酥脆香浓的健康燕麦曲奇"},
            "ingredients": [
                {"name": "오트밀 (롤드 오트)", "amount": "150g"},
                {"name": "박력분", "amount": "80g"},
                {"name": "버터 (실온)", "amount": "100g"},
                {"name": "황설탕", "amount": "100g"},
                {"name": "계란", "amount": "1개"},
                {"name": "바닐라 에센스", "amount": "1작은술"},
                {"name": "소금·베이킹소다", "amount": "각 한 꼬집"},
                {"name": "초콜릿 칩 (선택)", "amount": "50g"},
            ],
            "steps": [
                {"ko": "버터와 설탕을 크림처럼 섞어요.", "en": "Cream butter and sugar together."},
                {"ko": "계란과 바닐라를 넣고 섞어요.", "en": "Mix in egg and vanilla."},
                {"ko": "밀가루·소금·베이킹소다·오트밀을 넣어 반죽해요.", "en": "Add flour, salt, baking soda, and oats; mix into a dough."},
                {"ko": "초콜릿 칩을 넣어요 (선택).", "en": "Fold in chocolate chips if using."},
                {"ko": "한 스푼씩 떠 베이킹 시트에 올리고 175°C에서 12~14분 구워요.", "en": "Scoop onto baking sheet; bake at 175°C for 12-14 minutes."},
            ],
        },
        {
            "id": "madeleine",
            "name": {"ko": "마들렌", "en": "Madeleine", "ja": "マドレーヌ", "zh": "玛德琳"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "조개 모양 틀에 구운 프랑스 버터 케이크", "en": "Buttery French shell-shaped cake with a crispy edge", "ja": "貝形型で焼いたフランスのバターケーキ", "zh": "贝壳形烤制的法式黄油蛋糕"},
            "ingredients": [
                {"name": "박력분", "amount": "100g"},
                {"name": "버터 (녹인 것)", "amount": "100g"},
                {"name": "설탕", "amount": "100g"},
                {"name": "계란", "amount": "2개"},
                {"name": "베이킹파우더", "amount": "1작은술"},
                {"name": "레몬 제스트", "amount": "1/2개"},
                {"name": "바닐라 에센스", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "계란과 설탕을 하얗고 뽀얘질 때까지 거품기로 섞어요.", "en": "Whisk eggs and sugar until pale and fluffy."},
                {"ko": "밀가루·베이킹파우더를 체 쳐 넣고 섞어요.", "en": "Sift in flour and baking powder; fold in."},
                {"ko": "녹인 버터·레몬 제스트·바닐라를 넣고 섞어요.", "en": "Add melted butter, lemon zest, and vanilla; mix."},
                {"ko": "반죽을 냉장고에 30분 넣어요 (냉장 후 굽기가 핵심).", "en": "Rest batter in fridge 30 minutes — this is the key to the signature hump."},
                {"ko": "틀에 버터 바르고 190°C에서 11~12분 구워요.", "en": "Grease molds; bake at 190°C for 11-12 minutes."},
            ],
        },
    ],
}
