RECIPES_WEST = {
    "western/pasta": [
        {
            "id": "tomato-pasta",
            "name": {"ko": "토마토파스타", "en": "Tomato Pasta", "ja": "トマトパスタ", "zh": "番茄意面"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "파스타의 기본, 토마토 소스 하나만 잘 만들어도 절반은 성공", "en": "Master the tomato sauce and you've mastered pasta", "ja": "パスタの基本、トマトソースさえ上手く作れれば半分は成功", "zh": "意面基础，番茄酱做好就成功一半"},
            "ingredients": [
                {"name": "스파게티 면", "amount": "100g"},
                {"name": "홀토마토 캔", "amount": "1/2캔(200g)"},
                {"name": "다진 마늘", "amount": "3쪽"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "올리브오일", "amount": "3큰술"},
                {"name": "소금·후추·설탕", "amount": "약간씩"},
                {"name": "바질 (선택)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "끓는 물에 소금을 넣고 면을 패키지보다 1분 짧게 삶아요.", "en": "Boil pasta in well-salted water, 1 minute less than package says."},
                {"ko": "팬에 올리브오일로 마늘·양파를 약불에서 노릇하게 볶아요.", "en": "Sauté garlic and onion in olive oil over low heat until golden."},
                {"ko": "홀토마토를 으깨며 넣고 중불에서 10분 졸여요.", "en": "Add crushed tomatoes and simmer over medium heat for 10 minutes."},
                {"ko": "소금·설탕으로 간을 맞춰요. 설탕은 산미를 잡아줘요.", "en": "Season with salt and a pinch of sugar — sugar balances acidity."},
                {"ko": "면을 넣고 면수 2-3큰술을 더해 30초 버무려요.", "en": "Add pasta and 2-3 tbsp pasta water; toss for 30 seconds."},
            ],
        },
        {
            "id": "carbonara",
            "name": {"ko": "까르보나라", "en": "Carbonara", "ja": "カルボナーラ", "zh": "培根蛋黄意面"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "생크림 없이 계란과 치즈만으로 크리미하게", "en": "Creamy without cream — eggs and cheese are the secret", "ja": "生クリームなしで卵とチーズだけでクリーミーに", "zh": "不用奶油，只用鸡蛋和芝士就能做出丝滑口感"},
            "ingredients": [
                {"name": "스파게티 면", "amount": "100g"},
                {"name": "베이컨 또는 판체타", "amount": "80g"},
                {"name": "계란", "amount": "2개"},
                {"name": "파마산 치즈 (가루)", "amount": "4큰술"},
                {"name": "후추", "amount": "넉넉히"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "계란과 파마산 치즈를 잘 섞어 소스를 만들어요.", "en": "Mix eggs and parmesan cheese thoroughly."},
                {"ko": "면을 소금물에 삶아요.", "en": "Cook pasta in well-salted boiling water."},
                {"ko": "팬에 베이컨을 바삭하게 볶고 불을 꺼요.", "en": "Crisp the bacon in a pan, then turn off the heat."},
                {"ko": "삶은 면을 팬에 넣고 면수 3큰술을 더해요. 불은 끄거나 약불로.", "en": "Add drained pasta to pan with 3 tbsp pasta water. Keep heat off or very low."},
                {"ko": "계란 소스를 넣고 빠르게 버무려요. 열이 너무 세면 계란이 익어버려요.", "en": "Add egg sauce and toss quickly. Too much heat scrambles the eggs."},
                {"ko": "후추를 넉넉히 갈아 마무리해요.", "en": "Finish with generous freshly ground black pepper."},
            ],
        },
        {
            "id": "aglio-olio",
            "name": {"ko": "알리오올리오", "en": "Aglio e Olio", "ja": "アーリオオーリオ", "zh": "蒜油意面"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "마늘과 올리브오일만으로 이렇게 맛있을 수가", "en": "Just garlic and olive oil — impossibly good", "ja": "ニンニクとオリーブオイルだけでこんなに美味しいなんて", "zh": "只用大蒜和橄榄油竟然这么好吃"},
            "ingredients": [
                {"name": "스파게티 면", "amount": "100g"},
                {"name": "마늘", "amount": "5쪽"},
                {"name": "올리브오일", "amount": "4큰술"},
                {"name": "건고추", "amount": "1-2개"},
                {"name": "파슬리 (선택)", "amount": "약간"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "마늘을 얇게 편 썰어요.", "en": "Slice garlic thinly."},
                {"ko": "면을 삶아요. 면수는 버리지 마세요.", "en": "Cook pasta. Don't throw away the pasta water."},
                {"ko": "올리브오일에 마늘을 약불에서 천천히 노릇하게 볶아요. 타면 쓴맛이 나요.", "en": "Slowly cook garlic in olive oil over low heat until golden. Don't burn it."},
                {"ko": "건고추를 넣어 향을 내요.", "en": "Add dried chili for heat."},
                {"ko": "면과 면수 4큰술을 넣고 오일이 유화될 때까지 섞어요.", "en": "Add pasta and 4 tbsp pasta water; toss until oil emulsifies into a sauce."},
            ],
        },
    ],
    "western/meat": [
        {
            "id": "pan-steak",
            "name": {"ko": "팬 스테이크", "en": "Pan Steak", "ja": "パンステーキ", "zh": "煎牛排"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "집에서도 레스토랑 스테이크 가능, 버터 베이스팅이 핵심", "en": "Restaurant-quality steak at home — butter basting is everything", "ja": "家でもレストランのステーキが可能、バターバスティングが命", "zh": "在家也能做出餐厅级牛排，黄油浇汁是关键"},
            "ingredients": [
                {"name": "소고기 (등심 or 채끝)", "amount": "200g (2.5cm 두께)"},
                {"name": "버터", "amount": "2큰술"},
                {"name": "마늘", "amount": "3쪽"},
                {"name": "로즈마리 또는 타임", "amount": "1줄기"},
                {"name": "소금·후추", "amount": "넉넉히"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "고기를 실온에 30분 꺼내 두고, 소금·후추를 넉넉히 뿌려요.", "en": "Rest steak at room temperature 30 minutes; season generously with salt and pepper."},
                {"ko": "팬을 최대 강불로 달궈 연기가 나기 직전까지 가열해요.", "en": "Heat pan to maximum until nearly smoking."},
                {"ko": "기름 두르고 고기를 올려 한 면당 2-3분 굽고 뒤집어요. 자주 뒤집지 마세요.", "en": "Oil pan, place steak and cook 2-3 minutes per side. Resist flipping too much."},
                {"ko": "버터·마늘·허브를 넣고, 녹은 버터를 숟가락으로 고기에 계속 끼얹어요 (베이스팅).", "en": "Add butter, garlic, and herbs. Spoon melted butter over steak repeatedly (basting)."},
                {"ko": "불을 끄고 5분 휴지 후 썰어요. 휴지가 있어야 육즙이 안 빠져요.", "en": "Turn off heat and rest 5 minutes before slicing. Resting keeps the juices in."},
            ],
        },
        {
            "id": "hamburg-steak",
            "name": {"ko": "함박스테이크", "en": "Hamburg Steak", "ja": "ハンバーグ", "zh": "汉堡肉饼"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "폭신폭신한 고기 패티에 데미글라스 소스", "en": "Juicy meat patty with rich demi-glace sauce", "ja": "ふわふわ肉パティにデミグラスソース", "zh": "蓬松多汁的肉饼配浓郁德式酱汁"},
            "ingredients": [
                {"name": "소·돼지 혼합 다짐육", "amount": "250g"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "빵가루", "amount": "3큰술"},
                {"name": "우유", "amount": "2큰술"},
                {"name": "계란", "amount": "1개"},
                {"name": "소금·후추·너트맥", "amount": "약간씩"},
                {"name": "케첩·우스터소스", "amount": "각 2큰술 (소스용)"},
            ],
            "steps": [
                {"ko": "양파를 잘게 다져 기름에 볶아 식혀요.", "en": "Finely dice onion and sauté until soft; let cool."},
                {"ko": "빵가루를 우유에 불려요.", "en": "Soak breadcrumbs in milk."},
                {"ko": "다짐육·양파·빵가루·계란·소금·후추를 잘 치대어 반죽해요. 끈기가 생길 때까지요.", "en": "Mix ground meat, onion, breadcrumbs, egg, salt, and pepper until sticky."},
                {"ko": "타원형 패티로 빚어 가운데를 살짝 눌러요 (가운데가 볼록해지는 걸 방지).", "en": "Form oval patties; press a dimple in the center to prevent puffing."},
                {"ko": "팬에 굽고, 케첩+우스터소스를 섞어 소스를 만들어 함께 내요.", "en": "Pan-fry patties; mix ketchup and Worcestershire for sauce."},
            ],
        },
        {
            "id": "chicken-steak",
            "name": {"ko": "허브 치킨 스테이크", "en": "Herb Chicken Steak", "ja": "ハーブチキン", "zh": "香草鸡排"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "촉촉하고 향긋한 허브 닭가슴살 구이", "en": "Juicy herbed chicken breast that stays moist", "ja": "しっとり香り豊かなハーブ鶏胸肉グリル", "zh": "湿润芳香的香草烤鸡胸"},
            "ingredients": [
                {"name": "닭가슴살", "amount": "1장"},
                {"name": "올리브오일", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "로즈마리 또는 오레가노", "amount": "1작은술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "레몬즙", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "닭가슴살을 두께가 균일하도록 반으로 눌러 펴거나 포를 떠요.", "en": "Pound chicken breast to even thickness or butterfly it."},
                {"ko": "올리브오일·마늘·허브·소금·후추·레몬즙으로 재워 20분 이상 두어요.", "en": "Marinate in olive oil, garlic, herbs, salt, pepper, and lemon juice for 20+ minutes."},
                {"ko": "팬을 중강불로 달궈 닭을 올려요.", "en": "Heat pan over medium-high heat and add chicken."},
                {"ko": "한 면 4분, 뒤집어 4분 굽고 꺼내요. 자르면 분홍색이 없어야 해요.", "en": "Cook 4 minutes per side. No pink when sliced means it's done."},
                {"ko": "3분 휴지 후 서빙해요.", "en": "Rest 3 minutes before serving."},
            ],
        },
    ],
    "western/salad": [
        {
            "id": "caesar-salad",
            "name": {"ko": "시저 샐러드", "en": "Caesar Salad", "ja": "シーザーサラダ", "zh": "凯撒沙拉"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "드레싱만 잘 만들면 나머지는 쉬운 명품 샐러드", "en": "Get the dressing right and the rest is effortless", "ja": "ドレッシングさえ上手く作れば残りは簡単な名品サラダ", "zh": "酱汁做好了，其余轻而易举的名品沙拉"},
            "ingredients": [
                {"name": "로메인 상추", "amount": "4-5장"},
                {"name": "마요네즈", "amount": "3큰술"},
                {"name": "파마산 치즈 가루", "amount": "2큰술"},
                {"name": "레몬즙", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "우스터소스", "amount": "1작은술"},
                {"name": "크루통 (빵 구운 것)", "amount": "한 줌"},
            ],
            "steps": [
                {"ko": "마요네즈·파마산·레몬즙·마늘·우스터소스를 섞어 드레싱을 만들어요.", "en": "Mix mayo, parmesan, lemon juice, garlic, and Worcestershire for the dressing."},
                {"ko": "로메인은 먹기 좋게 뜯어 씻고 물기를 완전히 빼요.", "en": "Tear romaine into pieces, wash, and dry thoroughly."},
                {"ko": "드레싱을 상추에 버무려요.", "en": "Toss romaine with the dressing."},
                {"ko": "크루통과 파마산을 뿌려요.", "en": "Top with croutons and extra parmesan."},
            ],
        },
        {
            "id": "french-onion-soup",
            "name": {"ko": "프렌치 어니언 수프", "en": "French Onion Soup", "ja": "フレンチオニオンスープ", "zh": "法式洋葱汤"},
            "time": 50, "difficulty": 2,
            "desc": {"ko": "양파를 충분히 볶는 것이 핵심, 기다림이 맛을 만들어요", "en": "The long-cooked onions are the magic — patience pays off", "ja": "玉ねぎをしっかり炒めることが大事、待つことが味を作る", "zh": "洋葱充分炒制是关键，等待成就美味"},
            "ingredients": [
                {"name": "양파", "amount": "3개"},
                {"name": "버터", "amount": "2큰술"},
                {"name": "소고기 육수 또는 비프 스톡", "amount": "3컵"},
                {"name": "화이트와인 (선택)", "amount": "1/4컵"},
                {"name": "바게트", "amount": "2조각"},
                {"name": "그뤼에르 또는 모짜렐라 치즈", "amount": "50g"},
                {"name": "소금·후추·타임", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "양파를 얇게 슬라이스해요.", "en": "Slice onions thinly."},
                {"ko": "냄비에 버터를 녹이고 약불에서 양파를 30-40분 충분히 볶아요. 갈색이 나야 해요.", "en": "Melt butter and caramelize onions over low heat for 30-40 minutes until deep brown."},
                {"ko": "와인을 넣어 1분 볶은 뒤 육수·타임을 넣고 10분 끓여요.", "en": "Add wine, cook 1 minute, then add stock and thyme; simmer 10 minutes."},
                {"ko": "오븐용 그릇에 수프를 담고 바게트를 올려요.", "en": "Pour soup into oven-safe bowls and place baguette on top."},
                {"ko": "치즈를 얹어 230°C 오븐에서 치즈가 녹을 때까지 구워요.", "en": "Cover with cheese and bake at 230°C until melted and bubbly."},
            ],
        },
        {
            "id": "cream-soup",
            "name": {"ko": "크림 감자 수프", "en": "Cream of Potato Soup", "ja": "ポタージュ", "zh": "奶油土豆汤"},
            "time": 30, "difficulty": 1,
            "desc": {"ko": "부드럽고 따뜻한 포타주, 믹서기만 있으면 OK", "en": "Velvety smooth potage — just need a blender", "ja": "なめらかで温かいポタージュ、ミキサーがあればOK", "zh": "顺滑温暖的浓汤，有搅拌机就行"},
            "ingredients": [
                {"name": "감자", "amount": "2개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "우유 또는 생크림", "amount": "1컵"},
                {"name": "닭육수 또는 물", "amount": "1.5컵"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "감자·양파를 큼직하게 썰어요.", "en": "Roughly chop potatoes and onion."},
                {"ko": "냄비에 버터를 녹이고 양파를 볶아요.", "en": "Melt butter in a pot and sauté onion."},
                {"ko": "감자와 육수를 넣고 감자가 푹 익을 때까지 15분 끓여요.", "en": "Add potatoes and broth; boil 15 minutes until potato is very soft."},
                {"ko": "믹서기에 곱게 갈아요.", "en": "Blend until completely smooth."},
                {"ko": "냄비에 다시 담고 우유를 넣어 원하는 농도로 조절하고 소금·후추로 간해요.", "en": "Return to pot, add milk to adjust consistency, and season with salt and pepper."},
            ],
        },
    ],
    "western/bread": [
        {
            "id": "blt-sandwich",
            "name": {"ko": "BLT 샌드위치", "en": "BLT Sandwich", "ja": "BLTサンドイッチ", "zh": "BLT三明治"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "베이컨·상추·토마토의 완벽한 조합", "en": "Bacon, lettuce, tomato — the ultimate classic", "ja": "ベーコン・レタス・トマトの完璧な組み合わせ", "zh": "培根、生菜、番茄的完美组合"},
            "ingredients": [
                {"name": "식빵", "amount": "2장"},
                {"name": "베이컨", "amount": "3장"},
                {"name": "로메인 또는 양상추", "amount": "2장"},
                {"name": "토마토", "amount": "2-3슬라이스"},
                {"name": "마요네즈", "amount": "1.5큰술"},
                {"name": "소금·후추", "amount": "약간"},
            ],
            "steps": [
                {"ko": "베이컨을 팬에 바삭하게 구워요.", "en": "Fry bacon until crispy."},
                {"ko": "식빵을 토스터에 굽거나 팬에 노릇하게 구워요.", "en": "Toast the bread."},
                {"ko": "빵에 마요네즈를 고르게 펴 발라요.", "en": "Spread mayo evenly on the bread."},
                {"ko": "상추·토마토·베이컨 순으로 올리고 소금·후추를 뿌려요.", "en": "Layer lettuce, tomato, and bacon; season with salt and pepper."},
                {"ko": "빵을 덮고 대각선으로 잘라요.", "en": "Top with other slice and cut diagonally."},
            ],
        },
        {
            "id": "french-toast",
            "name": {"ko": "프렌치 토스트", "en": "French Toast", "ja": "フレンチトースト", "zh": "法式吐司"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "달걀물에 흠뻑 적신 촉촉한 아침 식사", "en": "Eggy, custardy breakfast that feels luxurious", "ja": "卵液にたっぷり浸したしっとりした朝食", "zh": "充分浸泡蛋液的湿润早餐"},
            "ingredients": [
                {"name": "두꺼운 식빵", "amount": "2장"},
                {"name": "계란", "amount": "2개"},
                {"name": "우유", "amount": "4큰술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "바닐라 에센스", "amount": "1/4작은술 (선택)"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "메이플시럽 또는 꿀", "amount": "취향껏"},
            ],
            "steps": [
                {"ko": "계란·우유·설탕·바닐라를 섞어 계란물을 만들어요.", "en": "Whisk eggs, milk, sugar, and vanilla together."},
                {"ko": "빵을 계란물에 양면 각 1분씩 충분히 적셔요.", "en": "Soak bread in egg mixture 1 minute per side."},
                {"ko": "팬에 버터를 녹이고 약중불로 달궈요.", "en": "Melt butter in pan over medium-low heat."},
                {"ko": "빵을 올려 한 면 3분씩 노릇하게 구워요.", "en": "Cook bread 3 minutes per side until golden."},
                {"ko": "메이플시럽이나 꿀을 뿌려 서빙해요.", "en": "Serve with maple syrup or honey."},
            ],
        },
        {
            "id": "egg-toast",
            "name": {"ko": "에그 토스트", "en": "Korean Egg Toast", "ja": "エッグトースト", "zh": "鸡蛋吐司"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "길거리 간식을 집에서, 계란+야채 토스트", "en": "Korean street food classic made at home", "ja": "屋台のおやつを家で、卵＋野菜トースト", "zh": "路边小吃在家做，鸡蛋蔬菜吐司"},
            "ingredients": [
                {"name": "식빵", "amount": "2장"},
                {"name": "계란", "amount": "2개"},
                {"name": "양배추 (채썰기)", "amount": "2큰술"},
                {"name": "당근 (채썰기)", "amount": "1큰술"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "설탕", "amount": "1/2작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "케첩", "amount": "취향껏"},
            ],
            "steps": [
                {"ko": "계란에 채 썬 양배추·당근·소금을 넣어 섞어요.", "en": "Mix eggs with shredded cabbage, carrot, and salt."},
                {"ko": "팬에 버터 녹이고 계란 야채를 부어 식빵 크기로 모양 잡아 익혀요.", "en": "Melt butter, pour in egg-vegetable mixture and shape to fit the bread."},
                {"ko": "식빵은 따로 또는 같은 팬에 노릇하게 구워요.", "en": "Toast the bread separately or in the same pan."},
                {"ko": "빵에 계란을 올리고 설탕을 살짝 뿌려요.", "en": "Place egg on bread and sprinkle lightly with sugar."},
                {"ko": "케첩을 뿌려 반으로 접어 드세요.", "en": "Add ketchup, fold in half, and enjoy."},
            ],
        },
    ],
    "western/baking": [
        {
            "id": "banana-bread",
            "name": {"ko": "바나나 브레드", "en": "Banana Bread", "ja": "バナナブレッド", "zh": "香蕉面包"},
            "time": 65, "difficulty": 2,
            "desc": {"ko": "검게 익은 바나나일수록 달콤, 실패 없는 홈베이킹", "en": "The blacker the bananas, the sweeter the bread", "ja": "黒く熟したバナナほど甘くなる、失敗なしのホームベーキング", "zh": "香蕉越黑越甜，不会失败的家庭烘焙"},
            "ingredients": [
                {"name": "잘 익은 바나나", "amount": "3개"},
                {"name": "박력분", "amount": "200g"},
                {"name": "설탕", "amount": "100g"},
                {"name": "버터 (녹인 것)", "amount": "80g"},
                {"name": "계란", "amount": "2개"},
                {"name": "베이킹소다", "amount": "1작은술"},
                {"name": "소금", "amount": "1/4작은술"},
            ],
            "steps": [
                {"ko": "오븐을 175°C로 예열하고 파운드 틀에 버터를 발라요.", "en": "Preheat oven to 175°C; grease a loaf pan."},
                {"ko": "바나나를 포크로 으깨 덩어리가 없도록 해요.", "en": "Mash bananas with a fork until smooth."},
                {"ko": "녹인 버터·설탕·계란을 섞고 바나나를 넣어요.", "en": "Mix melted butter, sugar, and eggs; stir in mashed banana."},
                {"ko": "밀가루·베이킹소다·소금을 체쳐 넣고 가볍게 섞어요. 너무 많이 섞으면 질겨져요.", "en": "Sift in flour, baking soda, and salt; fold gently. Overmixing makes it tough."},
                {"ko": "틀에 붓고 55-60분 구워요. 이쑤시개로 찔러 묻지 않으면 완성이에요.", "en": "Pour into pan and bake 55-60 minutes. A toothpick should come out clean."},
            ],
        },
        {
            "id": "chocolate-brownie",
            "name": {"ko": "초코 브라우니", "en": "Chocolate Brownie", "ja": "チョコブラウニー", "zh": "巧克力布朗尼"},
            "time": 45, "difficulty": 1,
            "desc": {"ko": "겉은 바삭, 속은 촉촉한 홈베이킹의 최강자", "en": "Crispy edges, fudgy center — the best beginner bake", "ja": "外はカリカリ、中はしっとりのホームベーキング最強", "zh": "外酥内润的家庭烘焙之王"},
            "ingredients": [
                {"name": "다크 초콜릿 또는 코코아파우더", "amount": "70g"},
                {"name": "버터", "amount": "80g"},
                {"name": "설탕", "amount": "150g"},
                {"name": "계란", "amount": "2개"},
                {"name": "박력분", "amount": "80g"},
                {"name": "소금", "amount": "1/4작은술"},
                {"name": "바닐라 에센스", "amount": "1/2작은술 (선택)"},
            ],
            "steps": [
                {"ko": "오븐 175°C 예열, 사각틀에 버터를 발라요.", "en": "Preheat oven to 175°C; grease a square baking pan."},
                {"ko": "초콜릿과 버터를 중탕으로 녹여요.", "en": "Melt chocolate and butter together in a double boiler."},
                {"ko": "설탕·계란을 넣고 잘 섞어요.", "en": "Stir in sugar and eggs until well combined."},
                {"ko": "밀가루·소금을 체쳐 넣고 섞어요.", "en": "Sift in flour and salt; fold in."},
                {"ko": "틀에 붓고 25-30분 구워요. 이쑤시개에 조금 묻으면 꺼내도 돼요 (촉촉하게).", "en": "Pour into pan and bake 25-30 minutes. A few moist crumbs on a toothpick means fudgy — perfect."},
            ],
        },
        {
            "id": "scone",
            "name": {"ko": "스콘", "en": "Scone", "ja": "スコーン", "zh": "司康"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "버터 향 가득한 영국식 스콘, 클로티드 크림과 함께", "en": "Buttery British scones — best with clotted cream", "ja": "バターの香りいっぱいのイギリス式スコーン、クロテッドクリームと一緒に", "zh": "奶油香十足的英式司康，搭配凝脂奶油更完美"},
            "ingredients": [
                {"name": "박력분", "amount": "200g"},
                {"name": "버터 (차가운 것)", "amount": "50g"},
                {"name": "설탕", "amount": "30g"},
                {"name": "베이킹파우더", "amount": "2작은술"},
                {"name": "우유", "amount": "80ml"},
                {"name": "계란", "amount": "1개"},
                {"name": "소금", "amount": "1/4작은술"},
            ],
            "steps": [
                {"ko": "오븐 200°C 예열해요.", "en": "Preheat oven to 200°C."},
                {"ko": "밀가루·설탕·베이킹파우더·소금을 섞고, 차가운 버터를 넣어 손가락으로 콩알 크기로 비벼요.", "en": "Mix flour, sugar, baking powder, and salt; rub in cold butter with fingertips until pea-sized."},
                {"ko": "계란과 우유를 섞어 반죽에 넣고 대충 모아요. 너무 치대면 딱딱해져요.", "en": "Mix egg and milk; add to flour mixture and combine roughly. Overworking makes them tough."},
                {"ko": "2cm 두께로 밀어 원형으로 잘라요.", "en": "Roll to 2cm thick and cut into rounds."},
                {"ko": "우유를 표면에 발라 200°C에서 15-18분 구워요.", "en": "Brush tops with milk and bake at 200°C for 15-18 minutes."},
            ],
        },
    ],
}
