RECIPES_EXTRA = {
    # ── 한식 추가 ────────────────────────────────────────────────
    "korean/rice": [
        {
            "id": "omurice",
            "name": {"ko": "오므라이스", "en": "Omurice", "ja": "オムライス", "zh": "蛋包饭"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "케첩볶음밥을 얇은 계란으로 감싼 인기 메뉴", "en": "Ketchup fried rice wrapped in a thin egg omelette", "ja": "ケチャップチャーハンを薄い卵で包んだ人気メニュー", "zh": "番茄酱炒饭用薄蛋皮包裹的人气料理"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "계란", "amount": "3개"},
                {"name": "닭가슴살 또는 햄", "amount": "60g"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "케첩", "amount": "3큰술"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "닭가슴살과 양파를 잘게 다져요.", "en": "Finely dice chicken and onion.", "ja": "鶏むね肉と玉ねぎを細かく刻みます。", "zh": "将鸡胸肉和洋葱切碎。"},
                {"ko": "버터에 양파·닭을 볶다가 밥과 케첩을 넣고 볶아요. 소금·후추로 간해요.", "en": "Sauté onion and chicken in butter, add rice and ketchup, season with salt and pepper.", "ja": "バターで玉ねぎと鶏肉を炒め、ご飯とケチャップを加えて炒め、塩こしょうで味付けします。", "zh": "用黄油炒洋葱和鸡肉，加入米饭和番茄酱炒匀，用盐和胡椒调味。"},
                {"ko": "볶음밥을 타원형으로 그릇에 모양 잡아 놓아요.", "en": "Shape the fried rice into an oval on the plate.", "ja": "チャーハンを楕円形に皿に盛り付けます。", "zh": "将炒饭在盘子上整成椭圆形。"},
                {"ko": "계란 2개를 잘 풀어 약불 팬에 얇게 펼쳐요. 반숙 상태에서 밥 위에 덮어요.", "en": "Beat 2 eggs and spread thin over low heat. Drape over rice while still soft.", "ja": "卵2個をよく溶いて弱火のフライパンに薄く広げます。半熟状態でご飯の上に被せます。", "zh": "将2个鸡蛋打散，在低火平底锅上摊薄。趁半熟状态盖在饭上。"},
                {"ko": "케첩을 줄무늬로 뿌려 마무리해요.", "en": "Drizzle ketchup on top and serve.", "ja": "ケチャップを縞模様にかけて仕上げます。", "zh": "以条纹状挤上番茄酱收尾。"},
            ],
        },
        {
            "id": "butter-rice",
            "name": {"ko": "버터 간장밥", "en": "Butter Soy Rice", "ja": "バター醤油ご飯", "zh": "黄油酱油饭"},
            "time": 5, "difficulty": 1,
            "desc": {"ko": "3분이면 완성, 밥도둑 중의 밥도둑", "en": "Three-ingredient rice bowl ready in 3 minutes", "ja": "3分で完成、ご飯泥棒の中のご飯泥棒", "zh": "3分钟完成，最完美的下饭菜"},
            "ingredients": [
                {"name": "따뜻한 밥", "amount": "1공기"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "계란 노른자 (선택)", "amount": "1개"},
                {"name": "김 가루", "amount": "약간"},
            ],
            "steps": [
                {"ko": "뜨거운 밥 위에 버터를 올려요.", "en": "Place butter on hot rice.", "ja": "熱いご飯の上にバターを乗せます。", "zh": "将黄油放在热饭上。"},
                {"ko": "간장을 뿌리고 버터가 녹을 때까지 기다렸다 섞어요.", "en": "Add soy sauce and let butter melt before stirring.", "ja": "醤油をかけ、バターが溶けるまで待ってから混ぜます。", "zh": "淋上酱油，等黄油融化后再搅拌。"},
                {"ko": "계란 노른자를 올리고 김 가루를 뿌려요.", "en": "Top with egg yolk and sprinkle nori flakes.", "ja": "卵の黄身を乗せ、青海苔をふりかけます。", "zh": "放上蛋黄，撒上海苔碎。"},
                {"ko": "잘 비벼서 드세요.", "en": "Mix everything together and enjoy.", "ja": "よく混ぜてお召し上がりください。", "zh": "充分拌匀食用。"},
            ],
        },
    ],
    "korean/soup": [
        {
            "id": "sundubu-jjigae",
            "name": {"ko": "순두부찌개", "en": "Sundubu Jjigae", "ja": "スンドゥブチゲ", "zh": "嫩豆腐汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "부드러운 순두부와 칼칼한 국물의 조화", "en": "Silky tofu in a fiery, comforting broth", "ja": "なめらかな豆腐とピリ辛スープの調和", "zh": "嫩滑豆腐与辛辣汤底的完美结合"},
            "ingredients": [
                {"name": "순두부", "amount": "1팩"},
                {"name": "바지락 또는 새우", "amount": "80g"},
                {"name": "고춧가루", "amount": "1.5큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "계란", "amount": "1개"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "국간장·소금", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "냄비에 참기름 두르고 고춧가루·마늘을 30초 볶아요.", "en": "Stir-fry chili flakes and garlic in sesame oil for 30 seconds.", "ja": "鍋にごま油を引き、唐辛子粉とにんにくを30秒炒めます。", "zh": "锅中倒入芝麻油，翻炒辣椒粉和蒜末30秒。"},
                {"ko": "양파와 해물을 넣고 볶아요.", "en": "Add onion and seafood; stir-fry.", "ja": "玉ねぎと海鮮を加えて炒めます。", "zh": "加入洋葱和海鲜翻炒。"},
                {"ko": "물 1.5컵을 붓고 끓여요.", "en": "Add 1.5 cups water and bring to a boil.", "ja": "水1.5カップを注いで煮立てます。", "zh": "加入1.5杯水煮沸。"},
                {"ko": "순두부를 숟가락으로 퍼 넣고 3분 끓여요.", "en": "Spoon in soft tofu and simmer 3 minutes.", "ja": "スプーンで絹ごし豆腐を入れ、3分煮ます。", "zh": "用勺子舀入嫩豆腐，煮3分钟。"},
                {"ko": "계란을 깨 넣고 국간장·소금으로 간해요.", "en": "Crack in egg and season with soy sauce and salt.", "ja": "卵を割り入れ、薄口醤油と塩で味を整えます。", "zh": "打入鸡蛋，用汤用酱油和盐调味。"},
            ],
        },
        {
            "id": "yukgaejang",
            "name": {"ko": "육개장", "en": "Yukgaejang", "ja": "ユッケジャン", "zh": "辣牛肉汤"},
            "time": 50, "difficulty": 2,
            "desc": {"ko": "소고기와 고사리가 어우러진 칼칼한 탕", "en": "Spicy shredded beef soup with fernbrake and vegetables", "ja": "牛肉とわらびが絡み合うピリ辛スープ", "zh": "牛肉与蕨菜交融的辛辣汤"},
            "ingredients": [
                {"name": "소고기 (양지 또는 사태)", "amount": "200g"},
                {"name": "고사리 (삶은 것)", "amount": "80g"},
                {"name": "대파", "amount": "1대"},
                {"name": "고춧가루", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1큰술"},
                {"name": "국간장", "amount": "1큰술"},
                {"name": "참기름", "amount": "1큰술"},
                {"name": "물", "amount": "4컵"},
            ],
            "steps": [
                {"ko": "소고기를 물에 삶아 건져 결대로 찢어요. 육수는 버리지 마세요.", "en": "Boil beef, remove and shred along the grain. Keep the broth.", "ja": "牛肉を茹でて取り出し、繊維に沿って裂きます。スープは捨てないでください。", "zh": "将牛肉煮熟捞出，顺纹理撕碎。保留汤汁。"},
                {"ko": "찢은 소고기·고사리·대파를 고춧가루·마늘·참기름으로 양념해 볶아요.", "en": "Season shredded beef, fernbrake, and green onion with chili flakes, garlic, and sesame oil; stir-fry.", "ja": "裂いた牛肉、ぜんまい、ねぎを唐辛子粉・にんにく・ごま油で和えて炒めます。", "zh": "将撕碎的牛肉、蕨菜、大葱用辣椒粉、蒜末、芝麻油调味后翻炒。"},
                {"ko": "육수를 붓고 20분 끓여요.", "en": "Add the reserved beef broth and boil 20 minutes.", "ja": "スープを注いで20分煮ます。", "zh": "加入保留的牛肉汤，煮20分钟。"},
                {"ko": "국간장으로 간을 맞춰요.", "en": "Season with soup soy sauce to taste.", "ja": "薄口醤油で味を整えます。", "zh": "用汤用酱油调味。"},
            ],
        },
    ],
    "korean/grill": [
        {
            "id": "gyeran-jjim",
            "name": {"ko": "계란찜", "en": "Korean Steamed Egg", "ja": "韓国風茶碗蒸し", "zh": "韩式蒸蛋"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "뚝배기에서 부풀어 오르는 폭신한 계란찜", "en": "Puffed, souffle-like steamed egg in a clay pot", "ja": "土鍋でふっくら膨らむふわふわ蒸し卵", "zh": "在砂锅中蓬松膨起的软嫩蒸蛋"},
            "ingredients": [
                {"name": "계란", "amount": "3개"},
                {"name": "멸치육수 또는 물", "amount": "180ml"},
                {"name": "국간장", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "쪽파·참기름", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "계란에 육수·국간장·소금을 넣고 잘 풀어요.", "en": "Beat eggs with broth, soup soy sauce, and salt.", "ja": "卵にだし・薄口醤油・塩を入れてよく溶き混ぜます。", "zh": "将鸡蛋与高汤、汤用酱油、盐一起打散混匀。"},
                {"ko": "뚝배기에 계란물을 부어요.", "en": "Pour into a clay pot or small pot.", "ja": "土鍋か小鍋に卵液を注ぎます。", "zh": "将蛋液倒入砂锅或小锅中。"},
                {"ko": "약불에서 뚜껑 덮고 10분 익혀요.", "en": "Cover and cook over low heat for 10 minutes.", "ja": "弱火で蓋をして10分加熱します。", "zh": "盖上锅盖，用小火加热10分钟。"},
                {"ko": "뚜껑을 열고 쪽파·참기름을 뿌려요. 살짝 부풀면 완성이에요.", "en": "Remove lid, add green onion and sesame oil. It should be puffed up.", "ja": "蓋を開けてネギとごま油をかけます。少し膨らんでいれば完成です。", "zh": "开盖撒上小葱和芝麻油。稍微膨起就完成了。"},
            ],
        },
        {
            "id": "dubu-jorim",
            "name": {"ko": "두부조림", "en": "Braised Spicy Tofu", "ja": "豆腐の煮付け", "zh": "辣炖豆腐"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "양념이 배어 쫄깃해진 두부, 밥 한 공기 순삭", "en": "Tofu soaked in spicy-sweet sauce — a rice stealer", "ja": "タレが染み込んでもちもちになった豆腐、ご飯が止まらない", "zh": "酱汁渗透后劲道十足的豆腐，一碗饭瞬间见底"},
            "ingredients": [
                {"name": "두부 (부침용)", "amount": "1모"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "참기름·쪽파", "amount": "약간씩"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "두부를 1.5cm 두께로 썰어 키친타월로 물기를 닦아요.", "en": "Slice tofu 1.5cm thick and pat dry with paper towels.", "ja": "豆腐を1.5cm厚に切り、キッチンペーパーで水気を拭き取ります。", "zh": "将豆腐切成1.5cm厚，用厨房纸巾吸干水分。"},
                {"ko": "팬에 기름 두르고 두부를 중불에서 양면 노릇하게 구워요.", "en": "Fry tofu in oil over medium heat until golden on both sides.", "ja": "フライパンに油を引き、中火で豆腐を両面きつね色に焼きます。", "zh": "锅中倒油，中火将豆腐两面煎至金黄。"},
                {"ko": "고춧가루·간장·마늘·설탕·물 3큰술을 섞어 소스를 만들어요.", "en": "Mix chili flakes, soy sauce, garlic, sugar, and 3 tbsp water for sauce.", "ja": "唐辛子粉・醤油・にんにく・砂糖・水大さじ3を混ぜてソースを作ります。", "zh": "将辣椒粉、酱油、蒜末、糖、3大勺水混合制成酱汁。"},
                {"ko": "소스를 두부 위에 붓고 약불에서 2분 졸여요.", "en": "Pour sauce over tofu and simmer on low 2 minutes.", "ja": "ソースを豆腐にかけ、弱火で2分煮詰めます。", "zh": "将酱汁浇在豆腐上，小火炖煮2分钟。"},
                {"ko": "참기름과 쪽파로 마무리해요.", "en": "Finish with sesame oil and green onion.", "ja": "ごま油とネギで仕上げます。", "zh": "用芝麻油和小葱收尾。"},
            ],
        },
    ],
    "korean/kimchi": [
        {
            "id": "japchae-egg",
            "name": {"ko": "미역줄기볶음", "en": "Stir-fried Wakame Stem", "ja": "わかめの茎の炒め物", "zh": "炒裙带菜茎"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "바다향 가득한 저칼로리 밑반찬", "en": "Low-calorie sea vegetable side with ocean flavor", "ja": "海の香りが豊かな低カロリーの副菜", "zh": "充满海洋气息的低热量小菜"},
            "ingredients": [
                {"name": "미역줄기 (염장 or 시판)", "amount": "150g"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "통깨", "amount": "약간"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "염장 미역줄기는 물에 30분 담가 짠맛을 빼고, 한 입 크기로 잘라요.", "en": "Soak salted wakame stem 30 minutes to remove salt; cut into pieces.", "ja": "塩蔵わかめの茎は水に30分浸けて塩抜きし、食べやすい大きさに切ります。", "zh": "将盐渍裙带菜茎在水中浸泡30分钟去盐，切成适口大小。"},
                {"ko": "끓는 물에 1분 데쳐 찬물에 헹궈요.", "en": "Blanch 1 minute; rinse in cold water.", "ja": "沸騰したお湯で1分湯がいて、冷水で洗います。", "zh": "在沸水中焯烫1分钟，用冷水冲洗。"},
                {"ko": "팬에 기름 두르고 마늘을 볶다가 미역줄기를 넣어요.", "en": "Stir-fry garlic in oil, then add wakame stem.", "ja": "フライパンに油を引き、にんにくを炒めてからわかめの茎を入れます。", "zh": "锅中倒油翻炒蒜末，再加入裙带菜茎。"},
                {"ko": "간장으로 간하고 참기름·통깨를 뿌려요.", "en": "Season with soy sauce, then finish with sesame oil and sesame seeds.", "ja": "醤油で味を付け、ごま油と白ごまをかけます。", "zh": "用酱油调味，撒上芝麻油和白芝麻。"},
            ],
        },
        {
            "id": "kongnamul",
            "name": {"ko": "콩나물무침", "en": "Bean Sprout Namul", "ja": "豆もやしのナムル", "zh": "豆芽凉拌"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "아삭아삭 해장에도 좋은 국민 반찬", "en": "Crunchy, refreshing — great after a long night too", "ja": "シャキシャキで二日酔いにも良い国民的おかず", "zh": "爽脆可口，解酒也很好的国民小菜"},
            "ingredients": [
                {"name": "콩나물", "amount": "200g"},
                {"name": "다진 마늘", "amount": "1/2작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "소금", "amount": "1/2작은술"},
                {"name": "고춧가루", "amount": "1/2작은술 (선택)"},
                {"name": "통깨", "amount": "약간"},
            ],
            "steps": [
                {"ko": "냄비에 물을 붓고 소금 약간 넣어 끓여요.", "en": "Bring salted water to a boil.", "ja": "鍋に水を入れて塩を少し加えて沸騰させます。", "zh": "锅中加水，放少许盐煮沸。"},
                {"ko": "콩나물을 넣고 뚜껑 덮어 4분 삶아요. 뚜껑을 열면 비린내가 나요.", "en": "Add bean sprouts, cover, and boil 4 minutes. Don't lift the lid or they'll smell fishy.", "ja": "もやしを入れて蓋をし、4分茹でます。蓋を開けると生臭くなります。", "zh": "加入豆芽，盖上锅盖煮4分钟。不要开盖，否则会有腥味。"},
                {"ko": "찬물에 헹궈 물기를 빼요.", "en": "Rinse in cold water and drain.", "ja": "冷水でよく洗って水気を切ります。", "zh": "用冷水冲洗后沥干。"},
                {"ko": "마늘·참기름·소금·고춧가루를 넣고 조물조물 무쳐 통깨를 뿌려요.", "en": "Toss with garlic, sesame oil, salt, and chili flakes; sprinkle sesame seeds.", "ja": "にんにく・ごま油・塩・唐辛子粉を入れて和え、白ごまをふります。", "zh": "加入蒜末、芝麻油、盐、辣椒粉拌匀，撒上白芝麻。"},
            ],
        },
    ],
    "korean/noodle": [
        {
            "id": "bibim-noodles",
            "name": {"ko": "비빔국수", "en": "Spicy Mixed Noodles", "ja": "ビビム麺", "zh": "拌面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "새콤달콤 매콤한 여름 국수, 10분이면 완성", "en": "Tangy, spicy, sweet — summer in a bowl", "ja": "酸っぱくて甘くて辛い夏の麺、10分で完成", "zh": "酸甜辣的夏日面条，10分钟完成"},
            "ingredients": [
                {"name": "소면 또는 중면", "amount": "1인분"},
                {"name": "고추장", "amount": "1.5큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "오이·당근·계란", "amount": "토핑용"},
            ],
            "steps": [
                {"ko": "고추장·식초·설탕·간장·참기름을 섞어 소스를 만들어요.", "en": "Mix gochujang, vinegar, sugar, soy sauce, and sesame oil for the sauce.", "ja": "コチュジャン・酢・砂糖・醤油・ごま油を混ぜてソースを作ります。", "zh": "将辣椒酱、醋、糖、酱油、芝麻油混合制成酱汁。"},
                {"ko": "면을 삶아 찬물에 헹궈 쫄깃하게 만들어요.", "en": "Cook noodles and rinse in cold water until chewy.", "ja": "麺を茹でて冷水でよく洗い、コシを出します。", "zh": "将面条煮熟，用冷水冲洗使其有弹性。"},
                {"ko": "오이와 당근을 채 썰어요.", "en": "Julienne cucumber and carrot.", "ja": "きゅうりとにんじんを千切りにします。", "zh": "将黄瓜和胡萝卜切丝。"},
                {"ko": "면에 소스를 넣고 골고루 버무려요.", "en": "Toss noodles with sauce until evenly coated.", "ja": "麺にソースを入れて均一に和えます。", "zh": "将酱汁倒入面条中均匀拌匀。"},
                {"ko": "채소와 반숙 계란을 올려 마무리해요.", "en": "Top with vegetables and a soft-boiled egg.", "ja": "野菜と半熟卵を乗せて仕上げます。", "zh": "摆上蔬菜和溏心蛋收尾。"},
            ],
        },
        {
            "id": "tteokbokki",
            "name": {"ko": "떡볶이", "en": "Tteokbokki", "ja": "トッポキ", "zh": "炒年糕"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "국민 분식의 대명사, 쫄깃한 떡과 달콤 매콤한 소스", "en": "Korea's most beloved street food — chewy rice cakes in spicy sauce", "ja": "国民的粉食の代名詞、もちもちの餅と甘辛ソース", "zh": "国民小吃的代名词，劲道年糕配甜辣酱汁"},
            "ingredients": [
                {"name": "떡볶이 떡", "amount": "200g"},
                {"name": "어묵", "amount": "1장"},
                {"name": "고추장", "amount": "2큰술"},
                {"name": "고춧가루", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "멸치육수 또는 물", "amount": "1.5컵"},
                {"name": "대파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "떡은 찬물에 10분 담가 불려요.", "en": "Soak rice cakes in cold water for 10 minutes.", "ja": "餅は冷水に10分浸けて柔らかくします。", "zh": "将年糕在冷水中浸泡10分钟泡软。"},
                {"ko": "냄비에 육수·고추장·고춧가루·설탕·간장을 넣고 끓여요.", "en": "Combine broth, gochujang, chili flakes, sugar, and soy sauce; bring to a boil.", "ja": "鍋にだし・コチュジャン・唐辛子粉・砂糖・醤油を入れて煮立てます。", "zh": "锅中加入高汤、辣椒酱、辣椒粉、糖、酱油煮沸。"},
                {"ko": "어묵을 먹기 좋게 잘라 넣어요.", "en": "Cut fish cake into pieces and add.", "ja": "さつま揚げを食べやすい大きさに切って加えます。", "zh": "将鱼糕切成适口大小加入。"},
                {"ko": "떡을 넣고 중불에서 소스가 졸아들 때까지 10분 저어가며 끓여요.", "en": "Add rice cakes and stir over medium heat for 10 minutes until sauce thickens.", "ja": "餅を入れて中火でソースが煮詰まるまで10分かき混ぜながら煮ます。", "zh": "加入年糕，中火搅拌煮10分钟直到酱汁收浓。"},
                {"ko": "대파를 올려 마무리해요.", "en": "Garnish with green onion and serve.", "ja": "長ねぎを乗せて仕上げます。", "zh": "放上大葱收尾。"},
            ],
        },
    ],

    # ── 중식 추가 ────────────────────────────────────────────────
    "chinese/noodle": [
        {
            "id": "chow-mein",
            "name": {"ko": "볶음면 (차오미엔)", "en": "Chow Mein", "ja": "チャーメン", "zh": "炒面"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "굵은 면을 채소와 함께 센불에서 볶는 중식 볶음면", "en": "Thick noodles stir-fried with vegetables over high heat", "ja": "太麺を野菜と一緒に強火で炒める中華炒め麺", "zh": "粗面条与蔬菜在大火中爆炒的中式炒面"},
            "ingredients": [
                {"name": "중화면 (볶음용)", "amount": "2인분"},
                {"name": "숙주나물", "amount": "한 줌"},
                {"name": "양파·당근", "amount": "각 1/4개"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "식용유", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "면을 삶아 찬물에 헹군 뒤 기름을 살짝 버무려 놓아요.", "en": "Boil noodles, rinse cold, toss with a little oil to prevent sticking.", "ja": "麺を茹でて冷水でよく洗い、くっつかないよう油を少し和えます。", "zh": "将面条煮熟，用冷水冲洗，拌入少量油防粘。"},
                {"ko": "채소를 채 썰어요.", "en": "Julienne all vegetables.", "ja": "野菜を千切りにします。", "zh": "将所有蔬菜切丝。"},
                {"ko": "센불 팬에 기름 두르고 채소를 빠르게 볶아요.", "en": "Stir-fry vegetables quickly over high heat.", "ja": "強火のフライパンに油を引き、野菜を素早く炒めます。", "zh": "大火锅中倒油，快速翻炒蔬菜。"},
                {"ko": "면을 넣고 간장·굴소스를 넣어 센불에서 골고루 볶아요.", "en": "Add noodles with soy sauce and oyster sauce; toss over high heat.", "ja": "麺を加え、醤油・オイスターソースを入れて強火で全体に炒めます。", "zh": "加入面条，放入酱油和蚝油，大火翻炒均匀。"},
                {"ko": "참기름을 뿌리고 마무리해요.", "en": "Finish with sesame oil.", "ja": "ごま油をかけて仕上げます。", "zh": "淋上芝麻油收尾。"},
            ],
        },
        {
            "id": "wonton-soup",
            "name": {"ko": "완탕면", "en": "Wonton Noodle Soup", "ja": "ワンタン麺", "zh": "云吞面"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "부드러운 완탕과 맑은 국물의 홍콩식 면 요리", "en": "Silky wontons in a clear, delicate Hong Kong-style broth", "ja": "なめらかなワンタンと澄んだスープの香港式麺料理", "zh": "嫩滑云吞配清澈汤底的香港风味面食"},
            "ingredients": [
                {"name": "완탕피", "amount": "15장"},
                {"name": "새우+돼지고기 (다진 것)", "amount": "각 50g"},
                {"name": "중화면", "amount": "1인분"},
                {"name": "닭육수", "amount": "3컵"},
                {"name": "간장·참기름·소금", "amount": "약간씩"},
                {"name": "생강 (다진 것)", "amount": "1/2작은술"},
            ],
            "steps": [
                {"ko": "다진 새우·돼지고기·생강·간장·참기름을 섞어 소를 만들어요.", "en": "Mix minced shrimp, pork, ginger, soy sauce, and sesame oil for filling.", "ja": "刻んだえび・豚肉・しょうが・醤油・ごま油を混ぜて餡を作ります。", "zh": "将虾仁碎、猪肉、姜、酱油、芝麻油混合制成馅料。"},
                {"ko": "완탕피에 소를 넣고 삼각형으로 접어 끝을 붙여요.", "en": "Fold wonton wrappers into triangles, sealing the edges tightly.", "ja": "ワンタン皮に餡を包んで三角形に折り、端をしっかり閉じます。", "zh": "在云吞皮中放馅，折成三角形，将边缘捏紧。"},
                {"ko": "끓는 물에 완탕을 넣어 떠오르면 2분 더 삶아요.", "en": "Boil wontons until they float, then 2 more minutes.", "ja": "沸騰したお湯でワンタンを茹で、浮いてきたらさらに2分茹でます。", "zh": "将云吞放入沸水中煮，浮起后再煮2分钟。"},
                {"ko": "닭육수를 끓여 소금·간장으로 간해요.", "en": "Bring chicken broth to a boil and season with salt and soy sauce.", "ja": "鶏がらスープを煮立て、塩・醤油で味を整えます。", "zh": "将鸡汤煮沸，用盐和酱油调味。"},
                {"ko": "그릇에 삶은 면·완탕을 담고 육수를 부어요.", "en": "Place noodles and wontons in bowl; pour broth over.", "ja": "丼に茹でた麺とワンタンを盛り付け、スープを注ぎます。", "zh": "将煮好的面条和云吞放入碗中，倒入汤汁。"},
            ],
        },
    ],
    "chinese/rice": [
        {
            "id": "yangzhou-rice",
            "name": {"ko": "양저우볶음밥", "en": "Yangzhou Fried Rice", "ja": "揚州チャーハン", "zh": "扬州炒饭"},
            "time": 20, "difficulty": 2,
            "desc": {"ko": "새우·햄·완두콩이 어우러진 화려한 중국식 볶음밥", "en": "The classic Chinese fried rice with shrimp, ham, and peas", "ja": "エビ・ハム・グリーンピースが調和した華やかな中国式炒飯", "zh": "虾仁、火腿、豌豆齐聚的华丽中式炒饭"},
            "ingredients": [
                {"name": "밥 (찬밥)", "amount": "1공기"},
                {"name": "새우", "amount": "5마리"},
                {"name": "햄", "amount": "40g"},
                {"name": "완두콩", "amount": "2큰술"},
                {"name": "계란", "amount": "2개"},
                {"name": "대파", "amount": "1/4대"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "새우·햄을 작게 썰어요.", "en": "Dice shrimp and ham small.", "ja": "えびとハムを小さく刻みます。", "zh": "将虾仁和火腿切小丁。"},
                {"ko": "센불 팬에 기름 두르고 계란을 스크램블해 꺼내요.", "en": "Scramble eggs in very hot oiled pan; set aside.", "ja": "強火の油を引いたフライパンで卵をスクランブルして取り出します。", "zh": "在大火热油锅中将鸡蛋炒散后取出备用。"},
                {"ko": "같은 팬에 새우·햄·완두콩을 볶아요.", "en": "Stir-fry shrimp, ham, and peas in same pan.", "ja": "同じフライパンでえび・ハム・グリーンピースを炒めます。", "zh": "在同一锅中翻炒虾仁、火腿和豌豆。"},
                {"ko": "찬밥을 넣고 센불에서 눌러가며 볶아요. 찬밥이 낱알이 더 잘 살아요.", "en": "Add cold rice and stir-fry over high heat, pressing firmly. Cold rice fries better.", "ja": "冷ごはんを入れ、強火で押しながら炒めます。冷ごはんの方が粒が立ちます。", "zh": "加入冷饭，大火边按压边翻炒。冷饭炒出来粒粒分明。"},
                {"ko": "계란을 다시 넣고 간장·소금으로 간해요.", "en": "Return eggs and season with soy sauce and salt.", "ja": "卵を戻し、醤油・塩で味を整えます。", "zh": "将鸡蛋倒回锅中，用酱油和盐调味。"},
            ],
        },
        {
            "id": "claypot-rice",
            "name": {"ko": "라프메이판 (소시지 솥밥)", "en": "Lap Mei Fan (Sausage Clay Pot Rice)", "ja": "臘味飯", "zh": "腊味饭"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "중국식 소시지와 함께 솥에서 지은 향기로운 밥", "en": "Aromatic rice cooked with Chinese sausage in a pot", "ja": "中国式ソーセージと一緒に炊いた香り豊かなご飯", "zh": "与腊肠一起煮出的香气四溢的米饭"},
            "ingredients": [
                {"name": "쌀", "amount": "1컵"},
                {"name": "중국식 소시지 (라장)", "amount": "2개"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "굴소스", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "쌀을 씻어 30분 불려요.", "en": "Wash rice and soak 30 minutes.", "ja": "米を洗って30分浸水させます。", "zh": "将米洗净后浸泡30分钟。"},
                {"ko": "두꺼운 냄비에 쌀+물(1:1.2)을 넣고 끓여요.", "en": "Add rice and water (1:1.2 ratio) to a heavy pot; bring to a boil.", "ja": "厚手の鍋に米と水（1:1.2）を入れて煮立てます。", "zh": "将米和水（比例1:1.2）放入厚底锅中煮沸。"},
                {"ko": "끓어오르면 약불로 줄이고 뚜껑 덮어 10분 뜸 들여요.", "en": "Reduce to low, cover, and steam 10 minutes.", "ja": "沸騰したら弱火にして蓋をし、10分蒸らします。", "zh": "沸腾后转小火，盖上锅盖焖10分钟。"},
                {"ko": "소시지를 얇게 썰어 밥 위에 올리고 5분 더 뜸 들여요.", "en": "Slice sausage and arrange on rice; steam 5 more minutes.", "ja": "ソーセージを薄く切ってご飯の上に並べ、さらに5分蒸らします。", "zh": "将香肠切薄片放在饭上，再焖5分钟。"},
                {"ko": "간장·굴소스·참기름을 섞어 뿌리고 쪽파를 올려요.", "en": "Mix soy sauce, oyster sauce, and sesame oil; drizzle over and top with green onion.", "ja": "醤油・オイスターソース・ごま油を混ぜてかけ、ネギを乗せます。", "zh": "将酱油、蚝油、芝麻油混合淋上，撒上小葱。"},
            ],
        },
    ],
    "chinese/stirfry": [
        {
            "id": "chive-pork",
            "name": {"ko": "부추잡채", "en": "Pork with Garlic Chives", "ja": "ニラと豚肉の炒め物", "zh": "韭菜炒肉"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "부추 향기와 돼지고기의 조합, 술안주로도 최고", "en": "Fragrant garlic chives with pork — great with rice or beer", "ja": "ニラの香りと豚肉の組み合わせ、おつまみにも最高", "zh": "韭菜香气与猪肉的组合，佐酒下饭两相宜"},
            "ingredients": [
                {"name": "부추", "amount": "1단"},
                {"name": "돼지고기 (앞다리살)", "amount": "120g"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "굴소스", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "돼지고기를 얇게 채 썰어 간장으로 밑간해요.", "en": "Slice pork thin; marinate with soy sauce.", "ja": "豚肉を薄く千切りにして醤油で下味を付けます。", "zh": "将猪肉切薄丝，用酱油腌制。"},
                {"ko": "부추는 5cm 길이로 잘라요.", "en": "Cut chives into 5cm pieces.", "ja": "ニラを5cmの長さに切ります。", "zh": "将韭菜切成5cm长段。"},
                {"ko": "센불 팬에 기름 두르고 마늘→돼지고기 순으로 볶아요.", "en": "Stir-fry garlic then pork in a very hot oiled pan.", "ja": "強火のフライパンに油を引き、にんにく→豚肉の順に炒めます。", "zh": "大火热油锅中依次翻炒蒜末和猪肉。"},
                {"ko": "부추를 넣고 굴소스를 더해 1분만 센불에서 빠르게 볶아요. 오래 볶으면 숨이 죽어요.", "en": "Add chives and oyster sauce; stir-fry just 1 minute over high heat. Overcooking wilts them.", "ja": "ニラを加えてオイスターソースを入れ、強火で1分だけ素早く炒めます。炒め過ぎると萎れてしまいます。", "zh": "加入韭菜和蚝油，大火快炒仅1分钟。炒太久会软烂。"},
                {"ko": "참기름을 뿌려 마무리해요.", "en": "Drizzle sesame oil and serve.", "ja": "ごま油をかけて仕上げます。", "zh": "淋上芝麻油收尾。"},
            ],
        },
        {
            "id": "kung-pao-chicken",
            "name": {"ko": "궁보기정 (쿵파오 치킨)", "en": "Kung Pao Chicken", "ja": "宮保鶏丁", "zh": "宫保鸡丁"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "얼얼하고 달콤한 사천식 닭고기 볶음", "en": "Sichuan classic — spicy, sweet, and numbing", "ja": "しびれるように甘い四川式鶏肉炒め", "zh": "麻辣甜香的四川风味炒鸡丁"},
            "ingredients": [
                {"name": "닭가슴살", "amount": "200g"},
                {"name": "땅콩", "amount": "3큰술"},
                {"name": "건고추", "amount": "4개"},
                {"name": "화자오 (산초, 선택)", "amount": "1/2작은술"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "전분", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "닭을 2cm 큐브로 썰어 간장·전분으로 밑간해요.", "en": "Dice chicken into 2cm cubes; marinate with soy sauce and starch.", "ja": "鶏肉を2cmの角切りにして醤油と片栗粉で下味を付けます。", "zh": "将鸡肉切成2cm方块，用酱油和淀粉腌制。"},
                {"ko": "간장·식초·설탕·전분을 섞어 소스를 만들어요.", "en": "Mix soy sauce, vinegar, sugar, and starch for the sauce.", "ja": "醤油・酢・砂糖・片栗粉を混ぜてソースを作ります。", "zh": "将酱油、醋、糖、淀粉混合制成酱汁。"},
                {"ko": "팬에 기름 두르고 화자오·건고추를 볶아 향을 내요.", "en": "Stir-fry Sichuan pepper and dried chilies until fragrant.", "ja": "フライパンに油を引き、花椒と乾燥唐辛子を炒めて香りを出します。", "zh": "锅中倒油，翻炒花椒和干辣椒出香气。"},
                {"ko": "닭을 넣고 익혀요.", "en": "Add chicken and cook through.", "ja": "鶏肉を入れて火が通るまで炒めます。", "zh": "加入鸡肉炒至熟透。"},
                {"ko": "소스를 넣어 빠르게 볶고 땅콩을 넣어 마무리해요.", "en": "Pour in sauce and toss quickly; add peanuts to finish.", "ja": "ソースを入れて素早く炒め、ピーナッツを加えて仕上げます。", "zh": "倒入酱汁快速翻炒，加入花生收尾。"},
            ],
        },
    ],
    "chinese/soup": [
        {
            "id": "hot-sour-soup",
            "name": {"ko": "산라탕 (신 매운 수프)", "en": "Hot and Sour Soup", "ja": "酸辣湯", "zh": "酸辣汤"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "새콤하고 매콤한 중식 대표 수프, 후추가 핵심", "en": "Tangy and spicy — black pepper gives this soup its kick", "ja": "酸っぱくて辛い中華の代表スープ、黒コショウが命", "zh": "酸辣兼具的中式代表汤品，黑胡椒是关键"},
            "ingredients": [
                {"name": "두부", "amount": "1/4모"},
                {"name": "목이버섯 (건조)", "amount": "5g"},
                {"name": "죽순 (시판)", "amount": "50g"},
                {"name": "계란", "amount": "1개"},
                {"name": "닭육수", "amount": "2.5컵"},
                {"name": "식초", "amount": "2큰술"},
                {"name": "간장", "amount": "1큰술"},
                {"name": "전분", "amount": "1.5큰술"},
                {"name": "흑후추", "amount": "넉넉히"},
            ],
            "steps": [
                {"ko": "목이버섯을 물에 불려 얇게 썰고, 두부·죽순도 채 썰어요.", "en": "Soak wood ear mushrooms; julienne mushrooms, tofu, and bamboo shoots.", "ja": "きくらげを水で戻して薄く切り、豆腐と筍も千切りにします。", "zh": "将木耳泡发切薄丝，豆腐和竹笋也切丝。"},
                {"ko": "육수를 끓이고 채소를 넣어 2분 익혀요.", "en": "Bring broth to a boil; add vegetables and cook 2 minutes.", "ja": "スープを煮立て、野菜を入れて2分加熱します。", "zh": "将高汤煮沸，加入蔬菜煮2分钟。"},
                {"ko": "간장·식초를 넣고 전분물로 걸쭉하게 만들어요.", "en": "Add soy sauce and vinegar; thicken with starch slurry.", "ja": "醤油と酢を加え、水溶き片栗粉でとろみをつけます。", "zh": "加入酱油和醋，用水淀粉勾芡使其浓稠。"},
                {"ko": "계란을 풀어 가느다랗게 부어요.", "en": "Drizzle beaten egg in thin streams.", "ja": "溶き卵を細く流し入れます。", "zh": "将打散的鸡蛋细细淋入。"},
                {"ko": "흑후추를 넉넉히 갈아 넣어요. 후추가 이 수프의 핵심이에요.", "en": "Grind plenty of black pepper over. Pepper is this soup's soul.", "ja": "黒こしょうをたっぷりひきます。こしょうがこのスープの命です。", "zh": "大量研磨黑胡椒加入。胡椒是这道汤的灵魂。"},
            ],
        },
        {
            "id": "winter-melon-soup",
            "name": {"ko": "동과탕 (동아 수프)", "en": "Winter Melon Soup", "ja": "冬瓜スープ", "zh": "冬瓜汤"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "부드럽고 담백한 중국 가정식 수프", "en": "Mild, delicate Chinese home-style soup", "ja": "なめらかであっさりとした中国家庭料理のスープ", "zh": "顺滑清淡的中国家常汤"},
            "ingredients": [
                {"name": "동아 (동과)", "amount": "300g"},
                {"name": "돼지고기 또는 닭고기", "amount": "100g"},
                {"name": "생강", "amount": "2쪽"},
                {"name": "물 또는 육수", "amount": "3컵"},
                {"name": "소금·참기름", "amount": "약간씩"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "동아의 껍질을 벗기고 2cm로 깍둑썰어요.", "en": "Peel winter melon and cut into 2cm cubes.", "ja": "冬瓜の皮を剥いて2cmの角切りにします。", "zh": "将冬瓜去皮切成2cm方块。"},
                {"ko": "고기를 얇게 썰어요.", "en": "Slice meat thinly.", "ja": "肉を薄く切ります。", "zh": "将肉切薄片。"},
                {"ko": "냄비에 물·생강을 넣고 끓이다가 고기를 먼저 익혀요.", "en": "Bring water and ginger to a boil; cook meat first.", "ja": "鍋に水と生姜を入れて煮立て、まず肉を火が通るまで煮ます。", "zh": "锅中加水和姜煮沸，先将肉煮熟。"},
                {"ko": "동아를 넣고 투명해질 때까지 10분 끓여요.", "en": "Add winter melon and simmer 10 minutes until translucent.", "ja": "冬瓜を加えて透明になるまで10分煮ます。", "zh": "加入冬瓜，煮10分钟直至透明。"},
                {"ko": "소금·참기름으로 간하고 쪽파를 올려요.", "en": "Season with salt and sesame oil; garnish with green onion.", "ja": "塩・ごま油で味を整え、ネギを乗せます。", "zh": "用盐和芝麻油调味，撒上小葱。"},
            ],
        },
    ],
    "chinese/dim": [
        {
            "id": "har-gow",
            "name": {"ko": "하가우 (새우만두)", "en": "Har Gow", "ja": "エビ餃子", "zh": "虾饺"},
            "time": 50, "difficulty": 3,
            "desc": {"ko": "반투명한 피가 특징인 홍콩식 딤섬의 꽃", "en": "The crown jewel of Hong Kong dim sum — translucent skin", "ja": "半透明の皮が特徴の香港式点心の花形", "zh": "半透明外皮为特色的香港点心之冠"},
            "ingredients": [
                {"name": "밀전분 (전분+밀가루)", "amount": "80g+20g"},
                {"name": "끓는 물", "amount": "100ml"},
                {"name": "새우", "amount": "150g"},
                {"name": "죽순 (다진 것)", "amount": "30g"},
                {"name": "참기름·소금·설탕", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "밀전분+밀가루에 끓는 물을 부어 반죽해요. 잘 치대야 해요.", "en": "Pour boiling water over starch and flour; knead well.", "ja": "でんぷんと薄力粉に熱湯を注いで生地をこねます。よくこねることが大切です。", "zh": "将沸水倒入淀粉和面粉中，充分揉成面团。"},
                {"ko": "새우는 다져서 죽순·양념과 섞어 소를 만들어요.", "en": "Mince shrimp; mix with bamboo shoots and seasonings.", "ja": "えびを刻んで筍・調味料と混ぜて餡を作ります。", "zh": "将虾仁剁碎，与竹笋和调味料混合制成馅料。"},
                {"ko": "반죽을 얇게 밀어 원형으로 잘라요.", "en": "Roll dough very thin and cut into circles.", "ja": "生地を薄く伸ばして丸く切ります。", "zh": "将面团擀薄，切成圆形。"},
                {"ko": "소를 넣고 주름을 7-9개 잡아 반달 모양으로 빚어요.", "en": "Fill and pleat into crescent shape with 7-9 folds.", "ja": "餡を包んで7〜9枚のひだを作り、三日月形に包みます。", "zh": "包入馅料，捏出7-9个褶皱，做成月牙形。"},
                {"ko": "찜기에 넣고 센불로 7-8분 쪄요.", "en": "Steam over high heat 7-8 minutes.", "ja": "蒸し器に入れて強火で7〜8分蒸します。", "zh": "放入蒸锅，大火蒸7-8分钟。"},
            ],
        },
        {
            "id": "egg-tart",
            "name": {"ko": "에그 타르트 (단타)", "en": "Egg Tart", "ja": "エッグタルト", "zh": "蛋挞"},
            "time": 45, "difficulty": 2,
            "desc": {"ko": "바삭한 타르트 껍질과 부드러운 커스터드, 홍콩 길거리 간식", "en": "Flaky pastry with silky egg custard — a Hong Kong classic", "ja": "サクサクのタルト生地と滑らかなカスタード、香港の街角おやつ", "zh": "酥脆挞皮配顺滑蛋奶冻，香港街头经典小吃"},
            "ingredients": [
                {"name": "시판 타르트 반죽 또는 파이지", "amount": "1팩"},
                {"name": "계란", "amount": "2개"},
                {"name": "설탕", "amount": "50g"},
                {"name": "우유", "amount": "150ml"},
                {"name": "바닐라 에센스", "amount": "1/4작은술"},
            ],
            "steps": [
                {"ko": "오븐을 190°C로 예열해요.", "en": "Preheat oven to 190°C.", "ja": "オーブンを190°Cに予熱します。", "zh": "将烤箱预热至190°C。"},
                {"ko": "타르트 반죽을 틀에 맞게 잘라 넣고 포크로 찍어요.", "en": "Press pastry into tart molds and prick with a fork.", "ja": "タルト生地を型に合わせて切って入れ、フォークで刺します。", "zh": "将挞皮剪成合适大小放入模具，用叉子戳孔。"},
                {"ko": "계란·설탕·우유·바닐라를 섞어 체에 걸러 커스터드를 만들어요.", "en": "Mix eggs, sugar, milk, and vanilla; strain for smooth custard.", "ja": "卵・砂糖・牛乳・バニラを混ぜてこし、滑らかなカスタードを作ります。", "zh": "将鸡蛋、糖、牛奶、香草混合后过筛，制成顺滑的蛋奶冻。"},
                {"ko": "타르트 껍질에 80%만 채워요.", "en": "Fill tart shells only 80% to prevent overflow.", "ja": "タルトシェルに80%だけ充填します。あふれるのを防ぐためです。", "zh": "将蛋液只填至挞壳的80%，防止溢出。"},
                {"ko": "190°C에서 20분 구워요. 커스터드가 살짝 흔들리면 OK.", "en": "Bake at 190°C for 20 minutes. Custard should jiggle slightly when done.", "ja": "190°Cで20分焼きます。カスタードが少し揺れていればOKです。", "zh": "190°C烤20分钟。蛋奶冻稍微晃动即可。"},
            ],
        },
    ],

    # ── 양식 추가 ────────────────────────────────────────────────
    "western/pasta": [
        {
            "id": "vongole",
            "name": {"ko": "봉골레 파스타", "en": "Spaghetti alle Vongole", "ja": "ボンゴレパスタ", "zh": "蛤蜊意面"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "조개의 바다향이 올리브오일에 녹아드는 이탈리안 클래식", "en": "Clam broth meets olive oil in this Italian seaside classic", "ja": "貝の海の香りがオリーブオイルに溶け込むイタリアンクラシック", "zh": "蛤蜊海鲜味融入橄榄油的意大利经典料理"},
            "ingredients": [
                {"name": "스파게티 면", "amount": "100g"},
                {"name": "모시조개 또는 바지락", "amount": "200g"},
                {"name": "마늘", "amount": "4쪽"},
                {"name": "올리브오일", "amount": "4큰술"},
                {"name": "화이트와인 (선택)", "amount": "1/4컵"},
                {"name": "건고추", "amount": "1개"},
                {"name": "파슬리", "amount": "약간"},
            ],
            "steps": [
                {"ko": "조개를 소금물에 1시간 해감해요.", "en": "Soak clams in salted water for 1 hour to purge sand.", "ja": "あさりを塩水に1時間浸けて砂を吐かせます。", "zh": "将蛤蜊在盐水中浸泡1小时去沙。"},
                {"ko": "면을 삶아요. 면수는 꼭 보관하세요.", "en": "Cook pasta; reserve pasta water.", "ja": "パスタを茹でます。茹で汁は必ず取っておいてください。", "zh": "将意面煮熟。一定要保留面汤。"},
                {"ko": "팬에 올리브오일·마늘·고추를 약불에서 볶아요.", "en": "Warm olive oil, garlic, and chili over low heat.", "ja": "フライパンにオリーブオイル・にんにく・唐辛子を弱火で炒めます。", "zh": "锅中用小火加热橄榄油、蒜末和辣椒。"},
                {"ko": "조개와 와인을 넣고 뚜껑 덮어 조개가 입을 벌릴 때까지 쪄요.", "en": "Add clams and wine; cover until clams open.", "ja": "あさりとワインを加えて蓋をし、貝が開くまで蒸します。", "zh": "加入蛤蜊和白葡萄酒，盖上锅盖蒸至贝壳打开。"},
                {"ko": "면과 면수 4큰술을 넣고 버무려 파슬리를 뿌려요.", "en": "Add pasta with 4 tbsp pasta water; toss and top with parsley.", "ja": "麺と茹で汁大さじ4を入れて和え、パセリをかけます。", "zh": "加入意面和4大勺面汤拌匀，撒上欧芹。"},
            ],
        },
        {
            "id": "mushroom-cream-pasta",
            "name": {"ko": "버섯 크림파스타", "en": "Mushroom Cream Pasta", "ja": "きのこクリームパスタ", "zh": "奶油蘑菇意面"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "버섯의 깊은 풍미가 살아있는 크리미한 파스타", "en": "Rich cream sauce with deep mushroom flavor", "ja": "キノコの深い風味が生きたクリーミーなパスタ", "zh": "蘑菇深厚风味与奶油酱汁完美融合的意面"},
            "ingredients": [
                {"name": "펜네 또는 링귀네", "amount": "100g"},
                {"name": "양송이버섯", "amount": "100g"},
                {"name": "생크림", "amount": "150ml"},
                {"name": "마늘", "amount": "2쪽"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "파마산 치즈", "amount": "3큰술"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "버섯은 슬라이스, 양파·마늘은 다져요.", "en": "Slice mushrooms; mince onion and garlic.", "ja": "きのこをスライスし、玉ねぎとにんにくを刻みます。", "zh": "将蘑菇切片，洋葱和蒜切碎。"},
                {"ko": "버터에 양파·마늘을 볶다가 버섯을 넣어 수분이 날아갈 때까지 볶아요.", "en": "Sauté onion and garlic in butter; add mushrooms and cook until dry.", "ja": "バターで玉ねぎとにんにくを炒め、きのこを加えて水分が飛ぶまで炒めます。", "zh": "用黄油炒洋葱和蒜，加入蘑菇炒至水分蒸发。"},
                {"ko": "생크림을 붓고 2-3분 졸여요.", "en": "Add cream and simmer 2-3 minutes.", "ja": "生クリームを注いで2〜3分煮詰めます。", "zh": "加入生奶油，炖煮2-3分钟。"},
                {"ko": "삶은 면과 면수 2큰술을 넣고 버무려요.", "en": "Add drained pasta and 2 tbsp pasta water; toss.", "ja": "茹でた麺と茹で汁大さじ2を入れて和えます。", "zh": "加入煮好的意面和2大勺面汤拌匀。"},
                {"ko": "파마산 치즈·소금·후추로 간을 맞춰요.", "en": "Season with parmesan, salt, and pepper.", "ja": "パルメザンチーズ・塩・こしょうで味を整えます。", "zh": "用帕玛森芝士、盐和胡椒调味。"},
            ],
        },
    ],
    "western/meat": [
        {
            "id": "meatballs",
            "name": {"ko": "미트볼 토마토 소스", "en": "Meatballs in Tomato Sauce", "ja": "ミートボールトマトソース", "zh": "番茄肉丸"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "부드럽고 촉촉한 미트볼에 진한 토마토 소스", "en": "Juicy meatballs simmered in rich tomato sauce", "ja": "柔らかくしっとりしたミートボールに濃厚トマトソース", "zh": "软嫩多汁的肉丸配浓郁番茄酱"},
            "ingredients": [
                {"name": "소·돼지 혼합 다짐육", "amount": "250g"},
                {"name": "빵가루", "amount": "3큰술"},
                {"name": "계란", "amount": "1개"},
                {"name": "파마산 치즈 가루", "amount": "2큰술"},
                {"name": "홀토마토 캔", "amount": "1/2캔"},
                {"name": "마늘", "amount": "2쪽"},
                {"name": "올리브오일", "amount": "2큰술"},
                {"name": "바질·소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "다짐육·빵가루·계란·치즈·소금·후추를 잘 치대어요.", "en": "Mix ground meat, breadcrumbs, egg, cheese, salt, and pepper well.", "ja": "ひき肉・パン粉・卵・チーズ・塩・こしょうをよく混ぜてこねます。", "zh": "将肉末、面包屑、鸡蛋、芝士、盐和胡椒充分混合。"},
                {"ko": "3cm 크기로 동그랗게 빚어요.", "en": "Roll into 3cm balls.", "ja": "3cmの大きさに丸めます。", "zh": "团成3cm大小的圆球。"},
                {"ko": "팬에 올리브오일 두르고 미트볼 겉면을 굴리며 갈색으로 구워요.", "en": "Sear meatballs in olive oil until browned on all sides.", "ja": "フライパンにオリーブオイルを引き、ミートボールを転がしながら全面を焼き色がつくまで焼きます。", "zh": "锅中倒橄榄油，将肉丸滚动煎至四面金黄。"},
                {"ko": "마늘을 볶고 홀토마토를 으깨 넣어 소스를 만들어요.", "en": "Add garlic and crushed tomatoes to make sauce.", "ja": "にんにくを炒め、ホールトマトを潰して加えてソースを作ります。", "zh": "翻炒蒜末，加入压碎的整粒番茄制成酱汁。"},
                {"ko": "미트볼을 넣고 15분 약불에서 함께 끓여요.", "en": "Add meatballs and simmer together 15 minutes.", "ja": "ミートボールを加えて弱火で15分一緒に煮ます。", "zh": "加入肉丸，小火一起炖煮15分钟。"},
            ],
        },
        {
            "id": "pork-chop",
            "name": {"ko": "포크찹 (두꺼운 돼지목살 구이)", "en": "Pork Chop", "ja": "ポークチョップ", "zh": "猪排"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "두껍게 썬 돼지목살을 겉은 바삭, 속은 촉촉하게", "en": "Thick pork chop — crispy outside, juicy inside", "ja": "厚切り豚首肉を外はカリカリ、中はしっとりに", "zh": "厚切猪颈肉，外酥里嫩"},
            "ingredients": [
                {"name": "돼지목살 (2cm 두께)", "amount": "1장"},
                {"name": "소금·후추", "amount": "넉넉히"},
                {"name": "마늘 가루", "amount": "1/2작은술"},
                {"name": "로즈마리", "amount": "1줄기"},
                {"name": "버터", "amount": "1큰술"},
                {"name": "식용유", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "고기를 실온에 20분 꺼내 소금·후추·마늘가루를 뿌려요.", "en": "Rest pork at room temperature 20 minutes; season with salt, pepper, and garlic powder.", "ja": "豚肉を室温に20分出して塩・こしょう・ガーリックパウダーをふります。", "zh": "将猪肉在室温放置20分钟，撒上盐、胡椒和蒜粉。"},
                {"ko": "팬을 강불로 달궈 기름을 두르고 고기를 올려요.", "en": "Heat pan with oil over high heat; place pork chop.", "ja": "フライパンを強火に熱して油を引き、肉を乗せます。", "zh": "将平底锅大火加热倒油，放入猪肉。"},
                {"ko": "한 면 3분 씩 구워요. 자꾸 뒤집지 마세요.", "en": "Cook 3 minutes per side. Don't keep flipping.", "ja": "片面3分ずつ焼きます。何度も裏返さないでください。", "zh": "每面煎3分钟。不要频繁翻面。"},
                {"ko": "버터와 로즈마리를 넣고 베이스팅하며 1분 더 구워요.", "en": "Add butter and rosemary; baste for 1 more minute.", "ja": "バターとローズマリーを加え、バスティングしながら1分さらに焼きます。", "zh": "加入黄油和迷迭香，淋油烘烤再1分钟。"},
                {"ko": "3분 휴지 후 서빙해요.", "en": "Rest 3 minutes before serving.", "ja": "3分休ませてから盛り付けます。", "zh": "静置3分钟后再上桌。"},
            ],
        },
    ],
    "western/salad": [
        {
            "id": "caprese",
            "name": {"ko": "카프레제", "en": "Caprese Salad", "ja": "カプレーゼ", "zh": "卡普里沙拉"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "모짜렐라·토마토·바질의 이탈리아 3색 샐러드", "en": "Italian tricolor of mozzarella, tomato, and basil", "ja": "モッツァレラ・トマト・バジルのイタリア3色サラダ", "zh": "马苏里拉、番茄、罗勒的意大利三色沙拉"},
            "ingredients": [
                {"name": "생모짜렐라 치즈", "amount": "125g"},
                {"name": "토마토", "amount": "1개"},
                {"name": "생바질", "amount": "한 줌"},
                {"name": "엑스트라버진 올리브오일", "amount": "2큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "발사믹 글레이즈 (선택)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "모짜렐라와 토마토를 1cm 두께로 슬라이스해요.", "en": "Slice mozzarella and tomato 1cm thick.", "ja": "モッツァレラとトマトを1cmの厚さにスライスします。", "zh": "将马苏里拉奶酪和番茄切成1cm厚片。"},
                {"ko": "접시에 번갈아 가며 예쁘게 올려요.", "en": "Arrange alternately on a plate.", "ja": "交互に美しく皿に並べます。", "zh": "交替摆放在盘子上。"},
                {"ko": "바질 잎을 사이사이에 끼워요.", "en": "Tuck basil leaves between the slices.", "ja": "バジルの葉をスライスの間に挟みます。", "zh": "将罗勒叶夹在切片之间。"},
                {"ko": "올리브오일을 뿌리고 소금·후추를 갈아요.", "en": "Drizzle olive oil and season with salt and pepper.", "ja": "オリーブオイルをかけ、塩・こしょうを挽きます。", "zh": "淋上橄榄油，研磨盐和胡椒。"},
                {"ko": "발사믹 글레이즈를 살짝 뿌리면 더 고급스러워요.", "en": "A drizzle of balsamic glaze makes it extra elegant.", "ja": "バルサミコグレーズを少しかけるとより上品になります。", "zh": "淋上少许香醋糖浆会更显高档。"},
            ],
        },
        {
            "id": "coleslaw",
            "name": {"ko": "코울슬로", "en": "Coleslaw", "ja": "コールスロー", "zh": "卷心菜沙拉"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "아삭하고 새콤달콤한 양배추 샐러드, 프라이드치킨 단짝", "en": "Crisp, tangy slaw — perfect alongside fried chicken", "ja": "シャキシャキ甘酸っぱいキャベツサラダ、フライドチキンの相棒", "zh": "爽脆酸甜的卷心菜沙拉，炸鸡的最佳拍档"},
            "ingredients": [
                {"name": "양배추", "amount": "1/4개"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "마요네즈", "amount": "3큰술"},
                {"name": "식초", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "양배추·당근을 얇게 채 썰어요.", "en": "Shred cabbage and carrot very thin.", "ja": "キャベツとにんじんを薄く千切りにします。", "zh": "将卷心菜和胡萝卜切细丝。"},
                {"ko": "소금 1작은술을 뿌려 10분 절인 뒤 물기를 꼭 짜요.", "en": "Salt, let sit 10 minutes, then squeeze out moisture.", "ja": "塩小さじ1をふって10分置き、水気をよく絞ります。", "zh": "撒上1小勺盐腌制10分钟，然后用力挤出水分。"},
                {"ko": "마요네즈·식초·설탕·소금·후추를 섞어 드레싱을 만들어요.", "en": "Mix mayo, vinegar, sugar, salt, and pepper for dressing.", "ja": "マヨネーズ・酢・砂糖・塩・こしょうを混ぜてドレッシングを作ります。", "zh": "将蛋黄酱、醋、糖、盐和胡椒混合制成沙拉酱。"},
                {"ko": "채소에 드레싱을 넣고 버무려요.", "en": "Toss vegetables with dressing.", "ja": "野菜にドレッシングを加えて和えます。", "zh": "将沙拉酱加入蔬菜中拌匀。"},
                {"ko": "냉장고에 30분 두면 맛이 더 좋아요.", "en": "Chill 30 minutes in the fridge for best flavor.", "ja": "冷蔵庫で30分冷やすとより美味しくなります。", "zh": "放入冰箱冷藏30分钟味道更佳。"},
            ],
        },
    ],
    "western/bread": [
        {
            "id": "croque-monsieur",
            "name": {"ko": "크로크무슈", "en": "Croque Monsieur", "ja": "クロックムッシュ", "zh": "法式火腿芝士三明治"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "구운 햄 치즈 샌드위치의 프랑스 버전, 베샤멜이 핵심", "en": "The French way to do a ham and cheese — béchamel makes it", "ja": "焼いたハムチーズサンドイッチのフランス版、ベシャメルが命", "zh": "烤火腿芝士三明治的法式版本，白酱是关键"},
            "ingredients": [
                {"name": "식빵 또는 바게트 슬라이스", "amount": "2장"},
                {"name": "슬라이스 햄", "amount": "2장"},
                {"name": "그뤼에르 또는 모짜렐라 치즈", "amount": "40g"},
                {"name": "버터", "amount": "2큰술"},
                {"name": "밀가루", "amount": "1큰술"},
                {"name": "우유", "amount": "100ml"},
                {"name": "소금·후추·너트맥", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "버터·밀가루를 볶다가 우유를 부어 베샤멜 소스를 만들어요.", "en": "Cook butter and flour, whisk in milk to make béchamel.", "ja": "バターと薄力粉を炒めて牛乳を入れてホワイトソースを作ります。", "zh": "炒黄油和面粉，加入牛奶制成白酱。"},
                {"ko": "소금·후추·너트맥으로 간해요.", "en": "Season béchamel with salt, pepper, and nutmeg.", "ja": "塩・こしょう・ナツメグで味を整えます。", "zh": "用盐、胡椒和肉豆蔻调味。"},
                {"ko": "빵에 베샤멜·햄·치즈를 올려 샌드위치를 만들어요.", "en": "Spread béchamel on bread, layer ham and cheese, sandwich.", "ja": "パンにホワイトソース・ハム・チーズを重ねてサンドイッチにします。", "zh": "在面包上抹上白酱，铺上火腿和芝士，夹成三明治。"},
                {"ko": "위에도 베샤멜을 바르고 치즈를 올려요.", "en": "Spread more béchamel on top and add extra cheese.", "ja": "上にもホワイトソースを塗り、チーズを乗せます。", "zh": "在上面也抹上白酱，再放上芝士。"},
                {"ko": "230°C 오븐에서 치즈가 녹고 황금색이 될 때까지 5-7분 구워요.", "en": "Bake at 230°C 5-7 minutes until cheese is golden and bubbly.", "ja": "230°Cのオーブンでチーズが溶けて黄金色になるまで5〜7分焼きます。", "zh": "放入230°C烤箱烤5-7分钟，直至芝士融化变成金黄色。"},
            ],
        },
        {
            "id": "pancakes",
            "name": {"ko": "아메리칸 팬케이크", "en": "American Pancakes", "ja": "アメリカンパンケーキ", "zh": "美式松饼"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "두툼하고 폭신한 미국식 팬케이크, 주말 아침 최고", "en": "Thick, fluffy pancakes — the ideal weekend breakfast", "ja": "厚くてふわふわのアメリカ式パンケーキ、週末の朝に最高", "zh": "厚实蓬松的美式松饼，周末早餐的最佳选择"},
            "ingredients": [
                {"name": "박력분", "amount": "150g"},
                {"name": "설탕", "amount": "2큰술"},
                {"name": "베이킹파우더", "amount": "1.5작은술"},
                {"name": "소금", "amount": "1/4작은술"},
                {"name": "계란", "amount": "1개"},
                {"name": "우유", "amount": "150ml"},
                {"name": "버터 (녹인 것)", "amount": "2큰술"},
            ],
            "steps": [
                {"ko": "가루류(밀가루·설탕·베이킹파우더·소금)를 섞어요.", "en": "Whisk together all dry ingredients.", "ja": "粉類（薄力粉・砂糖・ベーキングパウダー・塩）を混ぜます。", "zh": "将所有粉类材料（面粉、糖、泡打粉、盐）混合。"},
                {"ko": "계란·우유·녹인 버터를 섞어요.", "en": "Mix together egg, milk, and melted butter.", "ja": "卵・牛乳・溶かしバターを混ぜます。", "zh": "将鸡蛋、牛奶和融化的黄油混合。"},
                {"ko": "젖은 재료를 가루 재료에 넣고 살살 섞어요. 덩어리가 조금 있어도 OK.", "en": "Pour wet into dry and fold gently. A few lumps are fine.", "ja": "湿った材料を粉類に入れてそっと混ぜます。少しダマが残っていてもOKです。", "zh": "将湿性材料倒入粉类中轻轻搅拌。有少许结块也没关系。"},
                {"ko": "버터 바른 약불 팬에 국자로 떠서 부어요.", "en": "Ladle onto a lightly buttered pan over low-medium heat.", "ja": "バターを薄く塗った弱火のフライパンにお玉で注ぎます。", "zh": "用汤勺舀入抹了黄油的小火平底锅中。"},
                {"ko": "표면에 기포가 생기면 뒤집어 1분 더 구워요.", "en": "Flip when bubbles form on the surface; cook 1 more minute.", "ja": "表面に泡ができたら裏返してさらに1分焼きます。", "zh": "表面出现气泡时翻面，再煎1分钟。"},
            ],
        },
    ],
    "western/baking": [
        {
            "id": "madeleine",
            "name": {"ko": "마들렌", "en": "Madeleine", "ja": "マドレーヌ", "zh": "玛德琳"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "조개 모양 프랑스 구움 과자, 레몬향이 포인트", "en": "French shell-shaped cake with a hint of lemon", "ja": "貝殻型フランスの焼き菓子、レモンの香りがポイント", "zh": "贝壳形法式烘焙小点，柠檬香气是亮点"},
            "ingredients": [
                {"name": "박력분", "amount": "100g"},
                {"name": "버터 (녹인 것)", "amount": "90g"},
                {"name": "설탕", "amount": "90g"},
                {"name": "계란", "amount": "2개"},
                {"name": "베이킹파우더", "amount": "1/2작은술"},
                {"name": "레몬 제스트", "amount": "1/2개분"},
                {"name": "꿀", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "계란·설탕·꿀을 잘 섞어요.", "en": "Beat eggs, sugar, and honey together well.", "ja": "卵・砂糖・はちみつをよく混ぜます。", "zh": "将鸡蛋、糖和蜂蜜充分混合。"},
                {"ko": "체 친 밀가루·베이킹파우더를 넣고 섞어요.", "en": "Fold in sifted flour and baking powder.", "ja": "ふるった薄力粉とベーキングパウダーを入れて混ぜます。", "zh": "加入过筛的面粉和泡打粉搅拌。"},
                {"ko": "녹인 버터와 레몬 제스트를 넣어요.", "en": "Add melted butter and lemon zest.", "ja": "溶かしバターとレモンゼストを加えます。", "zh": "加入融化的黄油和柠檬皮碎。"},
                {"ko": "반죽을 냉장고에 30분 휴지시켜요. 이 단계가 볼록 솟은 배꼽을 만들어요.", "en": "Rest batter in the fridge 30 minutes — this creates the signature hump.", "ja": "生地を冷蔵庫で30分休ませます。このステップが特徴的なふっくら出っ張りを作ります。", "zh": "将面糊放入冰箱静置30分钟。这一步是形成标志性隆起的关键。"},
                {"ko": "버터 바른 틀에 80% 채워 190°C에서 12분 구워요.", "en": "Fill buttered molds 80%; bake at 190°C for 12 minutes.", "ja": "バターを塗った型に80%充填し、190°Cで12分焼きます。", "zh": "在抹了黄油的模具中填入80%，190°C烤12分钟。"},
            ],
        },
    ],

    # ── 일식 추가 ────────────────────────────────────────────────
    "japanese/sushi": [
        {
            "id": "maki-sushi",
            "name": {"ko": "마끼 (김초밥)", "en": "Maki Roll", "ja": "巻き寿司", "zh": "卷寿司"},
            "time": 40, "difficulty": 2,
            "desc": {"ko": "김에 밥과 재료를 돌돌 만 기본 스시", "en": "The classic nori roll — once you learn it, it's addictive", "ja": "海苔にご飯と具材を巻いた基本の寿司", "zh": "用海苔将米饭和食材卷起来的基础寿司"},
            "ingredients": [
                {"name": "스시 밥", "amount": "1공기"},
                {"name": "김 (초밥용)", "amount": "2장"},
                {"name": "오이", "amount": "1/4개"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "크래미 또는 참치캔", "amount": "50g"},
                {"name": "마요네즈", "amount": "1큰술"},
                {"name": "와사비 (선택)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "오이·당근을 길쭉하게 채 썰어요.", "en": "Cut cucumber and carrot into long thin sticks.", "ja": "きゅうりとにんじんを細長く切ります。", "zh": "将黄瓜和胡萝卜切成细长条。"},
                {"ko": "참치캔은 기름을 빼고 마요네즈와 섞어요.", "en": "Drain tuna and mix with mayo.", "ja": "ツナ缶の油を切ってマヨネーズと混ぜます。", "zh": "将金枪鱼罐头沥油，与蛋黄酱混合。"},
                {"ko": "대나무 발 위에 김을 올리고 스시 밥을 얇게 펴요. 위쪽 2cm는 남겨요.", "en": "Lay nori on bamboo mat; spread rice thinly, leaving 2cm at the top.", "ja": "巻き簾の上に海苔を置き、酢飯を薄く広げます。上部2cmは残します。", "zh": "在竹帘上铺上海苔，薄薄地铺上寿司饭。顶部留2cm空白。"},
                {"ko": "가운데에 재료를 올리고 단단히 말아요.", "en": "Place fillings in the center and roll firmly.", "ja": "中央に具材を乗せてしっかり巻きます。", "zh": "将馅料放在中央，用力卷紧。"},
                {"ko": "물에 적신 칼로 먹기 좋게 잘라요.", "en": "Slice with a wet knife.", "ja": "濡れた包丁で食べやすい大きさに切ります。", "zh": "用蘸湿的刀切成适口大小。"},
            ],
        },
        {
            "id": "inari-sushi",
            "name": {"ko": "이나리즈시 (유부초밥)", "en": "Inari Sushi", "ja": "いなり寿司", "zh": "稻荷寿司"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "달콤한 유부 안에 스시 밥을 채운 간편 초밥", "en": "Sweet tofu pockets filled with seasoned sushi rice", "ja": "甘い油揚げの中に酢飯を詰めた手軽な寿司", "zh": "甜味油豆腐袋内装满醋饭的简便寿司"},
            "ingredients": [
                {"name": "스시 밥", "amount": "1공기"},
                {"name": "유부초밥용 유부 (시판)", "amount": "10개"},
                {"name": "통깨", "amount": "약간"},
                {"name": "당근·시금치 등 나물 (선택)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "시판 유부초밥 팩은 유부와 소스가 함께 들어있어요.", "en": "Pre-packaged inari kits include seasoned tofu pockets.", "ja": "市販のいなり寿司パックには油揚げとソースが一緒に入っています。", "zh": "市售稻荷寿司套装包含油豆腐和酱汁。"},
                {"ko": "스시 밥을 지어 양념을 섞어요.", "en": "Cook and season the sushi rice.", "ja": "酢飯を炊いて調味します。", "zh": "将寿司饭煮好并调味。"},
                {"ko": "밥에 통깨를 넣어 섞어요.", "en": "Mix sesame seeds into the rice.", "ja": "ご飯に白ごまを混ぜます。", "zh": "将白芝麻拌入饭中。"},
                {"ko": "유부를 조심스럽게 열어 밥을 채워요. 너무 꽉 넣지 마세요.", "en": "Gently open each tofu pocket and fill with rice. Don't overstuff.", "ja": "油揚げをそっと開いてご飯を詰めます。詰め過ぎないように。", "zh": "轻轻打开油豆腐，填入米饭。不要填太满。"},
                {"ko": "입구를 접어 마무리해요.", "en": "Fold the opening closed.", "ja": "開口部を折って閉じます。", "zh": "将开口折叠封口。"},
            ],
        },
    ],
    "japanese/ramen": [
        {
            "id": "miso-ramen",
            "name": {"ko": "미소 라멘", "en": "Miso Ramen", "ja": "味噌ラーメン", "zh": "味噌拉面"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "된장의 깊은 감칠맛이 살아있는 진한 라멘", "en": "Rich miso broth with deep, savory complexity", "ja": "味噌の深い旨みが生きた濃厚ラーメン", "zh": "味噌深厚鲜味满溢的浓郁拉面"},
            "ingredients": [
                {"name": "생라멘 면", "amount": "1인분"},
                {"name": "닭육수", "amount": "2.5컵"},
                {"name": "미소 (된장)", "amount": "2큰술"},
                {"name": "고추장 또는 고추기름", "amount": "1작은술"},
                {"name": "마늘", "amount": "1작은술"},
                {"name": "버터", "amount": "1작은술"},
                {"name": "숙주·옥수수·버터", "amount": "토핑용"},
            ],
            "steps": [
                {"ko": "냄비에 기름 두르고 마늘을 볶아요.", "en": "Stir-fry garlic in a little oil.", "ja": "鍋に油を引いてにんにくを炒めます。", "zh": "锅中倒油翻炒蒜末。"},
                {"ko": "닭육수를 붓고 끓여요.", "en": "Add chicken broth and bring to a boil.", "ja": "鶏がらスープを注いで煮立てます。", "zh": "加入鸡汤煮沸。"},
                {"ko": "미소를 체에 걸러 풀어요. 끓이지 않아야 풍미가 살아요.", "en": "Dissolve miso through a strainer. Don't boil after adding miso.", "ja": "味噌をこし器で溶かします。味噌を加えた後は煮立てないようにしてください。", "zh": "用滤网将味噌溶化。加入味噌后不要再沸腾，以保留风味。"},
                {"ko": "고추기름을 넣어 매콤하게 해요.", "en": "Add chili oil for heat.", "ja": "ラー油を加えてピリ辛にします。", "zh": "加入辣椒油增添辣味。"},
                {"ko": "삶은 면을 담고 숙주·옥수수·버터를 올려요.", "en": "Add cooked noodles and top with bean sprouts, corn, and butter.", "ja": "茹でた麺を盛り付け、もやし・コーン・バターを乗せます。", "zh": "放入煮好的面条，摆上豆芽、玉米和黄油。"},
            ],
        },
        {
            "id": "soba",
            "name": {"ko": "자루소바 (냉소바)", "en": "Zaru Soba", "ja": "ざるそば", "zh": "冷荞麦面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "메밀향이 살아있는 시원한 냉소바", "en": "Chilled buckwheat noodles with fragrant dipping broth", "ja": "そばの香りが生きた冷たいざるそば", "zh": "保留荞麦香气的清凉冷荞麦面"},
            "ingredients": [
                {"name": "소바 면", "amount": "1인분"},
                {"name": "쯔유", "amount": "4큰술"},
                {"name": "물", "amount": "8큰술"},
                {"name": "무즙", "amount": "2큰술"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "와사비", "amount": "약간"},
                {"name": "김 (채 썬 것)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "소바를 끓는 물에 삶아요. 끓어 넘칠 것 같으면 찬물 약간 넣어요.", "en": "Boil soba noodles. If it boils over, add a splash of cold water.", "ja": "そばを沸騰したお湯で茹でます。吹きこぼれそうになったら冷水を少し加えます。", "zh": "将荞麦面放入沸水中煮。如果快溢出，加入少量冷水。"},
                {"ko": "찬물에 힘차게 헹궈 전분을 씻어내요.", "en": "Rinse vigorously in cold water to remove starch.", "ja": "冷水でしっかり洗ってでんぷんを落とします。", "zh": "用冷水大力冲洗去除淀粉。"},
                {"ko": "쯔유와 물을 섞어 소스를 만들어요.", "en": "Dilute tsuyu with water.", "ja": "めんつゆと水を混ぜてソースを作ります。", "zh": "将面汤与水混合制成蘸汁。"},
                {"ko": "소바를 채반에 담고 김을 올려요.", "en": "Arrange soba on a strainer and top with nori.", "ja": "そばを笊に盛り付けて海苔をかけます。", "zh": "将荞麦面盛在笊篱上，铺上海苔。"},
                {"ko": "소스에 무즙·쪽파·와사비를 넣어 찍어 드세요.", "en": "Mix grated daikon, green onion, and wasabi into sauce; dip and eat.", "ja": "ソースに大根おろし・ネギ・わさびを入れてつけて召し上がってください。", "zh": "在蘸汁中加入萝卜泥、小葱和芥末，蘸着吃。"},
            ],
        },
    ],
    "japanese/donburi": [
        {
            "id": "kaisen-don",
            "name": {"ko": "카이센동 (해산물 덮밥)", "en": "Kaisen Don", "ja": "海鮮丼", "zh": "海鲜盖饭"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "신선한 회를 스시 밥 위에 올리면 끝, 간단 고급 요리", "en": "Fresh sashimi over seasoned rice — effortlessly luxurious", "ja": "新鮮な刺身を酢飯の上に乗せるだけ、簡単高級料理", "zh": "新鲜刺身盖在醋饭上即完成，简单又高档"},
            "ingredients": [
                {"name": "스시 밥", "amount": "1공기"},
                {"name": "연어·참치·광어 (회용)", "amount": "각 50g"},
                {"name": "단새우 (선택)", "amount": "3마리"},
                {"name": "와사비", "amount": "약간"},
                {"name": "간장", "amount": "찍어 먹을 것"},
                {"name": "쪽파·초생강", "amount": "약간씩"},
            ],
            "steps": [
                {"ko": "스시 밥을 짓고 스시식초를 섞어 식혀요.", "en": "Make sushi rice and let cool.", "ja": "酢飯を炊いて寿司酢を混ぜて冷まします。", "zh": "将寿司饭煮好，拌入寿司醋冷却。"},
                {"ko": "생선을 0.5-1cm 두께로 썰어요.", "en": "Slice fish 0.5-1cm thick.", "ja": "魚を0.5〜1cmの厚さにスライスします。", "zh": "将鱼切成0.5-1cm厚片。"},
                {"ko": "밥을 그릇에 담고 와사비를 올려요.", "en": "Serve rice in a bowl with a touch of wasabi.", "ja": "丼にご飯を盛り付け、わさびを乗せます。", "zh": "将饭盛入碗中，放上芥末。"},
                {"ko": "생선을 예쁘게 펼쳐 올려요.", "en": "Arrange fish slices decoratively over the rice.", "ja": "魚を美しく広げて乗せます。", "zh": "将鱼片美观地摆放在饭上。"},
                {"ko": "쪽파·초생강을 올리고 간장을 곁들여요.", "en": "Garnish with green onion and pickled ginger; serve with soy sauce.", "ja": "ネギとガリを乗せ、醤油を添えます。", "zh": "摆上小葱和腌姜，搭配酱油食用。"},
            ],
        },
        {
            "id": "tendon",
            "name": {"ko": "텐동 (튀김 덮밥)", "en": "Tendon", "ja": "天丼", "zh": "天妇罗盖饭"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "바삭한 튀김 위에 달콤한 텐동 소스가 흐르는 덮밥", "en": "Crispy tempura over rice with sweet-savory tendon sauce", "ja": "サクサクの天ぷらに甘い天丼ソースがかかった丼", "zh": "酥脆天妇罗上浇淋甜咸天丼酱汁的盖饭"},
            "ingredients": [
                {"name": "밥", "amount": "1공기"},
                {"name": "새우·연근·고구마 등 튀김 재료", "amount": "적당량"},
                {"name": "박력분·계란·얼음물", "amount": "튀김 반죽용"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "미림", "amount": "2큰술"},
                {"name": "설탕", "amount": "1작은술"},
                {"name": "다시", "amount": "3큰술"},
            ],
            "steps": [
                {"ko": "간장·미림·설탕·다시를 끓여 텐동 소스를 만들어요.", "en": "Simmer soy sauce, mirin, sugar, and dashi to make tendon sauce.", "ja": "醤油・みりん・砂糖・だしを煮て天丼ソースを作ります。", "zh": "将酱油、味醂、糖和出汁煮开制成天丼酱汁。"},
                {"ko": "튀김 반죽을 만들어요. 얼음물과 밀가루를 섞되 젓가락으로 대충 섞어요.", "en": "Make batter with ice water and flour; mix roughly with chopsticks.", "ja": "氷水と薄力粉で衣を作ります。箸で大まかに混ぜてください。", "zh": "用冰水和面粉制作天妇罗面糊，用筷子粗略搅拌。"},
                {"ko": "재료에 밀가루를 살짝 뿌린 뒤 반죽을 입혀 170°C에서 튀겨요.", "en": "Dust ingredients with flour, dip in batter, and fry at 170°C.", "ja": "材料に薄力粉を軽くまぶして衣をつけ、170°Cで揚げます。", "zh": "在食材上薄薄撒一层面粉，裹上面糊，170°C油炸。"},
                {"ko": "밥 위에 튀김을 올려요.", "en": "Place tempura over rice.", "ja": "ご飯の上に天ぷらを乗せます。", "zh": "将天妇罗放在饭上。"},
                {"ko": "뜨거운 텐동 소스를 끼얹어요.", "en": "Pour hot tendon sauce over.", "ja": "熱い天丼ソースをかけます。", "zh": "浇上热天丼酱汁。"},
            ],
        },
    ],
    "japanese/tempura": [
        {
            "id": "vegetable-tempura",
            "name": {"ko": "야채튀김", "en": "Vegetable Tempura", "ja": "野菜の天ぷら", "zh": "蔬菜天妇罗"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "제철 채소의 맛을 살린 바삭한 튀김", "en": "Seasonal vegetables in the lightest, crispiest batter", "ja": "旬の野菜の味を生かしたサクサクの天ぷら", "zh": "保留时令蔬菜本味的酥脆天妇罗"},
            "ingredients": [
                {"name": "단호박·고구마·연근·표고버섯 등", "amount": "각 1/4개 또는 2-3개"},
                {"name": "박력분", "amount": "1컵"},
                {"name": "계란", "amount": "1개"},
                {"name": "얼음물", "amount": "1컵"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
                {"name": "튀김 소금 또는 쯔유", "amount": "찍어 먹을 것"},
            ],
            "steps": [
                {"ko": "채소를 0.5-1cm 두께로 썰어요.", "en": "Slice vegetables 0.5-1cm thick.", "ja": "野菜を0.5〜1cmの厚さにスライスします。", "zh": "将蔬菜切成0.5-1cm厚片。"},
                {"ko": "물기를 완전히 제거해요. 물기가 있으면 튀김이 바삭하지 않아요.", "en": "Pat completely dry — moisture makes tempura soggy.", "ja": "水気を完全に取り除きます。水気があると天ぷらがサクサクになりません。", "zh": "完全擦干水分。有水分会导致天妇罗不酥脆。"},
                {"ko": "박력분·계란·얼음물을 젓가락으로 10번만 섞어요.", "en": "Mix flour, egg, and ice water with just 10 stirs. Lumps are intentional.", "ja": "薄力粉・卵・氷水を箸で10回だけ混ぜます。ダマは意図的なものです。", "zh": "将面粉、鸡蛋和冰水只搅拌10次。有结块是正常的。"},
                {"ko": "채소에 밀가루 살짝 뿌리고 반죽 입혀 170°C에서 2분 튀겨요.", "en": "Dust vegetables with flour, coat in batter, and fry at 170°C for 2 minutes.", "ja": "野菜に薄力粉を軽くまぶして衣をつけ、170°Cで2分揚げます。", "zh": "在蔬菜上撒少量面粉，裹上面糊，170°C炸2分钟。"},
                {"ko": "소금이나 쯔유에 찍어 드세요.", "en": "Serve with tempura salt or tsuyu dipping sauce.", "ja": "天ぷら塩またはめんつゆにつけてお召し上がりください。", "zh": "搭配天妇罗盐或面汤蘸食。"},
            ],
        },
        {
            "id": "hire-katsu",
            "name": {"ko": "히레카츠 (안심 돈가스)", "en": "Hire Katsu (Pork Tenderloin Cutlet)", "ja": "ヒレカツ", "zh": "猪里脊排"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "지방이 없는 안심으로 만드는 부드러운 돈가스", "en": "Tender, lean pork cutlet — lighter than regular katsu", "ja": "脂身のないヒレ肉で作る柔らかいとんかつ", "zh": "用无脂里脊肉制作的嫩滑猪排"},
            "ingredients": [
                {"name": "돼지 안심", "amount": "150g"},
                {"name": "박력분", "amount": "3큰술"},
                {"name": "계란", "amount": "1개"},
                {"name": "빵가루", "amount": "5큰술"},
                {"name": "소금·후추", "amount": "약간씩"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
                {"name": "돈가스 소스·양배추", "amount": "곁들임용"},
            ],
            "steps": [
                {"ko": "안심을 2cm 두께로 잘라 고기망치나 칼등으로 두드려 펴요.", "en": "Cut tenderloin 2cm thick; pound to tenderize.", "ja": "ヒレ肉を2cmの厚さに切り、肉叩きか包丁の背で叩いて柔らかくします。", "zh": "将里脊肉切成2cm厚，用肉锤或刀背敲打嫩化。"},
                {"ko": "소금·후추로 밑간해요.", "en": "Season with salt and pepper.", "ja": "塩・こしょうで下味を付けます。", "zh": "用盐和胡椒腌制。"},
                {"ko": "밀가루→계란→빵가루 순으로 입혀요. 빵가루는 꾹꾹 눌러 붙여요.", "en": "Coat in flour, egg, then breadcrumbs; press crumbs on firmly.", "ja": "薄力粉→卵→パン粉の順につけます。パン粉はしっかり押し付けて密着させます。", "zh": "依次裹上面粉、鸡蛋液和面包糠，面包糠要用力按压贴紧。"},
                {"ko": "170°C 기름에 3분 튀겨요.", "en": "Deep-fry at 170°C for 3 minutes.", "ja": "170°Cの油で3分揚げます。", "zh": "170°C油炸3分钟。"},
                {"ko": "기름을 빼고 돈가스 소스와 채 썬 양배추와 함께 내요.", "en": "Drain oil and serve with tonkatsu sauce and shredded cabbage.", "ja": "油を切って、とんかつソースと千切りキャベツと一緒に盛り付けます。", "zh": "沥油后配上猪排酱和切丝卷心菜上桌。"},
            ],
        },
    ],
    "japanese/miso": [
        {
            "id": "miso-glazed-eggplant",
            "name": {"ko": "가지 된장구이 (나스 덴가쿠)", "en": "Miso-Glazed Eggplant", "ja": "なすの田楽", "zh": "味噌烤茄子"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "달콤한 미소 글레이즈가 가지에 배어든 고급 반찬", "en": "Sweet miso glaze soaked into silky eggplant", "ja": "甘い味噌グレーズがナスに染み込んだ高級副菜", "zh": "甜味噌酱汁渗透茄子的高档配菜"},
            "ingredients": [
                {"name": "가지", "amount": "2개"},
                {"name": "미소 (된장)", "amount": "2큰술"},
                {"name": "미림", "amount": "1큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "청주 또는 물", "amount": "1큰술"},
                {"name": "참기름", "amount": "1큰술"},
                {"name": "통깨", "amount": "약간"},
            ],
            "steps": [
                {"ko": "미소·미림·설탕·청주를 섞어 글레이즈를 만들어요.", "en": "Mix miso, mirin, sugar, and sake for the glaze.", "ja": "味噌・みりん・砂糖・清酒を混ぜてグレーズを作ります。", "zh": "将味噌、味醂、糖和清酒混合制成酱汁。"},
                {"ko": "가지를 반으로 갈라 칼집을 격자로 넣어요. 잘 익고 양념이 배어요.", "en": "Halve eggplant and score flesh in a crosshatch — helps it cook and absorb flavor.", "ja": "なすを半分に切り、格子状に切り込みを入れます。よく火が通り味が染み込みます。", "zh": "将茄子对半切开，切面划上格子刀纹。这样更容易熟透和入味。"},
                {"ko": "팬에 참기름 두르고 가지를 단면 아래로 놓고 중불에서 4분 구워요.", "en": "Heat sesame oil; place eggplant cut-side down and cook 4 minutes over medium.", "ja": "フライパンにごま油を引き、なすを切り面を下にして中火で4分焼きます。", "zh": "锅中倒入芝麻油，将茄子切面朝下中火煎4分钟。"},
                {"ko": "뒤집어 글레이즈를 단면에 발라요.", "en": "Flip and spread glaze on the cut surface.", "ja": "裏返してグレーズを切り面に塗ります。", "zh": "翻面，在切面上涂上酱汁。"},
                {"ko": "약불로 줄이고 뚜껑 덮어 3분 더 익혀요. 통깨를 뿌려요.", "en": "Reduce to low, cover, and cook 3 more minutes. Sprinkle sesame seeds.", "ja": "弱火にして蓋をし、さらに3分加熱します。白ごまをふります。", "zh": "转小火，盖上锅盖再加热3分钟。撒上白芝麻。"},
            ],
        },
        {
            "id": "sukiyaki",
            "name": {"ko": "스키야키", "en": "Sukiyaki", "ja": "すき焼き", "zh": "寿喜烧"},
            "time": 30, "difficulty": 2,
            "desc": {"ko": "달콤한 간장 국물에 소고기와 채소를 끓여 먹는 일본 전골", "en": "Japanese hot pot with beef and vegetables in a sweet soy broth", "ja": "甘い醤油だしで牛肉と野菜を煮て食べる日本の鍋料理", "zh": "在甜酱油汤底中煮牛肉和蔬菜的日式火锅"},
            "ingredients": [
                {"name": "소고기 (얇게 썬 것)", "amount": "200g"},
                {"name": "두부", "amount": "1/2모"},
                {"name": "대파·표고버섯·팽이버섯", "amount": "적당량"},
                {"name": "실곤약", "amount": "1/2팩"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "미림", "amount": "3큰술"},
                {"name": "설탕", "amount": "1.5큰술"},
                {"name": "생계란 (찍어 먹기용)", "amount": "1개"},
            ],
            "steps": [
                {"ko": "간장·미림·설탕을 섞어 와리시타 소스를 만들어요.", "en": "Mix soy sauce, mirin, and sugar to make warishita sauce.", "ja": "醤油・みりん・砂糖を混ぜてわりしたソースを作ります。", "zh": "将酱油、味醂和糖混合制成割下酱汁。"},
                {"ko": "전골 냄비에 소기름 또는 식용유를 두르고 소고기를 먼저 구워요.", "en": "Heat beef fat or oil in a pot; sear beef first.", "ja": "鍋に牛脂またはサラダ油を引き、牛肉を先に焼きます。", "zh": "锅中放入牛油或食用油，先将牛肉煎一下。"},
                {"ko": "와리시타를 붓고 채소·두부·곤약을 넣어요.", "en": "Pour in warishita and add vegetables, tofu, and konnyaku.", "ja": "わりしたを注いで野菜・豆腐・こんにゃくを加えます。", "zh": "倒入割下酱汁，加入蔬菜、豆腐和魔芋。"},
                {"ko": "뚜껑 덮고 5분 끓여요.", "en": "Cover and simmer 5 minutes.", "ja": "蓋をして5分煮ます。", "zh": "盖上锅盖煮5分钟。"},
                {"ko": "생계란을 풀어 재료를 찍어 드세요. 날계란이 싫으면 반숙 계란으로 대체해요.", "en": "Dip ingredients in beaten raw egg. Use soft-boiled if you prefer.", "ja": "生卵を溶いて具材をつけて召し上がってください。生卵が嫌な場合は半熟卵で代替できます。", "zh": "将生鸡蛋打散，蘸着吃。不喜欢生鸡蛋可以用溏心蛋代替。"},
            ],
        },
    ],
}
