RECIPES_JP = {
    "japanese/sushi": [
        {
            "id": "salmon-sushi",
            "name": {"ko": "연어초밥", "en": "Salmon Sushi", "ja": "サーモン寿司", "zh": "三文鱼寿司"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "집에서 만드는 연어초밥, 밥 온도가 핵심", "en": "Homemade salmon sushi — rice temperature is everything"},
            "ingredients": [
                {"name": "밥 (따뜻한 것)", "amount": "1공기"},
                {"name": "식초", "amount": "2큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "소금", "amount": "1작은술"},
                {"name": "신선한 연어 (회용)", "amount": "100g"},
                {"name": "와사비", "amount": "약간"},
            ],
            "steps": [
                {"ko": "식초·설탕·소금을 섞어 스시식초를 만들어요.", "en": "Mix vinegar, sugar, and salt to make sushi vinegar."},
                {"ko": "따뜻한 밥에 스시식초를 넣고 주걱으로 자르듯 섞어요. 뭉개면 안 돼요.", "en": "Fold sushi vinegar into warm rice with a spatula — don't mash."},
                {"ko": "부채질하며 한 김 식혀요. 광택이 나야 해요.", "en": "Fan while cooling. The rice should be glossy."},
                {"ko": "밥을 손에 쥐어 타원형으로 만들어요. 손에 물을 묻히면 안 달라붙어요.", "en": "Shape rice into ovals with wet hands to prevent sticking."},
                {"ko": "연어를 얇게 썰어 와사비를 살짝 올리고 밥 위에 얹어요.", "en": "Slice salmon, dab a little wasabi, and lay over the rice."},
            ],
        },
        {
            "id": "tuna-sushi",
            "name": {"ko": "참치초밥", "en": "Tuna Sushi", "ja": "マグロ寿司", "zh": "金枪鱼寿司"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "초밥의 클래식, 참치 아카미로 만드는 정통 초밥", "en": "The classic — authentic nigiri with tuna akami"},
            "ingredients": [
                {"name": "밥 (따뜻한 것)", "amount": "1공기"},
                {"name": "스시식초", "amount": "3큰술"},
                {"name": "신선한 참치 (회용)", "amount": "100g"},
                {"name": "와사비", "amount": "약간"},
                {"name": "간장", "amount": "찍어 먹을 것"},
            ],
            "steps": [
                {"ko": "밥에 스시식초를 섞어 샤리(초밥 밥)를 만들어요.", "en": "Mix vinegar into rice to make shari."},
                {"ko": "참치를 결 반대로 0.5cm 두께로 썰어요.", "en": "Slice tuna against the grain to 0.5cm thickness."},
                {"ko": "손바닥에 밥을 올리고 꾹 쥐어 타원형으로 만들어요.", "en": "Place rice on your palm and gently press into an oval."},
                {"ko": "참치 위에 와사비를 아주 조금 올려요.", "en": "Dab a tiny bit of wasabi on the tuna."},
                {"ko": "밥 위에 참치를 올리고 살짝 눌러 고정해요. 간장에 찍어 드세요.", "en": "Press tuna onto rice and serve with soy sauce for dipping."},
            ],
        },
        {
            "id": "tamago-sushi",
            "name": {"ko": "계란초밥 (타마고)", "en": "Tamago Sushi", "ja": "玉子寿司", "zh": "厚蛋烧寿司"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "달콤하고 폭신한 두꺼운 달걀말이 초밥", "en": "Sweet and fluffy thick omelette on sushi rice"},
            "ingredients": [
                {"name": "계란", "amount": "3개"},
                {"name": "설탕", "amount": "1.5큰술"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "미림", "amount": "1큰술"},
                {"name": "밥 (스시용)", "amount": "1/2공기"},
                {"name": "김", "amount": "적당히"},
            ],
            "steps": [
                {"ko": "계란·설탕·간장·미림을 잘 섞어요.", "en": "Beat eggs with sugar, soy sauce, and mirin."},
                {"ko": "사각 타마고야키 팬(없으면 일반 팬)에 기름 얇게 두르고 달구어요.", "en": "Lightly oil a rectangular tamagoyaki pan (or regular pan) and heat."},
                {"ko": "계란물을 3번에 나눠 부어가며 두툼하게 말아요.", "en": "Pour egg mixture in 3 batches, rolling each time to build layers."},
                {"ko": "식힌 뒤 1cm 두께로 썰어요.", "en": "Cool and slice to 1cm thickness."},
                {"ko": "스시 밥을 타원으로 만들고 계란을 올려 김으로 고정해요.", "en": "Form rice ovals, top with tamago, and wrap with a strip of nori."},
            ],
        },
    ],
    "japanese/ramen": [
        {
            "id": "shoyu-ramen",
            "name": {"ko": "간장 라멘", "en": "Shoyu Ramen", "ja": "醤油ラーメン", "zh": "酱油拉面"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "깊고 담백한 간장 베이스 라멘, 집에서도 충분히 가능", "en": "Deep, clean soy-based ramen you can make at home"},
            "ingredients": [
                {"name": "생라멘 면 또는 중면", "amount": "1인분"},
                {"name": "닭육수 또는 시판 육수", "amount": "2.5컵"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "미림", "amount": "1큰술"},
                {"name": "다진 마늘", "amount": "1작은술"},
                {"name": "참기름", "amount": "1작은술"},
                {"name": "반숙 계란·차슈·대파", "amount": "토핑용"},
            ],
            "steps": [
                {"ko": "냄비에 육수·간장·미림·마늘을 넣고 끓여요.", "en": "Combine broth, soy sauce, mirin, and garlic; bring to a boil."},
                {"ko": "간을 보고 부족하면 간장·소금으로 조절해요.", "en": "Taste and adjust seasoning with soy sauce or salt."},
                {"ko": "면을 별도 냄비에 삶아요.", "en": "Cook noodles in a separate pot."},
                {"ko": "그릇을 뜨겁게 데운 뒤 면을 담아요. 그릇이 차가우면 국물이 식어요.", "en": "Warm the bowl before serving — cold bowls cool the soup fast."},
                {"ko": "국물을 붓고 토핑을 올려요.", "en": "Pour broth over and add toppings."},
            ],
        },
        {
            "id": "curry-udon",
            "name": {"ko": "카레 우동", "en": "Curry Udon", "ja": "カレーうどん", "zh": "咖喱乌冬面"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "걸쭉한 카레 국물에 쫄깃한 우동면, 간단하고 든든", "en": "Thick curry broth with chewy udon — simple and satisfying"},
            "ingredients": [
                {"name": "우동 면 (냉동 가능)", "amount": "1인분"},
                {"name": "시판 카레 루", "amount": "1조각"},
                {"name": "닭육수 또는 물", "amount": "2컵"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "대파", "amount": "약간"},
                {"name": "간장", "amount": "1큰술"},
            ],
            "steps": [
                {"ko": "양파를 채 썰어 기름에 볶아요.", "en": "Slice onion and stir-fry in oil."},
                {"ko": "육수를 붓고 끓으면 카레 루를 넣어 녹여요.", "en": "Add broth and dissolve curry roux once boiling."},
                {"ko": "간장으로 간을 맞춰요.", "en": "Season with soy sauce."},
                {"ko": "우동 면을 삶아 그릇에 담아요.", "en": "Cook udon and place in bowl."},
                {"ko": "카레 국물을 붓고 대파를 올려요.", "en": "Pour curry broth over and top with green onion."},
            ],
        },
        {
            "id": "cold-udon",
            "name": {"ko": "냉우동 (자루우동)", "en": "Cold Udon", "ja": "ざるうどん", "zh": "冷乌冬面"},
            "time": 15, "difficulty": 1,
            "desc": {"ko": "여름에 먹는 시원한 쯔유 우동", "en": "Chilled udon with dipping broth for hot days"},
            "ingredients": [
                {"name": "우동 면", "amount": "1인분"},
                {"name": "쯔유 (시판)", "amount": "3큰술"},
                {"name": "물", "amount": "6큰술 (쯔유 희석용)"},
                {"name": "무즙 (간 무)", "amount": "2큰술"},
                {"name": "쪽파", "amount": "약간"},
                {"name": "김 (채 썬 것)", "amount": "약간"},
            ],
            "steps": [
                {"ko": "우동 면을 삶은 뒤 찬물에 헹궈 쫄깃하게 만들어요.", "en": "Cook udon, then rinse in cold water until firm and chewy."},
                {"ko": "쯔유를 물로 희석해 찍어 먹는 소스를 만들어요.", "en": "Dilute tsuyu with water to make the dipping sauce."},
                {"ko": "면을 채반이나 그릇에 담아요.", "en": "Arrange noodles on a bamboo strainer or plate."},
                {"ko": "무즙·쪽파·김을 올려요.", "en": "Top with grated daikon, green onion, and nori."},
                {"ko": "소스에 찍어 드세요.", "en": "Dip noodles in sauce and enjoy."},
            ],
        },
    ],
    "japanese/donburi": [
        {
            "id": "katsudon",
            "name": {"ko": "가츠동", "en": "Katsudon", "ja": "カツ丼", "zh": "炸猪排饭"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "바삭한 돈가츠를 달걀로 감싸 밥 위에 올린 일본식 덮밥", "en": "Crispy pork cutlet simmered with egg over rice"},
            "ingredients": [
                {"name": "돈가츠 (시판 또는 직접 튀긴 것)", "amount": "1장"},
                {"name": "밥", "amount": "1공기"},
                {"name": "계란", "amount": "2개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "쯔유", "amount": "3큰술"},
                {"name": "물", "amount": "5큰술"},
                {"name": "설탕", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "작은 팬에 쯔유·물·설탕을 넣고 끓여요.", "en": "Simmer tsuyu, water, and sugar in a small pan."},
                {"ko": "양파를 얇게 썰어 넣고 1-2분 익혀요.", "en": "Add sliced onion and cook 1-2 minutes."},
                {"ko": "돈가츠를 먹기 좋게 썰어 올려요.", "en": "Slice the katsu and lay it in the pan."},
                {"ko": "계란을 풀어 반 정도 익힌 상태로 부어요.", "en": "Beat eggs and pour over, cooking until just half-set."},
                {"ko": "뚜껑을 덮고 약불에서 30초, 반숙 상태에서 밥 위에 얹어요.", "en": "Cover and cook on low 30 seconds; slide over rice while still soft."},
            ],
        },
        {
            "id": "oyakodon",
            "name": {"ko": "오야코동", "en": "Oyakodon", "ja": "親子丼", "zh": "亲子丼"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "닭고기와 계란의 조합, 이름이 부모와 자식이라는 뜻", "en": "Chicken and egg together — ooya(parent) + ko(child)"},
            "ingredients": [
                {"name": "닭다리살", "amount": "150g"},
                {"name": "계란", "amount": "2개"},
                {"name": "양파", "amount": "1/4개"},
                {"name": "쯔유", "amount": "3큰술"},
                {"name": "물", "amount": "5큰술"},
                {"name": "밥", "amount": "1공기"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "닭다리살을 한 입 크기로 썰어요.", "en": "Cut chicken thigh into bite-sized pieces."},
                {"ko": "팬에 쯔유·물을 끓이고 양파와 닭을 넣어 익혀요.", "en": "Boil tsuyu and water; add onion and chicken until cooked."},
                {"ko": "계란을 풀어 가장자리부터 부어요.", "en": "Beat eggs and pour from the edges inward."},
                {"ko": "뚜껑 덮고 30초, 반숙 상태에서 불을 꺼요.", "en": "Cover, 30 seconds, turn off heat while still soft."},
                {"ko": "밥 위에 얹고 쪽파를 올려요.", "en": "Serve over rice and top with green onion."},
            ],
        },
        {
            "id": "gyudon",
            "name": {"ko": "규동", "en": "Gyudon", "ja": "牛丼", "zh": "牛肉盖饭"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "달콤한 간장 소스 소고기덮밥, 요시노야의 그 맛", "en": "Sweet soy beef bowl — the iconic Yoshinoya taste"},
            "ingredients": [
                {"name": "소고기 (불고기용 또는 얇게 썬 것)", "amount": "150g"},
                {"name": "양파", "amount": "1/2개"},
                {"name": "간장", "amount": "2큰술"},
                {"name": "미림", "amount": "2큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "다시 또는 물", "amount": "1/2컵"},
                {"name": "밥", "amount": "1공기"},
            ],
            "steps": [
                {"ko": "양파를 얇게 슬라이스해요.", "en": "Slice onion thinly."},
                {"ko": "냄비에 간장·미림·설탕·다시를 넣고 끓여요.", "en": "Combine soy sauce, mirin, sugar, and dashi; bring to a boil."},
                {"ko": "양파를 넣고 2분 익혀요.", "en": "Add onion and cook 2 minutes."},
                {"ko": "소고기를 넣어 색이 변할 때까지 익혀요.", "en": "Add beef and cook until no longer pink."},
                {"ko": "밥 위에 얹어요. 반숙 계란을 올리면 더 맛있어요.", "en": "Serve over rice. A soft-boiled egg on top makes it even better."},
            ],
        },
    ],
    "japanese/tempura": [
        {
            "id": "shrimp-tempura",
            "name": {"ko": "새우튀김 (에비텐)", "en": "Shrimp Tempura", "ja": "エビ天ぷら", "zh": "虾天妇罗"},
            "time": 25, "difficulty": 2,
            "desc": {"ko": "얇고 바삭한 튀김옷이 핵심, 반죽을 과하게 섞지 마세요", "en": "Light, crispy batter is everything — don't overmix"},
            "ingredients": [
                {"name": "큰 새우", "amount": "8마리"},
                {"name": "박력분", "amount": "1컵"},
                {"name": "계란", "amount": "1개"},
                {"name": "얼음물", "amount": "1컵"},
                {"name": "식용유 (튀김용)", "amount": "넉넉히"},
                {"name": "소금", "amount": "약간"},
            ],
            "steps": [
                {"ko": "새우는 껍질 벗기고 내장 제거 후, 배 쪽에 2-3군데 칼집을 넣어 펴요.", "en": "Peel and devein shrimp; make 2-3 cuts on the belly side to straighten."},
                {"ko": "박력분·계란·얼음물을 젓가락으로 대충 섞어요. 덩어리가 있어도 OK.", "en": "Mix flour, egg, and ice water with chopsticks — lumpy is fine."},
                {"ko": "기름을 170-175°C로 달궈요.", "en": "Heat oil to 170-175°C."},
                {"ko": "새우에 밀가루를 살짝 뿌리고 반죽을 입혀요.", "en": "Dust shrimp with flour, then coat in batter."},
                {"ko": "기름에 넣고 2-3분 바삭하게 튀겨요. 반죽 방울이 고소하게 퍼지면 돼요.", "en": "Fry 2-3 minutes until crispy. Batter droplets in the oil are normal."},
            ],
        },
        {
            "id": "yakitori",
            "name": {"ko": "닭꼬치 (야키토리)", "en": "Yakitori", "ja": "焼き鳥", "zh": "日式烤鸡串"},
            "time": 25, "difficulty": 1,
            "desc": {"ko": "달콤 짭짤한 타레 소스를 발라 구운 닭꼬치", "en": "Chicken skewers glazed with sweet-salty tare sauce"},
            "ingredients": [
                {"name": "닭다리살", "amount": "200g"},
                {"name": "대파", "amount": "1/2대"},
                {"name": "간장", "amount": "3큰술"},
                {"name": "미림", "amount": "3큰술"},
                {"name": "설탕", "amount": "1큰술"},
                {"name": "꼬치 (나무꼬치는 30분 물에 담가요)", "amount": "8개"},
            ],
            "steps": [
                {"ko": "닭다리살과 대파를 한 입 크기로 썰어요.", "en": "Cut chicken and green onion into bite-sized pieces."},
                {"ko": "간장·미림·설탕을 냄비에서 끓여 타레 소스를 만들어요.", "en": "Simmer soy sauce, mirin, and sugar to make tare glaze."},
                {"ko": "닭과 대파를 꼬치에 번갈아 꽂아요.", "en": "Thread chicken and green onion alternately onto skewers."},
                {"ko": "그릴 또는 팬에 중불로 구워요.", "en": "Grill over medium heat."},
                {"ko": "익으면서 타레 소스를 2-3번 발라가며 구워요.", "en": "Brush with tare 2-3 times during cooking."},
            ],
        },
        {
            "id": "grilled-salmon",
            "name": {"ko": "연어 구이 (시오야키)", "en": "Salt-Grilled Salmon", "ja": "鮭の塩焼き", "zh": "盐烤三文鱼"},
            "time": 20, "difficulty": 1,
            "desc": {"ko": "소금만 뿌려 구워도 이렇게 맛있는 일본식 생선구이", "en": "Just salt and heat — Japanese simplicity at its best"},
            "ingredients": [
                {"name": "연어 (토막)", "amount": "1토막"},
                {"name": "소금", "amount": "1작은술"},
                {"name": "레몬", "amount": "1/4개"},
                {"name": "식용유", "amount": "약간"},
            ],
            "steps": [
                {"ko": "연어에 소금을 뿌리고 15분 이상 두었다가 키친타월로 닦아요.", "en": "Salt the salmon and let sit 15+ minutes; pat dry with paper towel."},
                {"ko": "팬에 기름을 얇게 두르고 중불로 달궈요.", "en": "Lightly oil a pan and heat over medium."},
                {"ko": "껍질 쪽을 먼저 올려 4분 구워요.", "en": "Start skin-side down and cook 4 minutes."},
                {"ko": "뒤집어 3분 더 구워요.", "en": "Flip and cook 3 more minutes."},
                {"ko": "레몬을 짜서 뿌려 드세요.", "en": "Squeeze lemon over and serve."},
            ],
        },
    ],
    "japanese/miso": [
        {
            "id": "miso-soup",
            "name": {"ko": "미소시루", "en": "Miso Soup", "ja": "味噌汁", "zh": "味噌汤"},
            "time": 10, "difficulty": 1,
            "desc": {"ko": "일본 가정식의 기본 중의 기본, 5분이면 완성", "en": "The cornerstone of Japanese home cooking — done in 5 minutes"},
            "ingredients": [
                {"name": "다시마·가쓰오부시 육수 또는 시판 다시", "amount": "2컵"},
                {"name": "된장 (미소)", "amount": "1.5큰술"},
                {"name": "두부 (연두부 또는 부침용)", "amount": "1/4모"},
                {"name": "미역 (건조)", "amount": "1작은술"},
                {"name": "쪽파", "amount": "약간"},
            ],
            "steps": [
                {"ko": "건조 미역을 물에 5분 불려요.", "en": "Soak dried wakame in water for 5 minutes."},
                {"ko": "냄비에 육수를 끓여요.", "en": "Bring dashi stock to a boil."},
                {"ko": "두부를 작게 잘라 넣어요.", "en": "Add cubed tofu."},
                {"ko": "불을 약하게 줄이고 된장을 체에 걸러 풀어요. 끓이지 마세요.", "en": "Reduce heat; dissolve miso through a strainer. Never boil after adding miso."},
                {"ko": "미역·쪽파를 넣어 바로 드세요.", "en": "Add wakame and green onion; serve immediately."},
            ],
        },
        {
            "id": "chawanmushi",
            "name": {"ko": "차완무시", "en": "Chawanmushi", "ja": "茶碗蒸し", "zh": "茶碗蒸"},
            "time": 35, "difficulty": 2,
            "desc": {"ko": "달걀을 부드럽게 찐 일본식 계란찜, 다시가 핵심", "en": "Silky steamed egg custard — dashi makes the difference"},
            "ingredients": [
                {"name": "계란", "amount": "2개"},
                {"name": "다시 육수", "amount": "300ml"},
                {"name": "간장", "amount": "1작은술"},
                {"name": "미림", "amount": "1작은술"},
                {"name": "소금", "amount": "약간"},
                {"name": "새우·닭고기·은행 등 속재료", "amount": "취향껏"},
            ],
            "steps": [
                {"ko": "계란을 풀고 다시·간장·미림·소금을 넣어 잘 섞어요.", "en": "Beat eggs with dashi, soy sauce, mirin, and salt."},
                {"ko": "체에 걸러 기포를 없애요.", "en": "Strain through a sieve to remove bubbles."},
                {"ko": "내열 그릇에 속재료를 넣고 계란물을 부어요.", "en": "Place fillings in heat-safe cups; pour egg mixture over."},
                {"ko": "랩을 느슨하게 덮고 찜기에서 약불로 15분 쪄요. 강불이면 구멍이 생겨요.", "en": "Cover loosely with foil; steam on low for 15 minutes. High heat creates holes."},
                {"ko": "이쑤시개로 찔러 맑은 액체가 나오면 완성이에요.", "en": "Insert a toothpick — clear liquid means it's done."},
            ],
        },
        {
            "id": "tonjiru",
            "name": {"ko": "돼지고기 된장국 (톤지루)", "en": "Tonjiru", "ja": "豚汁", "zh": "猪肉味噌汤"},
            "time": 30, "difficulty": 1,
            "desc": {"ko": "돼지고기와 채소가 가득한 든든한 일본식 된장국", "en": "Hearty miso soup packed with pork and root vegetables"},
            "ingredients": [
                {"name": "돼지고기 (얇게 썬 것)", "amount": "100g"},
                {"name": "무", "amount": "1/6개"},
                {"name": "당근", "amount": "1/4개"},
                {"name": "감자", "amount": "1개"},
                {"name": "된장", "amount": "2.5큰술"},
                {"name": "다시 육수", "amount": "3컵"},
                {"name": "참기름", "amount": "1작은술"},
            ],
            "steps": [
                {"ko": "채소를 한 입 크기로 썰어요.", "en": "Chop all vegetables into bite-sized pieces."},
                {"ko": "냄비에 참기름을 두르고 돼지고기를 볶아요.", "en": "Heat sesame oil in a pot and stir-fry pork."},
                {"ko": "채소를 넣고 2분 볶아요.", "en": "Add vegetables and stir-fry 2 minutes."},
                {"ko": "다시를 붓고 채소가 익을 때까지 15분 끓여요.", "en": "Pour in dashi and simmer until vegetables are tender, about 15 minutes."},
                {"ko": "불을 줄이고 된장을 풀어요. 끓이지 않아야 풍미가 살아 있어요.", "en": "Reduce heat and dissolve miso. Don't boil to preserve flavor."},
            ],
        },
    ],
}
